/* English narrative for data. Key: Italian source text (see ../key.ts). */
export const EN_DATA: Readonly<Record<string, string>> = {
  "Tiro": "Shooting",
  "Palleggio": "Ball handling",
  "Passaggio": "Passing",
  "Difesa": "Defense",
  "Rimbalzo": "Rebounding",
  "Atletismo": "Athleticism",
  "Fisico": "Strength",
  "IQ cestistico": "Basketball IQ",
  "Clutch": "Clutch",
  "Tenuta": "Durability",
  "Etica del lavoro": "Work ethic",
  "Ego": "Ego",
  "Chimica": "Chemistry",
  "Costanza": "Consistency",
  "Motore": "Motor",
  "Media": "Media savvy",
  "Playmaker": "Point guard",
  "Guardia": "Shooting guard",
  "Ala piccola": "Small forward",
  "Ala forte": "Power forward",
  "Centro": "Center",
  "Italia": "Italy",
  "Europa": "Europe",
  "Spagna": "Spain",
  "Francia": "France",
  "Serbia": "Serbia",
  "Grecia": "Greece",
  "Lituania": "Lithuania",
  "Germania": "Germany",
  "Slovenia": "Slovenia",
  "Croazia": "Croatia",
  "Turchia": "Turkey",
  "Lettonia": "Latvia",
  "Georgia": "Georgia",
  "Americhe": "Americas",
  "Canada": "Canada",
  "Brasile": "Brazil",
  "Argentina": "Argentina",
  "Australia": "Australia",
  "Mondo": "World",
  "Nigeria": "Nigeria",
  "Primo turno": "First round",
  "Semifinali Est/Ovest": "Conference semifinals",
  "Finali Est/Ovest": "Conference finals",
  "Finali NBA": "NBA Finals",
  "Quarti di finale": "Quarterfinals",
  "Semifinale Final Four": "Final Four semifinal",
  "Finale Eurolega": "EuroLeague Final",
  "Est": "East",
  "Ovest": "West",
  "Eurolega": "EuroLeague",
  "palle rubate": "steals",
  "Come vuoi segnare i tuoi punti?": "How do you want to score your points?",
  "Il Cecchino": "The Sniper",
  "Tiro implacabile dal perimetro; in difesa lasci qualche scopertura.": "Relentless from the perimeter; on defense you leave a few gaps.",
  "La Guardia Completa": "The Complete Guard",
  "Tiro solido unito a una mente lucida in campo.": "A solid jumper paired with a clear head on the floor.",
  "Il Tiratore Dinamico": "The Dynamic Shooter",
  "Meno preciso, ma rapido nel palleggio e nel salto.": "Less accurate, but quick off the dribble and on the jumper.",
  "Il tiratore da ricezione": "The Catch-and-Shoot Specialist",
  "Tiri puliti, senza palleggiare. Dipendi da chi ti trova.": "Clean looks, no dribbling. You depend on whoever finds you.",
  "Che rapporto hai con il pallone in mano?": "How do you feel with the ball in your hands?",
  "Il Funambolo": "The Tightrope Walker",
  "Palleggio ipnotico, ma gioca spesso da solo.": "A hypnotic handle, but he often plays on his own.",
  "Il Playmaker Nato": "The Natural Point Guard",
  "Controllo di palla e visione di gioco crescono insieme.": "Ball control and court vision grow together.",
  "Il Tuttofare di Palla": "The Ball-Handling Utility Man",
  "Meno spettacolare, ma utile in più situazioni.": "Less flashy, but useful in more situations.",
  "Il Ritmo Controllato": "The Controlled Tempo",
  "Palla bassa, testa alta. Meno spettacolo, più possessi puliti.": "Ball low, head up. Less show, more clean possessions.",
  "Come fai rendere meglio i tuoi compagni?": "How do you make your teammates better?",
  "Il Regista Puro": "The Pure Playmaker",
  "Visione di gioco superiore, ma trascura la palestra.": "Superior court vision, but he skips the gym.",
  "La Mente Lucida": "The Clear Mind",
  "Passaggi precisi guidati da una grande lettura del gioco.": "Precise passes driven by a great read of the game.",
  "Il Facilitatore": "The Facilitator",
  "Crea spazi anche con palleggio e tiro.": "Creates space with the dribble and the jumper too.",
  "Il Passaggio in Corsa": "The Pass on the Run",
  "Assist in transizione. Il gioco si allarga quando corri.": "Assists in transition. The floor opens up when you run.",
  "Come fermi i tuoi avversari?": "How do you stop your opponents?",
  "Il Muro": "The Wall",
  "Difensore implacabile, ma il tiro ne risente.": "A relentless defender, but the jumper suffers.",
  "Lo Stopper Intelligente": "The Smart Stopper",
  "Legge le giocate avversarie prima che accadano.": "Reads the opponent's plays before they happen.",
  "La Presenza Fisica": "The Physical Presence",
  "Difende con corpo e posizione più che con reattività.": "Defends with body and position more than reflexes.",
  "Il Ladruncolo": "The Pickpocket",
  "Mani veloci, raddoppi, palle rubate. Qualche fallo di troppo.": "Quick hands, double teams, steals. A few fouls too many.",
  "Come domini il vetro?": "How do you own the glass?",
  "Il Dominatore del Vetro": "The Glass Eater",
  "Rimbalzista nato, ma poco a suo agio palla in mano.": "A born rebounder, but not comfortable with the ball in his hands.",
  "Il Lottatore": "The Battler",
  "Combatte ogni rimbalzo con forza pura.": "Fights for every rebound with pure strength.",
  "Il Rimbalzista Mobile": "The Mobile Rebounder",
  "Copre più campo grazie all'atletismo.": "Covers more ground thanks to his athleticism.",
  "Il Box-out Silenzioso": "The Silent Box-Out",
  "Posizione prima del salto. I rimbalzi arrivano senza rumore.": "Position before the jump. The rebounds come without noise.",
  "Qual è la tua arma fisica migliore?": "What is your best physical weapon?",
  "Lo Schiacciatore": "The Dunker",
  "Esplosività pura, ma a volte gioca d'istinto.": "Pure explosiveness, but sometimes plays on instinct.",
  "Un fisico costruito per reggere ogni scontro.": "A frame built to hold up in every collision.",
  "Il Volo Silenzioso": "The Silent Flight",
  "Usa l'atletismo al servizio di tiro e difesa.": "Puts his athleticism at the service of shooting and defense.",
  "Il Primo Passo": "The First Step",
  "Lo scatto sul palleggio. Arrivi dove gli altri pensano.": "The burst off the dribble. You get where others only think of going.",
  "Come reggi il contatto sotto canestro?": "How do you handle contact under the rim?",
  "Il Bisonte": "The Bison",
  "Forza bruta, ma perde un po' di esplosività.": "Brute strength, but he loses some explosiveness.",
  "Il Combattente": "The Fighter",
  "Forza messa al servizio della lotta a rimbalzo.": "Strength put to work in the battle on the boards.",
  "La Roccia Flessibile": "The Flexible Rock",
  "Fisico equilibrato tra difesa e rimbalzo.": "A frame balanced between defense and rebounding.",
  "Il Pivot Basso": "The Low-Post Big",
  "Spalle al canestro, piede perno, contatto continuo.": "Back to the basket, pivot foot, constant contact.",
  "Cosa ti rende un giocatore intelligente?": "What makes you a smart player?",
  "Il Professore": "The Professor",
  "Legge il gioco come nessun altro, ma trascura la palestra.": "Reads the game like no one else, but skips the gym.",
  "La Mente della Squadra": "The Team's Brain",
  "Intelligenza cestistica al servizio dei compagni.": "Basketball IQ at the service of his teammates.",
  "Il Veterano Precoce": "The Precocious Veteran",
  "Esperienza applicata a tiro e difesa.": "Experience applied to shooting and defense.",
  "L'Anticipo": "The Anticipation",
  "Leggi la linea di passaggio un secondo prima. Poi rubi o chiudi.": "You read the passing lane a second early. Then you steal it or close it.",
  "Mille tiri al giorno": "A thousand shots a day",
  "Ripeti il gesto finché diventa automatico.": "Repeat the motion until it becomes automatic.",
  "Laboratorio di palleggio": "Ball-handling lab",
  "Due palle, specchio, uscite strette.": "Two balls, a mirror, tight moves.",
  "Film e visione di gioco": "Film and court vision",
  "Ore di video per anticipare la seconda linea.": "Hours of video to read the second line early.",
  "Campo di difesa": "Defensive camp",
  "Slide, mano attiva, comunicazioni.": "Slides, active hands, communication.",
  "Guerra a rimbalzo": "War on the glass",
  "Box-out, tempismo, secondo salto.": "Box-out, timing, second jump.",
  "Pliometria e primo passo": "Plyometrics and first step",
  "Esplosività pura. Il corpo paga il conto.": "Pure explosiveness. The body pays the bill.",
  "Sala pesi": "Weight room",
  "Massa utile per il contatto.": "Useful mass for contact.",
  "Studio con lo staff": "Study sessions with the staff",
  "Schemi, scouting, letture pre-possesso.": "Sets, scouting, reads before the possession.",
  "Lavoro two-way": "Two-way work",
  "Tiro in uscita e chiusura sul perimetro, stesso pomeriggio.": "Shooting off screens and closing out on the perimeter, same afternoon.",
  "Possessi al buio": "Late-clock possessions",
  "Ripeti gli ultimi otto secondi finché il polso non trema più.": "Repeat the last eight seconds until your wrist stops shaking.",
  "Recupero e prevenzione": "Recovery and prevention",
  "Meno carico, più anni davanti.": "Less load, more years ahead.",
  "Il primo scontro con un veterano": "The first clash with a veteran",
  "Un giocatore esperto ti mette alla prova nel primo allenamento.": "An experienced player tests you at your first practice.",
  "Rispondi con rispetto": "You answer with respect",
  "Impari, non attacchi.": "You learn, you don't attack.",
  "Il tuo atteggiamento non passa inosservato allo staff.": "The staff notices your attitude.",
  "Ti fai valere subito": "You stand your ground right away",
  "Vuoi minuti da subito.": "You want minutes now.",
  "Fai rumore. Qualcuno nello spogliatoio storce il naso.": "You make noise. Someone in the locker room frowns.",
  "La stampa ti etichetta già «il predestinato»": "The press already labels you \"the chosen one\"",
  "Le aspettative crescono più in fretta di te.": "Expectations grow faster than you do.",
  "Abbassi le aspettative": "You lower expectations",
  "Giochi con calma i riflettori.": "You handle the spotlight calmly.",
  "L'allenatore apprezza la testa sulle spalle.": "The coach likes that your head is on straight.",
  "Accetti la pressione": "You accept the pressure",
  "Ti prendi la responsabilità.": "You take responsibility.",
  "Il pubblico inizia ad affezionarsi al tuo coraggio.": "The crowd starts to love your nerve.",
  "Un fastidio ai polpacci ti fa saltare qualche allenamento": "Calf tightness makes you miss a few practices",
  "Niente di grave, ma va gestito.": "Nothing serious, but it has to be managed.",
  "Forzi il rientro": "You force the comeback",
  "Non vuoi perdere minuti.": "You don't want to lose minutes.",
  "Torni prima. Il fisico prende nota.": "You come back early. Your body takes note.",
  "Segui i fisioterapisti": "You follow the physios",
  "Meglio prevenire.": "Better safe than sorry.",
  "Costruisci abitudini che pagheranno più avanti.": "You build habits that will pay off later.",
  "Battaglia per i minuti con un altro giovane": "A battle for minutes with another young player",
  "C'è un solo posto in rotazione che conta.": "There's only one rotation spot that matters.",
  "Arrivi primo in palestra": "You're first in the gym",
  "Etica prima della politica.": "Work ethic before politics.",
  "Lo staff inizia a fidarsi dei tuoi orari.": "The staff starts to trust your schedule.",
  "Chiedi spiegazioni sul ruolo": "You ask about your role",
  "Vuoi chiarezza, non silenzio.": "You want clarity, not silence.",
  "Ottieni risposte. Non tutte ti piacciono.": "You get answers. Not all of them you like.",
  "Il tuo rivale ti supera in una classifica di riviste": "Your rival passes you in a magazine ranking",
  "{RIVAL} è ovunque, in questi giorni.": "{RIVAL} is everywhere these days.",
  "Rispondi sul campo": "You answer on the court",
  "Lasci parlare le partite.": "You let the games do the talking.",
  "Trasformi la classifica in benzina.": "You turn the ranking into fuel.",
  "Non gli dai peso": "You pay it no mind",
  "Zero polemiche.": "No controversy.",
  "La tua calma viene letta come sicurezza.": "Your calm is read as confidence.",
  "L'allenatore ti chiede di sacrificare punti": "The coach asks you to give up some points",
  "{COACH} vuole più equilibrio in squadra.": "{COACH} wants more balance on the team.",
  "Accetti il sacrificio": "You accept the sacrifice",
  "Meno numeri, più squadra.": "Fewer numbers, more team.",
  "Il gruppo funziona meglio. Le tue medie no.": "The group works better. Your averages don't.",
  "Chiedi più libertà offensiva": "You ask for more offensive freedom",
  "Vuoi essere il riferimento.": "You want to be the go-to guy.",
  "Ottieni più palloni. La fiducia dello staff cala.": "You get more touches. The staff's trust drops.",
  "Un compagno attraversa un momento difficile": "A teammate is going through a tough time",
  "Il rendimento della squadra ne risente.": "The team's performance suffers.",
  "Lo supporti pubblicamente": "You back him publicly",
  "Ti esponi per lui.": "You stick your neck out for him.",
  "Diventi un punto di riferimento anche fuori dal campo.": "You become a reference point off the court too.",
  "Ti concentri solo sul tuo gioco": "You focus only on your own game",
  "Non è compito tuo.": "It's not your job.",
  "Resti concentrato. Qualcuno nota la distanza.": "You stay focused. Someone notices the distance.",
  "Una dichiarazione diventa virale per i motivi sbagliati": "A comment goes viral for the wrong reasons",
  "I social non perdonano.": "Social media doesn't forgive.",
  "Chiarisci in conferenza": "You clear it up at the press conference",
  "Meglio di petto.": "Better to face it head on.",
  "La situazione si sgonfia in fretta.": "It blows over quickly.",
  "Lasci correre": "You let it go",
  "Non alimenti la polemica.": "You don't feed the controversy.",
  "Lo staff apprezza il basso profilo. Il pubblico un po' meno.": "The staff likes the low profile. The fans, a little less.",
  "Dolore cronico al ginocchio": "Chronic knee pain",
  "Niente di grave, ma fastidioso. Gestirlo farà la differenza.": "Nothing serious, but annoying. Managing it will make the difference.",
  "Giochi ogni partita": "You play every game",
  "Non vuoi saltare nulla.": "You don't want to miss anything.",
  "I tifosi ti chiamano instancabile. Il fisico paga in silenzio.": "The fans call you tireless. Your body pays in silence.",
  "Accetti un turno di riposo": "You accept a rest day",
  "Pensi al lungo periodo.": "You think long term.",
  "Una scelta poco spettacolare, ma saggia.": "Not a flashy choice, but a wise one.",
  "Il rivale ti provoca prima della sfida diretta": "Your rival taunts you before the head-to-head",
  "{RIVAL} non le manda a dire.": "{RIVAL} doesn't mince words.",
  "Rispondi a tono": "You fire back",
  "Alzi lo scontro.": "You raise the stakes.",
  "La rivalità infiamma i titoli.": "The rivalry sets the headlines on fire.",
  "Ignori, parla il campo": "You ignore it and let the court talk",
  "Zero distrazioni.": "Zero distractions.",
  "La freddezza paga in spogliatoio.": "Staying cool pays off in the locker room.",
  "Snobbato per l'All-Star": "Snubbed for the All-Star Game",
  "I numeri c'erano. La chiamata no.": "The numbers were there. The call wasn't.",
  "Usalo come combustibile": "You use it as fuel",
  "Ogni allenamento ha un nome.": "Every practice has a name now.",
  "Chiudi il telefono. Apri la palestra.": "You switch off the phone. You open the gym.",
  "Parli con i media del torto": "You talk to the media about the snub",
  "Vuoi che si sappia.": "You want people to know.",
  "Fai discutere. Non tutti sono dalla tua parte.": "You get people talking. Not everyone is on your side.",
  "I più giovani ti guardano come mentore": "The younger players look at you as a mentor",
  "Il tuo ruolo in squadra sta cambiando.": "Your role on the team is changing.",
  "Abbracci il ruolo di leader": "You embrace the leader role",
  "Investi tempo sui più giovani.": "You invest time in the young guys.",
  "Diventi il punto fermo dello spogliatoio.": "You become the anchor of the locker room.",
  "Resti concentrato sul tuo gioco": "You stay focused on your own game",
  "Non è il momento di insegnare.": "It's not the time to teach.",
  "Efficiente come sempre. Un po' più solo.": "Efficient as ever. A little more alone.",
  "Il fisico non risponde più come una volta": "The body doesn't respond like it used to",
  "Gli anni si fanno sentire.": "The years are starting to show.",
  "Adatti lo stile": "You adapt your style",
  "Meno strappi, più lettura.": "Fewer bursts, more reading.",
  "Diventi più letale da fermo, meno spettacolare in transizione.": "You become deadlier in the half court, less spectacular in transition.",
  "Continui a spingere": "You keep pushing",
  "Non cambi un gioco che ha funzionato.": "You don't change a game that has worked.",
  "Il pubblico ama l'ostinazione. Il corpo un po' meno.": "The crowd loves the stubbornness. The body, a little less.",
  "Il rivale storico annuncia il ritiro": "Your long-time rival announces his retirement",
  "Un'era, quella con {RIVAL}, sta per chiudersi.": "An era, the one with {RIVAL}, is about to close.",
  "Parole di rispetto pubblico": "Words of public respect",
  "Chiudi il cerchio con eleganza.": "You close the circle with class.",
  "Il gesto viene applaudito da tutta la lega.": "The gesture is applauded across the league.",
  "Resti in silenzio": "You stay silent",
  "La rivalità è stata solo sul campo.": "The rivalry was only ever on the court.",
  "Non tutti capiscono. Tu sai che è stato reale.": "Not everyone understands. You know it was real.",
  "Lo staff propone un ruolo ridotto": "The staff proposes a reduced role",
  "Meno minuti, più impatto a partita in corso.": "Fewer minutes, more impact off the bench.",
  "Accetti il sesto uomo di lusso": "You accept being a luxury sixth man",
  "Il bene della squadra.": "The good of the team.",
  "Esci dalla titolarità. Entri nelle partite che contano.": "You leave the starting five. You step into the games that matter.",
  "Pretendi i minuti da titolare": "You demand starter's minutes",
  "Hai ancora qualcosa da dire.": "You still have something to say.",
  "Ottieni i minuti. Ogni possesso costa di più.": "You get the minutes. Every possession costs more.",
  "Uno sponsor ti propone un contratto ingombrante": "A sponsor offers you a demanding deal",
  "Più soldi, più visibilità, meno tempo libero.": "More money, more exposure, less free time.",
  "Accetti": "You accept",
  "Più visibilità mediatica.": "More media exposure.",
  "Il tuo volto inizia a comparire ovunque.": "Your face starts showing up everywhere.",
  "Rifiuti": "You decline",
  "Vuoi restare concentrato sul campo.": "You want to stay focused on the court.",
  "Lo staff apprezza le priorità chiare.": "The staff appreciates clear priorities.",
  "Un giornalista ti fa una domanda scomoda sullo spogliatoio": "A reporter asks you an awkward question about the locker room",
  "Il rapporto con {COACH} finisce sotto i riflettori.": "Your relationship with {COACH} ends up in the spotlight.",
  "Difendi l'allenatore": "You defend the coach",
  "Fai quadrato.": "You close ranks.",
  "Il gruppo si compatta attorno a te.": "The group rallies around you.",
  "Eviti di esporti": "You avoid exposing yourself",
  "Non è il momento.": "It's not the moment.",
  "Una risposta diplomatica, presto dimenticata.": "A diplomatic answer, soon forgotten.",
  "Piccolo infortunio alla caviglia in allenamento": "Minor ankle injury in practice",
  "Va gestito con attenzione.": "It has to be managed carefully.",
  "Ti alleni a carico ridotto": "You train on a reduced load",
  "Non vuoi fermarti.": "You don't want to stop.",
  "Tieni il ritmo, con un po' di rischio in più.": "You keep the rhythm, with a little more risk.",
  "Ti fermi qualche giorno": "You take a few days off",
  "Meglio sicuri.": "Better safe than sorry.",
  "Una pausa breve, utile più avanti.": "A short break, useful later on.",
  "Una vecchia intervista del rivale riemerge": "An old interview of your rival resurfaces",
  "Le parole di {RIVAL} tornano di moda.": "{RIVAL}'s words are back in fashion.",
  "La usi come motivazione": "You use it as motivation",
  "Parole in benzina.": "Words turned into fuel.",
  "Ogni allenamento ha un significato in più.": "Every practice means a little more.",
  "Non gli dai importanza": "You don't give it any weight",
  "Solo parole vecchie.": "Just old words.",
  "Resti concentrato su cose più importanti.": "You stay focused on more important things.",
  "La società esonera l'allenatore": "The club fires the coach",
  "{COACH} lascia la panchina: la squadra volta pagina.": "{COACH} leaves the bench: the team turns the page.",
  "Accogli il cambiamento": "You welcome the change",
  "Un nuovo inizio.": "A fresh start.",
  "Arriva {0}: il rapporto di fiducia riparte da zero.": "In comes {0}: the trust starts again from zero.",
  "Rimpiangi il vecchio sistema": "You miss the old system",
  "Fai più fatica ad adattarti.": "You struggle more to adapt.",
  "Con {0} l'ambientamento è più lento del previsto.": "With {0}, settling in takes longer than expected.",
  "Notte in bianco prima di una gara in nazionale mediatica": "A sleepless night before a nationally televised game",
  "Il corpo chiede sonno, la testa gira.": "The body wants sleep, the head is spinning.",
  "Chiudi tutto e dormi": "You shut everything off and sleep",
  "Recupero prima della luce.": "Recovery before daylight.",
  "Arrivi lucido. Poco contenuto per i social.": "You arrive sharp. Not much content for social media.",
  "Accetti l'evento e paghi dopo": "You do the event and pay later",
  "Visibilità ora, gambe dopo.": "Exposure now, legs later.",
  "Sei ovunque. In riscaldamento le gambe pesano.": "You're everywhere. In warm-ups your legs feel heavy.",
  "Il veterano della panchina ti prende da parte": "The bench veteran takes you aside",
  "Ti offre un consiglio che non tutti ricevono.": "He offers you advice not everyone gets.",
  "Ascolti e applichi": "You listen and apply it",
  "Angoli, tempi, dettagli da chi c'è già passato.": "Angles, timing, details from someone who has been there.",
  "Una frase in corridoio vale più di un filmato.": "One sentence in the hallway is worth more than a film session.",
  "Sorridi e fai a modo tuo": "You smile and do it your way",
  "Hai già un'idea di chi sei.": "You already have an idea of who you are.",
  "Restano due strade parallele nello stesso spogliatoio.": "Two parallel roads remain in the same locker room.",
  "Gli chiedi di allenarti dopo": "You ask him to train you after practice",
  "Due ore extra, ogni giorno.": "Two extra hours, every day.",
  "Il parquet vuoto, dopo gli altri, diventa la tua scuola.": "The empty floor, after everyone else has left, becomes your school.",
  "Un nuovo sistema offensivo": "A new offensive system",
  "{COACH} cambia tutto a metà stagione: meno isolamento, più movimento.": "{COACH} changes everything midseason: less isolation, more movement.",
  "Ti adatti per primo": "You adapt first",
  "Diventi il traduttore dello schema.": "You become the translator of the playbook.",
  "Il nuovo attacco gira intorno alle tue letture.": "The new offense runs through your reads.",
  "Chiedi i tuoi isolamenti": "You ask for your isolations",
  "Il tuo gioco ha portato fin qui.": "Your game is what got you here.",
  "Ottieni possessi. Lo staff segna la resistenza.": "You get possessions. The staff notes the resistance.",
  "Studi in silenzio": "You study in silence",
  "Niente dichiarazioni, solo compiti.": "No statements, just homework.",
  "Nessun titolo. Un giocatore diverso a marzo.": "No headlines. A different player by March.",
  "Una stella arriva in città": "A star comes to town",
  "La società manda a prendere un all-star. I minuti non si inventano.": "The club goes out and lands an All-Star. Minutes don't grow on trees.",
  "Accogli il nuovo riferimento": "You welcome the new go-to guy",
  "Meno palloni, più anelli possibili.": "Fewer touches, more possible rings.",
  "Il tuo ruolo cambia. La finestra del titolo si apre.": "Your role changes. The title window opens.",
  "Pretendi chiarezza sul tuo uso": "You demand clarity on how you'll be used",
  "Non vuoi sparire nel sistema.": "You don't want to disappear into the system.",
  "Ottieni un incontro. Non tutte le risposte ti piacciono.": "You get a meeting. Not all the answers please you.",
  "Alzi il livello in allenamento": "You raise the level in practice",
  "Se c'è una gerarchia, la vuoi guadagnare.": "If there's a pecking order, you want to earn your place in it.",
  "Lo spogliatoio nota chi arriva prima e resta dopo.": "The locker room notices who comes early and stays late.",
  "La gestione dei carichi: il dibattito": "Load management: the debate",
  "Lo staff propone di saltare il secondo di un back-to-back.": "The staff proposes sitting out the second night of a back-to-back.",
  "Accetti il piano": "You accept the plan",
  "Aprile vale più di gennaio.": "April is worth more than January.",
  "I tifosi fischiano. Il ginocchio ringrazia.": "The fans boo. The knee says thank you.",
  "Giochi tutte": "You play every game",
  "Il tuo nome è sulla maglia, non sul protocollo.": "Your name is on the jersey, not on the protocol.",
  "Il pubblico alza i cartelli. Il fisico prende nota.": "The crowd raises signs. The body takes note.",
  "Decidi gara per gara": "You decide game by game",
  "Un compromesso con i fisioterapisti.": "A compromise with the physios.",
  "Né eroe né assenteista. Una stagione gestita.": "Neither hero nor no-show. A managed season.",
  "Un rookie ti chiede di diventare il suo mentore": "A rookie asks you to be his mentor",
  "Ti guarda come tu guardavi i veterani, anni fa.": "He looks at you the way you looked at the veterans, years ago.",
  "Lo prendi sotto il tuo ala": "You take him under your wing",
  "Film, palestre vuote, telefonate a mezzanotte.": "Film, empty gyms, midnight phone calls.",
  "Inizi a lasciare qualcosa che non sta nel box score.": "You start leaving something that doesn't show up in the box score.",
  "Lo fai lavorare, senza sconti": "You make him work, no discounts",
  "La lezione è il livello, non la tenerezza.": "The lesson is the level, not tenderness.",
  "Lui cresce. Tu resti tagliente.": "He grows. You stay sharp.",
  "Non è il tuo mestiere": "It's not your job",
  "Hai ancora una carriera da chiudere.": "You still have a career to finish.",
  "Efficiente. Un po' più solo, in fondo al bus.": "Efficient. A little more alone, at the back of the bus.",
  "Una città ti offre la panchina, un giorno": "A city offers you the bench, one day",
  "Non ora. Ma il nome gira già tra i dirigenti.": "Not now. But your name is already going around among executives.",
  "Inizi a pensarti allenatore": "You start thinking of yourself as a coach",
  "Più schemi, meno strappi.": "More sets, fewer bursts.",
  "Vedi il campo da un'altra altezza, già da giocatore.": "You see the floor from a different height, while still a player.",
  "Sei ancora un giocatore": "You're still a player",
  "Il resto arriverà, se arriverà.": "The rest will come, if it comes.",
  "Chiudi la porta all'ufficio. Apri quella della palestra.": "You close the office door. You open the gym door.",
  "Una notte fuori finisce sui tabloid": "A night out ends up in the tabloids",
  "Niente illegale. Abbastanza per i titoli.": "Nothing illegal. Enough for the headlines.",
  "Ti scusi e sparisci": "You apologize and disappear",
  "Una settimana di silenzio, poi il lavoro.": "A week of silence, then work.",
  "La notizia muore. Lo staff respira.": "The story dies. The staff breathes.",
  "Rispondi a tono sui social": "You fire back on social media",
  "Non sei un santo, e non fai finta.": "You're no saint, and you don't pretend to be.",
  "Una parte del pubblico applaude. I veterani no.": "Part of the crowd applauds. The veterans don't.",
  "Trasformi tutto in beneficenza": "You turn it all into charity",
  "Visibilità pagata in un altro modo.": "Exposure paid for in another way.",
  "I tabloid restano. Cambia il sottotitolo.": "The tabloids stay. The subtitle changes.",
  "Il fisico ti chiede un mese diverso": "Your body asks you for a different month",
  "Meno carico, o un'estate da record. Non entrambi.": "Less load, or a record summer. Not both.",
  "Scarico e prevenzione": "Rest and prevention",
  "Arrivi intero a ottobre.": "You get to October in one piece.",
  "Niente highlight estivi. Un ottobre pulito.": "No summer highlights. A clean October.",
  "Un laboratorio tecnico": "A technical lab",
  "Tre nuovi movimenti, un costo fisico.": "Three new moves, a physical cost.",
  "A settembre il tiro ha un'altra uscita.": "By September the jumper has a different release.",
  "Campo e pesi, senza sconti": "Court and weights, no discounts",
  "Vuoi il primo passo di due anni fa.": "You want the first step you had two years ago.",
  "I numeri in palestra salgono. Qualcosa scricchiola.": "The gym numbers go up. Something creaks."
};
