/* English narrative for engine. Key: Italian source text (see ../key.ts). */
export const EN_ENGINE: Readonly<Record<string, string>> = {
  "Coach": "Coach",
  "{0} punti": "{0} points",
  "{0} rimbalzi": "{0} rebounds",
  "{0} assist": "{0} assists",
  "{0} palle rubate e {1} stoppate": "{0} steals and {1} blocks",
  "L'anno prima hai chiuso a {0}.": "The year before, you finished at {0}.",
  "proc-{0}-{1}": "proc-{0}-{1}",
  "A {0} anni il corpo manda il conto": "At {0}, the body sends the bill",
  "{0} anni, {1}. Il ginocchio avvisa prima del referto. Come rispondi?": "{0} years old, {1}. The knee speaks before the medical report does. How do you answer?",
  "Tagli i minuti": "You cut the minutes",
  "Meno partite, più giorni interi.": "Fewer games, more full days.",
  "Esci prima. Il referto, il giorno dopo, è più corto.": "You leave early. The next day's report is shorter.",
  "Salti due chiusure. Il passo, al rientro, è il tuo.": "You skip two closing stretches. When you come back, the step is yours.",
  "Giochi comunque": "You play anyway",
  "Il gruppo ha bisogno di te stasera.": "The group needs you tonight.",
  "Resti in campo. Il pubblico lo vede. Il corpo anche.": "You stay on the floor. The crowd sees it. So does the body.",
  "Chiudi la partita zoppicando. La vittoria non cura il ginocchio.": "You finish the game limping. The win doesn't heal the knee.",
  "Lavoro in palestra, lontano": "Gym work, out of sight",
  "Niente applausi. Solo il gesto corretto.": "No applause. Only the right movement.",
  "La porta della palestra si chiude. Fuori non succede niente. Dentro sì.": "The gym door closes. Outside, nothing happens. Inside, it does.",
  "A {0} anni {1} ti cerca": "At {0}, {1} comes looking for you",
  "{0} tiene il conto, e {1} lo sa. Non è un discorso. È una partita.": "{0} is keeping score, and {1} knows it. This is not a speech. It's a game.",
  "Gli rispondi a canestro": "You answer him at the rim",
  "Il primo possesso è tuo.": "The first possession is yours.",
  "{0} parla. Tu segni. La discussione finisce sul tabellone.": "{0} talks. You score. The argument ends on the scoreboard.",
  "Lo ignori": "You ignore him",
  "Il sistema vale più del duello.": "The system matters more than the duel.",
  "Non lo guardi. L'allenatore, dagli spalti, se ne accorge.": "You don't even look at him. The coach notices from the sideline.",
  "Alzi il tono in sala stampa": "You raise your voice in the press room",
  "Una frase, e la città si accende.": "One sentence, and the city lights up.",
  "La frase resta. La città sta dalla tua parte.": "The quote sticks. The city is on your side.",
  "La frase resta. Il giorno dopo sembra più grande di te.": "The quote sticks. The next day it looks bigger than you.",
  "A {0} anni scade il contratto": "At {0}, the contract is running out",
  "{0} anni, {1}. A giugno il foglio scade. Ogni possesso, da qui, ha un prezzo.": "{0} years old, {1}. In June the deal expires. From here on, every possession has a price.",
  "Gioca per il rinnovo": "You play for the extension",
  "Numeri puliti, zero teatro.": "Clean numbers, zero theater.",
  "Non chiedi niente a microfono acceso. Chiedi con le medie.": "You don't ask for anything with the mic on. You ask with your averages.",
  "Chiedi di cambiare aria": "You ask for a change of scenery",
  "Meglio una panchina onesta che un anno finto.": "Better an honest bench than a fake year.",
  "Lo dici all'agente, poi allo staff. La voce arriva prima del comunicato.": "You tell your agent, then the staff. The rumor arrives before the press release.",
  "Sta' zitto e produci": "You shut up and produce",
  "Il mercato parla a giugno.": "The market speaks in June.",
  "Nessuna dichiarazione. A giugno i numeri sono già sul tavolo.": "No statements. In June the numbers are already on the table.",
  "A {0} anni il ferro è freddo": "At {0}, the rim has gone cold",
  "{0} vince e perde. Il tuo tiro, in queste settimane, non collabora.": "{0} wins and loses. Your jumper, these past weeks, isn't cooperating.",
  "Tiri ancora": "You keep shooting",
  "La fiducia si allena, non si aspetta.": "Confidence is trained, not waited for.",
  "Il primo non entra. Il quarto sì. Lo spogliatoio respira.": "The first one doesn't fall. The fourth does. The locker room breathes.",
  "Servi gli altri": "You feed the others",
  "Il canestro può aspettare. Il compagno no.": "The basket can wait. Your teammate can't.",
  "Smetti di cercare il tuo tiro. La squadra trova il suo.": "You stop hunting your shot. The team finds its own.",
  "Una settimana di lavoro muto": "A week of silent work",
  "Niente interviste finché il gesto non torna.": "No interviews until the stroke comes back.",
  "Chiudi la porta. Quando la riapri, il rilascio è di nuovo il tuo.": "You close the door. When you open it again, the release is yours again.",
  "A {0} anni la città ti cerca": "At {0}, the city is looking for you",
  "{0} anni, e il gioco si vede dal primo quarto. {1} ti mette al centro di tutto.": "{0} years old, and it shows from the first quarter. {1} puts you at the center of everything.",
  "Ti prendi i possessi": "You take the possessions",
  "Quando entra, non lo restituisci.": "When it's falling, you don't give it back.",
  "Il pallone resta nelle tue mani. Qualcuno deve fare spazio.": "The ball stays in your hands. Someone has to make room.",
  "Lo dividi": "You share it",
  "Il momento è della squadra, non solo tuo.": "The moment belongs to the team, not just to you.",
  "Un assist al momento giusto vale più di un altro canestro tuo.": "An assist at the right moment is worth more than another bucket of your own.",
  "Abbassi il volume": "You turn the volume down",
  "Niente copertine. Domani c'è un'altra partita.": "No magazine covers. There's another game tomorrow.",
  "Esci dall'ingresso secondario. Il lavoro di domani è già scritto.": "You leave through the side entrance. Tomorrow's work is already written.",
  "A {0} anni i minuti non arrivano": "At {0}, the minutes aren't coming",
  "L'allenatore di {0} non ti cerca. Il quinto posto in panchina, invece, ti conosce per nome.": "The {0} coach isn't looking your way. The fifth seat on the bench, on the other hand, knows you by name.",
  "Chiedi un chiarimento": "You ask for an explanation",
  "Una frase chiara, a porte chiuse.": "One clear sentence, behind closed doors.",
  "Non alzi la voce. Chiedi il perché. La risposta, almeno, è vera.": "You don't raise your voice. You ask why. The answer, at least, is honest.",
  "Resti pronto": "You stay ready",
  "Quando ti chiama, tu sei già in piedi.": "When he calls you, you're already on your feet.",
  "Entri a metà quarto. Il primo possesso è pulito. L'allenatore annuisce.": "You check in midway through the quarter. The first possession is clean. The coach nods.",
  "Cerchi un'altra porta": "You look for another door",
  "Meglio un ruolo vero, anche altrove.": "Better a real role, even somewhere else.",
  "L'agente fa due telefonate. Tu, intanto, continui a scaldarti.": "Your agent makes two phone calls. Meanwhile, you keep warming up.",
  "A {0} anni il primo passo è più corto": "At {0}, the first step is shorter",
  "{0} anni. Il salto non è più quello dei venti. Il gioco, se vuoi, può esserlo.": "{0} years old. The bounce isn't what it was at twenty. The game, if you want, can be.",
  "Cambi il modo": "You change your approach",
  "Meno esplosione, più lettura.": "Less explosion, more reading.",
  "Arrivi un passo prima, non un palmo più in alto. Basta, e avanza.": "You get there a step early, not a hand higher. It's enough, and then some.",
  "Insisti sul fisico": "You double down on the body",
  "Un'altra estate di pesi e corsa.": "Another summer of weights and running.",
  "Il corpo risponde ancora. Non per tutta la stagione, ma risponde.": "The body still answers. Not for the whole season, but it answers.",
  "Fai giocare i giovani": "You let the young guys play",
  "Il tuo valore, adesso, è anche il loro.": "Your value, now, is theirs too.",
  "Un consiglio a bordo campo vale un canestro che non segni più.": "A word from the sideline is worth a basket you no longer score.",
  "A {0} anni i numeri chiedono un ruolo": "At {0}, the numbers demand a role",
  "{0} punti non stanno in un ruolo da quinto violino. {1} deve decidere chi comanda.": "{0} points don't fit in a fifth-fiddle role. {1} has to decide who's in charge.",
  "Le cifre dell'anno prima sono già un argomento. {0} può alzare il tuo uso, o tenerti dov'eri.": "Last year's numbers are already an argument. {0} can raise your usage, or keep you where you were.",
  "Chiedi i possessi": "You ask for the possessions",
  "Chiedi più minuti": "You ask for more minutes",
  "Il ruolo deve somigliare alle cifre.": "The role should match the numbers.",
  "Il palleggio arriva più spesso. Con lui, anche la responsabilità.": "The ball comes your way more often. With it, the responsibility.",
  "Lo staff allunga il tuo turno. Il resto lo fai in campo.": "The staff stretches your shift. The rest you do on the floor.",
  "Resti nello schema": "You stay within the system",
  "I numeri vanno bene anche senza un discorso.": "The numbers are fine even without a speech.",
  "Non sposti nessuno. Segni lo stesso, e lo spogliatoio resta intero.": "You don't push anyone aside. You score anyway, and the locker room stays whole.",
  "Difesa prima del tiro": "Defense before the shot",
  "Un altro modo di pesare, oltre il tabellino.": "Another way to make your weight felt, beyond the box score.",
  "Il primo possesso lo passi a togliere il tiro. Poi arriva il tuo.": "You spend the first possession taking away their shot. Then yours comes.",
  "A {0} anni l'area non perdona": "At {0}, the paint doesn't forgive",
  "A {0} anni la regia è tua": "At {0}, the offense is yours to run",
  "A {0} anni il lato debole è libero": "At {0}, the weak side is open",
  "{0} ti vuole sotto canestro. Ogni rimbalzo, stasera, ha un nome.": "{0} wants you under the basket. Tonight every rebound has a name.",
  "{0} ti consegna il pallone. Il ritmo della sera dipende da te.": "{0} hands you the ball. The rhythm of the night depends on you.",
  "{0} anni da {1}. {2} ti chiede di scegliere un lato e restarci.": "{0} years old as a {1}. {2} asks you to pick a side and stay there.",
  "Chiudi l'area": "You lock down the paint",
  "Alzi il ritmo": "You push the pace",
  "Attacchi per primo": "You attack first",
  "Il tuo gioco, senza chiedere il permesso.": "Your game, without asking permission.",
  "Una stoppata cambia il quarto. L'area, per un po', è tua.": "One block changes the quarter. For a while, the paint is yours.",
  "Il primo passaggio arriva prima della difesa. Il canestro è una conseguenza.": "The first pass arrives before the defense does. The basket is a consequence.",
  "Prendi la linea e tiri. Il ferro, stavolta, collabora.": "You take the lane and shoot. This time the rim cooperates.",
  "Stai nello schema": "You stay within the play",
  "Il disegno vale più dell'iniziativa.": "The design matters more than initiative.",
  "Esegui. Non è spettacolo. È una vittoria che non fa rumore.": "You execute. It's not a show. It's a win that makes no noise.",
  "Una sera da gregario": "A role-player's night",
  "Qualcun altro segna. Tu gli togli il difensore.": "Someone else scores. You take his defender away.",
  "Nessuno dice il tuo nome al microfono. Nello spogliatoio, sì.": "Nobody says your name on the mic. In the locker room, they do.",
  "rival-{0}": "rival-{0}",
  "Lo scontro con {0}": "The showdown with {0}",
  "{0} ti sfida a viso aperto davanti a tutta la lega.": "{0} challenges you openly in front of the whole league.",
  "Rispondi a canestro": "You answer with buckets",
  "Lasci parlare il gioco.": "You let your game do the talking.",
  "Rispondi sul parquet. La rivalità diventa personale.": "You answer on the floor. The rivalry gets personal.",
  "Gioco di squadra": "Team basketball",
  "Resti professionale.": "You stay professional.",
  "La maturità impressiona più di qualsiasi schiacciata.": "Maturity impresses more than any dunk.",
  "Botta e risposta mediatico": "A war of words in the media",
  "Alzi il tono in conferenza.": "You turn up the volume at the press conference.",
  "Il pubblico ama il duello.": "The crowd loves the duel.",
  "Qualcuno inizia a considerarti arrogante.": "Some people start to think you're arrogant.",
  "injury-{0}": "injury-{0}",
  "Un infortunio serio": "A serious injury",
  "Il fisico aveva già dato segnali.": "Your body had already sent signals.",
  "A metà carriera un problema fisico ti ferma sul serio.": "Midway through your career, a physical problem stops you for real.",
  "Riabilitazione aggressiva": "Aggressive rehab",
  "Torni prima, il fisico ne risente.": "You come back sooner; your body pays for it.",
  "Torni veloce. Il primo passo non è più lo stesso.": "You come back fast. The first step isn't the same anymore.",
  "Percorso prudente": "The cautious route",
  "Salti partite, torni intero.": "You miss games, you come back whole.",
  "La strada lunga: perdi tempo, torni davvero.": "The long road: you lose time, you truly come back.",
  "Chirurgia sperimentale": "Experimental surgery",
  "Rischio alto, possibile ripresa piena.": "High risk, a chance at a full recovery.",
  "L'intervento va oltre le aspettative.": "The operation goes beyond expectations.",
  "La scommessa non paga: ripresa lunga e dolorosa.": "The gamble doesn't pay off: a long, painful recovery.",
  "la Nazionale Italiana": "the Italian national team",
  "la tua Nazionale": "your national team",
  "nation-{0}": "nation-{0}",
  "Convocazione internazionale": "International call-up",
  "{0} ti chiama per il grande torneo dell'estate.": "{0} calls you up for the big summer tournament.",
  "Accetti e guidi la squadra": "You accept and lead the team",
  "Rischi di più, per un sogno più grande.": "You risk more, for a bigger dream.",
  "Medaglia internazionale": "International medal",
  "Porti a casa una medaglia con {0}.": "You bring home a medal with {0}.",
  "Avventura con {0} senza medaglia, a testa alta.": "A run with {0} without a medal, head held high.",
  "Rifiuti per riposare": "You decline to rest",
  "Pensi alla stagione di club.": "You think about the club season.",
  "Le critiche arrivano. Tu arrivi fresco.": "The criticism comes. You come in fresh.",
  "Ruolo ridotto": "A reduced role",
  "Un compromesso.": "A compromise.",
  "Dai una mano a {0} senza esporti troppo.": "You help {0} without overexposing yourself.",
  "quiet-{0}-{1}": "quiet-{0}-{1}",
  "Lavoro silenzioso": "Quiet work",
  "Niente dichiarazioni. Solo ripetizioni.": "No statements. Only reps.",
  "Chiudi la porta della palestra. Fuori non succede niente. Dentro sì.": "You close the gym door. Outside, nothing happens. Inside, it does.",
  "Nessuna intervista. Il gesto, ripetuto, diventa un altro gesto.": "No interviews. The motion, repeated, becomes a different motion.",
  "Lo staff nota l'orario, non la voce. È quello che volevi.": "The staff notices the hours, not the voice. That's what you wanted.",
  "Stai col gruppo": "You stick with the group",
  "Cene, filmati, il resto.": "Dinners, film sessions, the rest.",
  "Una settimana da spogliatoio. Serve, anche quando non fa notizia.": "A locker-room week. It matters, even when it doesn't make the news.",
  "Ridi alle battute giuste. Il gruppo si accorcia di un palmo.": "You laugh at the right jokes. The group gets a little closer.",
  "Non sei il centro. Sei il collante, e per una volta ti sta bene.": "You're not the center. You're the glue, and for once that suits you.",
  "Una sera per te": "A night for yourself",
  "Spegni il telefono. Domani c'è.": "You switch off the phone. Tomorrow will still be there.",
  "Una notte senza schema. Il giorno dopo il tiro esce più pulito.": "A night without a playbook. The next day the shot comes out cleaner.",
  "Chiudi gli occhi prima delle undici. Sembra poco. Non lo è.": "You close your eyes before eleven. It sounds like little. It isn't.",
  "Il silenzio, scelto, vale più di un'altra sessione stanca.": "Silence, when you choose it, is worth more than another tired session.",
  "Prima stagione da professionista. I minuti non si regalano, e il Rookie of the Year nemmeno. Come vuoi presentarti?": "Your first season as a pro. Minutes aren't handed out, and neither is Rookie of the Year. How do you want to introduce yourself?",
  "Uso aggressivo": "Aggressive usage",
  "Palloni, tiri, responsabilità. La corsa al Rookie of the Year parte da te.": "Touches, shots, responsibility. The Rookie of the Year race starts with you.",
  "Ti prendi i possessi. Qualcuno in spogliatoio deve fare spazio.": "You take the possessions. Someone in the locker room has to make room.",
  "Impara il sistema": "Learn the system",
  "Meno numeri subito, più fiducia dello staff.": "Fewer numbers right away, more trust from the staff.",
  "I minuti arrivano perché sei utile, non perché sei rumoroso.": "The minutes come because you're useful, not because you're loud.",
  "Impatto a due vie": "Two-way impact",
  "Difesa, rimbalzi, i dettagli che chiudono le gare.": "Defense, rebounds, the details that close out games.",
  "Lo staff si fida delle tue chiusure sul perimetro prima dei tuoi tiri.": "The staff trusts your perimeter closeouts before your shots.",
  "Iso sul possesso decisivo": "Iso on the deciding possession",
  "Te la giochi tu, in prima persona.": "You take it on yourself, personally.",
  "Il possesso è tuo. Il palazzetto lo sa.": "The possession is yours. The arena knows it.",
  "Il passaggio extra": "The extra pass",
  "Ti fidi del sistema e del compagno libero.": "You trust the system and the open teammate.",
  "Il passaggio arriva pulito. Il palazzetto capisce dopo.": "The pass arrives clean. The arena understands a moment later.",
  "Alza l'intensità difensiva": "Raise the defensive intensity",
  "Partita da spogliatoio, non da highlight.": "A locker-room game, not a highlight game.",
  "Il fiato brucia. Loro sentono il contatto.": "Your lungs burn. They feel the contact.",
  "Gioco fisico, ogni possesso": "Physical play, every possession",
  "Contatto, box-out, niente regali.": "Contact, box-outs, no gifts.",
  "Ogni rimbalzo è una piccola guerra.": "Every rebound is a small war.",
  "Attacca il mismatch subito": "Attack the mismatch right away",
  "Una partita sola: scegli il vantaggio e costringili ad aiutare.": "One game only: pick the advantage and force them to help.",
  "Il primo vantaggio è tuo. Adesso devono scegliere cosa concedere.": "The first advantage is yours. Now they have to choose what to give up.",
  "Fai la lettura giusta": "Make the right read",
  "Rallenta il possesso, chiama il compagno libero e non forzare il tiro.": "Slow the possession down, find the open teammate and don't force the shot.",
  "Il vantaggio arriva dalla lettura. Il passaggio giusto sposta tutta la difesa.": "The advantage comes from the read. The right pass moves the whole defense.",
  "Alza il livello in difesa": "Raise your level on defense",
  "Proteggi l'area e obbliga l'avversario a guadagnarsi ogni canestro.": "Protect the paint and make the opponent earn every basket.",
  "Ogni rimbalzo è un possesso in più. Ogni arresto, una porta chiusa.": "Every rebound is an extra possession. Every stop, a door slammed shut.",
  "Prendi il controllo della serie": "Take control of the series",
  "Più uso, più responsabilità. Se sbagli, è tua.": "More usage, more responsibility. If you miss, it's on you.",
  "La serie cambia spalla. Ora è sulla tua.": "The series changes shoulders. Now it's on yours.",
  "Fidati dello staff": "Trust the staff",
  "Esegui il piano. Niente eroismi.": "Run the game plan. No heroics.",
  "Il piano tiene. Tu tieni il piano.": "The plan holds. You hold to the plan.",
  "Cambia i matchup in difesa": "Switch the defensive matchups",
  "Chiedi i compiti sporchi sul loro migliore.": "You ask for the dirty work on their best player.",
  "Il loro migliore suda di più. È già qualcosa.": "Their best player sweats more. That's already something.",
  "Il tiro che ti definirà": "The shot that will define you",
  "Quando la palla arriva, non la passi.": "When the ball comes, you don't pass it.",
  "Il palazzetto trattiene il fiato con te.": "The arena holds its breath with you.",
  "Fai grandi i compagni": "Make your teammates great",
  "L'anello è di tutti, o non è di nessuno.": "The ring belongs to everyone, or to no one.",
  "L'assist che chiude una serie pesa come un canestro.": "The assist that closes out a series weighs as much as a basket.",
  "Partita da guerra": "A war of a game",
  "Ogni rimbalzo, ogni chiusura sul perimetro, ogni secondo.": "Every rebound, every perimeter closeout, every second.",
  "Finiamo con le ginocchia sporche. È il modo giusto.": "We finish with dirty knees. That's the right way.",
  "Campione": "Champion",
  "Titolo, {SCORE} su {OPP}.": "Title, {SCORE} over {OPP}.",
  "Partita vinta {SCORE} contro {OPP}.": "Game won {SCORE} against {OPP}.",
  "Serie vinta {SCORE} su {OPP}.": "Series won {SCORE} over {OPP}.",
  "Elim. {0} {1}": "Out: {0} {1}",
  "Sconfitta {SCORE} contro {OPP}. Stagione finita.": "Lost {SCORE} to {OPP}. Season over.",
  "Eliminati {SCORE} da {OPP}.": "Eliminated {SCORE} by {OPP}.",
  "Rinnovo. Resta la casa che ti ha formato.": "Extension. Stay at the home that made you.",
  "Restare. I corridoi li conosci, e questo, a volte, vale più della cifra.": "Staying. You know the hallways, and sometimes that's worth more than the number.",
  "La dirigenza vuole continuità. Tu sei la continuità.": "The front office wants continuity. You are the continuity.",
  "Stessa maglia, altri anni. Il pubblico lo ha già deciso.": "Same jersey, more years. The crowd has already decided.",
  "Casa. I numeri sul contratto contano, i corridoi di più.": "Home. The numbers on the contract matter; the hallways matter more.",
  "Restare qui. Lo staff non lo dice come una preghiera: lo dice come un piano.": "Staying here. The staff doesn't say it like a prayer: they say it like a plan.",
  "Rinnovo a {0}.": "Extension with {0}.",
  "Meno soldi, un vero contendente. L'anello è il contratto.": "Less money, a real contender. The ring is the contract.",
  "Vieni a vincere. Lo stipendio è il prezzo, giugno è la merce.": "Come and win. The salary is the price; June is the prize.",
  "Un roster da titolo. Ti chiedono di essere il pezzo che manca, non il volto.": "A title roster. They're asking you to be the missing piece, not the face.",
  "Meno milioni, più aprile. La proposta è chiara.": "Fewer millions, more April. The offer is clear.",
  "Giugno, non la cifra più alta. La cifra è il pedaggio.": "June, not the highest figure. The figure is the toll.",
  "Un contendente vero. I soldi arrivano dopo, se arrivano.": "A real contender. The money comes later, if it comes.",
  "Offerta da contendente: {0}.": "Contender's offer: {0}.",
  "Ruolo da riferimento, soldi di mercato, progetto solido.": "A lead role, market money, a solid project.",
  "Un equilibrio: minuti, cifra, una piazza che non ti chiede di essere Dio.": "A balance: minutes, money, a market that doesn't ask you to be God.",
  "Mercato vero, ruolo vero. Niente promesse da copertina.": "Real market, real role. No cover-story promises.",
  "Ti vogliono al centro, senza spaccare il salario.": "They want you at the center, without breaking the cap.",
  "Una piazza di mezzo. I minuti ci sono, le scuse no.": "A mid-table market. The minutes are there; the excuses aren't.",
  "Né massimo né miseria. Un mestiere, detto chiaro.": "Neither a max deal nor peanuts. A job, said plainly.",
  "Offerta di mercato: {0}.": "Market offer: {0}.",
  "Il contratto più ricco. I soldi arrivano prima del progetto.": "The richest contract. The money comes before the project.",
  "La cifra più alta. Il resto, dicono, si costruisce intorno.": "The highest figure. The rest, they say, gets built around it.",
  "La cifra più alta. La piazza ricostruisce, e tu sei il cartellone.": "The highest figure. The market is rebuilding, and you're the billboard.",
  "Più soldi di tutti. Lo sanno, e lo usano come argomento.": "More money than anyone. They know it, and they use it as an argument.",
  "La cifra parla prima dello schema. Lo schema, dicono, arriverà.": "The money talks before the system. The system, they say, will come.",
  "Soldi veri, progetto da scrivere. Il foglio è già firmato sulla riga della cifra.": "Real money, a project still to be written. The sheet is already signed on the dollar line.",
  "Il contratto massimo: {0}.": "The max contract: {0}.",
  "Eurolega: un altro palcoscenico, un'altra gloria.": "EuroLeague: another stage, another kind of glory.",
  "Europa. Palazzetti pieni, tattica stretta, un ultimo atto diverso.": "Europe. Packed arenas, tight tactics, a different final act.",
  "Un campionato che parla un'altra lingua. L'anello, lì, ha un altro peso.": "A league that speaks another language. Over there, a ring carries a different weight.",
  "Un'altra geografia. I palazzetti più piccoli, le coppe più lunghe.": "Another geography. Smaller arenas, longer cup runs.",
  "Eurolega. Un ultimo atto in un'altra lingua, con la stessa palla.": "EuroLeague. A last act in another language, with the same ball.",
  "Eurolega: {0}.": "EuroLeague: {0}.",
  "Due anni per dimostrare che il picco non è alle spalle.": "Two years to show the peak is not behind you.",
  "Un contratto corto, una chance lunga. Tocca a te riempirla.": "A short contract, a long chance. It's up to you to fill it.",
  "Prove. Minuti, fiducia, niente alibi di lungo periodo.": "A prove-it deal. Minutes, trust, no long-term alibis.",
  "Due inverni. Basta per dirsi ancora, o per chiudere.": "Two winters. Enough to say you're still here, or to close the book.",
  "Un biennio per farsi rivedere. Niente scuse di lungo contratto.": "Two years to get noticed again. No long-contract excuses.",
  "Due anni a {0}.": "Two years with {0}.",
  "{CLUB} vuole un pezzo da titolo. Minuti veri, pressione vera.": "{CLUB} wants a piece for a title run. Real minutes, real pressure.",
  "{CLUB} caccia giugno. Ti chiedono di arrivare già pronto.": "{CLUB} is chasing June. They want you to arrive ready.",
  "Da contendente, {CLUB} offre il ruolo che i playoff non perdonano.": "As a contender, {CLUB} offers the kind of role the playoffs don't forgive.",
  "{CLUB} è in corsa. Ti vogliono per chiudere, non per ricostruire.": "{CLUB} is in the race. They want you to close, not to rebuild.",
  "{CLUB} vuole un pezzo da titolo.": "{CLUB} wants a piece for a title run.",
  "{CLUB} offre un ruolo da riferimento in un progetto a metà strada.": "{CLUB} offers a lead role in a project halfway there.",
  "{CLUB} non è in cima, non è in fondo. Ti vuole come volto, non come salvezza.": "{CLUB} is neither at the top nor at the bottom. They want you as the face, not as a savior.",
  "Un passo di lato, verso {CLUB}: minuti, responsabilità, niente scuse.": "A step sideways, toward {CLUB}: minutes, responsibility, no excuses.",
  "{CLUB} mette sul tavolo un ruolo da riferimento, senza promettere giugno.": "{CLUB} puts a lead role on the table, without promising June.",
  "{CLUB} offre un ruolo da riferimento.": "{CLUB} offers a lead role.",
  "{CLUB} ricostruisce. Minuti subito, vittorie dopo — se arrivano.": "{CLUB} is rebuilding. Minutes now, wins later — if they come.",
  "A {CLUB} sei il progetto, non il complemento. I minuti non mancano.": "At {CLUB} you're the project, not the add-on. Minutes won't be a problem.",
  "{CLUB} è in basso. Ti danno le chiavi, e il peso che ne viene.": "{CLUB} is near the bottom. They hand you the keys, and the weight that comes with them.",
  "Ricostruzione a {CLUB}: possessi tuoi, classifica da scrivere.": "Rebuild at {CLUB}: your possessions, a standings table still to be written.",
  "{CLUB} ricostruisce intorno a te.": "{CLUB} is rebuilding around you.",
  "Scambio estivo": "Summer trade",
  "Ritiro": "Retirement",
  "Gioca a 36 anni": "Play at 36",
  "Chiudi ora": "Retire now",
  "Estate chiusa": "Summer over",
  "Luglio è passato. Settembre legge il passo.": "July is gone. September reads your step.",
  "{0} {1} ({2}) è nel foglio.": "{0} {1} ({2}) is on the sheet.",
  "Estate di tregua": "A summer of truce",
  "Il corpo ha chiesto tregua. Gliel'hai data.": "Your body asked for a truce. You gave it one.",
  "Overall {0} → {1} ({2}{3})": "Overall {0} → {1} ({2}{3})",
  "Nelle partite chiuse il polso non trema: il possesso diventa un compito, non un giudizio.": "In close games your wrist doesn't shake: the possession becomes a task, not a verdict.",
  "Quando il cronometro stringe, gli altri cercano te. Tu cerchi lo spazio, non l'applauso.": "When the clock tightens, the others look for you. You look for space, not applause.",
  "Gli ultimi possessi ti trovano già pronto. Il silenzio del palazzetto, a te, non pesa.": "The last possessions find you already ready. The arena's silence doesn't weigh on you.",
  "Gli ultimi possessi ti pesano più del dovuto: il corpo arriva, la testa arriva un secondo dopo.": "The last possessions weigh on you more than they should: the body gets there, the head a second later.",
  "Nelle chiusure il parquet si allunga. Non è paura: è un conto che non torna ancora.": "In crunch time the floor gets longer. It's not fear: it's a sum that doesn't add up yet.",
  "Quando la partita chiede una firma, tu senti troppe voci. Il gesto ne risente.": "When the game asks for a signature, you hear too many voices. The stroke suffers.",
  "Nelle chiusure sei credibile, non ancora inevitabile. Il mestiere c'è: manca l'abitudine a firmarle.": "In crunch time you're credible, not yet inevitable. The skill is there; the habit of closing isn't.",
  "I possessi caldi non ti spaventano, ma non ti appartengono ancora. Un altro ottobre, forse.": "Hot possessions don't scare you, but they don't belong to you yet. Another October, maybe.",
  "Quando il palazzetto trattiene il fiato, tu resti nel mezzo: né eroe, né assente.": "When the arena holds its breath, you stay in the middle: neither hero nor absent.",
  "Il fisico manda segnali. Ogni estate conta, e non tutte le estati restituiscono lo stesso corpo.": "The body is sending signals. Every summer counts, and not every summer gives you back the same body.",
  "Le ginocchia parlano prima dello staff. Tu fai finta di non sentire, ma il calendario no.": "Your knees speak before the staff does. You pretend not to hear, but the calendar doesn't.",
  "Il corpo tiene a giorni alterni. La carriera, da qui, si misura nei recuperi, non nei colpi da copertina.": "The body holds up every other day. From here, the career is measured in recoveries, not highlight plays.",
  "Il corpo tiene, anche quando gli altri si fermano. Lo staff lo nota più dei giornali.": "The body holds up, even when others go down. The staff notices it more than the papers do.",
  "Le notti si accumulano e tu resti in campo. Non è rumore: è un vantaggio silenzioso.": "The nights pile up and you stay on the floor. It's not noise: it's a silent advantage.",
  "La disponibilità è già un talento. Tu ci sei, partita dopo partita, e la panchina lo sa.": "Availability is already a talent. You're there, game after game, and the bench knows it.",
  "Il corpo risponde, con qualche conto da pagare a marzo. Niente allarmi, niente certezze.": "The body answers, with a few bills to pay in March. No alarms, no certainties.",
  "Una stagione intera è un mestiere di gestione. Tu non sei di vetro, e non sei di ferro.": "A full season is a job of management. You're not made of glass, and you're not made of iron.",
  "Lo staff parla del tuo orario, non dei tuoi highlight. La palestra si accende prima di te, e tu ci sei già.": "The staff talks about your hours, not your highlights. The gym lights come on before you arrive, and you're already there.",
  "Il lavoro extra non è una dichiarazione. È una stanza, un orario, un gesto ripetuto finché diventa tuo.": "Extra work isn't a statement. It's a room, a schedule, a motion repeated until it becomes yours.",
  "Arrivi prima. Restiamo. È l'unica biografia che lo staff racconta senza giri di parole.": "You arrive early. You stay late. It's the only biography the staff tells without beating around the bush.",
  "In palestra arrivi. Non sempre resti. Il talento copre, per ora: non coprirà per sempre.": "You show up to the gym. You don't always stay. Talent covers for it, for now: it won't cover forever.",
  "Il gesto naturale ti salva le settimane pigre. Lo staff lo vede, e non è un complimento.": "Natural feel saves your lazy weeks. The staff sees it, and it's not a compliment.",
  "C'è un margine che non stai usando. Si vede da come esci, non da come entri.": "There's a margin you're not using. It shows in how you leave, not in how you arrive.",
  "Lavori quanto basta per restare nel giro. Qualcuno, in palestra, fa di più: lo senti.": "You work just enough to stay in the mix. Someone in the gym does more: you can feel it.",
  "La disciplina c'è, senza diventare una religione. Un gradino sopra, o uno sotto: lo scegli tu.": "The discipline is there, without becoming a religion. One step up, or one down: your call.",
  "In spogliatoio qualcuno gira intorno al tuo nome. A {0} il volume si alza quando entri.": "In the locker room, people tiptoe around your name. In {0} the volume rises when you walk in.",
  "Il tuo nome pesa più della maglia, qualche sera. Non tutti in cerchio lo digeriscono.": "Some nights your name weighs more than the jersey. Not everyone in the huddle swallows that.",
  "Vuoi la palla, e lo dici col corpo. La squadra può seguirti, o può stancarsi.": "You want the ball, and your body says so. The team can follow you, or it can get tired of it.",
  "Passi la palla anche quando il tiro c'è. Generoso, a tratti troppo: i compagni lo sanno.": "You pass the ball even when the shot is there. Generous, at times too much: your teammates know it.",
  "Ti sottrai al centro. Funziona, finché la partita non chiede che tu ci resti.": "You step away from the center. It works, until the game asks you to stay there.",
  "Il vanto non fa parte del tuo vocabolario. A volte, però, il parquet lo chiede.": "Bragging isn't in your vocabulary. Sometimes, though, the floor demands it.",
  "Il gruppo si muove meglio quando sei in campo. Non è statistica: è un modo di respirare insieme.": "The group moves better when you're on the floor. It's not a stat: it's a way of breathing together.",
  "Le letture arrivano un tempo prima. I compagni alzano la mano senza chiamare.": "The reads come a beat early. Teammates raise a hand without calling for it.",
  "A {0} il gioco diventa più semplice con te: meno voci, più geometrie.": "In {0} the game gets simpler with you: fewer voices, cleaner geometry.",
  "C'è distanza, in spogliatoio. Non è una lite: è un silenzio che pesa più di una lite.": "There's distance in the locker room. It's not a fight: it's a silence that weighs more than a fight.",
  "Le geometrie non tornano. Tu vedi una cosa, gli altri un'altra, e il pallone paga.": "The geometry doesn't add up. You see one thing, the others another, and the ball pays for it.",
  "Il gruppo ti tiene nel conto, non ancora nel cerchio. Si sente tra un tempo morto e l'altro.": "The group counts on you, but hasn't let you into the circle yet. You can feel it between timeouts.",
  "Il rapporto col gruppo è professionale, non ancora intimo. Si costruisce a dicembre, si verifica ad aprile.": "Your relationship with the group is professional, not yet close. It's built in December and tested in April.",
  "Né estraneo né perno. Occupi il posto che ti hanno dato, e aspetti che diventi tuo.": "Neither outsider nor cornerstone. You fill the spot they gave you, and wait for it to become yours.",
  "Le tue medie non mentono: sei lo stesso, notte dopo notte. I coach comprano questo, non l'esplosione.": "Your averages don't lie: you're the same, night after night. Coaches buy that, not the explosion.",
  "La ripetibilità è il tuo lusso. Poche sere vuote, poche sere inventate.": "Repeatability is your luxury. Few empty nights, few made-up ones.",
  "Una sera sei un altro. La successiva, un altro ancora. Lo staff non sa quale versione convocare.": "One night you're someone else. The next, someone else again. The staff doesn't know which version to call on.",
  "Il talento arriva a ondate. Le partite in cui manca, pesano più di quelle in cui avanza.": "Talent comes in waves. The games where it's missing weigh more than the ones where it overflows.",
  "Il quinto fallo arriva tardi. Tu no. Il secondo salto è ancora il primo, a tre minuti dalla sirena.": "The fifth foul comes late. You don't. Your second jump is still your first, three minutes from the buzzer.",
  "Il fiato dura più del copione. Sulle transizioni resti, quando gli altri chiedono il cambio.": "Your wind lasts longer than the script. In transition you stay out there when the others ask for a sub.",
  "Il primo salto è tuo. Il terzo, no. Le transizioni lunghe ti scoprono.": "The first jump is yours. The third isn't. Long transitions expose you.",
  "A fine gara le gambe negoziano. Il mestiere, lì, diventa gestione, non dominio.": "At the end of games your legs start negotiating. The job, there, becomes management, not domination.",
  "La stampa ti cerca, e tu sai cosa dire. Una frase al posto giusto vale una settimana di pace.": "The press seeks you out, and you know what to say. A sentence in the right place buys you a week of peace.",
  "Davanti ai microfoni non improvvisi. Costruisci la versione, e la città la compra.": "In front of the microphones you don't improvise. You build the story, and the city buys it.",
  "Davanti ai microfoni preferisci il silenzio. Non sempre aiuta: il vuoto lo riempie qualcun altro.": "In front of the microphones you prefer silence. It doesn't always help: someone else fills the void.",
  "Le interviste ti stanno strette. Una risposta di troppo, o di meno, e la storia ti sfugge.": "Interviews feel tight on you. One answer too many, or too few, and the story slips away from you.",
  "In queste settimane il gesto entra da solo. Non è magia: è un periodo, e va abitato senza spiegarlo.": "These weeks the shot goes in on its own. It's not magic: it's a stretch, and you live in it without explaining it.",
  "La palla esce pulita. Lo senti prima del tabellone, e lo staff ha smesso di correggere.": "The ball comes off clean. You feel it before the scoreboard does, and the staff has stopped correcting you.",
  "Il periodo è opaco. I tiri che di solito cadono, adesso negoziano. Non è finita: è una traversata.": "It's a murky stretch. The shots that usually fall are now negotiating. It's not over: it's a crossing.",
  "Il corpo è in ritardo di un tempo. Si aspetta, si lavora, non si inventa una svolta in conferenza.": "Your body is a beat behind. You wait, you work, you don't invent a turnaround at a press conference.",
  "L'allenatore ti lascia i minuti anche quando sbagli. È un credito: si restituisce in campo, non a parole.": "The coach leaves you out there even when you miss. It's a credit: you pay it back on the floor, not with words.",
  "Dalla panchina arriva fiducia, non un'istruzione ogni possesso. Raro, e si sente.": "From the bench comes trust, not an instruction every possession. Rare, and you feel it.",
  "La panchina ti guarda con il cronometro in mano. I minuti non sono un diritto, stavolta.": "The bench watches you with a stopwatch in hand. Minutes aren't a right, this time.",
  "Il coach chiede prove, non promesse. Ogni rotazione è un esame, e lo sai.": "The coach asks for proof, not promises. Every rotation is an exam, and you know it.",
  "A {0} anni, a {1}, il palazzetto è ancora una stanza nuova. Ogni sera impari un nome.": "At {0}, in {1}, the arena is still a new room. Every night you learn a name.",
  "Sei ancora in costruzione. Le sere belle non fanno una carriera: fanno un inizio, se le tieni.": "You're still under construction. Good nights don't make a career: they make a start, if you hold on to them.",
  "Il corpo impara più in fretta della fama. Meglio così: la fama, da sola, non insegna i copioni.": "The body learns faster than fame does. Better that way: fame alone doesn't teach you the scripts.",
  "A {0} anni il mestiere è scegliere cosa non fare. A {1} lo sanno prima i tifosi.": "At {0}, the job is choosing what not to do. In {1}, the fans know it first.",
  "Il mestiere adesso è scegliere cosa non fare. Le gambe lo sanno prima della testa.": "The job now is choosing what not to do. Your legs know it before your head does.",
  "Non corri più tutte le cause. Corri quelle che chiudono le partite, e basta.": "You don't chase every lost cause anymore. You chase the ones that close out games, and that's it.",
  "Questi sono gli anni in cui il mestiere si vede intero. A {0}, a {1} anni, la finestra è aperta.": "These are the years when the whole craft shows. In {0}, at {1}, the window is open.",
  "Il picco non si dichiara. Si gioca, si tiene, si lascia che i numeri lo raccontino dopo.": "A peak isn't declared. It's played, held, and you let the numbers tell it later.",
  "La città ha già una versione di te. Tu puoi confermarla, o puoi stancarla: non puoi ignorarla.": "The city already has a version of you. You can confirm it or wear it out: you can't ignore it.",
  "Fuori dal palazzetto il tuo nome è ancora un sussurro. In un certo senso è un lusso.": "Outside the arena your name is still a whisper. In a way, that's a luxury.",
  "Il palazzetto europeo chiede un altro passo: più fisico, meno possessi, nessuna notte facile.": "European arenas ask for a different step: more physical, fewer possessions, no easy nights.",
  "I tratti coperti restano coperti. Resta questo: come ti senti, oggi, dentro la vita in corso.": "The hidden traits stay hidden. What remains is this: how you feel, today, inside the life you're living.",
  "Niente verdetto, ancora. Solo il diario di come il mestiere ti sta attraversando.": "No verdict yet. Only the journal of how the craft is moving through you.",
  "Le sensazioni non sono statistiche. Sono il modo in cui la stagione ti parla, quando i numeri tacciono.": "Feelings aren't stats. They're how the season speaks to you when the numbers go quiet.",
  "Carriera in ombra": "A career in the shadows",
  "Non tutte le storie finiscono con un trofeo alzato, e va bene così.": "Not every story ends with a trophy held high, and that's fine.",
  "Il fenomeno": "The phenomenon",
  "Una carriera che entra nei libri. Non tutti ci arrivano; tu ci sei arrivato.": "A career that goes into the books. Not everyone gets there; you did.",
  "Leggenda di franchigia": "Franchise legend",
  "Il tipo di giocatore attorno a cui una città costruisce un decennio.": "The kind of player a city builds a decade around.",
  "Stella affidabile": "Reliable star",
  "Non sempre sui titoli, ma decisivo quando la serie si stringe.": "Not always in the headlines, but decisive when the series tightens.",
  "Comprimario solido": "Solid role player",
  "Il compagno che ogni squadra da titolo vorrebbe avere accanto.": "The teammate every title team would want by its side.",
  "Giocatore di rotazione": "Rotation player",
  "Una carriera onesta, fatta di minuti guadagnati, non regalati.": "An honest career, made of minutes earned, not handed out.",
  "Tutto è partito da un campus universitario.": "It all started on a college campus.",
  "Il ragazzo cresciuto in Europa è arrivato più lontano di quanto molti immaginassero.": "The kid who grew up in Europe went further than many imagined.",
  "Chi ha bruciato le tappe non ha mai smesso di correre.": "The one who skipped steps never stopped running."
};
