/* English narrative for feel. Key: Italian source text (see ../key.ts). */
export const EN_FEEL: Readonly<Record<string, string>> = {
  "Il fisico ha chiesto il conto: notti in sala medica, lo spogliatoio che parla a voce bassa.": "Your body sent the bill: nights in the training room, a locker room that talks in low voices.",
  "Hai saltato più sere di quante avresti voluto. Da fuori il campo sembra più lontano.": "You missed more nights than you'd have liked. From the outside, the court looks farther away.",
  "Le sedute con il fisioterapista sono diventate un appuntamento. Non un'eccezione.": "Sessions with the physio have become a standing appointment. Not an exception.",
  "La lista infortuni ti tiene in una stanza laterale. Si gioca, tu conti i giorni.": "The injury list keeps you in a side room. They play; you count the days.",
  "Un infortunio non fa rumore. Fa vuoto: i minuti che non sono tuoi.": "An injury doesn't make noise. It leaves a void: the minutes that aren't yours.",
  "Torni, ti fermi, torni. Il calendario non aspetta le tue ginocchia.": "You come back, you stop, you come back. The schedule doesn't wait for your knees.",
  "La stagione ha un buco nel mezzo. Lo riempi di ghiaccio e di attesa.": "The season has a hole in the middle. You fill it with ice and waiting.",
  "Il referto dice assente. Tu c'eri, in sala, a guardare gli altri coprire la tua voce.": "The report says out. You were there, in the room, watching others cover for your voice.",
  "Conti i giorni dal ritorno. Ogni mattina il ginocchio risponde prima di te.": "You count the days since your return. Every morning the knee answers before you do.",
  "Una settimana sì, due no. Il mestiere, da ferito, è aspettare senza spegnersi.": "One week on, two weeks off. The job, when you're hurt, is waiting without switching off.",
  "Al mattino le ginocchia parlano prima di te. Poi, piano, il corpo obbedisce.": "In the morning your knees speak before you do. Then, slowly, the body obeys.",
  "Non corri come a ventidue. Compensi con la testa, e la testa tiene.": "You don't run like you did at twenty-two. You compensate with your head, and your head holds.",
  "Ogni riscaldamento è un negoziato. Ogni quarto, una trattativa vinta.": "Every warm-up is a negotiation. Every quarter, a negotiation won.",
  "I giovani partono. Tu arrivi dopo, e spesso arrivi meglio.": "The young guys take off first. You get there later, and often you get there better.",
  "Il corpo ha un archivio. A ottobre lo sfogli con cura, pagina dopo pagina.": "The body keeps an archive. In October you leaf through it carefully, page by page.",
  "Dormi di più, parli di meno. È l'unica forma di lusso che ti concedi.": "You sleep more, you talk less. It's the only luxury you allow yourself.",
  "La palla arriva dove la mettevi a venticinque. Ci metti un passo in più.": "The ball arrives where you used to put it at twenty-five. It takes you one more step.",
  "A quest'età il riscaldamento è già una partita. La vinci in silenzio, ogni sera.": "At this age the warm-up is already a game. You win it in silence, every night.",
  "Non chiedi al corpo di essere giovane. Gli chiedi di arrivare a maggio.": "You don't ask your body to be young. You ask it to make it to May.",
  "Trentadue anni. Il corpo non è vecchio: è informato, e pretendi che lo resti.": "Thirty-two. The body isn't old: it's informed, and you demand it stays that way.",
  "A trentadue il primo passo è ancora tuo. Il secondo, lo negozi.": "At thirty-two the first step is still yours. The second, you negotiate.",
  "Trentadue: il talento è ancora lì, il calendario inizia a parlare. Tu rispondi col posto.": "Thirty-two: the talent is still there, the calendar starts to talk. You answer with positioning.",
  "A trentadue non sei un ragazzo. Non sei un relitto. Sei un mestiere che tiene.": "At thirty-two you're not a kid. You're not a wreck. You're a craft that holds up.",
  "Trentadue anni, e ogni ottobre è ancora una firma tua, non dello staff.": "Thirty-two, and every October is still your signature, not the staff's.",
  "A trentadue il corpo chiede un orario. Tu glielo dai, e scendi lo stesso.": "At thirty-two your body asks for a schedule. You give it one, and you take the floor anyway.",
  "Trentatré anni non sono un numero. Sono un modo diverso di scendere in campo.": "Thirty-three isn't a number. It's a different way of taking the floor.",
  "A trentatré il calendario si legge col corpo, non col talento.": "At thirty-three you read the calendar with your body, not your talent.",
  "Trentatré: i minuti si pesano. Tu li tieni, senza chiedere che qualcuno li chiami coraggio.": "Thirty-three: minutes get weighed. You hold on to them, without asking anyone to call it courage.",
  "A trentatré il primo contatto è un negoziato. Il quarto quarto, se arriva, è tuo.": "At thirty-three the first contact is a negotiation. The fourth quarter, if it comes, is yours.",
  "Trentatré anni. Lo specchio non mente, e tu non gli chiedi di mentire.": "Thirty-three. The mirror doesn't lie, and you don't ask it to.",
  "A trentatré il mestiere è arrivare a maggio con le gambe tue, non con un alibi.": "At thirty-three the job is getting to May on your own legs, not with an alibi.",
  "Trentaquattro anni. Ogni ottobre è una firma, e la fai ancora tu.": "Thirty-four. Every October is a signature, and you still sign it.",
  "A trentaquattro il mestiere è durare senza sparire.": "At thirty-four the job is to last without disappearing.",
  "Trentaquattro: il posto prima della copertina. Tu lo tieni, anche se è più stretto.": "Thirty-four: the spot before the cover. You hold it, even if it's narrower.",
  "A trentaquattro le ginocchia fanno l'appello. Tu rispondi ancora sì.": "At thirty-four your knees take roll call. You still answer present.",
  "Trentaquattro anni, e il ruolo è già una vittoria, se lo tieni dritto.": "Thirty-four, and the role is already a win, if you keep it straight.",
  "A trentaquattro non chiedi al corpo di essere giovane. Gli chiedi di firmare ottobre.": "At thirty-four you don't ask your body to be young. You ask it to sign October.",
  "Trentacinque anni. I minuti si contano, non si sprecano.": "Thirty-five. Minutes are counted, not wasted.",
  "A trentacinque il corpo firma dopo. Tu firmi adesso, e tieni il posto.": "At thirty-five the body signs later. You sign now, and hold your spot.",
  "Trentacinque: il posto prima della voce. Questo è un altro inverno, e lo tieni dritto.": "Thirty-five: the spot before the voice. This is another winter, and you keep it straight.",
  "A trentacinque il mestiere è non sparire in punta, e tu non sparisci.": "At thirty-five the job is not to vanish at the end, and you don't vanish.",
  "Trentacinque anni. Lo staff misura i possessi; tu misuri quello che resta.": "Thirty-five. The staff measures possessions; you measure what's left.",
  "A trentacinque ogni riscaldamento è un inventario. Lo fai prima che lo faccia lo staff.": "At thirty-five every warm-up is an inventory. You take it before the staff does.",
  "Trentasei anni. I minuti che restano, detti chiaro, e tenuti.": "Thirty-six. The minutes that are left, said plainly, and held.",
  "A trentasei il posto è già una vittoria. Tu lo tieni, senza copertina.": "At thirty-six the spot is already a win. You hold it, no magazine cover.",
  "Trentasei: il corpo ha un'agenda. Tu la leggi, e scendi lo stesso.": "Thirty-six: the body has an agenda. You read it, and take the floor anyway.",
  "A trentasei non c'è un altro ottobre da sprecare. Questo, lo firmi.": "At thirty-six there's no other October to waste. This one, you sign.",
  "Trentasei anni, e la voce, usata poco, vale più di un giro in sala pesi.": "Thirty-six, and your voice, used sparingly, is worth more than a trip to the weight room.",
  "A trentasei il campionato riparte. Tu conti i minuti che restano, e li tieni dritti.": "At thirty-six the season starts again. You count the minutes that are left, and keep them straight.",
  "Quasi tutte le partite. In Europa il corpo è un contratto con te stesso.": "Almost every game. In Europe the body is a contract with yourself.",
  "Trentaquattro sere, o quasi. Qui non si nasconde dietro i minuti gestiti.": "Thirty-four nights, or close. Here you can't hide behind managed minutes.",
  "Viaggi corti, presenze lunghe. Hai firmato ogni appello.": "Short trips, long attendance. You answered every roll call.",
  "Il fisico ha tenuto il ritmo della coppa. Non era scontato.": "Your body kept up with the cup schedule. That wasn't a given.",
  "Ottantadue sere, o quasi. Gli altri si fermano. Tu no.": "Eighty-two nights, or close. Others stop. You don't.",
  "Il calendario non ti ha piegato. Lo staff lo dice piano, come un complimento vero.": "The schedule didn't bend you. The staff says it quietly, like a real compliment.",
  "Una presenza da colonna. I minuti si sommano senza chiedere permesso.": "A pillar's attendance record. The minutes add up without asking permission.",
  "Disponibile, sempre. È un mestiere poco fotografato e molto pagato in fiducia.": "Available, always. It's a job that rarely gets photographed and gets paid well in trust.",
  "Hai chiuso l'anno intero. La statistica più quieta, e la più rara.": "You played the whole year. The quietest stat, and the rarest.",
  "Niente notti vuote. Il corpo ha firmato tutte le pagine del calendario.": "No empty nights. Your body signed every page of the calendar.",
  "A {CITY} il gruppo si muove come se ti conoscesse da sempre.": "In {CITY} the group moves as if it had always known you.",
  "In spogliatoio, a {CITY}, il silenzio è comodo. Non è freddezza: è abitudine buona.": "In the locker room in {CITY}, the silence is comfortable. It's not coldness: it's a good habit.",
  "I compagni ti cercano con lo sguardo prima del tempo morto. A {CITY} sei un pezzo dello schema.": "Teammates look for you before the timeout. In {CITY} you're part of the playbook.",
  "Due, tre anni qui. A {CITY} non devi più presentarti: entri, e lo schema ti riconosce.": "Two, three years here. In {CITY} you no longer need to introduce yourself: you walk in, and the system knows you.",
  "Le battute interne, a {CITY}, ti includono senza sforzo. Sei di casa.": "The inside jokes in {CITY} include you without effort. You're at home.",
  "Passi corti, sguardi lunghi. A {CITY} il gruppo ha imparato il tuo tempo.": "Short steps, long looks. In {CITY} the group has learned your rhythm.",
  "A {CITY} entri nello spogliatoio e il rumore non cambia. È il segno che sei dei loro.": "In {CITY} you walk into the locker room and the noise doesn't change. It's the sign you're one of them.",
  "Due inverni, o più. A {CITY} il tuo posto a tavola non si discute più.": "Two winters, or more. In {CITY} your seat at the table is no longer up for debate.",
  "Qualcuno in panchina gira intorno al tuo nome, non al tuo viso.": "Someone on the bench tiptoes around your name, not your face.",
  "Lo spogliatoio ti fa spazio. Non sempre di buon grado.": "The locker room makes room for you. Not always willingly.",
  "Le telecamere arrivano prima dei compagni. Lo senti, e loro anche.": "The cameras arrive before your teammates. You feel it, and so do they.",
  "Il tuo isolamento è diventato un fatto, non un'accusa. Peggio.": "Your isolation has become a fact, not an accusation. Worse.",
  "Parli al plurale in conferenza. In campo, il possessivo è singolare.": "You say \"we\" at press conferences. On the court, the pronoun is singular.",
  "C'è rispetto, e c'è distanza. Quest'anno pesa di più la seconda.": "There's respect, and there's distance. This year the second weighs more.",
  "C'è una distanza, in spogliatoio. Non la misuri, la senti.": "There's a distance in the locker room. You don't measure it; you feel it.",
  "I discorsi si fermano quando entri. Non è guerra: è freddo.": "Conversations stop when you walk in. It isn't war: it's cold.",
  "Mangi da solo più sere di quanto vorresti ammettere.": "You eat alone more nights than you'd like to admit.",
  "Le risate partono dall'altra parte del tavolo. Arrivano smorzate.": "The laughter starts at the other end of the table. It reaches you muffled.",
  "Nessuno è ostile. Nessuno ti aspetta, e si sente.": "Nobody is hostile. Nobody waits for you, either, and it shows.",
  "Il cerchio si chiude un palmo prima di te. Ci stai, a fatica.": "The circle closes a hand's width before you. You fit in, barely.",
  "A {CITY}, {FANS} entra già caldo. Tu cerchi il possesso, che è più onesto del coro.": "In {CITY}, {FANS} shows up already fired up. You look for the possession, which is more honest than the chant.",
  "{FANS} ha una voce. Quest'anno la senti anche quando il palazzetto è mezzo vuoto.": "{FANS} has a voice. This year you hear it even when the arena is half empty.",
  "Al palazzetto di {CITY} il rumore cambia quando tocchi palla. {FANS} non chiede numeri: chiede presenza.": "In the {CITY} arena the noise changes when you touch the ball. {FANS} doesn't ask for numbers: it asks for presence.",
  "La città di {CITY} ti riconosce per strada. Non è fama: è abitudine, e pesa lo stesso.": "The city of {CITY} recognizes you on the street. It isn't fame: it's habit, and it weighs just the same.",
  "{TEAM} è una maglia. {CITY} è una stanza. Tu abiti tutte e due, con attenzione diversa.": "{TEAM} is a jersey. {CITY} is a room. You live in both, with different kinds of care.",
  "A {AGE} anni il palazzetto è ancora una stanza nuova. Ogni sera impari un nome.": "At {AGE}, the arena is still a new room. Every night you learn a name.",
  "Hai {AGE} anni e il mestiere ti guarda dall'alto. Tu rispondi coi possessi, non con le interviste.": "You're {AGE} and the job looks down on you. You answer with possessions, not interviews.",
  "Troppo giovane per i discorsi da veterano. A {AGE} anni basta arrivare in orario e leggere la difesa.": "Too young for veteran speeches. At {AGE}, it's enough to show up on time and read the defense.",
  "A {AGE} anni le ginocchia hanno un archivio. Lo sfogli al mattino, poi scendi in campo.": "At {AGE}, your knees keep an archive. You leaf through it in the morning, then take the floor.",
  "Trenta e oltre. A {CITY} il pubblico non ti chiede più di sorprendere: ti chiede di durare.": "Thirty and beyond. In {CITY} the crowd no longer asks you to surprise them: it asks you to last.",
  "A {AGE} anni il talento è un conto già fatto. Resta il mestiere, che è più raro.": "At {AGE}, talent is a sum already done. What's left is the craft, which is rarer.",
  "A {AGE} anni il primo passo è ancora una decisione. Il secondo, un negoziato.": "At {AGE}, the first step is still a decision. The second, a negotiation.",
  "Il calendario, a {AGE} anni, si legge col corpo. Tu lo leggi prima dello staff.": "At {AGE}, you read the calendar with your body. You read it before the staff does.",
  "A {AGE} anni non sei in ritardo: sei in orario, e {CITY} lo misura in minuti.": "At {AGE} you're not late: you're on time, and {CITY} measures it in minutes.",
  "A {AGE} anni ogni ottobre è una trattativa col corpo. {FANS} lo sa, e ti aspetta lo stesso.": "At {AGE}, every October is a negotiation with your body. {FANS} knows it, and waits for you anyway.",
  "Il calendario non è più un amico. A {AGE} anni lo leggi come un contratto, riga per riga.": "The calendar is no longer a friend. At {AGE} you read it like a contract, line by line.",
  "A {AGE} anni il posto viene prima della copertina. Tu lo tieni, e {CITY} lo vede.": "At {AGE}, the spot comes before the cover. You hold it, and {CITY} sees it.",
  "I minuti, a {AGE} anni, si contano. Non si regalano, e tu non li sprechi.": "At {AGE}, minutes are counted. They're not handed out, and you don't waste them.",
  "A {AGE} anni lo specchio fa l'appello. Tu rispondi ancora sì, senza alzare la voce.": "At {AGE}, the mirror takes roll call. You still answer present, without raising your voice.",
  "Il mestiere, a {AGE} anni, è durare senza sparire. {FANS} lo capisce dal passo.": "At {AGE}, the job is to last without disappearing. {FANS} can tell from your step.",
  "Le sere in casa hanno un rumore diverso: arrivano presto, aspettano te.": "Home nights have a different sound: they come early, and they wait for you.",
  "La classifica sorride. Il palazzetto arriva già caldo, e ti chiede di restare tale.": "The standings are smiling. The arena arrives already fired up, and asks you to stay that way.",
  "Vincere è diventato un'abitudine pericolosa: ci si abitua, e poi pesa.": "Winning has become a dangerous habit: you get used to it, and then it weighs on you.",
  "I pomeriggi di marzo sanno già di aprile. La città ci crede, e ti guarda.": "March afternoons already taste like April. The city believes, and watches you.",
  "Una striscia che tiene. Lo staff non esulta: conta, e basta.": "A streak that holds. The staff doesn't celebrate: it counts, and that's it.",
  "Ogni vittoria sembra dovuta. È il momento in cui si sbaglia di più.": "Every win feels owed. That's when the most mistakes happen.",
  "Il pubblico canta prima del salto. Tu cerchi di non crederci troppo.": "The crowd sings before the tip-off. You try not to believe it too much.",
  "La stagione pende dalla parte giusta. Resta da non farla cadere.": "The season tilts the right way. Now the job is not to let it fall.",
  "I numeri in classifica ti coprono. Non coprono gli errori, e lo sai.": "The standings cover for you. They don't cover your mistakes, and you know it.",
  "Una piazza che ha già deciso. Tu tieni il mestiere, che è più fragile della fede loro.": "A fan base that has already made up its mind. You hold on to the craft, which is more fragile than their faith.",
  "Vince, e poi di nuovo. Il rischio è smettere di leggere i possessi.": "Win, and then again. The risk is that you stop reading the possessions.",
  "Aprile è un'ipotesi concreta. Novembre, a questo punto, sembra lontano.": "April is a concrete possibility. November, at this point, seems far away.",
  "Vinci, e il palazzetto ti chiede di non smettere. Tu tieni il possesso, che è più onesto.": "You win, and the arena asks you not to stop. You hold the possession, which is more honest.",
  "Una classifica che copre. Tu conti i minuti, che non coprono niente.": "The standings cover for you. You count the minutes, which cover nothing.",
  "Le sconfitte si accumulano come polvere. Lo staff chiude la porta prima di parlare.": "The losses pile up like dust. The staff closes the door before speaking.",
  "Il pubblico di casa fischia tardi, come chi non sa più a chi arrabbiarsi.": "The home crowd boos late, like people who no longer know who to be angry at.",
  "La classifica è un peso. Ogni novembre sembra aprile, e non nel modo buono.": "The standings are a weight. Every November feels like April, and not in a good way.",
  "Si cerca un colpevole. Poi si cerca un possesso. Poi si tace.": "They look for someone to blame. Then for a possession. Then they go quiet.",
  "Le conferenze durano poco. Le notti, no.": "The press conferences are short. The nights aren't.",
  "Un anno storto. Lo senti nel modo in cui i compagni salutano, la sera.": "A crooked year. You feel it in the way your teammates say goodnight.",
  "Niente alibi che tenga. I numeri sono lì, e non ti coprono.": "No alibi holds. The numbers are there, and they don't cover for you.",
  "Si gioca per l'orgoglio, che è una valuta debole a febbraio.": "You play for pride, which is a weak currency in February.",
  "La classifica non mente. Mente chi parla di «processo» a marzo inoltrato.": "The standings don't lie. Whoever talks about \"the process\" in late March does.",
  "Ogni trasferta è una tregua. Il palazzetto di casa, no.": "Every road trip is a truce. The home arena isn't.",
  "Si perde con dignità, poi si perde senza. Il confine è sottile.": "You lose with dignity, then you lose without it. The line is thin.",
  "I tempi morti si allungano. Non perché c'è da dire: perché non c'è.": "Timeouts get longer. Not because there's something to say: because there isn't.",
  "Perdi, e poi di nuovo. Il mestiere, in questi mesi, è non cercare un colpevole in te.": "You lose, and then again. The job, these months, is not to look for the culprit in yourself.",
  "Una stagione storta. Tu resti, possessi dopo possesso, anche quando la stanza si svuota.": "A crooked season. You stay, possession after possession, even when the room empties.",
  "Ottavi per un soffio. I playoff sono una porta socchiusa, non un diritto.": "Eighth by a whisker. The playoffs are a door left ajar, not a right.",
  "L'ultimo treno. A bordo si sta in piedi, ma si parte.": "The last train. You're standing on board, but you're leaving.",
  "Ottavi. Nessuno vi teme, e questo, a volte, basta per entrare.": "Eighth seed. Nobody fears you, and sometimes that's enough to get in.",
  "Una gara, un possesso, e siete dentro. Fragile, e vero.": "One game, one possession, and you're in. Fragile, and real.",
  "Primi in classifica. Il privilegio, ad aprile, si paga in aspettative.": "First in the standings. In April, that privilege is paid for in expectations.",
  "La testa di serie. Tutti vogliono il vostro scalpo, e lo dicono.": "The top seed. Everyone wants your scalp, and they say so.",
  "Primi. Lo staff lo tratta come un dato, non come una festa.": "First. The staff treats it as a data point, not a party.",
  "Il campo centrale, da ora. Ogni errore si vede da più lontano.": "Center court, from now on. Every mistake can be seen from farther away.",
  "Il premio pesa. Non sul collo: su quello che ti chiederanno da ora in poi.": "The award weighs. Not around your neck: on what they'll ask of you from now on.",
  "MVP. Una parola corta che allunga ogni domanda, da ottobre in poi.": "MVP. A short word that makes every question longer, from October on.",
  "Te l'hanno dato. Adesso tocca dimostrare che non era un incidente di calendario.": "They gave it to you. Now you have to prove it wasn't a scheduling accident.",
  "MVP. Una sera il nome è tuo. Da ottobre le domande, però, sono più lunghe.": "MVP. For one night the name is yours. From October, though, the questions get longer.",
  "Il premio più corto. Il mestiere, sotto, resta identico, e tu lo sai.": "The shortest award. The craft underneath stays exactly the same, and you know it.",
  "Te l'hanno appeso. Il campionato ricomincia, e il peso arriva dopo.": "They hung it on you. The season starts again, and the weight comes later.",
  "A febbraio, per una settimana, sei esistito in un'altra luce.": "In February, for a week, you existed in a different light.",
  "La chiamata All-Star arriva come un respiro. Poi torna il campionato, che non perdona.": "The All-Star call arrives like a breath. Then the regular season comes back, and it doesn't forgive.",
  "Una maglia diversa per un fine settimana. Poi di nuovo la tua, che pesa di più.": "A different jersey for a weekend. Then your own again, which weighs more.",
  "Il voto è arrivato. Non cambia i lunedì, cambia il modo in cui ti presentano.": "The vote came in. It doesn't change your Mondays; it changes how they introduce you.",
  "Il Rookie of the Year non è un arrivo. È un modo per dirti che adesso ti guardano.": "Rookie of the Year isn't an arrival. It's a way of telling you they're watching now.",
  "Il premio da ragazzo. Una targa che dice: da ora il dubbio è degli altri, non tuo.": "The kid's award. A plaque that says: from now on the doubt belongs to others, not to you.",
  "Rookie of the Year. Una sera ti chiamano per nome, e il nome pesa già.": "Rookie of the Year. One night they call your name, and the name already weighs.",
  "Il premio da ragazzo. Lo tieni, sapendo che ottobre prossimo non perdona i debutti.": "The kid's award. You keep it, knowing next October doesn't forgive debut seasons.",
  "Te l'hanno dato al primo giro. Adesso tocca diventare altro, e lo sai.": "They gave it to you on the first go-round. Now you have to become something else, and you know it.",
  "Il Rookie of the Year. Lo spogliatoio ti guarda diverso: non è affetto, è attesa.": "Rookie of the Year. The locker room looks at you differently: it isn't affection, it's expectation.",
  "A {AGE} anni, Defensive Player of the Year. Di solito aspettano i canestri. Stavolta hanno contato le mani.": "At {AGE}, Defensive Player of the Year. Usually they wait for the buckets. This time they counted the hands.",
  "Troppo giovane, dicono, per coprire così. Il premio è arrivato lo stesso.": "Too young, they say, to cover like that. The award came anyway.",
  "Defensive Player of the Year, a {AGE} anni. Chiudi già, e non hai ancora il discorso di un veterano.": "Defensive Player of the Year, at {AGE}. You already lock people up, and you don't have a veteran's speech yet.",
  "A {AGE} anni ti volevano veloce. Ti hanno visto sporco, e il nome te l'hanno messo addosso.": "At {AGE} they wanted you fast. They saw you get dirty, and they pinned the name on you.",
  "Il premio di chi toglie, e tu sei ancora un ragazzo. Il palmo, però, è già da uomo.": "The award for those who take things away, and you're still a kid. The hand, though, is already a man's.",
  "A {AGE} anni chiudere non finisce in copertina. Quest'anno il premio è tuo lo stesso.": "At {AGE}, shutting people down doesn't make the cover. This year the award is yours anyway.",
  "A {AGE} anni il premio di chi chiude non è una sorpresa: è il mestiere, contato tardi.": "At {AGE}, the award for closers is no surprise: it's the craft, counted late.",
  "Defensive Player of the Year, a {AGE} anni. Le ginocchia tengono i nomi. Tu ci metti ancora il palmo.": "Defensive Player of the Year, at {AGE}. Your knees remember the names. You still put the hand up.",
  "A {AGE} anni non corri come prima. Chiudi meglio. Il premio è questo, nudo.": "At {AGE} you don't run like before. You close out better. That's the award, bare.",
  "Il premio di chi toglie. A {AGE} anni togliere è un orario, non un salto.": "The award for those who take things away. At {AGE}, taking away is a schedule, not a leap.",
  "A {AGE} anni i canestri degli altri restano corti perché tu sei ancora lì, un palmo prima.": "At {AGE}, other people's shots still come up short because you're still there, a hand early.",
  "Defensive Player of the Year. A quest'età è un rispetto che arriva dopo i minuti, non prima.": "Defensive Player of the Year. At this age it's a respect that comes after the minutes, not before.",
  "Defensive Player of the Year. Non è un premio da debutto: si conta ogni aprile, e quest'anno il nome è il tuo.": "Defensive Player of the Year. It's not a debut award: it's counted every April, and this year the name is yours.",
  "Quest'anno ti hanno letto sulle stoppate e sulle palle rubate, non sui canestri.": "This year they read you through blocks and steals, not buckets.",
  "Il premio difensivo. Pochi applausi, molte graffiature, e il rispetto giusto.": "The defensive award. Little applause, lots of scratches, and the right kind of respect.",
  "Defensive Player of the Year. Una parola che non finisce in copertina, e per questo vale di più.": "Defensive Player of the Year. A title that never makes the cover, and that's why it's worth more.",
  "Ti hanno visto chiudere. È un complimento che si paga in contatti, non in copertina.": "They saw you lock people up. It's a compliment paid in contact, not in magazine covers.",
  "Il premio di chi toglie. Lo staff, per una volta, parla del tuo palmo prima del tuo polso.": "The award for those who take things away. For once, the staff talks about your hand before your wrist.",
  "Defensive Player of the Year. I canestri degli altri sono restati corti, e qualcuno li ha contati.": "Defensive Player of the Year. Other people's shots came up short, and someone counted them.",
  "Una stagione a coprire. Il premio, quando arriva, non ha bisogno di un'altra parola.": "A season spent covering. The award, when it comes, doesn't need another word.",
  "Hanno contato i possessi fermati. È il tuo mestiere, e stavolta ha un nome.": "They counted the possessions you stopped. It's your craft, and this time it has a name.",
  "Il tiro esce corto. Lo sai prima ancora del fischio.": "The shot comes up short. You know it before the whistle.",
  "Il ritmo non è il tuo. Ogni possesso è un metro da recuperare.": "The rhythm isn't yours. Every possession is ground to make up.",
  "C'è sabbia negli ingranaggi. Non si vede, si sente nel rullo dei possessi.": "There's sand in the gears. You can't see it; you feel it in the roll of the possessions.",
  "Le serate facili sono sparite. Tutto costa un dribbling in più.": "The easy nights are gone. Everything costs one more dribble.",
  "Tutto entra. Anche i tiri che non dovevano.": "Everything goes in. Even the shots that shouldn't.",
  "C'è una settimana in cui il canestro sembra più largo. È durata di più.": "There's a week when the rim looks wider. This one lasted longer.",
  "Il polso è caldo. I compagni te la cercano senza chiedere.": "Your wrist is hot. Teammates look for you without asking.",
  "Una vena. La cavalchi sapendo che non è eterna, e proprio per questo la tieni.": "A hot streak. You ride it knowing it isn't eternal, and that's exactly why you hold on to it.",
  "Trentasei minuti a notte. Il fiato diventa un orario.": "Thirty-six minutes a night. Your wind becomes a schedule.",
  "Il carico è da titolare vero. Le gambe lo sanno prima della statistica.": "A real starter's workload. Your legs know it before the stats do.",
  "Chiudi quasi ogni serata in campo. Lo staff si fida, il corpo annota.": "You finish almost every night on the floor. The staff trusts you; the body takes notes.",
  "Minuti da colonna. A marzo si pagano gli interessi.": "Pillar minutes. In March you pay the interest.",
  "Dalla panchina il campo sembra più lontano.": "From the bench, the court looks farther away.",
  "I minuti arrivano a pezzi. Devi farli pesare tutti, perché sono pochi.": "The minutes come in pieces. You have to make all of them count, because there are few.",
  "Entri a partita in corsa. Non c'è riscaldamento che basti, c'è solo la testa.": "You come in mid-game. No warm-up is enough; there's only your head.",
  "Un ruolo ridotto. Ogni possesso è un'udienza, non una serata.": "A reduced role. Every possession is an audition, not an evening.",
  "Qualcuno in tribuna ha già deciso chi sei. Tu stai ancora imparando il nome degli schemi.": "Someone in the stands has already decided who you are. You're still learning the names of the plays.",
  "I numeri da ragazzo grande. Lo spogliatoio ti guarda diverso, e tu fai finta di non sentire.": "Big-kid numbers. The locker room looks at you differently, and you pretend not to hear.",
  "Troppo presto per questo uso. Lo staff lo sa, e ti butta lo stesso.": "Too early for this usage. The staff knows it, and throws you in anyway.",
  "Una matricola che non si nasconde. Il calendario, il primo, è già una ferita e una scuola.": "A rookie who doesn't hide. The first schedule is already a wound and a school.",
  "Settanta sere al primo giro. Pochi le fanno. Tutte lasciano un segno.": "Seventy nights in your first go-round. Few manage it. All of them leave a mark.",
  "L'anello non si descrive. Si tiene, e si tace un poco.": "A ring can't be described. You hold it, and you stay quiet for a while.",
  "A giugno il mondo ha il tuo nome. A luglio ricomincia il lavoro, identico e diverso.": "In June the world has your name. In July the work starts again, the same and different.",
  "Confetti, ghiaccio, una foto che durerà più di te. Poi il silenzio buono.": "Confetti, ice, a photo that will outlast you. Then the good kind of silence.",
  "Avete chiuso. Per una notte la città non ha altre domande.": "You closed it out. For one night the city has no other questions.",
  "La corsa si è fermata prima del discorso che avevi preparato.": "The run stopped before the speech you had prepared.",
  "Fuori. Il silenzio dopo l'ultimo fischio dura più della serie.": "Out. The silence after the final whistle lasts longer than the series.",
  "Una porta che si chiude. Dietro resta la primavera, incompleta.": "A door closing. Behind it stays the spring, unfinished.",
  "Si torna a casa a maggio. L'estate inizia troppo presto, e lo sai.": "You head home in May. Summer starts too early, and you know it.",
  "{RIVAL} è una voce in sottofondo. Non la togli, la usi.": "{RIVAL} is a voice in the background. You don't remove it; you use it.",
  "Ogni tanto torna {RIVAL}. Non sul referto: nella testa, dove conta.": "Every now and then {RIVAL} comes back. Not on the box score: in your head, where it counts.",
  "{RIVAL} resta un metro. Ti misuri lì, anche quando non giocate.": "{RIVAL} remains a yardstick. You measure yourself there, even when you don't play each other.",
  "Il nome di {RIVAL} compare ancora. Basta per alzare il tono di una settimana.": "{RIVAL}'s name pops up again. It's enough to raise the tone of a whole week.",
  "Il sistema è {LAB}. Ti chiedono di sporcarti prima di illuminare.": "The system is {LAB}. They ask you to get dirty before you shine.",
  "Chiudere, poi aprire. Lo staff lo ripete senza alzare la voce.": "Lock down, then open up. The staff repeats it without raising its voice.",
  "Prima il palmo, poi il tiro. Qui l'ordine non si discute.": "Hand first, then the shot. Here the order isn't up for debate.",
  "Ogni possesso inizia dal lato debole. Lo schema non perdona chi guarda solo il ferro.": "Every possession starts on the weak side. The system doesn't forgive those who only look at the rim.",
  "Le mani basse, il petto alto. {LAB} non è uno slogan: è un orario.": "Hands low, chest high. {LAB} isn't a slogan: it's a schedule.",
  "Rubare un secondo sulla linea. Poi il resto del quarto è più facile.": "Steal a second on the line. Then the rest of the quarter is easier.",
  "I fischi arrivano. I canestri degli altri, no. È questo il mestiere, qui.": "The whistles come. The other team's buckets don't. That's the job here.",
  "Coprire, ruotare, parlare. Il talento senza voce, in questa piazza, non basta.": "Cover, rotate, talk. Talent without a voice isn't enough in this town.",
  "Una serata pulita vale più di una esplosione. Lo capisci a marzo.": "A clean night is worth more than an explosion. You understand it in March.",
  "Il tabellone degli altri resta basso. È l'unico applauso che lo staff cerca.": "The other team's scoreboard stays low. It's the only applause the staff is after.",
  "Tutto gira intorno al perimetro. {LAB}: se non spacchi la linea, resti fuori dallo schema.": "Everything revolves around the perimeter. {LAB}: if you don't break the line, you're out of the system.",
  "I tre punti non sono un lusso. Qui sono il pane.": "Threes aren't a luxury. Here they're bread and butter.",
  "Spazi, uscite, il tiro che deve partire in tempo. Sempre.": "Spacing, screens, the shot that has to go up on time. Always.",
  "La linea da tre è il fuso orario della squadra. Chi arriva in ritardo resta in panchina.": "The three-point line is the team's time zone. Whoever arrives late sits on the bench.",
  "Ricezione e tiro, piedi già pronti. Lo staff conta i decimi, non i palleggi.": "Catch and shoot, feet already set. The staff counts tenths of a second, not dribbles.",
  "Un passaggio in più verso l'angolo. Qui è legge, non cortesia.": "One more pass to the corner. Here it's law, not courtesy.",
  "Il ferro interno è un'esca. Il vero possesso vive fuori.": "The inside game is bait. The real possession lives outside.",
  "Allargare, allargare, poi il tiro. Chi chiude il campo si offende da solo.": "Spread it, spread it, then shoot. Whoever shrinks the floor hurts himself.",
  "I quintetti piccoli, le uscite lunghe. {LAB} come grammatica.": "Small lineups, long closeouts. {LAB} as grammar.",
  "Ogni sera lo stesso esame: gambe ferme, polso sciolto, nessuna esitazione.": "Every night the same exam: feet set, loose wrist, no hesitation.",
  "Uno contro uno, possessi lunghi. Il sistema ti guarda e aspetta che decida tu.": "One-on-one, long possessions. The system looks at you and waits for you to decide.",
  "Ti danno il lato. Il resto è tuo, per meglio o per peggio.": "They give you the side. The rest is yours, for better or worse.",
  "Pochi passaggi, una decisione. Lo schema si fida del tuo ego, e lo sa.": "Few passes, one decision. The system trusts your ego, and knows it.",
  "Chiaro: il campo si svuota, e tocca a te leggere il corpo davanti.": "It's clear: the floor clears out, and it's up to you to read the body in front of you.",
  "Niente alibi di circolazione. Isolamento vuole dire responsabilità, nuda.": "No ball-movement alibis. Isolation means responsibility, bare.",
  "Il tempo morto avversario arriva quando tieni tu. È un complimento scomodo.": "The opponent's timeout comes when you've got it going. It's an uncomfortable compliment.",
  "Un metro quadro, un difensore, il resto della squadra a guardare. Così si gioca, qui.": "One square meter, one defender, the rest of the team watching. That's how it's played here.",
  "Creare dal palleggio è il mestiere, non l'eccezione. Lo staff non chiede scuse.": "Creating off the dribble is the job, not the exception. The staff doesn't apologize.",
  "La palla ti cerca tardi, di proposito. Devi essere pronto senza riscaldamento.": "The ball finds you late, on purpose. You have to be ready without a warm-up.",
  "Chiudere in isolamento. Se sbagli, il palazzetto lo sa prima di te.": "Closing out in isolation. If you miss, the arena knows it before you do.",
  "La palla deve uscire. Se la tieni, lo schema si offende.": "The ball has to move. If you hold it, the system takes offense.",
  "Il passaggio in più, sempre. Il tiro bello è quello che arriva pulito, non quello che tieni.": "The extra pass, always. The good shot is the one that comes clean, not the one you hold on to.",
  "Il gruppo vive di circolazione. Tu sei un nodo, non un capolinea.": "The group lives on ball movement. You're a junction, not the end of the line.",
  "Due passaggi in più, un ferro più gentile. Qui la pazienza è un atletismo.": "Two extra passes, a kinder rim. Here patience is a form of athleticism.",
  "Lo schema gira come un orologio. Chi ferma la lancetta si sente, e non in bene.": "The system runs like clockwork. Whoever stops the hand gets noticed, and not in a good way.",
  "Ricevi, leggi, dai. Il canestro è di chi arriva terzo, non di chi chiede per primo.": "Catch, read, give. The basket belongs to whoever arrives third, not to whoever asks first.",
  "Niente eroismi da palleggio. La bellezza, qui, è un assist in ritardo di un secondo.": "No dribbling heroics. Beauty, here, is an assist one second late.",
  "Il coach conta i passaggi prima dei punti. Lo impari, o resti fuori dal nastro.": "The coach counts passes before points. You learn it, or you're out of the rotation.",
  "Muovere senza palla è metà del contratto. L'altra metà è non trattenerla.": "Moving without the ball is half the contract. The other half is not holding on to it.",
  "Una squadra che parla con i passaggi. Le parole, in panchina, arrivano dopo.": "A team that talks with passes. The words on the bench come later.",
  "Primo passo, transizione, di nuovo. Il fiato è il quaderno degli schemi.": "First step, transition, again. Your wind is the playbook.",
  "Corrono. Tu stai nel loro respiro, o resti indietro.": "They run. You stay in their breath, or you fall behind.",
  "Niente set lunghi. La prima uscita è già un possesso vero.": "No long sets. The first action is already a real possession.",
  "L'aria arriva corta. Chi pensa due volte ha già perso il contropiede.": "The air comes short. Whoever thinks twice has already lost the fast break.",
  "Rimbalzo, uscita, canestro in dieci secondi. Il resto è commento.": "Rebound, outlet, basket in ten seconds. The rest is commentary.",
  "Il ritmo non si negozia. O lo tieni, o lo subisci da chi arriva prima.": "The pace isn't negotiable. Either you set it, or you suffer it from whoever gets there first.",
  "Partono in quattro. Tu sei il quinto, o sei un ostacolo.": "Four of them take off. You're the fifth, or you're in the way.",
  "Niente tempo morto per riprendere fiato. Il fiato è il lavoro, qui.": "No timeout to catch your breath. Breath is the work, here.",
  "Una transizione dopo l'altra. Il campionato, a questo passo, è una maratona corta.": "One transition after another. At this pace, the season is a short marathon.",
  "Chi vuole costruire al mezzo campo resta a guardare il tabellone che corre.": "Whoever wants to build in the half court ends up watching the scoreboard run.",
  "Ogni possesso è un contatto. Le braccia alzano prima della testa.": "Every possession is contact. The arms go up before the head.",
  "Sotto, si paga in spalle. Qui il corpo è il regolamento non scritto.": "Down low, you pay with your shoulders. Here the body is the unwritten rule.",
  "Chiusura sul rimbalzo, spinta, di nuovo. La partita ha un rumore sordo.": "Box out on the rebound, push, again. The game has a dull thud to it.",
  "Niente raffinatezza che tenga se non tieni la posizione. Lo impari sulle costole.": "No finesse holds up if you can't hold your position. You learn it on your ribs.",
  "I falli arrivano, i fischi no. Si gioca così, e lo staff non si scusa.": "The fouls come, the whistles don't. That's how it's played, and the staff doesn't apologize.",
  "Un metro guadagnato col petto vale più di un dribbling. Qui è cultura.": "A meter gained with your chest is worth more than a dribble. Here it's culture.",
  "Le ginocchia dei lunghi parlano. Tu rispondi con il corpo, non con la voce.": "The bigs' knees talk. You answer with your body, not your voice.",
  "Rimbalzi sporchi, secondi possessi. La statistica pulita arriva dopo, se arriva.": "Dirty rebounds, second chances. The clean stats come later, if they come.",
  "Chi ha paura del contatto resta perimetro. Chi resta, qui, si sporca.": "Whoever fears contact stays on the perimeter. Whoever stays, here, gets dirty.",
  "A fine gara i vestiti pesano. È il segno che avete giocato la loro lingua.": "At the end of the game your clothes feel heavy. It's the sign you played in their language.",
  "Poche parole, tanti dettagli. Una squadra che ha già visto giugno.": "Few words, lots of details. A team that has already seen June.",
  "I silenzi in sala video durano un secondo in più. Tutti capiscono perché.": "The silences in the film room last a second longer. Everyone understands why.",
  "Niente urla. Il rispetto, qui, è un orario.": "No shouting. Respect, here, is punctuality.",
  "Si gioca con la memoria. Gli schemi hanno già un nome, e i nomi pesano.": "You play with memory. The plays already have names, and the names carry weight.",
  "I giovani ascoltano. I vecchi non ripetono. Funziona, la maggior parte delle sere.": "The young listen. The old don't repeat themselves. It works, most nights.",
  "Un tempo morto detto piano vale più di uno urlato. Lo staff lo sa da anni.": "A timeout spoken softly is worth more than one shouted. The staff has known it for years.",
  "Niente drammi da spogliatoio. Il mestiere, qui, è una stanza ordinata.": "No locker-room drama. The job here is a tidy room.",
  "Chi alza la voce si squalifica da solo. Il tono giusto è basso, e fermo.": "Whoever raises his voice disqualifies himself. The right tone is low, and firm.",
  "Hanno già perso una finale. Si sente nel modo in cui chiudono i quarti.": "They've already lost a Finals. You can feel it in how they close out quarters.",
  "L'esperienza non si dichiara. Si vede in chi arriva in orario, ogni volta.": "Experience isn't declared. It shows in who arrives on time, every time.",
  "Qui si cresce in pubblico. Gli errori sono previsti, non perdonati in automatico.": "Here you grow up in public. Mistakes are expected, not forgiven automatically.",
  "Un progetto, detto chiaro. I minuti sono una scuola, e la scuola interroga.": "A project, stated clearly. Minutes are a school, and the school gives tests.",
  "Sbagli, resti, riprovi. Lo staff annota più di quanto parli.": "You miss, you stay, you try again. The staff takes more notes than it speaks.",
  "I possessi arrivano a pezzi, come compiti. Devi consegnarli puliti.": "Possessions come in pieces, like homework. You have to hand them in clean.",
  "Niente copertine. Solo ripetizioni, e un coach che non mentisce sulle valutazioni.": "No magazine covers. Just reps, and a coach who doesn't lie about evaluations.",
  "La pazienza è il sistema. Chi la scambia per debolezza esce dal nastro.": "Patience is the system. Whoever mistakes it for weakness drops out of the rotation.",
  "Ogni settimana un ruolo un po' più largo. Mai abbastanza da sentirti arrivato.": "Every week a slightly bigger role. Never enough to feel you've made it.",
  "I filmati restano corti. I verbali di allenamento, no.": "The film sessions stay short. The practice reports don't.",
  "Cresci alla luce dei fischi. È scomodo, e per questo funziona.": "You grow up under the whistles. It's uncomfortable, and that's why it works.",
  "Il futuro è la scusa. Il presente è una lista di correzioni, ogni sera.": "The future is the excuse. The present is a list of corrections, every night.",
  "Sbagli, resti, riprovi. Tu consegni i possessi puliti, e lo staff annota.": "You miss, you stay, you try again. You hand in clean possessions, and the staff takes notes.",
  "Set lunghi, letture lente. Chi ha fretta resta fuori dallo schema.": "Long sets, slow reads. Whoever's in a hurry falls out of the system.",
  "Mezzo campo, pazienza, il tiro giusto al secondo giusto.": "Half court, patience, the right shot at the right second.",
  "Niente transizioni facili. Tutto si costruisce, possesso dopo possesso.": "No easy transitions. Everything is built, possession after possession.",
  "Ventiquattro secondi usati fino in fondo. Il canestro, se arriva, è meritatissimo.": "Twenty-four seconds used to the very end. The basket, if it comes, is well deserved.",
  "Un blocco, una finta, un'uscita. Lo schema ha il tempo di un respiro lungo.": "A screen, a fake, a curl. The play has the length of a long breath.",
  "Chi tira al dodicesimo secondo si prende uno sguardo. Qui si aspetta il diciottesimo.": "Whoever shoots at twelve seconds gets a look. Here you wait for eighteen.",
  "Difese schierate, sempre. Vincere vuole dire smontarle, non superarle di corsa.": "Set defenses, always. Winning means taking them apart, not outrunning them.",
  "Il quaderno degli schemi è un libro, non un volantino. Lo sfogli, o resti in panchina.": "The playbook is a book, not a flyer. You study it, or you sit on the bench.",
  "Pazienza tattica. Il pubblico fischia; lo staff no, e tu stai con lo staff.": "Tactical patience. The crowd boos; the staff doesn't, and you side with the staff.",
  "Un possesso da adulti. Niente scorciatoie, niente scuse di ritmo.": "A grown-up possession. No shortcuts, no tempo excuses.",
  "Ventiquattro secondi, il tiro giusto. Tu aspetti il diciottesimo, anche se fischiano.": "Twenty-four seconds, the right shot. You wait for eighteen, even when they boo.",
  "Palazzetti più piccoli, tattica più stretta. Qui il fiato ha un altro accento.": "Smaller arenas, tighter tactics. Here your breathing has a different accent.",
  "In Eurolega ogni possesso è una lezione. Gli errori si pagano in greco, in serbo, in silenzio.": "In the EuroLeague every possession is a lesson. Mistakes are paid for in Greek, in Serbian, in silence.",
  "Viaggi corti, difese lunghe. L'Europa ti chiede di pensare prima di saltare.": "Short trips, long defenses. Europe asks you to think before you jump.",
  "Un'altra lingua in panchina. Il blocco e uscita, però, è lo stesso.": "Another language on the bench. The pick-and-pop, though, is the same.",
  "Coppe infrasettimanali, gambe pesanti, una testa che deve restare lucida il giovedì.": "Midweek cup games, heavy legs, a head that has to stay sharp on Thursday.",
  "I numeri ti inseguono. Non sei più quello che li rincorre.": "The numbers chase you. You're no longer the one chasing them.",
  "Uso da prima opzione. Lo paghi in fischi, in lodi, in sonno.": "First-option usage. You pay for it in boos, in praise, in sleep.",
  "Ogni difesa è disegnata su di te. È un complimento che stanca.": "Every defense is designed around you. It's a tiring compliment.",
  "L'anno scorso l'anello. Quest'anno ti chiedono di non essere un incidente.": "Last year, the ring. This year they're asking you not to be a fluke.",
  "Giugno è lontano. Il contratto con te stesso, no.": "June is far away. The contract with yourself isn't.",
  "Si torna da campioni. Il bersaglio sulle spalle è più largo.": "You come back as champions. The target on your back is wider.",
  "La primavera scorsa è restata sotto le unghie. Ogni possesso di ottobre ne porta un pezzo.": "Last spring stayed under your fingernails. Every October possession carries a piece of it.",
  "L'eliminazione precedente non si è sciolta. Lavora in silenzio, a ottobre.": "The last elimination hasn't faded. It works in silence, in October.",
  "Nuova maglia, stessa testa. {TEAM} è un'altra lingua da imparare.": "New jersey, same head. {TEAM} is another language to learn.",
  "Hai lasciato {OLD}. Il corridoio nuovo puzza di vernice e di attesa.": "You left {OLD}. The new hallway smells of paint and of waiting.",
  "Prima settimana a {TEAM}: nomi, uscite, un armadietto che non è ancora tuo.": "First week with {TEAM}: names, sets, a locker that isn't yours yet.",
  "Due anelli, o più. Il lavoro non si è fatto più facile. Si è fatto più silenzioso.": "Two rings, or more. The work hasn't gotten easier. It's gotten quieter.",
  "Hai già alzato. Adesso alzi lo sguardo, e basta.": "You've already lifted one. Now you lift your gaze, and that's it.",
  "Una stagione come le altre, se le altre esistono: lavoro, aerei, silenzi.": "A season like the others, if there are others: work, flights, silences.",
  "Niente da appendere al muro. Solo i giorni, fatti fino in fondo.": "Nothing to hang on the wall. Just the days, lived all the way through.",
  "Un anno di mezzo: non si racconta, si attraversa.": "An in-between year: you don't tell it, you go through it.",
  "Niente apice. I giorni, notte dopo notte, e il calendario che avanza.": "No peak. The days, night after night, and the calendar moving on.",
  "Si gioca, si vola, si dorme. Poi di nuovo. L'anno tiene senza chiedere applausi.": "You play, you fly, you sleep. Then again. The year holds up without asking for applause.",
  "Nessun titolo da dare a questi mesi. Restano, e questo basta.": "No title to give these months. They stay, and that's enough.",
  "Il mestiere, nudo. Niente racconto che tenga il posto del lavoro.": "The craft, bare. No story can take the place of the work.",
  "Un inverno senza tesi. Si tiene, e si va avanti.": "A winter without a thesis. You hold on, and you keep going.",
  "Le settimane si sommano senza fare rumore. A volte è un dono.": "The weeks add up without making noise. Sometimes it's a gift.",
  "Niente da dichiarare a giugno. L'anno è stato, e basta.": "Nothing to declare in June. The year happened, and that's it.",
  "Tra un'impresa e l'altra c'è questo: i giorni uguali, tenuti dritti.": "Between one feat and the next there's this: identical days, kept straight.",
  "Il calendario non chiede un racconto. Chiede di esserci.": "The calendar doesn't ask for a story. It asks you to show up.",
  "A {CITY} l'anno avanza senza proclami.": "In {CITY} the year moves on without proclamations.",
  "Si tiene il mestiere, a {CITY}, e si gira pagina.": "You hold on to the craft in {CITY}, and you turn the page.",
  "Niente da appendere. A {CITY} i giorni bastano.": "Nothing to hang up. In {CITY}, the days are enough.",
  "A {CITY} i giorni tengono, senza chiedere applausi.": "In {CITY} the days hold up, without asking for applause.",
  "Il mestiere, a {CITY}, basta. Si gira pagina.": "In {CITY}, the craft is enough. You turn the page.",
  "A {CITY} niente da dichiarare. L'anno è stato, e basta.": "In {CITY}, nothing to declare. The year happened, and that's it.",
  "Si attraversa, a {CITY}, e si tiene il posto.": "You get through it in {CITY}, and you hold your spot.",
  "A {CITY} il calendario non chiede un racconto. Chiede di esserci.": "In {CITY} the calendar doesn't ask for a story. It asks you to show up.",
  "Niente apice. A {CITY} i giorni, tenuti dritti, bastano.": "No peak. In {CITY} the days, kept straight, are enough.",
  "A {0} l'anno tiene, senza chiedere applausi.": "In {0} the year holds up, without asking for applause.",
  "{ROUND} contro {OPP}. Una partita sola, e il primo possesso arriva già pesante.": "{ROUND} against {OPP}. One game, and the first possession already feels heavy.",
  "Final Four: {OPP} dall'altra parte, una sera sola per tenere aperta la stagione.": "Final Four: {OPP} on the other side, a single night to keep the season alive.",
  "Niente gara dopo questa. {ROUND} comincia con le gambe ferme e la testa sveglia.": "No game after this one. {ROUND} starts with steady legs and an alert head.",
  "Il palazzetto è neutro, il rumore no. {OPP} aspetta il primo errore.": "The arena is neutral; the noise isn't. {OPP} is waiting for the first mistake.",
  "Una semifinale secca, una finale secca. Prima, {ROUND} contro {OPP}.": "A one-game semifinal, a one-game final. First, {ROUND} against {OPP}.",
  "{0} contro {1}. Una partita sola.": "{0} against {1}. One game.",
  "{ROUND} contro {OPP}. In tunnel il rumore arriva prima della luce.": "{ROUND} against {OPP}. In the tunnel the noise arrives before the light.",
  "La palla, prima del salto, pesa come a novembre. Poi no.": "Before the tip, the ball weighs what it did in November. Then it doesn't.",
  "{COACH} parla poco. Lo fa quando serve, e adesso serve.": "{COACH} says little. He speaks when it's needed, and now it's needed.",
  "Fuori, {OPP}. Dentro, la stessa domanda: chi tiene l'ultimo possesso.": "Outside, {OPP}. Inside, the same question: who holds the last possession.",
  "{ROUND}. Sette sere, o meno, per decidere chi resta in questa primavera.": "{ROUND}. Seven nights, or fewer, to decide who stays in this spring.",
  "Contro {OPP} non si improvvisa. Si arriva già con una ferita, o se ne prende una.": "Against {OPP} you don't improvise. You arrive already wounded, or you take a wound.",
  "Il campo di aprile non perdona i possessi pigri. {OPP} lo sa.": "The April floor doesn't forgive lazy possessions. {OPP} knows it.",
  "{ROUND}: il fiato è corto, le letture lunghe.": "{ROUND}: short breath, long reads.",
  "Stasera non si nasconde. {OPP} è dall'altra parte, e basta.": "Tonight there's nowhere to hide. {OPP} is on the other side, and that's it.",
  "Prima del salto, {COACH} ti guarda un secondo in più. Poi fischiano.": "Before the tip, {COACH} looks at you a second longer. Then the whistle.",
  "Una serie non è una partita ripetuta. È un argomento, e {OPP} ha il suo.": "A series isn't one game played over and over. It's an argument, and {OPP} has its own.",
  "Il pubblico è già in gola. Tu cerchi il primo possesso pulito.": "The crowd is already in your throat. You look for the first clean possession.",
  "Non è novembre. Chi tratta {ROUND} come novembre esce.": "It's not November. Whoever treats {ROUND} like November goes home.",
  "In sala video hanno detto poco. Il resto, contro {OPP}, si vede in campo.": "Not much was said in the film room. The rest, against {OPP}, shows on the floor.",
  "Sette, al massimo. Ogni sera brucia una pagina.": "Seven, at most. Every night burns a page.",
  "Il corpo ricorda le serie vecchie. La testa sceglie quali ascoltare.": "The body remembers old series. The head chooses which ones to listen to.",
  "Nelle partite chiuse il polso deve restare. {ROUND} inizia da lì.": "In close games the wrist has to hold. {ROUND} starts there.",
  "Nessuno vi deve niente. A volte è il vantaggio più pulito.": "Nobody owes you anything. Sometimes that's the cleanest advantage.",
  "Il privilegio è una trappola se lo tratti come un diritto.": "Home court is a trap if you treat it as a right.",
  "Sanno chi sei. Il piano, stanotte, sei tu.": "They know who you are. Tonight, the game plan is you.",
  "Il parquet di {ROUND} non perdona chi arriva già spiegato.": "The {ROUND} floor doesn't forgive those who arrive already figured out.",
  "Una primavera, un avversario. {OPP}. Il resto è mestiere.": "One spring, one opponent. {OPP}. The rest is craft.",
  "Tu non alzi la voce. {ROUND} la alza per te, e {OPP} è già in campo.": "You don't raise your voice. {ROUND} raises it for you, and {OPP} is already on the floor.",
  "Prima del salto conti un possesso. Poi {OPP}, e il resto è mestiere nudo.": "Before the tip you count one possession. Then {OPP}, and the rest is bare craft.",
  "La serie inizia quando smetti di pensare al campionato. {ROUND} lo chiede adesso.": "The series begins when you stop thinking about the regular season. {ROUND} demands it now.",
  "Contro {OPP} il primo errore pesa tre. Tu cerchi di non firmarlo tu.": "Against {OPP} the first mistake counts triple. You try not to be the one who makes it.",
  "{0} contro {1}.": "{0} against {1}.",
  "L'armadietto, per un mese, ha saputo di attesa. Poi settembre è arrivato lo stesso.": "For a month your locker smelled of waiting. Then September came anyway.",
  "Non hai firmato niente. Hai ascoltato le voci, e hai tenuto il mestiere.": "You didn't sign anything. You listened to the rumors, and you held on to the craft.",
  "Il mercato fa rumore a luglio. Tu, per ora, resti dove sei.": "The market makes noise in July. You, for now, stay where you are.",
  "Una piazza vera sul foglio. Tu non eri al tavolo, e l'estate è passata sopra la tua testa.": "A real destination on the sheet. You weren't at the table, and the summer passed over your head.",
  "Voci, smentite, un silenzio. La valigia è restata semiaperta, e questo è già un mestiere.": "Rumors, denials, a silence. The suitcase stayed half open, and that's already a skill.",
  "Lo scambio è una frase, per ora. Una frase che pesa, e tu la tieni senza firmarla.": "The trade is a sentence, for now. A heavy sentence, and you hold it without signing it.",
  "Qualcuno ha fatto il tuo nome. Tu hai fatto la valigia, poi l'hai disfatta. Per ora.": "Someone floated your name. You packed your bag, then unpacked it. For now.",
  "L'estate è già chiusa.": "The summer is already over.",
  "Una voce da un altro fuso. Palazzetti più stretti, un ultimo atto nominato, non firmato.": "A voice from another time zone. Tighter arenas, a final act mentioned, not signed.",
  "Europa resta una frase. A quest'età le frasi pesano, e questa di più.": "Europe remains a sentence. At this age, sentences weigh, and this one more than most.",
  "Il ruolo, la voce, poi — se serve — l'Europa. Per ora è solo una porta socchiusa.": "The role, the voice, then — if needed — Europe. For now it's just a door left ajar.",
  "Non hai firmato. Hai ascoltato. L'inverno, poi, deciderà.": "You didn't sign. You listened. Winter will decide.",
  "Una porta in un'altra lingua. Resta sul tavolo, e pesa.": "A door in another language. It stays on the table, and it weighs.",
  "Palazzetti più piccoli, tattica più stretta. Te lo hanno detto piano, come un rispetto.": "Smaller arenas, tighter tactics. They told you quietly, as a sign of respect.",
  "Tre gare, un aereo, una maglia che non sta nel contratto. L'hai già indossata.": "Three games, a flight, a jersey that isn't in the contract. You've already worn it.",
  "La tua Nazionale non paga i minuti di club. Paga un altro debito, e tu lo sai.": "Your national team doesn't pay club minutes. It pays another debt, and you know it.",
  "Estate corta. Pesi leggeri, sonno lungo, un fisioterapista che ormai conosce i tuoi silenzi.": "A short summer. Light weights, long sleep, a physio who by now knows your silences.",
  "Il corpo ha chiesto tregua. Gliel'hai data, a pezzi, come si dà da bere a qualcuno che non deve spegnersi.": "Your body asked for a truce. You gave it one, in pieces, the way you give water to someone who mustn't fade.",
  "Niente trekking, niente show. Solo la manutenzione di ciò che resta.": "No hiking, no show. Just maintenance of what's left.",
  "Arrivare a ottobre intero: a quest'età è l'unico orgoglio che conta.": "Getting to October in one piece: at this age it's the only pride that counts.",
  "Il recupero è la forma più adulta del lavoro. L'hai tenuto.": "Recovery is the most grown-up form of work. You stuck to it.",
  "Partite vere, senza staff. Sudore diverso, e una fame che a volte si era spenta.": "Real games, no staff. A different sweat, and a hunger that had sometimes gone out.",
  "Un palazzetto piccolo. Il gesto, lì, è tornato a essere solo un gesto.": "A small gym. There, the motion went back to being just a motion.",
  "Asfalto, un pubblico che non ti doveva niente. Tu hai tirato lo stesso, e il polso se n'è ricordato.": "Asphalt, a crowd that owed you nothing. You shot anyway, and your wrist remembered.",
  "Niente minutaggi, niente schemi. Solo te, e una palla che non mente.": "No minutes counts, no plays. Just you, and a ball that doesn't lie.",
  "L'estate è finita su un telefono. Tu hai spento, e sei rimasto in palestra.": "The summer ended up on a phone. You switched it off, and stayed in the gym.",
  "Un filmato, troppi occhi. Il lavoro, sotto, è rimasto lo stesso di sempre.": "A video, too many eyes. The work underneath stayed the same as always.",
  "Hai spento la telecamera. Il gesto, senza pubblico, è tornato tuo.": "You turned the camera off. Without an audience, the motion became yours again.",
  "Niente sudore da copertina. A ottobre le letture arriveranno un tempo prima.": "No magazine-cover sweat. In October the reads will come a beat early.",
  "Estate in una stanza buia. I possessi degli altri, a volume basso.": "A summer in a dark room. Other people's possessions, volume down.",
  "Hai riletto una serie. Hai trovato un possesso che non avevi visto. Basta quello.": "You rewatched a series. You found a possession you hadn't seen. That's enough.",
  "Hai corretto un polso. Il ragazzo ha fatto canestro. La voce, usata così, è un mestiere.": "You fixed a kid's wrist. The kid scored. A voice used like that is a craft.",
  "Hai insegnato, e il gesto è tornato. Strano, e giusto.": "You taught, and the stroke came back. Strange, and right.",
  "Due settimane in quota. Sei sceso con un altro serbatoio, e ottobre lo sentirà.": "Two weeks at altitude. You came down with a bigger tank, and October will feel it.",
  "Aria sottile, gambe dure. Il primo contropiede di ottobre è più lungo.": "Thin air, hard legs. The first October fast break is longer.",
  "Hai giocato per altri. Il gesto è rimasto tuo, la sera è stata di qualcun altro.": "You played for others. The motion stayed yours; the night belonged to someone else.",
  "Un palazzetto pieno, niente classifica. Sei tornato più leggero.": "A packed arena, no standings. You came back lighter.",
  "Due settimane a casa. Il mestiere, spento, ti ha restituito un pezzo di te.": "Two weeks at home. The craft, switched off, gave you back a piece of yourself.",
  "Casa, tavola, silenzio. Il corpo ha ringraziato senza chiedere scusa.": "Home, the dinner table, silence. Your body said thank you without apologizing.",
  "Estate di gradi, non di chili. A ottobre il primo passo è più lungo.": "A summer of range of motion, not pounds. In October the first step is longer.",
  "Hai lavorato dove non si vede. Le ginocchia, a novembre, non presentano il conto in anticipo.": "You worked where no one can see. In November your knees won't send the bill early.",
  "Asfalto, un ferro storto, una fame dritta. Sei tornato con le mani segnate.": "Asphalt, a bent rim, a straight hunger. You came back with marked hands.",
  "Niente minutaggi. Solo tiri, e un pubblico che non ti doveva niente.": "No minutes counts. Just shots, and a crowd that owed you nothing.",
  "Hai visto il contatto dall'altra sponda. A ottobre le mani sono più basse.": "You saw contact from the other side. In October your hands are lower.",
  "Due giorni di regolamento. Lo staff trova un giocatore che legge il palmo, non lo discute.": "Two days on the rulebook. The staff finds a player who reads the officials instead of arguing.",
  "Palestra vuota, musica bassa. A quest'età l'estate è un secondo campionato.": "An empty gym, low music. At this age summer is a second season.",
  "Sei tornato a casa una settimana. Poi il campo ti è mancato prima delle persone, e ti sei vergognato un poco.": "You went home for a week. Then you missed the court before you missed the people, and felt a little ashamed.",
  "Agosto sapeva di sudore e di fame. I compagni di scuola avevano già un lavoro. Tu avevi questo.": "August tasted of sweat and hunger. Your schoolmates already had jobs. You had this.",
  "Tre volte al giorno, la stessa uscita. A settembre il gesto è un altro.": "Three times a day, the same move. By September it's a different motion.",
  "Nessuno ti guardava, d'estate. È il momento in cui si cambia davvero.": "Nobody was watching you in the summer. That's when you really change.",
  "Sudore, filmati, un quaderno di schemi. L'inverno si costruisce adesso.": "Sweat, film, a notebook of plays. Winter is built now.",
  "A quest'età luglio è un secondo campionato. Tu l'hai giocato senza pubblico.": "At this age July is a second season. You played it without an audience.",
  "Sei rimasto quando gli altri sono andati al mare. Il ferro, a settembre, lo sa.": "You stayed when the others went to the beach. The rim knows it in September.",
  "{LAB}. Sudore, ripetizioni, la stessa voce nello specchio.": "{LAB}. Sweat, reps, the same voice in the mirror.",
  "L'estate non è vacanza. È il modo in cui l'inverno prossimo non ti trova impreparato.": "Summer isn't a vacation. It's how next winter doesn't catch you unprepared.",
  "Tre settimane di lavoro sporco. A ottobre si vedrà se sono bastate.": "Three weeks of dirty work. In October we'll see if they were enough.",
  "Pochi testimoni, molti tiri. Il miglioramento, se arriva, non fa rumore.": "Few witnesses, many shots. Improvement, if it comes, makes no noise.",
  "Agosto è una stanza senza pubblico. Meglio: si lavora sul vero.": "August is a room without an audience. Better: you work on what's real.",
  "Hai ripetuto finché il gesto ha smesso di essere una decisione. Poi di nuovo.": "You repeated until the motion stopped being a decision. Then again.",
  "Il telefono è rimasto in borsa. La palla, no.": "The phone stayed in the bag. The ball didn't.",
  "Sudore senza pubblico. A ottobre si vede chi ha lavorato per davvero.": "Sweat without an audience. In October you see who really worked.",
  "Un'estate da artigiano: gli stessi tiri, lo stesso specchio, un altro polso.": "A craftsman's summer: the same shots, the same mirror, a different wrist.",
  "Niente amichevoli da copertina. Solo ripetizioni, e il silenzio che serve.": "No showcase exhibitions. Just reps, and the silence it takes.",
  "Hai chiuso luglio in palestra. Lo staff, a settembre, lo capisce dal passo.": "You finished July in the gym. In September the staff can tell from your step.",
  "Tre settimane sporche. A ottobre si vedrà se sono bastate, e tu lo sai già.": "Three dirty weeks. In October we'll see if they were enough, and you already know.",
  "Due inverni di campus, palestre piene, un nome che ancora non pesa. {TEAM} chiama il tuo.": "Two winters on campus, packed gyms, a name that doesn't weigh yet. {TEAM} calls yours.",
  "Hai imparato a perdere in pubblico. {TEAM} scommette che saprai anche vincere.": "You learned to lose in public. {TEAM} is betting you'll know how to win too.",
  "Il torneo di marzo alle spalle. {TEAM} firma. Il mestiere, adesso, inizia per davvero.": "March Madness behind you. {TEAM} signs you. The job, now, really begins.",
  "Il campus ti lascia i fondamentali e una testa più ferma. {TEAM} ti sceglie. Il resto si costruisce.": "Campus leaves you the fundamentals and a steadier head. {TEAM} picks you. The rest gets built.",
  "{TEAM} ti prende dal campus. Hai già perso, hai già vinto, in un'altra lingua. Da qui è vero.": "{TEAM} takes you off campus. You've already lost and won, in another language. From here, it's real.",
  "Due primavere di palestra piena, poi il salto. {TEAM} firma. Tu non sei più uno studente.": "Two springs of packed gyms, then the jump. {TEAM} signs you. You're not a student anymore.",
  "Il torneo di marzo ti ha visto da ragazzo. {TEAM} ti vuole da uomo. La differenza, adesso, la fai tu.": "March Madness saw you as a kid. {TEAM} wants you as a man. Now the difference is up to you.",
  "{0} ti prende dal campus. Il mestiere inizia qui.": "{0} takes you off campus. The job starts here.",
  "Cresci lontano dai riflettori americani: tattica, pazienza, palazzetti più stretti. {TEAM} scommette su quella testa.": "You grew up far from the American spotlight: tactics, patience, tighter arenas. {TEAM} is betting on that head.",
  "L'Europa ti ha insegnato a leggere prima di saltare. {TEAM} firma. Arrivi già da professionista.": "Europe taught you to read before you jump. {TEAM} signs you. You arrive already a professional.",
  "Un'altra geografia, la stessa palla. {TEAM} chiama. Un accento che in NBA si sente, e tiene.": "Another geography, the same ball. {TEAM} calls. An accent you can hear in the NBA, and one that holds up.",
  "Coppe infrasettimanali, difese lunghe, un passaporto già caldo. {TEAM} ti prende così.": "Midweek cup games, long defenses, a passport already warm. That's how {TEAM} takes you.",
  "Hai giocato da uomo tra uomini. {TEAM} lo ha visto. Una testa che non si spaventa del tempo morto.": "You played as a man among men. {TEAM} saw it. A head that doesn't panic at a timeout.",
  "{TEAM} firma l'accento, non solo il gesto. Arrivi già sapendo cosa chiede un tempo morto vero.": "{TEAM} signs the accent, not just the motion. You arrive already knowing what a real timeout demands.",
  "Palazzetti stretti, coppe lunghe. {TEAM} scommette che quella testa tiene anche qui.": "Tight arenas, long cup runs. {TEAM} is betting that head holds up here too.",
  "{0} firma. Arrivi dall'Europa, già da professionista.": "{0} signs you. You arrive from Europe, already a professional.",
  "Bruci le tappe. {TEAM} punta su di te senza farti invecchiare in un campus. Contratto breve, minuti subito.": "You skip steps. {TEAM} bets on you without letting you age on a campus. A short contract, minutes right away.",
  "Niente campus, niente attesa. {TEAM} ti prende grezzo. Due inverni, e il lavoro che inizia stanotte.": "No campus, no waiting. {TEAM} takes you raw. Two winters, and work that starts tonight.",
  "Salti il campus. {TEAM} accetta il rischio. Un contratto corto, e la fame che non si insegna.": "You skip college. {TEAM} accepts the risk. A short contract, and a hunger that can't be taught.",
  "{TEAM} non aspetta che tu sia pronto. Ti prende così. Due inverni, e il parquet che non mente.": "{TEAM} doesn't wait for you to be ready. It takes you as you are. Two winters, and a floor that doesn't lie.",
  "Dalla G-League al salto. {TEAM} firma corto. Niente alibi di campus, solo minuti da coprire.": "From the G League to the jump. {TEAM} signs you short. No campus alibis, just minutes to fill.",
  "{TEAM} ti ha visto in palazzetti vuoti. Adesso i palazzetti sono pieni, e tu resti lo stesso.": "{TEAM} saw you in empty gyms. Now the arenas are full, and you stay the same.",
  "Niente vetrina da marzo. {TEAM} prende la fame, e la fame, da qui, è il contratto.": "No March showcase. {TEAM} signs the hunger, and from here on the hunger is the contract.",
  "{0} ti prende grezzo. Contratto breve, minuti subito.": "{0} takes you raw. A short contract, minutes right away.",
  "Nessun premio individuale. Il lavoro resta, senza targa.": "No individual awards. The work remains, without a plaque.",
  "La lega ha scritto altri nomi. Il tuo anno è nel referto, non nella bacheca.": "The league wrote other names. Your year is in the box score, not the trophy case.",
  "Niente All-Star, niente titoli da appendere. Si chiude lo stesso.": "No All-Star, no titles to hang up. You close the year anyway.",
  "I voti sono andati altrove. Tu conti i minuti, che sono più onesti.": "The votes went elsewhere. You count the minutes, which are more honest.",
  "Un anno senza vetrina. Succede anche a chi merita, e anche a chi no.": "A year out of the shop window. It happens to those who deserve it too, and to those who don't.",
  "La bacheca resta com'era. Non tutte le stagioni devono lasciare un oggetto.": "The trophy case stays as it was. Not every season has to leave an object behind.",
  "Nessuna chiamata a febbraio. Marzo, però, c'è stato, intero.": "No call in February. March, though, was there, all of it.",
  "I premi hanno scelto altri. Il campo, no.": "The awards chose others. The court didn't.",
  "Niente targa. Il referto, però, c'è, pagina dopo pagina.": "No plaque. The box score, though, is there, page after page.",
  "Un anno da operaio. I voti passano oltre, il lavoro resta.": "A blue-collar year. The votes pass you by; the work remains.",
  "La bacheca individuale resta vuota. Non è una sentenza, è un elenco.": "The individual trophy case stays empty. It's not a sentence; it's a list.",
  "Nessun premio col tuo nome. Si chiude l'anno lo stesso, dritti.": "No award with your name on it. You close the year anyway, standing tall.",
  "I voti hanno scelto altri. Tu chiudi l'anno senza targa, e il campo resta onesto.": "The votes chose others. You close the year without a plaque, and the court stays honest.",
  "Niente chiamata a febbraio. Tu conti i possessi, che non votano.": "No call in February. You count the possessions, which don't vote.",
  "Nessun premio individuale, quest'anno.": "No individual award this year.",
  "Rookie of the Year. Una targa da ragazzo: da ora ti guardano, e non è un complimento gratuito.": "Rookie of the Year. A kid's plaque: from now on they watch you, and that's no free compliment.",
  "Il Rookie of the Year. Lo tieni, sapendo che il secondo ottobre non perdona i debutti.": "Rookie of the Year. You keep it, knowing the second October doesn't forgive rookie seasons.",
  "Il premio da ragazzo. Il dubbio, da stasera, è degli altri. Il lavoro, no: resta tuo.": "The kid's award. From tonight the doubt belongs to others. The work doesn't: it stays yours.",
  "Te l'hanno dato al primo giro. Adesso tocca diventare altro, senza alzare la voce.": "They gave it to you on the first go-round. Now you have to become something else, without raising your voice.",
  "Rookie of the Year. Lo tieni in tasca, non al collo. Ottobre, poi, non perdona i debutti.": "Rookie of the Year. You keep it in your pocket, not around your neck. October doesn't forgive debut seasons.",
  "Rookie of the Year. Da ora ti guardano.": "Rookie of the Year. From now on, they're watching you.",
  "A {AGE} anni te l'hanno dato per le chiusure. Il dubbio era l'età. Il palmo ha risposto prima.": "At {AGE} they gave it to you for your closeouts. The doubt was your age. Your hand answered first.",
  "A {AGE} anni, Defensive Player of the Year. Lo tieni in tasca: ottobre non perdona i palmi pigri.": "At {AGE}, Defensive Player of the Year. You keep it in your pocket: October doesn't forgive lazy hands.",
  "A {AGE} anni coprire è già un nome. Te l'hanno appeso senza festa, e questo basta.": "At {AGE}, covering already has a name. They pinned it on you without a party, and that's enough.",
  "Troppo presto, dicevano. Tu hai chiuso abbastanza da farli tacere, e il premio è questo.": "Too early, they said. You locked down enough to shut them up, and this is the award.",
  "A {AGE} anni la difesa ha il tuo nome. Non è un complimento: è un orario, da stasera.": "At {AGE}, the defense has your name on it. It's not a compliment: from tonight, it's a schedule.",
  "Chiudevi già, senza discorso. A {AGE} anni te l'hanno scritto su una targa, e basta.": "You were already locking people up, without a speech. At {AGE} they wrote it on a plaque, and that's it.",
  "Defensive Player of the Year. Il rispetto giusto.": "Defensive Player of the Year. The right kind of respect.",
  "A {AGE} anni te l'hanno dato per la memoria. Le ginocchia tengono l'archivio; tu ci metti il palmo.": "At {AGE} they gave it to you for your memory. Your knees keep the archive; you put the hand up.",
  "Premio tardi, e giusto. A quest'età chiudere è il mestiere che resta, e l'hanno letto.": "A late award, and a fair one. At this age, defense is the craft that remains, and they read it.",
  "A {AGE} anni coprire è già una vittoria. Te l'hanno riconosciuto senza copertina.": "At {AGE}, covering is already a win. They recognized it without a magazine cover.",
  "Il corpo firma dopo. La difesa l'hai firmata tu, tutte le sere, e qualcuno l'ha messa su una targa.": "The body signs later. You signed the defense yourself, every night, and someone put it on a plaque.",
  "A {AGE} anni il premio da chi chiude. Non chiedono più i numeri da manifesto: chiedono che tu resti lì.": "At {AGE}, the closer's award. They don't ask for poster numbers anymore: they ask you to stay right there.",
  "Defensive Player of the Year, a {AGE} anni. Il rispetto arriva quando i canestri da copertina sono già andati.": "Defensive Player of the Year, at {AGE}. Respect arrives when the cover-worthy buckets are already gone.",
  "Defensive Player of the Year. Si nota chi toglie, e quest'anno hai tolto abbastanza da avere un nome.": "Defensive Player of the Year. People notice those who take away, and this year you took away enough to earn a name.",
  "Defensive Player of the Year. Pochi applausi, molte graffiature, il rispetto che non finisce in copertina.": "Defensive Player of the Year. Little applause, lots of scratches, the respect that never makes the cover.",
  "Il premio a chi chiude. Lo staff, per una volta, parla del tuo palmo prima del tuo polso.": "The award for closers. For once, the staff talks about your hand before your wrist.",
  "Ti hanno visto coprire. È un complimento che si paga in contatti, e l'hai pagato.": "They saw you cover. It's a compliment paid in contact, and you paid it.",
  "Una targa per i possessi che non sono nati. Il mestiere, sotto, resta identico, e tu lo sai.": "A plaque for possessions that never happened. The craft underneath stays exactly the same, and you know it.",
  "Te l'hanno appeso per quello che togli. Da ottobre le domande, però, restano le stesse.": "They hung it on you for what you take away. From October, though, the questions stay the same.",
  "MVP. Una sera ti chiamano per nome, e il nome, da stasera, pesa di più.": "MVP. One night they call your name, and from tonight the name weighs more.",
  "Te l'hanno appeso. Il campionato, però, ricomincia identico, e tu lo sai.": "They hung it on you. The season, though, starts again just the same, and you know it.",
  "Il premio più corto. Le domande, da ottobre, sono le più lunghe.": "The shortest award. From October, the questions are the longest.",
  "MVP. Il peso arriva dopo.": "MVP. The weight comes later.",
  "All-Star. Un respiro, poi i lunedì, che non votano.": "All-Star. A breath, then the Mondays, which don't vote.",
  "Il voto è una luce corta. Il campionato, dopo, è lo stesso parquet.": "The vote is a short light. The season, afterwards, is the same floor.",
  "All-Star. Poi torna il campionato.": "All-Star. Then the regular season comes back.",
  "All-NBA. Una riga in una lista che non si compra, si tiene.": "All-NBA. A line on a list you can't buy, only keep.",
  "Il quintetto della lega. Non è un filmato: è un elenco, e il tuo nome c'è.": "The league's best five. It's not a highlight reel: it's a list, and your name is on it.",
  "All-NBA. Una riga secca. Il mestiere, sotto, resta identico.": "All-NBA. One plain line. The craft underneath stays the same.",
  "Il quintetto. I lunedì non cambiano; cambia il modo in cui ti chiamano.": "The All-NBA team. Mondays don't change; the way they introduce you does.",
  "Una lista, un nome. Il tuo. Poi ottobre, che non legge le liste.": "A list, a name. Yours. Then October, which doesn't read lists.",
  "All-NBA. Lo tieni in tasca, non al collo.": "All-NBA. You keep it in your pocket, not around your neck.",
  "All-NBA. Il nome c'è.": "All-NBA. The name is there.",
  "Ti hanno mosso. Da {FROM} a {TO}, senza che tu fossi al tavolo. L'armadietto nuovo non è ancora tuo.": "They moved you. From {FROM} to {TO}, without you at the table. The new locker isn't yours yet.",
  "Una chiamata, non una domanda. {FROM} ti cede: a {TO} l'estate ricomincia da un corridoio sconosciuto.": "A phone call, not a question. {FROM} trades you: in {TO} the summer starts again from an unknown hallway.",
  "Lo scambio si fa sopra la tua testa. Lasci {FROM}, atterri a {TO}. Il mestiere, stavolta, è obbedire.": "The trade happens over your head. You leave {FROM}, you land in {TO}. This time the job is to comply.",
  "Non l'hai scelto. {FROM} chiude, {TO} apre. Fai la valigia, e basta.": "You didn't choose it. {FROM} closes, {TO} opens. You pack your bag, and that's it.",
  "Ti spostano. {FROM} resta una maglia nello zaino; {TO} è un nome da imparare in fretta.": "They move you. {FROM} remains a jersey in your backpack; {TO} is a name to learn fast.",
  "Niente voto, niente rifiuto. Da {FROM} a {TO}: il mercato ha deciso, tu cammini.": "No vote, no veto. From {FROM} to {TO}: the market decided, you walk.",
  "Ceduto. {FROM} non ti ha chiesto il parere. A {TO} l'aria è diversa, e le scarpe ancora storte.": "Traded. {FROM} didn't ask your opinion. In {TO} the air is different, and the shoes still don't fit.",
  "Un aereo, un comunicato, un'altra insegna. {FROM} alle spalle, {TO} davanti. Si gioca lo stesso.": "A flight, a press release, another logo. {FROM} behind you, {TO} ahead. You play just the same.",
  "La dirigenza di {FROM} ha fatto i conti. I tuoi non c'entrano. {TO} ti aspetta, già.": "The {FROM} front office did its math. Yours didn't count. {TO} is already waiting for you.",
  "Mosso. Il parquet di {FROM} lo conoscevi al buio. Quello di {TO} si impara da lunedì.": "Moved. You knew the {FROM} floor in the dark. The {TO} floor you learn starting Monday.",
  "Ti hanno spostato. {FROM} resta un odore di spogliatoio; {TO} è un corridoio da imparare a memoria.": "They moved you. {FROM} remains a locker-room smell; {TO} is a hallway to learn by heart.",
  "Niente firma tua. Da {FROM} a {TO} il mestiere è lo stesso: scendere, e farsi riconoscere.": "Not your signature. From {FROM} to {TO} the job is the same: take the floor, and make them know you.",
  "Ti hanno mosso. Da {0} a {1}.": "They moved you. From {0} to {1}.",
  "Fuori dai playoff. Si gira pagina: estate, corpo, un'altra stagione.": "Out of the playoffs. Time to turn the page: summer, body, another season.",
  "La primavera è degli altri. A voi resta il lavoro di giugno, che è più duro.": "The spring belongs to others. You're left with June's work, which is harder.",
  "Niente serie. L'anno si chiude in campionato, e ha il sapore che ha.": "No series. The year ends in the regular season, and it tastes the way it tastes.",
  "La classifica non vi ha aperto la porta. Si torna a casa prima, e si lavora dopo.": "The standings didn't open the door for you. You go home early, and work later.",
  "Playoff lontani. Si accetta, si annota, si ricomincia.": "The playoffs are far away. You accept it, take note, start again.",
  "Fuori. Non è una tragedia, è un dato. Poi l'estate chiede conto.": "Out. It's not a tragedy; it's a fact. Then summer comes to collect.",
  "La griglia si chiude senza di voi. Resta il lavoro, che non aspetta i playoff.": "The bracket closes without you. The work remains, and it doesn't wait for the playoffs.",
  "Niente tunnel ad aprile. Un'estate più lunga, e più onesta.": "No April tunnel. A longer summer, and a more honest one.",
  "La primavera è una porta chiusa. Tu giri pagina: corpo, mestiere, un altro ottobre.": "The spring is a closed door. You turn the page: body, craft, another October.",
  "Fuori dalla griglia. Non cerchi alibi. Cerchi luglio, che è più utile.": "Out of the bracket. You don't look for alibis. You look for July, which is more useful.",
  "Fuori dai playoff. Si gira pagina.": "Out of the playoffs. Time to turn the page.",
  "all'Est": "in the East",
  "all'Ovest": "in the West",
  "in Eurolega": "in the EuroLeague",
  "{SEED}° in Eurolega. Quarti al meglio delle cinque, poi la Final Four.": "{SEED} seed in the EuroLeague. Best-of-five quarterfinals, then the Final Four.",
  "Dentro, {SEED}°. Prima una serie al meglio delle cinque, poi una partita sola per turno.": "In, as the {SEED} seed. First a best-of-five series, then a single game each round.",
  "{SEED}° in Europa: vantaggio del campo nei quarti, Final Four in campo neutro.": "{SEED} seed in Europe: home court in the quarterfinals, Final Four on neutral ground.",
  "{0}° in Eurolega. I playoff partono ora.": "{0} seed in the EuroLeague. The playoffs start now.",
  "{SEED}° {PLACE}. I playoff partono ora, serie al meglio delle sette.": "{SEED} seed {PLACE}. The playoffs start now, best-of-seven series.",
  "{SEED}° {PLACE}. La primavera ha un nome, e per ora è il vostro turno.": "{SEED} seed {PLACE}. Spring has a name, and for now it's your turn.",
  "Dentro, {SEED}° {PLACE}. Da qui ogni sera vale una settimana di campionato.": "In, the {SEED} seed {PLACE}. From here every night is worth a week of the regular season.",
  "{SEED}° {PLACE}. Sette partite, o meno, e niente più alibi di classifica.": "{SEED} seed {PLACE}. Seven games, or fewer, and no more standings alibis.",
  "{SEED}° {PLACE}. La porta è aperta. Dietro, {PLACE}, ogni sera vale una settimana.": "{SEED} seed {PLACE}. The door is open. Behind it, {PLACE}, every night is worth a week.",
  "Dentro da {SEED}°. {PLACE} non perdona i possessi pigri, e tu lo sai.": "In as the {SEED} seed. {PLACE} doesn't forgive lazy possessions, and you know it.",
  "{0}° {1}. I playoff partono ora.": "{0} seed {1}. The playoffs start now.",
  "I risultati sono chiusi. Quarti al meglio delle cinque, poi la Final Four.": "The results are in. Best-of-five quarterfinals, then the Final Four.",
  "Dentro. Prima la serie, poi una partita secca alla volta.": "In. First the series, then one single game at a time.",
  "La griglia è pronta: i quarti durano fino a tre vittorie; la Final Four no.": "The bracket is set: the quarterfinals go to three wins; the Final Four doesn't.",
  "I playoff partono ora, turno per turno.": "The playoffs start now, round by round.",
  "I risultati sono chiusi. I playoff partono ora, turno per turno.": "The results are in. The playoffs start now, round by round.",
  "Dentro. Il campionato è archivio. Adesso si parla un'altra lingua.": "In. The regular season is archived. Now you speak another language.",
  "La porta è aperta. Dietro, le serie, che non perdonano i possessi pigri.": "The door is open. Behind it, the series, which don't forgive lazy possessions.",
  "{TEAM} vuole tenerti. Sul tavolo ci sono anche altri progetti.": "{TEAM} wants to keep you. There are other projects on the table too.",
  "Rinnovo in casa, e voci da fuori. Tocca scegliere la piazza, non solo la cifra.": "An extension at home, and voices from outside. You have to choose the place, not just the figure.",
  "{TEAM} mette l'estensione sul tavolo. Gli altri mettono il resto.": "{TEAM} puts the extension on the table. The others put down the rest.",
  "Restare o partire: {TEAM} ha già detto la sua. Adesso tocca a te.": "Stay or leave: {TEAM} has already had its say. Now it's your turn.",
  "{TEAM} tiene aperta la porta. Fuori ci sono altre insegne, e nessuna è gratuita.": "{TEAM} keeps the door open. Outside there are other logos, and none of them come free.",
  "L'estensione di {TEAM} è una frase vera. Le altre piazze, se arrivano, pesano lo stesso.": "The {TEAM} extension is a real offer. The other markets, if they come, weigh just as much.",
  "{TEAM} non ti caccia. Ti chiede di scegliere, e la scelta non sta solo nei milioni.": "{TEAM} isn't pushing you out. It asks you to choose, and the choice isn't just about the millions.",
  "Rimanere a {TEAM} è una porta. Partire è un'altra. Tutte e due hanno un prezzo.": "Staying with {TEAM} is one door. Leaving is another. Both have a price.",
  "{0} vuole tenerti. Ci sono anche altre strade.": "{0} wants to keep you. There are other roads too.",
  "Il contratto è scaduto. Le strade sono sul tavolo: soldi, anni, una città da scegliere.": "The contract has expired. The roads are on the table: money, years, a city to choose.",
  "Svincolato. Le offerte arrivano con facce diverse, e nessuna è gratuita.": "Free agent. The offers arrive with different faces, and none of them come free.",
  "Mercato aperto. Ogni cifra ha un prezzo che non sta nel contratto.": "The market is open. Every figure has a price that isn't in the contract.",
  "Niente maglia, per ora. Solo fogli, cifre, e il nome di una città.": "No jersey, for now. Just papers, figures, and the name of a city.",
  "Svincolato. Tu scegli la piazza, non solo la cifra, e nessuna è senza prezzo.": "Free agent. You choose the place, not just the figure, and none of them come without a price.",
  "Il foglio è bianco. Le piazze no: hanno un nome, un palazzetto, un prezzo.": "The sheet is blank. The markets aren't: they have a name, an arena, a price.",
  "Contratto finito. Restano le città, e tu devi sceglierne una senza mentire a te stesso.": "Contract over. The cities remain, and you have to pick one without lying to yourself.",
  "Svincolato. Il mestiere, adesso, è leggere le piazze prima delle cifre.": "Free agent. The job, now, is reading the markets before the figures.",
  "Il contratto è scaduto. Tocca scegliere.": "The contract has expired. Time to choose.",
  "Un ottobre senza titoli": "An October without headlines",
  "La settimana che non fa notizia": "The week that makes no news",
  "Tra una voce e l'altra": "Between one rumor and the next",
  "Il giorno dopo i giornali": "The day after the papers",
  "Una stagione che chiede silenzio": "A season that asks for silence",
  "Niente da dichiarare": "Nothing to declare",
  "Il lavoro che non si vede": "The work no one sees",
  "Una parentesi nel calendario": "A pause in the calendar",
  "Senza copertina": "No magazine cover",
  "Tra due notizie": "Between two stories",
  "Un mercoledì qualunque": "An ordinary Wednesday",
  "Fuori dal rumore": "Away from the noise",
  "La pausa che pesa": "The pause that weighs",
  "Niente avversario col nome": "No named opponent",
  "Solo il mestiere": "Just the craft",
  "Un inverno senza tesi": "A winter without a thesis",
  "La pagina bianca": "The blank page",
  "Niente riflettori, stavolta": "No spotlight, this time",
  "Una settimana da spogliatoio": "A locker-room week",
  "Il silenzio di novembre": "The silence of November",
  "I giorni uguali, tenuti dritti": "Identical days, kept straight",
  "Niente apice": "No peak",
  "Un lunedì che non chiede niente": "A Monday that asks for nothing",
  "La stanza senza microfoni": "The room without microphones",
  "Dopo il rumore, prima del prossimo": "After the noise, before the next",
  "Un appello senza nome": "A roll call with no name",
  "La tregua del mestiere": "The truce of the craft",
  "Niente tesi da vendere": "No thesis to sell",
  "Un ottobre senza copertina": "An October without a cover",
  "La settimana che non ha un nome": "The week without a name",
  "Tra un aereo e il prossimo silenzio": "Between one flight and the next silence",
  "Un febbraio senza tesi": "A February without a thesis",
  "La palestra, nuda, di lunedì": "The gym, bare, on a Monday",
  "Niente avversario da copertina": "No cover-story opponent",
  "I giorni che non fanno titolo": "The days that don't make headlines",
  "Non tutte le settimane hanno un avversario col nome. Questa chiede solo di essere attraversata.": "Not every week has a named opponent. This one only asks to be gotten through.",
  "Lo staff non alza la voce. Tu devi decidere come usare il vuoto.": "The staff doesn't raise its voice. You have to decide how to use the void.",
  "Niente copertine. Resta il lavoro, nudo, e tre modi di tenerlo.": "No magazine covers. The work remains, bare, and three ways to hold on to it.",
  "Una pausa nel rumore. Può essere un dono o un avvertimento.": "A pause in the noise. It can be a gift or a warning.",
  "Il rumore è altrove. Qui restano tre scelte, e nessuna fa notizia.": "The noise is elsewhere. Here there are three choices, and none of them makes news.",
  "Un vuoto nel calendario. Si riempie, o si subisce.": "A gap in the calendar. You fill it, or you suffer it.",
  "Niente avversario col nome. Resta da decidere come tenere i giorni.": "No named opponent. What's left is deciding how to hold on to the days.",
  "Lo staff aspetta. Non una dichiarazione: un modo di stare.": "The staff is waiting. Not for a statement: for a way of being.",
  "I giornali hanno trovato un altro nome. A te resta la palestra, e tre modi di entrarci.": "The papers have found another name. You're left with the gym, and three ways to walk in.",
  "Una settimana senza tesi. Si tiene, o si spreca. Tocca a te.": "A week without a thesis. You hold on to it, or you waste it. It's up to you.",
  "Il calendario non chiede un racconto. Chiede di esserci. Come, lo scegli tu.": "The calendar doesn't ask for a story. It asks you to show up. How, you choose.",
  "Niente da appendere. Solo i giorni, e tre modi di farli pesare.": "Nothing to hang up. Just the days, and three ways to make them count.",
  "Una settimana senza nome. Tu scegli come tenerla, e basta.": "A week without a name. You choose how to hold on to it, and that's it.",
  "Il vuoto nel calendario non è un alibi. È un compito, nudo.": "A gap in the calendar isn't an alibi. It's a task, bare.",
  "un'": "un'"
};
