/* English narrative for league. Key: Italian source text (see ../key.ts). */
export const EN_LEAGUE: Readonly<Record<string, string>> = {
  "{0} punti, {1} vittorie": "{0} points, {1} wins",
  "{0} punti, {1}-{2}": "{0} points, {1}-{2}",
  "Miglior difesa, {0} punti subiti": "Best defense, {0} points allowed",
  "Da {0} a {1} punti": "From {0} to {1} points",
  "Il salto di qualità della stagione": "The breakout of the season",
  "{0} minuti, {1} punti": "{0} minutes, {1} points",
  "Dalla panchina, {0} punti": "Off the bench, {0} points",
  "{0}-{1} (noi–{2}, {3})": "{0}-{1} (us vs. {2}, {3})",
  "Serie chiusa {SCORE}. {OPP} non ha più risposte.": "Series closed out {SCORE}. {OPP} has no answers left.",
  "{SCORE}: il palazzetto canta il tuo nome, {OPP} è fuori.": "{SCORE}: the arena chants your name, {OPP} is out.",
  "Li spezzi {SCORE}. La difesa di {OPP} cede sul più bello.": "You break them {SCORE}. The {OPP} defense gives way at the worst moment.",
  "Una serie da spogliatoio, {SCORE}. {OPP} resta sul parquet.": "A locker-room series, {SCORE}. {OPP} is left on the floor.",
  "{SCORE}. Hai letto i loro tempi morti meglio di loro.": "{SCORE}. You read their timeouts better than they did.",
  "Gara dopo gara, {SCORE}. {OPP} esce a testa bassa.": "Game after game, {SCORE}. {OPP} walks off with heads down.",
  "{SCORE} e via. {OPP} ha lottato; tu hai chiuso.": "{SCORE} and done. {OPP} fought; you closed.",
  "La serie finisce {SCORE}. In tunnel, stavolta, il rumore è tuo.": "The series ends {SCORE}. In the tunnel, this time, the noise is yours.",
  "{SCORE}. La porta della serie si chiude alle loro spalle.": "{SCORE}. The series door closes behind them.",
  "Li mandi a casa {SCORE}. Nessun discorso: il tabellone basta.": "You send them home {SCORE}. No speech: the scoreboard is enough.",
  "{OPP} cede {SCORE}. La serie, alla fine, aveva il tuo passo.": "{OPP} gives way {SCORE}. In the end, the series moved at your pace.",
  "Chiusa {SCORE}. Il fiato torna, {OPP} no.": "Closed out {SCORE}. Your breath comes back; {OPP} doesn't.",
  "Una vittoria dopo l'altra, {SCORE}. {OPP} guarda il tabellone spento.": "One win after another, {SCORE}. {OPP} stares at a dark scoreboard.",
  "Li superi {SCORE}. Non è stata fortuna: è stato un piano tenuto.": "You get past them {SCORE}. It wasn't luck: it was a plan you stuck to.",
  "Serie vinta {SCORE}. Il tunnel, all'uscita, ha il tuo respiro.": "Series won {SCORE}. The tunnel, on the way out, carries your breath.",
  "{OPP} esce {SCORE}. Tu resti, e questo basta come discorso.": "{OPP} goes out {SCORE}. You stay, and that's speech enough.",
  "La serie si chiude {SCORE}. {OPP} ha avuto le sue occasioni; voi avete tenuto l'ultimo possesso.": "The series closes {SCORE}. {OPP} had its chances; you held the last possession.",
  "{SCORE}. Il tunnel, all'uscita, ha il tuo respiro e il loro silenzio.": "{SCORE}. The tunnel, on the way out, carries your breath and their silence.",
  "Partita chiusa {SCORE}. {OPP} non ha più risposte.": "Game over, {SCORE}. {OPP} has no answers left.",
  "Una sera sola, {SCORE}: il palazzetto canta il tuo nome.": "One night only, {SCORE}: the arena chants your name.",
  "Final Four superata. {SCORE}, e il tabellone resta aperto.": "Final Four semifinal won. {SCORE}, and the bracket stays open.",
  "{SCORE} contro {OPP}. Hai tenuto l'ultimo possesso.": "{SCORE} against {OPP}. You held the last possession.",
  "Una partita, nessun domani per loro. {SCORE} e si va avanti.": "One game, no tomorrow for them. {SCORE} and you move on.",
  "Finisce {SCORE}. Una partita sola, e {OPP} va avanti.": "It ends {SCORE}. One game only, and {OPP} moves on.",
  "{SCORE} contro {OPP}. La Final Four finisce qui.": "{SCORE} against {OPP}. The Final Four ends here.",
  "Il tabellone non concede un'altra sera: {SCORE}, stagione finita.": "The scoreboard doesn't grant another night: {SCORE}, season over.",
  "Una partita decisa in pochi possessi. {OPP} ha tenuto l'ultimo.": "A game decided in a handful of possessions. {OPP} held the last one.",
  "{OPP} passa dopo una partita sola. Il parquet si svuota in fretta.": "{OPP} goes through after a single game. The floor empties fast.",
  "{OPP} chiude {SCORE}. La corsa si ferma qui.": "{OPP} closes it out {SCORE}. The run stops here.",
  "Un possesso di troppo, una sera di meno. {OPP} passa {SCORE}.": "One possession too many, one night too few. {OPP} goes through {SCORE}.",
  "La serie scivola via {SCORE}. {OPP} era più pronto stanotte.": "The series slips away {SCORE}. {OPP} was more ready tonight.",
  "{SCORE}. Hanno trovato l'angolo che non coprivi.": "{SCORE}. They found the corner you weren't covering.",
  "Fine corsa, {SCORE}. {OPP} merita il turno successivo.": "End of the road, {SCORE}. {OPP} deserves the next round.",
  "{OPP} va avanti {SCORE}. Tu resti con una primavera incompiuta.": "{OPP} moves on {SCORE}. You're left with an unfinished spring.",
  "{SCORE}. Non è stata una rapina: sono stati migliori, punto.": "{SCORE}. It wasn't a robbery: they were better, period.",
  "Eliminati {SCORE}. Il tunnel, all'uscita, è più lungo.": "Eliminated {SCORE}. The tunnel, on the way out, is longer.",
  "{SCORE}. Una serie che si è stretta, e voi ci siete passati attraverso stretti.": "{SCORE}. A series that tightened, and you squeezed through it.",
  "{OPP} chiude il discorso {SCORE}. Resta da ascoltare, e poi andarsene.": "{OPP} ends the conversation {SCORE}. All that's left is to listen, and then leave.",
  "Fuori {SCORE}. Non servono alibi: la serie ha scelto loro.": "Out {SCORE}. No alibis needed: the series chose them.",
  "{SCORE}. La primavera si chiude prima del discorso che avevi pronto.": "{SCORE}. The spring closes before the speech you had ready.",
  "Eliminati da {OPP}, {SCORE}. Si torna a casa con i possessi sbagliati in testa.": "Eliminated by {OPP}, {SCORE}. You head home with the wrong possessions in your head.",
  "{SCORE}. Hanno tenuto un possesso in più. Basta quello, a giugno.": "{SCORE}. They held one more possession. In June, that's all it takes.",
  "La corsa finisce {SCORE}. {OPP} va avanti, tu resti con aprile incompleto.": "The run ends {SCORE}. {OPP} moves on; you're left with an unfinished April.",
  "{SCORE}. Si torna a casa con i possessi sbagliati, e nient'altro da dire.": "{SCORE}. You head home with the wrong possessions, and nothing else to say.",
  "Fuori {SCORE} da {OPP}. La primavera si chiude in punta, senza discorso.": "Out {SCORE} against {OPP}. The spring ends abruptly, without a speech.",
  "È il titolo. {OPP} cede {SCORE}, e l'anello pesa al dito.": "It's the title. {OPP} gives way {SCORE}, and the ring weighs on your finger.",
  "{SCORE} in finale. Confetti, ghiaccio, silenzio — poi il rumore.": "{SCORE} in the Finals. Confetti, ice, silence — then the noise.",
  "Li chiudi {SCORE}. Per una notte il mondo ha il tuo nome.": "You close them out {SCORE}. For one night the world has your name.",
  "{SCORE}. Alzi qualcosa che non si descrive. Si tiene.": "{SCORE}. You lift something that can't be described. You just hold it.",
  "Finale chiusa {SCORE} su {OPP}. La città, stanotte, è tua.": "Finals closed out {SCORE} over {OPP}. Tonight the city is yours.",
  "{SCORE}. Giugno vi appartiene, e {OPP} lo sa per ultimo.": "{SCORE}. June belongs to you, and {OPP} is the last to find out.",
  "Campioni, {SCORE}. Il peso al dito arriva dopo, a casa, in silenzio.": "Champions, {SCORE}. The weight on your finger comes later, at home, in silence.",
  "{OPP} cede in finale {SCORE}. Non si trova una frase: si alza.": "{OPP} gives way in the Finals {SCORE}. You can't find a sentence: you lift it.",
  "Anello, {SCORE}. {OPP} c'è quasi arrivato. Voi ci siete arrivati.": "A ring, {SCORE}. {OPP} almost got there. You got there.",
  "{SCORE} in sette, o meno. Il dito pesa, e la città canta.": "{SCORE} in seven, or fewer. Your finger feels heavy, and the city sings.",
  "Campioni contro {OPP}, {SCORE}. Il silenzio dopo i confetti è il più buono.": "Champions against {OPP}, {SCORE}. The silence after the confetti is the best kind.",
  "Giugno chiude {SCORE}. L'anello non si descrive: si tiene, e si tace un poco.": "June closes {SCORE}. A ring can't be described: you hold it, and stay quiet for a while.",
  "{SCORE}. La serie più lunga dell'anno, e l'unica che resta appesa.": "{SCORE}. The longest series of the year, and the only one that stays hanging on the wall.",
  "Titolo, {SCORE} su {OPP}. Il parquet, stanotte, ha un altro suono.": "Title, {SCORE} over {OPP}. Tonight the floor sounds different.",
  "{OPP} si ferma {SCORE}. Voi no. È questo, il discorso.": "{OPP} stops at {SCORE}. You don't. That's the speech.",
  "Campioni. {SCORE}. Il resto, a casa, senza microfoni.": "Champions. {SCORE}. The rest at home, no microphones.",
  "{SCORE}. Per una notte la città non ha altre domande. Poi sì, e tu ci sei.": "{SCORE}. For one night the city has no other questions. Then it does, and you're there.",
  "Anello. {SCORE} su {OPP}. Si tiene, e si tace un poco.": "A ring. {SCORE} over {OPP}. You hold it, and stay quiet for a while.",
  "Eurolega tua. {SCORE} contro {OPP}, e il trofeo sale con te.": "The EuroLeague is yours. {SCORE} against {OPP}, and the trophy goes up with you.",
  "Una partita per il titolo, {SCORE} contro {OPP}. Sei campione d'Europa.": "One game for the title, {SCORE} against {OPP}. You're the champion of Europe.",
  "Ultimo possesso, ultima sirena: {SCORE} contro {OPP}. Il trofeo è tuo.": "Last possession, final buzzer: {SCORE} against {OPP}. The trophy is yours.",
  "Final Four, ultima pagina: campioni d'Europa, {SCORE} contro {OPP}.": "Final Four, last page: champions of Europe, {SCORE} against {OPP}.",
  "Una sola finale, e basta così: {SCORE} contro {OPP}. La coppa è tua.": "A single final, and that's that: {SCORE} against {OPP}. The cup is yours.",
  "{OPP} si ferma qui. La finale finisce {SCORE}, la coppa parte con te.": "{OPP} stops here. The final ends {SCORE}, and the cup leaves with you."
};
