/* English narrative for legacy. Key: Italian source text (see ../key.ts). */
export const EN_LEGACY: Readonly<Record<string, string>> = {
  "Candidato, non eletto": "Nominated, not inducted",
  "Fuori dalla Hall": "Outside the Hall",
  "Una carriera breve. Il mestiere non ha avuto il tempo di diventare abitudine.": "A short career. The craft never had time to become a habit.",
  "Quindici stagioni, o più: {0} anni di referto. La longevità, qui, non è un incidente.": "Fifteen seasons, or more: {0} years in the box scores. Longevity, here, is no accident.",
  "{0} stagioni. Abbastanza per una biografia, non abbastanza per annoiarsi.": "{0} seasons. Enough for a biography, not enough to get bored.",
  "Sei partito da pochi minuti. Il picco è arrivato dopo, quando il ruolo ha smesso di essere un favore.": "You started from scraps of minutes. The peak came later, when the role stopped being a favor.",
  "Il tuo primo anno prometteva. Il resto della carriera non ha confermato il rumore di ottobre.": "Your first year was promising. The rest of the career didn't live up to the October buzz.",
  "Hai cominciato già visibile. Il resto è stato tenere quella luce accesa.": "You started out already in the spotlight. The rest was keeping that light on.",
  "Il Rookie of the Year c'è stato. Poi bisognava diventare altro.": "Rookie of the Year happened. Then you had to become something else.",
  "{0} volte Defensive Player of the Year. Si nota chi toglie, e tu hai tolto abbastanza da restare nei libri.": "{0}-time Defensive Player of the Year. People notice those who take away, and you took away enough to stay in the books.",
  "Defensive Player of the Year, una volta. Il rispetto che non finisce in copertina, e per questo dura.": "Defensive Player of the Year, once. The respect that never makes the cover, and that's why it lasts.",
  "{0} MVP. Non è un premio che si eredita: si ripete, o si smentisce.": "{0} MVPs. It isn't an award you inherit. You do it again, or the first one starts to look like a fluke.",
  "Un MVP. Una stagione in cui la lega ha detto il suo nome per primo.": "One MVP. A season when the league said your name first.",
  "{0} anelli. Una dinastia ha avuto il suo volto, e il volto eri tu.": "{0} rings. A dynasty had its face, and the face was yours.",
  "Due titoli. Abbastanza per non essere un incidente di calendario.": "Two titles. Enough not to be a scheduling accident.",
  "Un titolo. Basta per cambiare il modo in cui una città ricorda giugno.": "One title. Enough to change how a city remembers June.",
  "Nessun anello, un picco da fenomeno. Il palmarès resta incompleto, non piccolo.": "No ring, a phenomenon's peak. The trophy case stays incomplete, not small.",
  "Nessun titolo. Non tutte le carriere chiudono con i confetti.": "No titles. Not every career ends with confetti.",
  "Gli infortuni hanno scritto più di una pagina. Il corpo ha chiesto il conto, più di una volta.": "Injuries wrote more than one page. The body came to collect, more than once.",
  "Un anno spezzato. Si vede ancora, nel modo in cui conta i minuti.": "A broken year. It still shows, in the way you count minutes.",
  "Quattro maglie, o più. {0} città. Il mestiere è stato un viaggio, non una casa.": "Four jerseys, or more. {0} cities. The craft was a journey, not a home.",
  "Una sola maglia: {0}. Raro, e si vede.": "A single jersey: {0}. Rare, and it shows.",
  "Due maglie. Un passaggio, non un esilio.": "Two jerseys. A move, not an exile.",
  "Hai chiuso con un anello da veterano. Il tipo di fine che si racconta senza alzare la voce.": "You finished with a ring as a veteran. The kind of ending you tell without raising your voice.",
  "I tuoi ultimi minuti sono stati pochi. Il picco, però, resta negli occhi di chi c'era.": "Your last minutes were few. The peak, though, stays in the eyes of those who were there.",
  "La Hall of Fame ti tiene. I numeri, e il contesto, bastano.": "The Hall of Fame keeps you. The numbers, and the context, are enough.",
  "La Hall ti discute, non ti chiude. Resta il dibattito, che è già una forma di rispetto.": "The Hall debates you and doesn't close the case. The argument stays, and that is already a kind of respect.",
  "Fuori dalla Hall. Un picco alto non è un passaporto, e lo sai.": "Outside the Hall. A high peak isn't a passport, and you know it.",
  "{0} è restato nel discorso. Non sul referto di ogni sera: nella testa, dove le rivalità durano.": "{0} stayed in the conversation. Not on every night's box score: in your head, where rivalries last.",
  "Una svolta di mercato: {0}. Da lì la vita ha preso un'altra strada.": "A market turning point: {0}. From there, your life took another road.",
  "Sei arrivato dall'Europa. Si sente ancora, nel modo in cui leggi il campo.": "You came from Europe. It still shows, in the way you read the floor.",
  "Hai bruciato le tappe. Il grezzo, all'inizio, era il punto di forza e il rischio.": "You skipped steps. Rawness, at the start, was both your strength and your risk.",
  "Una carriera senza proclami. I giorni, fatti fino in fondo, e basta.": "A career without proclamations. The days, lived all the way through, and that's it."
};
