/* Proper names of players, coaches and clubs: never translated (a few Italian place/feature names are). */
export const EN_NAMES: Readonly<Record<string, string>> = {
  "Devon Marsh": "Devon Marsh",
  "Kalen Ibe": "Kalen Ibe",
  "Tomas Vukovic": "Tomas Vukovic",
  "Andre Kellerman": "Andre Kellerman",
  "Riko Tanaka": "Riko Tanaka",
  "Elijah Voss": "Elijah Voss",
  "Mateo Ruiz": "Mateo Ruiz",
  "Nico Halvorsen": "Nico Halvorsen",
  "Coach Ferretti": "Coach Ferretti",
  "Coach Whitfield": "Coach Whitfield",
  "Coach Delgado": "Coach Delgado",
  "Coach Okafor": "Coach Okafor",
  "Coach Lindqvist": "Coach Lindqvist",
  "Coach Brennan": "Coach Brennan",
  "L'Atleta Puro": "The Pure Athlete",
  "IQ Cestistico": "Basketball IQ",
  "Team USA": "Team USA",
  "EuroLeague Champion": "EuroLeague Champion",
  "NBA Champion": "NBA Champion",
  "Finals MVP": "Finals MVP",
  "All-NBA First Team": "All-NBA First Team",
  "All-NBA Second Team": "All-NBA Second Team",
  "All-NBA Third Team": "All-NBA Third Team",
  "Most Improved Player": "Most Improved Player",
  "Sixth Man": "Sixth Man",
  "Boston Celtics": "Boston Celtics",
  "Darius Lang": "Darius Lang",
  "Oklahoma City Thunder": "Oklahoma City Thunder",
  "Soren Blake": "Soren Blake",
  "Ellis Ward": "Ellis Ward",
  "Nella Hall": "In the Hall",
  "New York Knicks": "New York Knicks",
  "New York": "New York",
  "Jonah Hale": "Jonah Hale",
  "Marcus Veld": "Marcus Veld",
  "Brooklyn Nets": "Brooklyn Nets",
  "Tariq Bell": "Tariq Bell",
  "Toronto Raptors": "Toronto Raptors",
  "Cleveland Cavaliers": "Cleveland Cavaliers",
  "Detroit Pistons": "Detroit Pistons",
  "Milwaukee Bucks": "Milwaukee Bucks",
  "Indiana Pacers": "Indiana Pacers",
  "Chicago Bulls": "Chicago Bulls",
  "Orlando Magic": "Orlando Magic",
  "Atlanta Hawks": "Atlanta Hawks",
  "Miami Heat": "Miami Heat",
  "Luis Navarro": "Luis Navarro",
  "Charlotte Hornets": "Charlotte Hornets",
  "Pavel Holm": "Pavel Holm",
  "Washington Wizards": "Washington Wizards",
  "Chris Adeyemi": "Chris Adeyemi",
  "Oklahoma City": "Oklahoma City",
  "Denver Nuggets": "Denver Nuggets",
  "Milan Kovac": "Milan Kovac",
  "Minnesota Timberwolves": "Minnesota Timberwolves",
  "Ilya Petrov": "Ilya Petrov",
  "Portland Trail Blazers": "Portland Trail Blazers",
  "Jamal Crowe": "Jamal Crowe",
  "Utah Jazz": "Utah Jazz",
  "Salt Lake City": "Salt Lake City",
  "Owen Drake": "Owen Drake",
  "Houston Rockets": "Houston Rockets",
  "Darius Cole": "Darius Cole",
  "Dallas Mavericks": "Dallas Mavericks",
  "Stefan Popovic": "Stefan Popovic",
  "San Antonio Spurs": "San Antonio Spurs",
  "San Antonio": "San Antonio",
  "Rafael Mendes": "Rafael Mendes",
  "Memphis Grizzlies": "Memphis Grizzlies",
  "Kwame Rivers": "Kwame Rivers",
  "New Orleans Pelicans": "New Orleans Pelicans",
  "New Orleans": "New Orleans",
  "Etienne Bourg": "Etienne Bourg",
  "Los Angeles Lakers": "Los Angeles Lakers",
  "Los Angeles": "Los Angeles",
  "Miles Navarro": "Miles Navarro",
  "Golden State Warriors": "Golden State Warriors",
  "San Francisco": "San Francisco",
  "Kenji Sato": "Kenji Sato",
  "LA Clippers": "LA Clippers",
  "Omar Grant": "Omar Grant",
  "Phoenix Suns": "Phoenix Suns",
  "Felix Ortega": "Felix Ortega",
  "Sacramento Kings": "Sacramento Kings",
  "Harvey Quinn": "Harvey Quinn",
  "Real Madrid": "Real Madrid",
  "Sergio Varela": "Sergio Varela",
  "FC Barcelona": "FC Barcelona",
  "Nikola Ristic": "Nikola Ristic",
  "Kostas Elia": "Kostas Elia",
  "Dimitris Vlachos": "Dimitris Vlachos",
  "Can Erdem": "Can Erdem",
  "Anadolu Efes": "Anadolu Efes",
  "Arda Yilmaz": "Arda Yilmaz",
  "Lorenzo Bianchi": "Lorenzo Bianchi",
  "Virtus Bologna": "Virtus Bologna",
  "Marco Neri": "Marco Neri",
  "AS Monaco": "AS Monaco",
  "Alpha Diallo": "Alpha Diallo",
  "Zalgiris Kaunas": "Zalgiris Kaunas",
  "Jonas Petrauskas": "Jonas Petrauskas",
  "Partizan Belgrado": "Partizan Belgrado",
  "Luka Jovanovic": "Luka Jovanovic",
  "Maccabi Tel Aviv": "Maccabi Tel Aviv",
  "Tel Aviv": "Tel Aviv",
  "Gal Rosen": "Gal Rosen",
  "Iker Sanz": "Iker Sanz",
  "Bayern Monaco": "Bayern Monaco",
  "Monaco di Baviera": "Munich",
  "Leon Krüger": "Leon Krüger",
  "Crvena Zvezda": "Crvena Zvezda",
  "Marko Ilic": "Marko Ilic",
  "ALBA Berlino": "ALBA Berlino",
  "Tim Schafer": "Tim Schafer",
  "Asher Quinn": "Asher Quinn",
  "Malik Crowe": "Malik Crowe",
  "Luka Petrovic": "Luka Petrovic",
  "Jalen Voss": "Jalen Voss",
  "Enzo Moretti": "Enzo Moretti",
  "Caleb Okoye": "Caleb Okoye",
  "Theo Marais": "Theo Marais",
  "Isaiah Flint": "Isaiah Flint",
  "Mateo Silva": "Mateo Silva",
  "Noah Berg": "Noah Berg",
  "Kobe Daramy": "Kobe Daramy",
  "Pavel Novak": "Pavel Novak",
  "PIVOT 23": "PIVOT 23",
  "Career Card": "Career Card"
};
