/* English narrative for PivotApp. Key: Italian source text (see ../key.ts). */
export const EN_PIVOTAPP: Readonly<Record<string, string>> = {
  "Si va avanti.": "Moving on.",
  "La pagina si è persa. Si va avanti.": "The page got lost. Moving on.",
  "Italia": "Italy",
  "Il Rookie": "The Rookie",
  "Percorso": "Path",
  "Chiamata": "The call",
  "{0} Sei la {1}ª scelta. Contratto: {2} {3} a {4} milioni.": "{0} You are the {1:ord} pick. Contract: {2} {2|year|years} at {4} million.",
  "Stagione {0} · {1}": "Season {0} · {1}",
  "Stagione": "Season",
  "Dentro. I playoff partono.": "In. The playoffs begin.",
  "Fuori. Si gira pagina.": "Out. Time to turn the page.",
  "Fuori": "Out",
  "Playoff": "Playoffs",
  "Scelta": "Choice",
  "vs {0}": "vs {0}",
  "Estate": "Summer",
  "Mantenimento": "Holding steady",
  "{0} ha chiuso senza chiederti il permesso.": "{0} closed the deal without asking your permission.",
  "{0} è sul foglio. Puoi salire o restare.": "{0} is on the sheet. You can go, or you can stay.",
  "Agenzia libera": "Free agency",
  "Rinnovo": "Extension",
  "Trasferimento": "Move",
  "Resti a {0}: {1} anni a ${2}M a stagione.": "You stay with {0}: {1} years at ${2}M a season.",
  "Lasci {0} per {1}: {2} anni a ${3}M a stagione.": "You leave {0} for {1}: {2} years at ${3}M a season.",
  "Scambio": "Trade",
  "Lo scambio si fa: da {0} a {1}.": "The trade goes through: from {0} to {1}.",
  "Resto": "I stay",
  "Rifiuti. Resti a {0}, che apprezza la fedeltà.": "You decline. You stay with {0}, and they appreciate the loyalty.",
  "Scambio chiuso": "Trade done",
  "La dirigenza ha deciso: da {0} a {1}. {2}": "The front office made the call: from {0} to {1}. {2}",
  "Decisione": "Decision",
  "Un'altra stagione.": "One more season.",
  "Italiano": "Italiano",
  "English": "English",
  "Powered by Totem": "Powered by Totem",
  "1 season played": "1 season played",
  "{0} seasons played": "{0} seasons played",
  "1 stagione giocata": "1 season played",
  "{0} stagioni giocate": "{0} seasons played",
  "{0} Overall {1} → {2} ({3}{4}).": "{0} Overall {1} → {2} ({3}{4}).",
  "Europa": "Europe",
  "vignette beat-important stake-gold": "vignette beat-important stake-gold",
  "beat-wow finale": "beat-wow finale",
  "· OVR": "· OVR",
  "GP ·": "GP ·",
  "GP · PER": "GP · PER",
  "PPG · OVR": "PPG · OVR",
  "· sim": "· sim",
  "Career Card ·": "Career Card ·",
  "· Legacy": "· Legacy",
  "{0}. Il mestiere si è mosso: overall {1} → {2}. Poi squilla il telefono: {3}ª scelta, {4}.": "{0}. Your game has moved: overall {1} → {2}. Then the phone rings: {3:ord} pick, {4}.",
  "Il Draft si avvicina. {0}, {1}, deve scegliere i primi passi da professionista.": "The Draft is coming. {0}, {1}, has to choose the first steps as a pro."
};
