/* English narrative for playoff-doors. Key: Italian source text (see ../key.ts). */
export const EN_PLAYOFF_DOORS: Readonly<Record<string, string>> = {
  "Chiedi il possesso, anche se trema": "Ask for the ball, even if your hand shakes",
  "Non ti nascondi. Il primo aprile è un esame.": "You don't hide. Your first April is an exam.",
  "Alzi la mano, anche se trema. Qualcuno in panchina alza un sopracciglio. Poi la palla arriva, e il primo aprile è già un esame.": "You raise your hand, even if it shakes. Someone on the bench raises an eyebrow. Then the ball arrives, and your first April is already an exam.",
  "Segui i veterani, possesso dopo possesso": "Follow the veterans, possession after possession",
  "Loro questa serie la sanno a memoria. Tu copi il passo, possesso dopo possesso, senza chiedere il permesso di esistere.": "They know this series by heart. You copy their pace, possession after possession, without asking permission to exist.",
  "Un passaggio in più, un tempo morto ascoltato fino in fondo. Il palazzetto capisce dopo; lo staff, subito.": "One more pass, a timeout listened to all the way. The arena understands later; the staff, right away.",
  "Prendi il compito sporco sul loro giovane": "Take the dirty job on their young star",
  "Stessa età, un altro contratto. Chiudi lui.": "Same age, a different contract. Lock him up.",
  "Il loro ragazzo suda. Tu anche. È un inizio.": "Their kid is sweating. So are you. It's a start.",
  "Ogni rimbalzo, come se fosse l'ultimo": "Every rebound as if it were the last",
  "Il corpo è nuovo. Usalo, senza risparmiarti.": "The body is new. Use it, hold nothing back.",
  "Chiusura sul rimbalzo, secondo salto, un fallo che vale. Le ginocchia annotano.": "Box out, second jump, a foul worth giving. Your knees take notes.",
  "Ascolta il tempo morto, poi esegui": "Listen to the timeout, then execute",
  "Niente invenzioni. Il piano è già scritto.": "No improvising. The plan is already written.",
  "Ripeti lo schema a voce bassa, come una preghiera laica. Entri. Lo staff non sorride: annuisce, e basta.": "You repeat the play under your breath, the way you've said it a hundred times. You go in. The staff doesn't smile. They nod, and that's it.",
  "La fame, nuda, sul possesso largo": "Raw hunger, on the wide-open possession",
  "Se arrivi fin qui da ragazzo, non restare educato. La fame, nuda, vale più del copione.": "If you made it this far as a kid, don't stay polite. Raw hunger is worth more than the script.",
  "Un tiro che a novembre non avresti preso. Stasera sì.": "A shot you wouldn't have taken in November. Tonight you do.",
  "Parla tu, anche se la voce trema": "You speak up, even if your voice shakes",
  "Un cerchio, tre secondi, una frase. Basta quella, e il gruppo si stringe intorno.": "A huddle, three seconds, one sentence. That's enough, and the group tightens around it.",
  "Dici poco. Il gruppo si stringe. Qualcuno più vecchio di te annuisce.": "You say little. The group tightens. Someone older than you nods.",
  "Ruota, aiuta, non cercare il contrasto": "Rotate, help, don't go looking for the clash",
  "Il loro veterano è più furbo. Tu copri gli spazi.": "Their veteran is craftier. You cover the gaps.",
  "Un aiuto in tempo. Lo staff non sorride: annota.": "A help rotation on time. The staff doesn't smile: it takes notes.",
  "Il tabellone, anche se non è il tuo mestiere": "The glass, even if it's not your job",
  "Un corpo in più sotto. Basta quello.": "One more body under the rim. That's enough.",
  "Un rimbalzo sporco. Le mani bruciano. Resta.": "A dirty rebound. Your hands burn. You stay.",
  "Uno contro uno, sul possesso decisivo": "One-on-one, on the deciding possession",
  "Te la giochi tu, in prima persona.": "You take it on yourself, personally.",
  "Il possesso è tuo. Il palazzetto lo sa prima del fischio, e tu non puoi fare finta di non sentirlo.": "The possession is yours. The arena knows it before the whistle, and you can't pretend not to hear it.",
  "Il passaggio in più, anche a tre secondi": "The extra pass, even with three seconds left",
  "Ti fidi del sistema e del compagno libero.": "You trust the system and the open teammate.",
  "Il passaggio arriva pulito. Il palazzetto capisce dopo.": "The pass arrives clean. The arena understands a moment later.",
  "Alza il muro, ogni uscita": "Build the wall, every closeout",
  "Partita da spogliatoio, non da copertina.": "A locker-room game, not a magazine-cover game.",
  "Il fiato brucia. Loro sentono il contatto prima del canestro.": "Your lungs burn. They feel the contact before the basket.",
  "Gioco fisico, ogni possesso": "Physical play, every possession",
  "Contatto, blocco sul rimbalzo, niente regali.": "Contact, box-outs, no gifts.",
  "Ogni rimbalzo è una piccola guerra. La vinci sporca.": "Every rebound is a small war. You win it dirty.",
  "Leggi il loro tempo morto meglio di loro": "Read their timeout better than they do",
  "Hanno un piano. Tu hai visto i possessi, a volume basso, e li hai tenuti.": "They have a plan. You've watched the possessions quietly, and kept them.",
  "Cambi un abbinamento a voce. Lo staff, per una volta, ti lascia fare.": "You call out a matchup switch. For once, the staff lets you.",
  "Prendi il controllo della serie": "Take control of the series",
  "Più uso, più responsabilità. Se sbagli, è tua.": "More usage, more responsibility. If you miss, it's on you.",
  "La serie cambia spalla. Ora è sulla tua.": "The series shifts. Now it sits on your shoulder.",
  "Fidati dello staff, senza eroismi": "Trust the staff, no heroics",
  "Esegui il piano. Niente copertine.": "Run the game plan. No magazine covers.",
  "Il piano tiene. Tu tieni il piano.": "The plan holds. You hold to the plan.",
  "Cambia gli abbinamenti in difesa": "Switch the defensive matchups",
  "Chiedi i compiti sporchi sul loro migliore.": "You ask for the dirty work on their best player.",
  "Il loro migliore suda di più. È già qualcosa.": "Their best player sweats more. That's already something.",
  "Il tiro che ti definirà": "The shot that will define you",
  "Quando la palla arriva, non la passi. Il palazzetto lo sa prima di te, e tu tiri lo stesso.": "When the ball comes, you don't pass it. The arena knows it before you do, and you shoot anyway.",
  "Il palazzetto trattiene il fiato con te. Tu non tremi: tiri, e il mondo, per un secondo, aspetta.": "The arena holds its breath with you. You don't shake: you shoot, and for a second the world waits.",
  "Fai grandi i compagni": "Make your teammates great",
  "L'anello è di tutti, o non è di nessuno.": "The ring belongs to everyone, or to no one.",
  "L'assist che chiude una serie pesa come un canestro.": "The assist that closes out a series weighs as much as a basket.",
  "Partita da guerra": "A war of a game",
  "Ogni rimbalzo, ogni uscita, ogni secondo.": "Every rebound, every closeout, every second.",
  "Finisci con le ginocchia sporche. È il modo giusto.": "You finish with dirty knees. That's the right way.",
  "Chiudi la bocca, apri il campo": "Shut your mouth, open the floor",
  "Niente dichiarazioni. Solo possessi puliti.": "No statements. Only clean possessions.",
  "Il silenzio, stavolta, è un piano. Tiene fino all'ultimo fischio.": "Silence, this time, is a plan. It holds until the final whistle.",
  "Pochi possessi, quelli giusti": "Few possessions, the right ones",
  "Non corri come a ventiquattro. Non serve.": "You don't run like you did at twenty-four. You don't need to.",
  "Due decisioni, nient'altro. La serie, per una sera, ha il tuo orario.": "Two decisions, nothing more. For one night, the series runs on your clock.",
  "Il tiro che hai guadagnato in dieci anni": "The shot you earned over ten years",
  "Non è fame. È mestiere, al momento giusto.": "It's not hunger. It's craft, at the right moment.",
  "I piedi sanno già dove. Il palazzetto, un attimo dopo.": "Your feet already know where. The arena, a moment later.",
  "Copri i buchi, non i titoli": "Plug the gaps, not the headlines",
  "Aiuti, rotazioni, la voce giusta.": "Help defense, rotations, the right voice.",
  "Un aiuto in ritardo di un passo, arrivato lo stesso. Lo staff lo vede.": "A help rotation a step late, but there anyway. The staff sees it.",
  "Il corpo sa giugno. Ascoltalo": "The body knows June. Listen to it",
  "Contatto scelto, non sprecato.": "Contact chosen, not wasted.",
  "Un blocco sul rimbalzo, non due. Basta quello, e le ginocchia restano tue.": "One box-out, not two. That's enough, and your knees stay yours.",
  "Il tempo morto lo dici tu, piano": "You call the timeout, quietly",
  "La voce che hai guadagnato. Usala.": "The voice you've earned. Use it.",
  "Due dita sul petto, un compito a testa. Il cerchio si chiude.": "Two fingers on the chest, one job each. The circle closes.",
  "Fai spazio, poi chiudi tu il cerchio": "Make room, then close the circle yourself",
  "I giovani corrono. Tu decidi quando fermarsi.": "The young guys run. You decide when to stop.",
  "Un passaggio in più, poi il tiro tuo. L'ordine, stavolta, è quello.": "One more pass, then your shot. This time, that's the order.",
  "Una serie da adulti": "A grown-up series",
  "Niente urla. I possessi, tenuti.": "No shouting. Possessions, held.",
  "Chiudi un quarto con un gesto piccolo. Pesano più dei trenta punti.": "You close out a quarter with a small gesture. It weighs more than thirty points.",
  "Prendi il loro, anche se costa": "Take their best man, even if it costs you",
  "Il compito che i giovani non vogliono.": "The job the young guys don't want.",
  "Il loro migliore ti guarda diverso al terzo quarto. È il rispetto giusto.": "Their best player looks at you differently in the third quarter. It's the right kind of respect.",
  "Un possesso, la voce che hai guadagnato": "One possession, the voice you've earned",
  "Se arriva a te, è perché deve. A quest'età il coraggio è un possesso tenuto, non un urlo.": "If it comes to you, it's because it has to. At this age, courage is a possession held, not a scream.",
  "Non tremi. Non esulti. Tiri, e il mondo aspetta, come se il mestiere, per una volta, fosse una preghiera.": "You don't shake. You don't celebrate. You shoot, and the world waits, as if the craft, for once, were a prayer.",
  "Ginocchia sporche, ancora una volta": "Dirty knees, one more time",
  "Il corpo firma dopo. Tu firmi adesso.": "The body signs later. You sign now.",
  "Un rimbalzo all'ultimo. Le articolazioni presenteranno il conto a luglio.": "One last-second rebound. Your joints will send the bill in July.",
  "L'anello è di chi arriva terzo": "The ring belongs to whoever arrives third",
  "Fai grande chi deve chiudere. Poi, se resta, chiudi tu.": "Make great whoever has to close. Then, if there's anything left, you close.",
  "L'assist, poi il blocco sul rimbalzo. Il dito, se arriva, pesa lo stesso.": "The assist, then the box-out. The ring, if it comes, weighs the same.",
  "Tieni il posto, non la copertina": "Hold your spot, not the cover",
  "A quest'età il ruolo è già una vittoria.": "At this age, the role is already a win.",
  "Due possessi, tenuti. Lo staff non applaude: annota che ci sei ancora.": "Two possessions, held. The staff doesn't applaud: it notes that you're still here.",
  "Il corpo ha un orario. Rispettalo": "The body has a schedule. Respect it",
  "Contatto scelto, recupero vero, niente eroismo vuoto.": "Contact chosen, real recovery, no empty heroics.",
  "Un contatto sì, il secondo no. A giugno le ginocchia te ne sono grate.": "One contact yes, the second no. In June your knees will thank you.",
  "Gli ultimi minuti, detti chiaro": "The last minutes, said plainly",
  "La voce, usata poco, quando serve.": "The voice, used sparingly, when it's needed.",
  "Un tempo morto, due nomi, niente teatro. La serie, per un attimo, ha il tuo passo.": "A timeout, two names, no theater. For a moment, the series moves at your pace.",
  "Prima il palmo, poi il resto": "Hand first, then the rest",
  "Qui il patto è questo. Tienilo, tutta la serie.": "That's the deal here. Keep it, the whole series.",
  "Niente tiri facili. Il tabellone degli altri resta basso, e basta.": "No easy shots. The other team's scoreboard stays low, and that's it.",
  "Parla in copertura, ogni rotazione": "Talk on coverage, every rotation",
  "Il talento senza voce, in questa piazza, non basta.": "Talent without a voice isn't enough in this town.",
  "Due voci, un aiuto. La loro stella resta a due palleggi dal ferro.": "Two voices, one help. Their star stays two dribbles from the rim.",
  "Niente tre facili, questo è il patto": "No easy threes, that's the deal",
  "Uscita lunga, mano alta, il resto è commento.": "Long closeout, high hand, the rest is commentary.",
  "L'angolo resta muto. Lo staff non esulta: conta.": "The corner stays silent. The staff doesn't celebrate: it counts.",
  "Spacca la linea, ogni uscita": "Break the line, every curl",
  "Il tiro da tre non è un lusso. Qui è il pane.": "The three isn't a luxury. Here it's bread and butter.",
  "Piedi pronti, ricezione, via. Il palazzetto è già in piedi.": "Feet ready, catch, release. The arena is already on its feet.",
  "Il passaggio in più verso l'angolo": "The extra pass to the corner",
  "Qui è legge, non cortesia.": "Here it's law, not courtesy.",
  "Il canestro arriva dal lato debole. Lo schema, per una sera, è una preghiera esaudita.": "The basket comes from the weak side. For one night, the play is a prayer answered.",
  "Nessuna esitazione sulla linea": "No hesitation on the line",
  "Se i piedi sono pronti, tiri. Punto.": "If your feet are ready, you shoot. Period.",
  "Un tre che a novembre avresti finto. Stasera no.": "A three you'd have faked in November. Not tonight.",
  "Svuota il lato, decidi tu": "Clear out the side, you decide",
  "Uno contro uno. Il resto della squadra guarda.": "One-on-one. The rest of the team watches.",
  "Il campo si svuota. Il tempo morto avversario arriva quando tieni tu.": "The floor clears. The opponent's timeout comes when you've got it going.",
  "L'ultimo possesso, nudo": "The last possession, bare",
  "Niente alibi di circolazione.": "No ball-movement alibis.",
  "Un metro quadro, un difensore, il resto a guardare. Così si chiude, qui.": "One square meter, one defender, the rest watching. That's how you close here.",
  "Leggi il corpo davanti, non il copione": "Read the body in front of you, not the script",
  "L'isolamento è una responsabilità, nuda.": "Isolation is a responsibility, bare.",
  "Una finta, un passo. Il canestro è una conseguenza, non un urlo.": "A fake, a step. The basket is a consequence, not a scream.",
  "La palla deve uscire": "The ball has to move",
  "Se la tieni, lo schema si offende.": "If you hold it, the play takes offense.",
  "Due passaggi in più, un ferro più gentile. Qui la pazienza è un atletismo.": "Two extra passes, a softer rim. Here patience is a form of athleticism.",
  "Il canestro è di chi arriva terzo": "The basket belongs to whoever arrives third",
  "Ricevi, leggi, dai. Poi, se resta, tira.": "Catch, read, give. Then, if there's time left, shoot.",
  "L'assist in ritardo di un secondo. Il palazzetto, per una volta, capisce lo schema.": "The assist a second late. For once, the arena understands the play.",
  "Lo schema è un orologio. Non fermarlo": "The offense is a clock. Don't stop it",
  "Chi tiene la lancetta si sente, e non in bene.": "Whoever holds the hand of the clock gets noticed, and not in a good way.",
  "Gira, gira, il tiro pulito. Lo staff conta i passaggi prima dei punti.": "Around and around, the clean shot. The staff counts passes before points.",
  "Primo passo, niente set lunghi": "First step, no long sets",
  "Corrono. Tu stai nel loro respiro, o resti indietro.": "They run. You stay in their breath, or you fall behind.",
  "Rimbalzo, uscita, canestro in dieci secondi. Il resto è commento.": "Rebound, outlet, basket in ten seconds. The rest is commentary.",
  "Spingi, anche dopo il canestro loro": "Push, even after they score",
  "Il ritmo non si negozia.": "The pace isn't up for negotiation.",
  "Partono in quattro. Tu sei il quinto. Il tabellone corre.": "Four of them take off. You're the fifth. The scoreboard races.",
  "Tieni il fiato quando gli altri lo perdono": "Keep your breath when the others lose theirs",
  "Il quinto fallo arriva tardi. Tu no.": "The fifth foul comes late. You don't.",
  "Un contropiede a tre minuti dalla fine. Le gambe dicono ancora sì.": "A fast break with three minutes left. Your legs still say yes.",
  "Un metro col petto, non col palleggio": "One meter with your chest, not with the dribble",
  "Qui il corpo è il regolamento non scritto.": "Here the body is the unwritten rule.",
  "Chiusura sul rimbalzo, spinta, di nuovo. La partita ha un rumore sordo.": "Box out, push, again. The game has a dull thud to it.",
  "I secondi possessi, tutti": "Every second-chance possession",
  "Rimbalzi sporchi. La statistica pulita arriva dopo.": "Dirty rebounds. The clean stats come later.",
  "Un possesso in più, poi un altro. Loro iniziano a guardare l'orologio.": "One more possession, then another. They start watching the clock.",
  "I falli arrivano, i tiri loro no": "The fouls come, their shots don't",
  "Si gioca così, e lo staff non si scusa.": "That's how it's played, and the staff doesn't apologize.",
  "Un contatto, un fischio tardi. La loro stella esce per un possesso. Basta.": "A contact, a late whistle. Their star sits for a possession. That's enough.",
  "Poche parole, i dettagli giusti": "Few words, the right details",
  "Niente urla. Il rispetto, qui, è un orario.": "No shouting. Respect, here, is a schedule.",
  "Un tempo morto detto piano vale più di uno urlato. Lo staff lo sa da anni.": "A timeout spoken softly is worth more than one shouted. The staff has known it for years.",
  "Gioca con la memoria della serie": "Play with the memory of the series",
  "Gli schemi hanno già un nome, e i nomi pesano.": "The plays already have names, and the names carry weight.",
  "Un possesso visto a maggio, due anni fa. Stasera lo chiudi.": "A possession you saw in May, two years ago. Tonight you finish it.",
  "Tieni insieme la stanza": "Hold the room together",
  "Niente drammi da spogliatoio. Il mestiere, qui, è ordinato.": "No locker-room drama. The craft, here, is orderly.",
  "Una frase sola prima del salto. Il gruppo entra già chiuso.": "One sentence before the tip. The group walks in already locked in.",
  "Gioca pulito, anche se trema": "Play clean, even if your hand shakes",
  "Gli errori sono previsti. Non perdonati in automatico.": "Mistakes are expected. Not automatically forgiven.",
  "Un possesso da compito. Lo consegni senza macchie. Lo staff annota.": "A by-the-book possession. You hand it in spotless. The staff takes notes.",
  "Copri l'errore del compagno, poi il tuo": "Cover your teammate's mistake, then your own",
  "Qui si cresce in pubblico. Resta in campo.": "Here you grow up in public. Stay on the floor.",
  "Un aiuto, un blocco sul rimbalzo. Il ragazzo sbaglia, tu copri. Il cerchio tiene.": "A help, a box-out. The kid misses, you cover. The circle holds.",
  "Prendi il tiro che stai imparando": "Take the shot you're still learning",
  "Se aspetti di essere pronto, la serie è finita.": "If you wait until you're ready, the series is over.",
  "Esiti mezzo secondo, poi tiri. Entra. Qualcosa si sposta, in te.": "You hesitate half a second, then shoot. It drops. Something shifts inside you.",
  "Ventiquattro secondi, il tiro giusto": "Twenty-four seconds, the right shot",
  "Chi tira al dodicesimo si prende uno sguardo.": "Whoever shoots at twelve gets a look.",
  "Un blocco, una finta, un'uscita. Lo schema ha il tempo di un respiro lungo.": "A screen, a fake, a curl. The play takes the time of one long breath.",
  "Set lunghi, letture lente": "Long sets, slow reads",
  "Chi ha fretta resta fuori dallo schema.": "Whoever's in a hurry falls out of the play.",
  "Il quaderno degli schemi è un libro, non un volantino. Lo sfogli, e il canestro arriva meritatissimo.": "The playbook is a book, not a flyer. You leaf through it, and the basket comes well earned.",
  "Pazienza tattica, anche se fischiano": "Tactical patience, even if they boo",
  "Il pubblico vuole il tiro. Lo staff vuole il diciottesimo secondo.": "The crowd wants the shot. The staff wants the eighteenth second.",
  "Aspetti. Poi il colpo. Il palazzetto, per una volta, ha torto.": "You wait. Then the strike. For once, the arena is wrong.",
  "Tieni il pallone vivo, sempre": "Keep the ball alive, always",
  "Sei il primo passaggio. Il resto del quintetto respira con te.": "You're the first pass. The rest of the lineup breathes with you.",
  "Un ingresso in post, un passaggio in più, il tiro pulito. La serie ha il tuo ritmo.": "An entry pass to the post, one more pass, the clean shot. The series has your rhythm.",
  "Uscita lunga, mano alta": "Long closeout, high hand",
  "Il loro tiratore è il tuo compito, tutta la serie.": "Their shooter is your assignment, the whole series.",
  "Due passi, una mano. Il tre resta corto. Lo staff non dice niente: è già un voto.": "Two steps, one hand. The three falls short. The staff says nothing: that's already a grade.",
  "L'area è tua, anche se costa": "The paint is yours, even if it costs you",
  "Chiusura sul rimbalzo, secondo salto, il fallo utile.": "Box out, second jump, the useful foul.",
  "Un canestro sporco, una stoppata, un corpo che non si sposta. L'area ha un padrone.": "A dirty basket, a block, a body that won't move. The paint has an owner.",
  "Resta pronto, anche se non parti": "Stay ready, even if you don't start",
  "Il primo ingresso è un esame. Non arrivarci freddo.": "Your first stint is an exam. Don't arrive cold.",
  "Entri a partita in corsa. Lo schema, per fortuna, lo avevi già in bocca.": "You come in mid-game. Luckily, you already had the play on your lips.",
  "Prendi il contatto, resta in piedi": "Take the contact, stay on your feet",
  "Un corpo fermo vale più di un salto in ritardo.": "A planted body is worth more than a late jump.",
  "Un fallo offensivo, un possesso. Lo staff non sorride: annota il petto.": "A charge drawn, a possession. The staff doesn't smile: it notes the chest.",
  "Due liberi, come se fosse giugno": "Two free throws, as if it were June",
  "La lunetta non trema se la tratti da mestiere.": "The free-throw line doesn't shake if you treat it like a craft.",
  "Due tiri, nient'altro. Il palazzetto tace. Tu no: respiri, e segni.": "Two shots, nothing else. The arena goes quiet. You don't: you breathe, and you score.",
  "Anticipa la mano, non il salto": "Beat the hand, not the jump",
  "Il loro passaggio basso è tuo, se leggi un tempo prima.": "Their bounce pass is yours, if you read it a beat early.",
  "Una mano, un possesso. Il palazzetto ci mette un attimo a capire che eri lì.": "One hand, one possession. The arena takes a moment to realize you were there.",
  "Chiama il blocco, a voce alta": "Call the screen, out loud",
  "Se non parli, lo schema resta un disegno.": "If you don't talk, the play stays a drawing.",
  "Due voci, un blocco. Il canestro arriva pulito, e lo staff lo mette sul conto della stanza.": "Two voices, one screen. The basket comes clean, and the staff credits the room.",
  "Aiuta tardi, arrivi lo stesso": "Help late, get there anyway",
  "Il contrasto bello è quello che non si vede in copertina.": "The beautiful stop is the one that never makes the cover.",
  "Un corpo in più sulla linea. Il loro tiratore esita. Basta quello.": "One more body on the line. Their shooter hesitates. That's enough.",
  "Il ferro sporco, tutta la serie": "The dirty rim, the whole series",
  "I secondi possessi non fanno titolo. Fanno giugno.": "Second-chance possessions don't make headlines. They make June.",
  "Una spazzata, poi un'altra. Loro iniziano a guardare le spalle, non il cronometro.": "One putback, then another. They start looking over their shoulders, not at the clock.",
  "Il passaggio corto, quello che tiene": "The short pass, the one that holds",
  "Niente diagonali da copertina. Il possesso vivo, sempre.": "No highlight-reel skip passes. A live possession, always.",
  "Due metri, un compagno libero. Il palazzetto capisce dopo, lo staff subito.": "Two meters, an open teammate. The arena understands later, the staff right away.",
  "Scegli i possessi, lascia i titoli": "Choose your possessions, leave the headlines",
  "A quest'età il coraggio è dire no a un tiro storto.": "At this age, courage is saying no to a bad shot.",
  "Un rifiuto, un passaggio, un canestro altrui. La serie, per una sera, ha il tuo orario.": "A refusal, a pass, someone else's basket. For one night, the series runs on your clock.",
  "Primo passo in transizione, sempre": "First step in transition, always",
  "Se aspetti il set, la serie ti passa sopra.": "If you wait for the set, the series runs over you.",
  "Rimbalzo, uscita, un tiro in dieci secondi. Il quintetto respira il tuo ritmo.": "Rebound, outlet, a shot in ten seconds. The lineup breathes your rhythm.",
  "Taglia senza palla, poi finisci": "Cut without the ball, then finish",
  "Il secondo taglio è il mestiere che non si fotografa.": "The second cut is the craft nobody photographs.",
  "Uno spazio, una ricezione, un canestro da tre metri. Lo schema, per una volta, è una preghiera esaudita.": "A gap, a catch, a basket from three meters. For once, the play is a prayer answered.",
  "Tieni la posizione, non il palleggio": "Hold position, not the dribble",
  "L'area si guadagna col petto, poi si finisce.": "The paint is earned with the chest, then finished.",
  "Un sigillo, un passaggio interno, due punti sporchi. L'area ha un padrone, e sei tu.": "A seal, an entry pass, two dirty points. The paint has an owner, and it's you.",
  "I minuti che restano, tenuti dritti": "The minutes that remain, played straight",
  "A quest'età il posto è già una vittoria. Lo tieni, senza copertina.": "At this age, the spot is already a win. You hold it, no cover.",
  "Due possessi, tenuti. Lo staff non applaude: annota che ci sei ancora, e questo basta.": "Two possessions, held. The staff doesn't applaud: it notes that you're still here, and that's enough.",
  "Due correzioni, e basta": "Two corrections, and that's it",
  "La voce, usata poco, quando serve. I giovani ascoltano.": "The voice, used sparingly, when it's needed. The young guys listen.",
  "Il corpo firma dopo. Tu firmi adesso": "The body signs later. You sign now",
  "Contatto scelto, niente eroismo vuoto. Durare è già un mestiere.": "Contact chosen, no empty heroics. Lasting is already a craft.",
  "Tieni il mestiere": "Stick to the craft",
  "Possessi puliti, niente copertine.": "Clean possessions, no magazine covers.",
  "Niente eroismi. La serie, per una sera, ha il tuo passo, e il passo, tenuto, vale più di una copertina.": "No heroics. For one night, the series moves at your pace, and the pace, held, is worth more than a cover."
};
