/* English narrative for story-feel. Key: Italian source text (see ../key.ts). */
export const EN_STORY_FEEL: Readonly<Record<string, string>> = {
  "Natale in trasferta": "Christmas on the road",
  "Ventitré dicembre, hotel di una città che non conosci. Tua madre ti chiama mentre fai stretching sul tappeto.": "December twenty-third, a hotel in a city you don't know. Your mother calls while you're stretching on the carpet.",
  "Restituisci la chiamata, a lungo": "You return the call, and talk for a long time",
  "La voce di casa prima della veglia, anche lontano.": "The voice of home before Christmas Eve, even from far away.",
  "Appendi e sei più leggero. Il giorno dopo il tiro esce pulito.": "You hang up feeling lighter. The next day your shot comes out clean.",
  "Due minuti, poi i possessi in sala": "Two minutes, then film in the video room",
  "Domani si gioca. Lei lo sa.": "There's a game tomorrow. She knows.",
  "Chiudi il telefono. Sul comodino resta la luce della sveglia.": "You put the phone down. On the nightstand, only the alarm clock's glow remains.",
  "Chiedi a un compagno di cenare insieme": "You ask a teammate to have dinner together",
  "Nessuno dovrebbe passare la vigilia da solo.": "Nobody should spend Christmas Eve alone.",
  "Si ride poco, si mangia male, si sta meglio.": "Little laughter, bad food, and you feel better.",
  "Il volo di notte": "The red-eye",
  "Ritardo a terra, tre ore. Lo scivolo dell'aereo, il sonno che non arriva, una partita fra trentasei ore.": "A three-hour delay on the tarmac. The jet bridge, the sleep that won't come, a game in thirty-six hours.",
  "Tappi, mascherina, disciplina": "Earplugs, eye mask, discipline",
  "Dormi come sai dormire: per mestiere.": "You sleep the way you know how: professionally.",
  "L'atterraggio è sporco. Tu no: hai dormito per mestiere, e si vede dal passo.": "The landing is rough. You aren't: you slept like a pro, and it shows in your stride.",
  "Partita a carte in fondo all'aereo": "Cards at the back of the plane",
  "Il gruppo tiene, anche a diecimila metri.": "The group holds, even at ten thousand meters.",
  "In fondo all'aereo si conta a voce bassa. Arrivi già in cerchio, senza dirlo.": "At the back of the plane, scores are kept in low voices. You arrive already a unit, without saying so.",
  "Studi i possessi dell'avversario": "You study the opponent's possessions",
  "Lo schermo è piccolo. La testa no.": "The screen is small. Your head isn't.",
  "Lo schermo trema. L'uscita dal blocco, però, la tieni. Al mattino basta un cenno.": "The screen shakes. You still lock in the curl off the screen. In the morning, a nod is enough.",
  "La prima volta che cantano il tuo nome": "The first time they chant your name",
  "Terzo quarto, palla ferma. Un pezzo di curva inizia, poi tutto il palazzetto. Non è uno slogan: è il tuo cognome.": "Third quarter, dead ball. One section starts, then the whole arena. It's not a slogan: it's your last name.",
  "Alzi un palmo, basta": "You raise a palm, that's all",
  "Ringrazi senza fermarti.": "You say thanks without stopping.",
  "Il gesto è piccolo. Resta.": "The gesture is small. It stays.",
  "Te la prendi, sul possesso dopo": "You take it, on the next possession",
  "Se chiamano te, tiri tu.": "If they're calling you, you shoot.",
  "Canestro. Urlo. Qualcosa si sposta, in te, e non torna indietro.": "Basket. A roar. Something shifts inside you, and it doesn't shift back.",
  "Cerchi il compagno libero": "You look for the open teammate",
  "Il coro può aspettare un passaggio.": "The chant can wait for a pass.",
  "L'assist è più rumoroso del tiro. Strano, e giusto.": "The assist is louder than the shot. Strange, and right.",
  "Un compagno si rompe, i suoi minuti diventano tuoi": "A teammate goes down, his minutes become yours",
  "Lo portano via in barella. {COACH} ti guarda e non dice niente. Non serve.": "They carry him off on a stretcher. {COACH} looks at you and says nothing. No need.",
  "Accetti il carico": "You accept the load",
  "Più possessi, più responsabilità, più usura.": "More possessions, more responsibility, more wear.",
  "I minuti arrivano pesanti. Li tieni.": "The minutes come heavy. You handle them.",
  "Chiedi di spartirli": "You ask to share them",
  "Il gruppo prima dell'eroismo.": "The group before heroics.",
  "Non sei il salvatore. Sei uno che tiene insieme i pezzi.": "You're not the savior. You're the one who holds the pieces together.",
  "Vai a trovarlo in sala medica dopo": "You visit him in the training room afterwards",
  "I minuti aspettano. Lui no.": "The minutes can wait. He can't.",
  "Non si parla di basket. Si parla di quando torna. Tu ascolti.": "Nobody talks basketball. You talk about when he'll be back. You listen.",
  "La sala video che brucia": "The film session that burns",
  "{COACH} ferma il filmato sette volte sullo stesso errore. La stanza è silenziosa in un modo che fa male.": "{COACH} stops the tape seven times on the same mistake. The room is silent in a way that hurts.",
  "Prendi appunti, a testa bassa": "You take notes, head down",
  "Impari in pubblico, che è il modo più duro.": "You learn in public, which is the hardest way.",
  "Esci con le orecchie calde e lo schema a posto.": "You walk out with burning ears and the play down cold.",
  "Rispondi, a voce alta": "You answer back, out loud",
  "Non era solo colpa tua e lo dici.": "It wasn't only your fault, and you say so.",
  "Il silenzio dopo è peggio del filmato. Qualcosa si incrina.": "The silence afterwards is worse than the tape. Something cracks.",
  "Chiedi di rivederlo da solo, dopo": "You ask to review it alone, afterwards",
  "La correzione, senza platea.": "The correction, without an audience.",
  "Restate in due nella stanza. Si parla poco. Si capisce tutto.": "The two of you stay in the room. Little is said. Everything is understood.",
  "Il campo del paese, d'estate": "The hometown court, in summer",
  "Torni dove hai imparato a palleggiare. L'asfalto è storto, i tabelloni cantano. Un ragazzino ti chiede se sei davvero tu.": "You go back to where you learned to dribble. The asphalt is crooked, the backboards rattle. A kid asks if it's really you.",
  "Giochi con loro fino al buio": "You play with them until dark",
  "Niente staff, niente cronometro.": "No staff, no game clock.",
  "Sudore diverso. Ti ricorda perché hai cominciato.": "A different kind of sweat. It reminds you why you started.",
  "Restano due tiri, poi via": "Two more shots, then you leave",
  "Il programma non aspetta il paese.": "The schedule doesn't wait for your hometown.",
  "Firmi due maglie. In macchina, per un chilometro, ti manca già l'asfalto storto.": "You sign two jerseys. In the car, for a kilometer, you already miss the crooked asphalt.",
  "Chiedi al ragazzino di mostrarti il suo tiro": "You ask the kid to show you his shot",
  "Oggi sei tu l'adulto sul campo.": "Today you're the grown-up on the court.",
  "Correggi il polso. Lui fa canestro. Qualcosa si chiude, in pace.": "You fix his wrist. He scores. Something settles, at peace.",
  "Dopo una battuta a secco": "After a scoreless night",
  "Zero punti. Zero. Lo spogliatoio fa rumore intorno a te, e tu no. La doccia è lunga.": "Zero points. Zero. The locker room makes noise around you, and you don't. The shower is long.",
  "Resti al ferro, a palazzetto vuoto": "You stay at the rim, in an empty arena",
  "Il palazzetto vuoto è un giudice onesto.": "An empty arena is an honest judge.",
  "I custodi spengono le luci a una a una. Tu continui.": "The custodians turn off the lights one by one. You keep going.",
  "Ne parli con {COACH}": "You talk it over with {COACH}",
  "Meglio una verità scomoda che un silenzio.": "Better an uncomfortable truth than silence.",
  "Non ti consola. Ti dà un compito. È meglio.": "He doesn't console you. He gives you a task. That's better.",
  "Spegni la testa, dormi": "You switch your head off, you sleep",
  "Domani è un'altra pelle.": "Tomorrow is a different skin.",
  "Il sonno è una scelta. Al mattino il tiro è ancora tuo.": "Sleep is a choice. In the morning your shot is still yours.",
  "La lista di febbraio, e tu no": "The February list, and you're not on it",
  "Esce la lista. Il tuo nome non c'è. I messaggi arrivano lo stesso, come se fosse colpa loro.": "The list comes out. Your name isn't there. The messages arrive anyway, as if it were their fault.",
  "Silenzio stampa, più lavoro": "Media silence, more work",
  "La risposta è in palestra, a febbraio.": "The answer is in the gym, in February.",
  "Non fai una dichiarazione. Fai tre sedute in più. Si vede.": "You don't make a statement. You put in three extra sessions. It shows.",
  "Una frase secca, poi basta": "One curt sentence, then that's it",
  "Dici che meriti di più. Punto.": "You say you deserve more. Period.",
  "I giornali titolano. Lo spogliatoio ascolta, e pesa.": "The papers run headlines. The locker room listens, and weighs it.",
  "Festeggi chi c'è andato, in squadra": "You celebrate the teammates who made it",
  "Il palazzetto è più grande del tuo orgoglio.": "The arena is bigger than your pride.",
  "Un abbraccio in mezzo al corridoio. Costa. Vale.": "A hug in the middle of the hallway. It costs. It's worth it.",
  "Il silenzio dopo il fischio": "The silence after the whistle",
  "Serie finita. Doccia. Autobus. Nessuno alza la voce. Fuori piove su una città che non è la tua.": "Series over. Shower. Bus. Nobody raises their voice. Outside, it's raining on a city that isn't yours.",
  "Parli tu, per primo": "You speak first",
  "Qualcuno deve rompere il ghiaccio.": "Someone has to break the ice.",
  "Dici poco. Basta. Il viaggio di ritorno è meno lungo.": "You say little. It's enough. The ride home feels shorter.",
  "Metti le cuffie e lasci stare": "You put your headphones on and let it be",
  "Il lutto, a modo tuo.": "Grief, your way.",
  "Il rumore bianco ti tiene compagnia. Domani riparti da lì.": "White noise keeps you company. Tomorrow you start again from there.",
  "Chiedi a {COACH} cosa ha visto": "You ask {COACH} what he saw",
  "Anche una sconfitta si studia.": "Even a loss can be studied.",
  "Due minuti in fondo al bus. Una frase sola, che ti resta.": "Two minutes at the back of the bus. One sentence, and it stays with you.",
  "Le scarpe ancora bagnate": "Shoes still wet",
  "Primo mese. Lo spogliatoio è un linguaggio che non parli. Le tue scarpe, messe storte, dicono che sei nuovo.": "First month. The locker room is a language you don't speak. Your shoes, set down crooked, say you're new.",
  "Chiedi come si fa, qui": "You ask how things are done here",
  "Meglio una domanda che un errore ripetuto.": "Better a question than a repeated mistake.",
  "Un veterano ti mostra il posto. È una cosa piccola. Non lo è.": "A veteran shows you your spot. It's a small thing. It isn't.",
  "Osservi e copi, in silenzio": "You watch and copy, in silence",
  "Impari il rito senza disturbarlo.": "You learn the ritual without disturbing it.",
  "In una settimana le scarpe sono dritte. Qualcuno lo nota.": "Within a week your shoes are straight. Someone notices.",
  "Arrivi prima di tutti": "You arrive before everyone else",
  "Il rispetto, a modo tuo: l'orario.": "Respect, your way: punctuality.",
  "La palestra è vuota e accesa. È il tuo modo di entrare.": "The gym is empty and lit. It's your way of walking in.",
  "Una notte in cui il corpo dice no": "A night when your body says no",
  "Alle tre, il ginocchio. Non è un infortunio da referto. È un avviso. Domani c'è gara.": "At three in the morning, the knee. It's not an injury for the report. It's a warning. There's a game tomorrow.",
  "Chiami lo staff, subito": "You call the staff, right away",
  "Meglio una notte persa che un mese.": "Better to lose a night than a month.",
  "Ghiaccio, silenzio, una gara in dubbio. Il ginocchio ringrazia.": "Ice, silence, a game in doubt. The knee is grateful.",
  "Dormi sul fianco e speri": "You sleep on your side and hope",
  "I minuti non si regalano. Nemmeno i rischi.": "Minutes aren't given away. Neither are risks.",
  "Scendi in campo. Tieni. Qualcosa, sotto, ha contato.": "You take the floor. You hold up. Something, underneath, kept count.",
  "Chiedi un carico diverso in allenamento": "You ask for a different workload in practice",
  "Non eroismo: mestiere.": "Not heroics: craft.",
  "{COACH} sposta due esercizi. Non è gloria. È una carriera che dura.": "{COACH} moves two drills. It's not glory. It's a career that lasts.",
  "Un ragazzo ti chiede un consiglio": "A kid asks you for advice",
  "La matricola della tua squadra. Vent'anni. Ti ferma in corridoio e non sa come iniziare la frase.": "Your team's rookie. Twenty years old. He stops you in the hallway and doesn't know how to start the sentence.",
  "Gli dici la verità scomoda": "You tell him the uncomfortable truth",
  "Quello che avresti voluto sentirti dire.": "What you would have wanted to hear.",
  "Ascolta. Annuisce. Tornerà. Le carriere si passano così.": "He listens. Nods. He'll be back. That's how careers get passed on.",
  "Lo porti in palestra con te": "You take him to the gym with you",
  "Meno parole, più ripetizioni.": "Fewer words, more reps.",
  "Due canestri, tre correzioni. Esce più alto di quando è entrato.": "Two baskets, three corrections. He walks out taller than he walked in.",
  "Lo rimandi allo staff": "You send him to the staff",
  "Non sei il suo allenatore.": "You're not his coach.",
  "La frase è corretta e fredda. Resta nel corridoio un secondo in più del dovuto.": "The sentence is correct and cold. It lingers in the hallway a second longer than it should.",
  "L'ultima estate che conta": "The last summer that counts",
  "Il contratto è corto. Lo specchio no. Ti chiedi se il corpo arriverà a novembre, o se novembre arriverà senza di te.": "The contract is short. The mirror isn't. You wonder whether your body will make it to November, or whether November will arrive without you.",
  "Un programma da ragazzo, di nascosto": "A young man's program, in secret",
  "Due sedute in più. Lo staff non deve saperlo tutto.": "Two extra sessions. The staff doesn't need to know everything.",
  "Le gambe bruciano. Per una settimana ti senti di nuovo ventiquattro.": "Your legs burn. For a week you feel twenty-four again.",
  "Ascolti il fisioterapista": "You listen to the physio",
  "Durare è già un mestiere.": "Lasting is already a craft.",
  "Meno chili, più sonno. Novembre ti trova in piedi.": "Fewer kilos, more sleep. November finds you on your feet.",
  "Giochi a basket, solo basket": "You play basketball, just basketball",
  "Tiri, passaggi, nient'altro. Come la prima estate.": "Shots, passes, nothing else. Like that first summer.",
  "Niente numeri. Solo il suono della rete. Ti basta, e si vede.": "No numbers. Just the sound of the net. It's enough for you, and it shows.",
  "Una domenica in cui vince la panchina": "A Sunday when the bench wins",
  "Il coach ti lascia fuori nel quarto quarto di una gara che si poteva chiudere. Il palazzetto non fischia te. Fischia la scelta.": "The coach leaves you out in the fourth quarter of a game that could have been closed out. The arena doesn't boo you. It boos the decision.",
  "Chiedi il perché, a porte chiuse": "You ask why, behind closed doors",
  "Una domanda, non una scena.": "A question, not a scene.",
  "{COACH} parla due minuti. Non ti consola. Ti spiega. È abbastanza.": "{COACH} talks for two minutes. He doesn't console you. He explains. It's enough.",
  "Lavori il giorno dopo, in silenzio": "You work the next day, in silence",
  "La risposta è in palestra.": "The answer is in the gym.",
  "Nessuna dichiarazione. Tre sedute in più. Lo staff lo nota, e basta.": "No statement. Three extra sessions. The staff notices, and that's it.",
  "Lo lasci correre": "You let it go",
  "Non tutte le sere sono tue.": "Not every night is yours.",
  "Un giorno di freddo. Il gruppo, stranamente, si stringe.": "A cold day. The group, strangely, pulls together.",
  "Il tempo morto che chiami tu": "The timeout you call",
  "Terzo quarto, palla in mano, lo schema si rompe. Alzi un palmo. {COACH} annuisce. Il palazzetto capisce dopo.": "Third quarter, ball in your hands, the play breaks down. You raise a palm. {COACH} nods. The arena understands later.",
  "Disegni tu il possesso": "You draw up the possession yourself",
  "Voce bassa, dita sul petto, un compito a testa.": "Low voice, fingers on the chest, one job each.",
  "Il canestro arriva pulito. Non è il tuo: è di tutti. Conta di più.": "The basket comes clean. It's not yours: it belongs to everyone. That counts more.",
  "Chiedi l'isolamento": "You call for the isolation",
  "Se hai fermato il gioco, chiudilo tu.": "If you stopped the game, you finish it.",
  "Uno contro uno. Entra. Qualcuno in panchina alza le sopracciglia. Va bene.": "One-on-one. It goes in. Someone on the bench raises an eyebrow. That's fine.",
  "Lo rimetti allo staff": "You hand it back to the staff",
  "Hai fermato il caos. Il piano è loro.": "You stopped the chaos. The plan is theirs.",
  "{COACH} apprezza il gesto. Il possesso successivo è più ordinato.": "{COACH} appreciates the gesture. The next possession is more orderly.",
  "Il primo tempo morto che non capisci": "The first timeout you don't understand",
  "{COACH} disegna tre uscite. Tu annuisci. In campo, al primo possesso, la testa è vuota.": "{COACH} draws up three sets. You nod. On the floor, on the first possession, your head is empty.",
  "Chiedi al veterano, in corsa": "You ask the veteran, on the run",
  "Due parole, un palmo. Lo schema, al possesso dopo, è tuo.": "Two words, a palm. On the next possession, the play is yours.",
  "Esegui quello che hai capito": "You execute what you understood",
  "Niente invenzioni. Il poco, tenuto.": "No improvising. The little you have, held.",
  "Non è bello. È pulito. Lo staff non sorride: annuisce.": "It's not pretty. It's clean. The staff doesn't smile: it nods.",
  "Resti a rivedere il disegno, dopo": "You stay to go over the diagram, afterwards",
  "Ripassa il disegno col pennarello spento. Due minuti, e lo schema torna a essere una cosa tua.": "You trace the diagram with a capped marker. Two minutes, and the play becomes yours again.",
  "Una trasferta in cui il ferro è storto": "A road game where the rim is crooked",
  "Palazzetto avverso, tabellone che canta, tre tiri corti di fila. Il pubblico ha già deciso.": "Hostile arena, rattling backboard, three short shots in a row. The crowd has already decided.",
  "Cerchi il contatto, non il tiro": "You seek contact, not the shot",
  "Punti in lunetta, non in pedana.": "Points at the line, not on the highlight reel.",
  "Due liberi, nient'altro. Il palazzetto tace. Tu respiri, e segni.": "Two free throws, nothing else. The arena goes quiet. You breathe, and you score.",
  "Passi, anche quando il tiro c'è": "You pass, even when the shot is there",
  "Il ferro storto non è un alibi per tenerti.": "A crooked rim isn't an excuse to hold the ball.",
  "L'assist arriva pulito. Il palazzetto, per una volta, non sa a chi arrabbiarsi.": "The assist arrives clean. For once, the arena doesn't know who to be angry at.",
  "Tiri il quarto, lo stesso": "You take the fourth shot anyway",
  "Se hai i piedi pronti, parti. Punto.": "If your feet are ready, you go. Period.",
  "Un tre che a novembre avresti finto. Stasera no. Entra, o no: hai tirato.": "A three you'd have faked in November. Not tonight. In or out: you took it.",
  "Il ragazzo nuovo prende i tuoi minuti di ottobre": "The new kid takes your October minutes",
  "Non è un affronto. È un calendario. Tu lo sai prima di loro, e fa più male.": "It's not an insult. It's a calendar. You know it before they do, and it hurts more.",
  "Gli cedi i minuti, tieni la voce": "You give him the minutes, keep the voice",
  "Il mestiere cambia forma, non peso.": "The craft changes shape, not weight.",
  "Gli dai i possessi. Ti tieni i tempi morti, e per una sera il peso sta dritto.": "You give him the possessions. You keep the timeouts, and for one night the weight stays balanced.",
  "Chiedi i minuti che restano, chiari": "You ask for the remaining minutes, plainly",
  "Fedeltà non è silenzio.": "Loyalty isn't silence.",
  "{COACH} ascolta. Non promette. Sposta due minuti. È già qualcosa.": "{COACH} listens. He doesn't promise. He moves two minutes. It's something.",
  "Lavori sul corpo, in silenzio": "You work on your body, in silence",
  "Togli un piano di palestra. Novembre, poi, ti trova in piedi senza un comunicato.": "You drop one gym session. November then finds you on your feet, no press release needed.",
  "Una settimana senza avversario col nome": "A week without a named opponent",
  "Niente copertine, niente tempi morti urlati. Solo i giorni, e tre modi di tenerli.": "No magazine covers, no shouted timeouts. Just the days, and three ways to get through them.",
  "Chiudi la porta della palestra": "You close the gym door",
  "Ripetizioni, nient'altro.": "Reps, nothing else.",
  "Fuori non succede niente. Dentro, il gesto diventa un altro gesto.": "Nothing happens outside. Inside, the motion becomes a different motion.",
  "Stai col gruppo, senza scene": "You stick with the group, no scenes",
  "Cene, sala video, il resto.": "Dinners, film room, the rest.",
  "Cene corte, sala video. Il gruppo si accorcia di un palmo, e nessuno scrive un titolo.": "Short dinners, film room. The group gets a hand's width closer, and nobody writes a headline.",
  "Spegni e dormi": "You switch off and sleep",
  "Domani c'è, comunque.": "Tomorrow comes, regardless.",
  "Spegni prima delle undici. Il tiro, al mattino, esce senza chiedere scusa.": "Lights out before eleven. In the morning, your shot comes out without apologizing.",
  "Il mercoledì che non chiede niente": "The Wednesday that asks for nothing",
  "Allenamento normale, conferenza vuota, un corridoio senza microfoni.": "Normal practice, empty press conference, a hallway with no microphones.",
  "Arrivi prima, resti dopo": "You arrive early, stay late",
  "L'orario è l'unica dichiarazione.": "Your schedule is your only statement.",
  "La luce è accesa quando entri. Lo staff segna l'ora, non una dichiarazione.": "The light is on when you walk in. The staff notes the time, not a statement.",
  "Chiedi i possessi noiosi": "You ask for the boring possessions",
  "I possessi che nessuno taglia.": "The possessions nobody cuts.",
  "Niente sequenze. Una lettura, corretta, vale una settimana.": "No highlight reels. One correct read is worth a week.",
  "Una telefonata a casa, lunga": "A long call home",
  "Il mestiere non è tutto il giorno.": "The craft isn't the whole day.",
  "Appendi più leggero. Il palazzetto, dopo, è solo un palazzetto.": "You hang up lighter. The arena, afterwards, is just an arena.",
  "Nessuno ti chiede un'intervista": "Nobody asks you for an interview",
  "I microfoni sono sull'altra sponda. Tu sei un nome in fondo al referto.": "The microphones are on the other side. You're a name at the bottom of the box score.",
  "Usi il vuoto": "You use the emptiness",
  "Nessuno guarda: si cambia per davvero.": "Nobody's watching: you can really change.",
  "L'anonimato, stavolta, è un dono. Lo spendi in palestra.": "Anonymity, this time, is a gift. You spend it in the gym.",
  "Ti metti vicino ai veterani": "You sit near the veterans",
  "Ascolti, non interrompi.": "You listen, you don't interrupt.",
  "Due frasi rubate in corridoio. Valgono più di una copertina.": "Two sentences overheard in the hallway. They're worth more than a magazine cover.",
  "Scrivi tre cose sul quaderno": "You write three things in your notebook",
  "Cosa sai, cosa no, cosa fai finta.": "What you know, what you don't, what you pretend.",
  "Il quaderno si riempie. Tu anche, un palmo.": "The notebook fills up. So do you, a little.",
  "Una striscia senza tesi": "A streak with no storyline",
  "Vinci, perdi, vinci. I giornali hanno trovato un altro nome.": "You win, you lose, you win. The papers have found another name.",
  "Tieni il mestiere, nudo": "You stick to the craft, bare",
  "Niente racconto che tenga il posto del lavoro.": "No story taking the place of the work.",
  "I giorni uguali, tenuti dritti. A volte è un dono.": "Identical days, kept straight. Sometimes that's a gift.",
  "Chiedi un uso diverso": "You ask for a different role",
  "Il vuoto non è un alibi per restare uguale.": "The emptiness isn't an excuse to stay the same.",
  "Lo staff sposta un'uscita, niente discorso. Il vuoto, almeno, ha un compito nuovo.": "The staff moves one set, no speech. The emptiness, at least, has a new task.",
  "Copri i buchi degli altri": "You cover for the others",
  "Se i riflettori sono altrove, il lavoro sporco è tuo.": "If the spotlight is elsewhere, the dirty work is yours.",
  "Niente targa. Il gruppo, però, si muove meglio. Si sente.": "No plaque. The group, though, moves better. You can feel it.",
  "Ottobre, nudo, di nuovo": "October, bare, again",
  "Niente rivincite, niente copertine. Solo ottobre, di nuovo.": "No revenge, no magazine covers. Just October, again.",
  "Accetti i minuti che restano": "You accept the minutes that remain",
  "Il ruolo, prima della voce.": "The role, before the voice.",
  "Non sei più il piano. Sei chi tiene insieme il piano.": "You're no longer the plan. You're the one who holds the plan together.",
  "Diventi la voce, senza chiederlo": "You become the voice, without asking",
  "Un tempo morto piano, un ragazzo che ascolta.": "A quiet timeout, a kid who listens.",
  "Due correzioni in allenamento. Lui alza lo sguardo. La carriera si passa così.": "Two corrections in practice. He looks up. That's how careers get passed on.",
  "Tratti il corpo da archivio": "You treat your body like an archive",
  "Il corpo, trattato da archivio. Novembre arriva e tu ci sei, senza vanto.": "Your body, handled like an archive. November arrives and you're there, without boasting.",
  "Hotel, bus, un pasto freddo": "Hotel, bus, a cold meal",
  "Hotel, bus, un pasto freddo. Nessuna tesi da vendere.": "Hotel, bus, a cold meal. No storyline to sell.",
  "Dormi come un mestiere": "You sleep like it's part of the job",
  "Mascherina, tappi, disciplina.": "Eye mask, earplugs, discipline.",
  "Mascherina, tappi. Scendi con gli occhi a posto. Il gruppo, il giorno dopo, è più corto.": "Eye mask, earplugs. You get off with your eyes in order. The group, the next day, is tighter.",
  "Carte in fondo al bus": "Cards at the back of the bus",
  "Le carte tengono il bus. A terra, il cerchio è già fatto, senza riunione.": "The cards hold the bus together. Once you land, the circle has formed, no meeting needed.",
  "Un filmato corto, lo schermo piccolo": "A short clip, a small screen",
  "La testa non ha fusi.": "Your head has no time zones.",
  "{COACH} non chiede il sonno. Chiede tre uscite. Domani, quando le chiede, annuisci e basta.": "{COACH} doesn't ask about sleep. He asks about three sets. Tomorrow, when he does, you just nod.",
  "La conferenza che non chiede": "The press conference that asks nothing",
  "La conferenza dura tre minuti. Nessuno alza la mano.": "The press conference lasts three minutes. Nobody raises a hand.",
  "Ringrazi, già in corridoio": "You say thanks, already in the hallway",
  "Il parquet è più onesto dei microfoni.": "The hardwood is more honest than microphones.",
  "Tre minuti, zero domande. Esci come sei entrato: pulito, e già altrove.": "Three minutes, zero questions. You leave the way you came in: clean, and already elsewhere.",
  "Lasci una riga vera, e basta": "You leave one true line, and that's it",
  "Anche se non l'hanno chiesta.": "Even if nobody asked for it.",
  "Lasci una riga vera sul tavolo. Qualcuno la raccoglie. La stanza, no.": "You leave one true line on the table. Someone picks it up. The room doesn't.",
  "Torni al ferro quando chiudono": "You go back to the rim when they lock up",
  "Il palazzetto si svuota. Tu resti al ferro, da solo, finché la luce cala.": "The arena empties. You stay at the rim, alone, until the lights dim.",
  "Una pausa che può essere un dono": "A break that could be a gift",
  "Una pausa nel rumore. Può essere un dono o un avvertimento.": "A pause in the noise. It could be a gift or a warning.",
  "Lo tratti come un dono": "You treat it as a gift",
  "Respiri. Poi torni.": "You breathe. Then you come back.",
  "Il vuoto, tenuto, pesa più di un'altra seduta stanca.": "The emptiness, held, is worth more than another tired session.",
  "Lo tratti come un avvertimento": "You treat it as a warning",
  "Se non fai notizia, qualcuno ha smesso di contarti.": "If you're not news, someone has stopped counting you.",
  "Raddoppi le ripetizioni. Lo staff lo vede, non lo dice, e questo basta.": "You double your reps. The staff sees it, doesn't say it, and that's enough.",
  "Chiedi a {COACH} cosa vede": "You ask {COACH} what he sees",
  "Due minuti. Un compito, nient'altro. Lo tieni.": "Two minutes. One task, nothing else. You keep it.",
  "Un mercoledì senza tesi": "A Wednesday with no storyline",
  "Niente avversario col nome. Resta da decidere come tenere i giorni.": "No named opponent. All that's left is deciding how to get through the days.",
  "La chiave, prima di tutti": "The key, before everyone",
  "La chiave gira. Sei il primo rumore del giorno, e lo tieni basso.": "The key turns. You're the first sound of the day, and you keep it low.",
  "Tieni il quaderno, nient'altro": "You keep your notebook, nothing else",
  "Tre righe a fine seduta. A marzo sei un altro, di poco. Basta.": "Three lines at the end of each session. By March you're a slightly different player. That's enough.",
  "Lasci correre la settimana": "You let the week go by",
  "Non tutte devono diventare una tesi.": "Not every week has to become a storyline.",
  "Lasci la settimana senza copertina. A volte è il modo più onesto di tenerla.": "You let the week go by without a cover. Sometimes that's the most honest way to get through it.",
  "La pioggia sul tetto del bus": "Rain on the bus roof",
  "Dopo il fischio, il bus. La città scorre bagnata. Nessuno alza il volume.": "After the whistle, the bus. The city slides by, wet. Nobody turns up the volume.",
  "Guardi il vetro, nient'altro": "You look out the window, nothing else",
  "Il rumore tiene. Tu no.": "The noise holds. You don't.",
  "I lampioni passano. Arrivi più vuoto, e più a posto.": "The streetlights pass. You arrive emptier, and more at peace.",
  "Due parole al posto accanto": "A few words to the seat next to you",
  "Il viaggio è lungo. Non deve esserlo muto.": "The ride is long. It doesn't have to be silent.",
  "Si parla poco. Il bus, dopo, è meno lungo.": "Little is said. The ride, afterwards, feels shorter.",
  "Segni un possesso sul quaderno": "You note a possession in your notebook",
  "Una riga, nel buio. Poi la tieni.": "One line, in the dark. Then you keep it.",
  "Una lettura, corretta, tra un lampione e l'altro. Basta.": "One read, corrected, between one streetlight and the next. That's enough.",
  "Il caffè delle sette": "Seven o'clock coffee",
  "La cucina è fredda. Il corpo non è ancora arrivato. La palestra aspetta.": "The kitchen is cold. Your body hasn't arrived yet. The gym is waiting.",
  "Lo bevi in piedi, poi via": "You drink it standing, then go",
  "Chi arriva prima non deve dirlo.": "Whoever arrives first doesn't need to say it.",
  "La tazza vuota sul lavandino. La palestra è accesa. Entri.": "The empty mug in the sink. The gym lights are on. You walk in.",
  "Ti siedi un minuto, e basta": "You sit for a minute, that's all",
  "Il corpo chiede poco. Glielo dai.": "Your body asks for little. You give it that.",
  "Un minuto fermo. Il ginocchio ringrazia senza fare rumore.": "One still minute. The knee says thanks without making a sound.",
  "Chiami casa, mentre raffredda": "You call home while it cools",
  "La voce prima del mestiere, anche alle sette.": "The voice before the craft, even at seven.",
  "Due minuti. Lei non chiede i punti. Tu no, il mestiere.": "Two minutes. She doesn't ask about points. You don't talk shop.",
  "Un corridoio senza eco": "A hallway with no echo",
  "Il palazzetto è vuoto. Restano le luci basse e i tuoi passi, nudi.": "The arena is empty. What's left are the dim lights and your footsteps, bare.",
  "Cammini lento, ascolti": "You walk slowly, listening",
  "Il mestiere, sentito da fuori, è un altro mestiere.": "The craft, heard from outside, is a different craft.",
  "I passi tengono. Esci più piccolo, e più a posto.": "Your steps hold. You walk out smaller, and more at peace.",
  "Un altro giro di liberi": "Another round of free throws",
  "Le luci basse non giudicano. Il ferro sì.": "Dim lights don't judge. The rim does.",
  "I custodi aspettano. Tu finisci i dieci. Poi spegni.": "The custodians wait. You finish your ten. Then you switch off the lights.",
  "Aspetti chi è ancora in doccia": "You wait for whoever is still in the shower",
  "Nessuno dovrebbe uscire da solo, stasera.": "Nobody should leave alone tonight.",
  "Aspetti. Uscite insieme. Il piazzale, dopo, è meno lungo.": "You wait. You leave together. The parking lot, afterwards, feels shorter.",
  "Lavoro silenzioso": "Quiet work",
  "Niente dichiarazioni. Solo ripetizioni.": "No statements. Just reps.",
  "Chiudi la porta della palestra. Fuori non succede niente. Dentro, il gesto diventa un altro gesto, e tu lo tieni.": "You close the gym door. Nothing happens outside. Inside, the motion becomes a different motion, and you keep it.",
  "Nessuna intervista. Il gesto, ripetuto senza pubblico, diventa un altro gesto, e settembre lo saprà.": "No interviews. The motion, repeated without an audience, becomes a different motion, and September will know it.",
  "Lo staff nota l'orario, non la voce. È quello che volevi, e per una volta ti basta.": "The staff notices your schedule, not your voice. That's what you wanted, and for once it's enough.",
  "Lavoro silenzioso. Niente dichiarazioni. Solo ripetizioni, e il gesto che diventa un altro.": "Quiet work. No statements. Just reps, and a motion that becomes something else.",
  "Chiudi la porta. Fuori non succede niente. Dentro, il gesto tiene.": "You close the door. Nothing happens outside. Inside, the motion holds.",
  "Niente intervista. Il gesto, ripetuto senza pubblico, a settembre è un altro.": "No interview. The motion, repeated without an audience, is different by September.",
  "Stai col gruppo": "You stick with the group",
  "Una settimana da spogliatoio. Serve, anche quando non fa notizia, e il gruppo si accorcia di un palmo.": "A locker-room week. It matters, even when it's not news, and the group gets a hand's width closer.",
  "Ridi alle battute giuste. Il gruppo si accorcia di un palmo, e per una volta ti sta bene non essere il centro.": "You laugh at the right jokes. The group gets a hand's width closer, and for once you're fine not being the center.",
  "Non sei il centro. Sei il collante, e per una volta ti sta bene, perché il collante tiene più del titolo.": "You're not the center. You're the glue, and for once that's fine, because glue holds better than a headline.",
  "Stai col gruppo. Cene, sala video, il resto. Il gruppo, dopo, è più corto.": "You stick with the group. Dinners, film room, the rest. The group, afterwards, is tighter.",
  "Cene, sala video, il resto. Nessun titolo, e il cerchio si stringe lo stesso.": "Dinners, film room, the rest. No headline, and the circle tightens anyway.",
  "Ridi alle battute giuste. Per una volta ti sta bene non essere il centro.": "You laugh at the right jokes. For once you're fine not being the center.",
  "Una sera per te": "An evening for yourself",
  "Spegni il telefono. Domani c'è.": "You turn off your phone. Tomorrow will come.",
  "Una notte senza schema. Il giorno dopo il tiro esce più pulito, e tu non chiedi perché.": "A night without a game plan. The next day your shot comes out cleaner, and you don't ask why.",
  "Chiudi gli occhi prima delle undici. Sembra poco. Non lo è: il corpo ringrazia senza chiedere scusa.": "You close your eyes before eleven. It seems like little. It isn't: your body says thanks without apologizing.",
  "Il silenzio, scelto, vale più di un'altra seduta stanca, e tu lo tieni come un mestiere.": "Silence, chosen, is worth more than another tired session, and you keep it like a craft.",
  "Spegni il telefono. Domani c'è. Il corpo, per una volta, ringrazia.": "You turn off your phone. Tomorrow will come. Your body, for once, says thanks.",
  "Spegni e basta. Il giorno dopo il gesto esce pulito, senza un perché da vendere.": "You just switch off. The next day the motion comes out clean, with no reason to sell.",
  "Il telefono in borsa prima delle undici. Il corpo, per una volta, non protesta.": "Phone in the bag before eleven. Your body, for once, doesn't complain.",
  "Sei il primo rumore nel parquet vuoto. Entri, e questo è già un rispetto.": "You're the first sound on the empty hardwood. You walk in, and that's already a form of respect.",
  "L'orario è l'unica dichiarazione. Basta.": "Your schedule is your only statement. That's enough.",
  "Arrivi prima di tutti. Lo staff nota l'orario, non la voce.": "You arrive before everyone. The staff notices your schedule, not your voice.",
  "La palestra, nuda, di lunedì. Entri, e questo è già un mestiere.": "The gym, bare, on a Monday. You walk in, and that's already a craft.",
  "Prima di tutti. Il rispetto, a modo tuo, è l'orario.": "Before everyone. Respect, your way, is punctuality.",
  "La porta è aperta, la palestra vuota. Tu entri, e basta.": "The door is open, the gym empty. You walk in, and that's it.",
  "Quelli che nessuno taglia.": "The ones nobody cuts.",
  "I tagli noiosi, tenuti. Una lettura corretta vale una settimana, e tu la tieni.": "The boring cuts, kept. One correct read is worth a week, and you keep it.",
  "I possessi brutti, studiati a volume basso. A ottobre si vedono.": "The ugly possessions, studied with the volume down. By October they show.",
  "Chiedi i possessi noiosi. Quelli che nessuno taglia, e tu li tieni.": "You ask for the boring possessions. The ones nobody cuts, and you keep them.",
  "Una lettura, corretta, a volume basso. Ottobre, poi, è più pulito.": "One read, corrected, volume down. October, afterwards, is cleaner.",
  "I possessi che nessuno taglia. Li studi, e a marzo sei un altro, di poco.": "The possessions nobody cuts. You study them, and by March you're slightly different.",
  "Niente copertine. Una correzione, tenuta, vale una settimana.": "No magazine covers. One correction, kept, is worth a week.",
  "Una telefonata lunga": "A long phone call",
  "Casa prima della veglia, anche a marzo.": "Home before Christmas Eve, even in March.",
  "Riattacchi più leggero. Il palazzetto, dopo, è solo un palazzetto.": "You hang up lighter. The arena, afterwards, is just an arena.",
  "La voce di casa. Poi il mestiere, che resta mestiere.": "The voice of home. Then the craft, which stays the craft.",
  "Una telefonata lunga. Casa prima della veglia, anche a marzo.": "A long phone call. Home before Christmas Eve, even in March.",
  "Appendi. Il palazzetto, dopo, pesa meno, e questo basta.": "You hang up. The arena, afterwards, weighs less, and that's enough.",
  "La voce di casa, tenuta. Poi il mestiere, che non è tutto il giorno.": "The voice of home, kept. Then the craft, which isn't the whole day.",
  "Una telefonata. Appendi più leggero, e il giorno dopo il tiro esce più pulito.": "A phone call. You hang up lighter, and the next day your shot comes out cleaner.",
  "Copri i buchi, nient'altro": "You cover the gaps, nothing else",
  "Niente targa sul petto. Il gruppo, coperto, si muove meglio. Si sente.": "No badge on your chest. The group, covered, moves better. You can feel it.",
  "I buchi si coprono in silenzio. È un mestiere poco fotografato.": "Gaps get covered in silence. It's a craft rarely photographed.",
  "Copri i buchi, nient'altro. Se i riflettori sono altrove, il lavoro sporco è tuo.": "You cover the gaps, nothing else. If the spotlight is elsewhere, the dirty work is yours.",
  "Niente copertina. Il gruppo, coperto, si muove meglio. Si sente.": "No magazine cover. The group, covered, moves better. You can feel it.",
  "I buchi, coperti in silenzio. Il mestiere, così, non chiede applausi.": "The gaps, covered in silence. The craft, this way, doesn't ask for applause.",
  "Lavoro sporco, niente tesi. Il gruppo, dopo, è più corto, e giusto.": "Dirty work, no storyline. The group, afterwards, is tighter, and right.",
  "Tieni il quaderno": "You keep your notebook",
  "Tre fogli, nient'altro. Si riempiono, e tu anche, un palmo.": "Three pages, nothing else. They fill up, and so do you, a little.",
  "Tre righe a fine seduta. A marzo sono un altro giocatore, di poco. Basta.": "Three lines at the end of each session. By March you're a slightly different player. That's enough.",
  "Tieni il quaderno. Cosa sai, cosa no, cosa fai finta.": "You keep your notebook. What you know, what you don't, what you pretend.",
  "Tre righe. A marzo sei un altro, di poco, e questo basta.": "Three lines. By March you're slightly different, and that's enough.",
  "Il quaderno, nient'altro. Si riempie, e tu anche.": "The notebook, nothing else. It fills up, and so do you.",
  "Cosa sai, cosa no. Tre righe a fine seduta, e il palmo in più.": "What you know, what you don't. Three lines at the end of each session, and a little extra.",
  "Non tutte le settimane devono diventare una tesi.": "Not every week has to become a storyline.",
  "I giorni uguali. Li tieni dritti, e a volte è un dono.": "Identical days. You keep them straight, and sometimes that's a gift.",
  "Niente apice. Si tiene, e si va avanti.": "No peak. You hold on, and keep going.",
  "Lasci correre. Non tutte le settimane devono diventare una tesi.": "You let it go. Not every week has to become a storyline.",
  "Niente tesi da vendere. Si tiene, e si gira pagina.": "No storyline to sell. You hold on, and turn the page.",
  "Lasci correre la settimana. Il mestiere, nudo, basta.": "You let the week go by. The craft, bare, is enough.",
  "Una settimana senza apice. Si tiene dritta, e questo è già un mestiere.": "A week with no peak. You keep it straight, and that's already a craft.",
  "Studi i possessi noiosi": "You study the boring possessions",
  "Quelli che nessuno taglia in sala video.": "The ones nobody cuts in the film room.",
  "Niente sequenze da copertina. Una lettura, corretta, vale una settimana, e ottobre la ricorda.": "No highlight reels. One correct read is worth a week, and October remembers it.",
  "I possessi brutti, tenuti a volume basso. A ottobre li hai già visti, e corretti.": "The ugly possessions, kept with the volume down. By October you've already seen them, and fixed them.",
  "Studi i possessi noiosi. Quelli che nessuno taglia in sala video.": "You study the boring possessions. The ones nobody cuts in the film room.",
  "Una lettura, corretta, a volume basso. Ottobre la ricorda, e tu anche.": "One read, corrected, volume down. October remembers it, and so do you.",
  "I possessi brutti, tenuti. A ottobre si vedono, e tu li hai già corretti.": "The ugly possessions, kept. By October they show, and you've already fixed them.",
  "Una correzione tenuta in sala video vale una settimana di campionato.": "One correction kept in the film room is worth a week of the season.",
  "Una cena col gruppo, senza tesi": "Dinner with the group, no storyline",
  "Il collante, non il centro.": "The glue, not the center.",
  "A tavola si ride poco, si mangia male, si sta meglio. Il gruppo si accorcia di un palmo.": "At the table there's little laughter, bad food, and everyone feels better. The group gets a hand's width closer.",
  "Resti il collante, non il centro, e per una volta ti sta bene.": "You stay the glue, not the center, and for once that's fine.",
  "Una cena col gruppo, senza tesi. Il collante, non il centro.": "Dinner with the group, no storyline. The glue, not the center.",
  "Si ride poco. Il gruppo, dopo, è più corto, e giusto.": "Little laughter. The group, afterwards, is tighter, and right.",
  "Non sei il centro. Per una volta ti sta bene, e il collante tiene.": "You're not the center. For once that's fine, and the glue holds.",
  "Una cena, niente tesi. Il gruppo si accorcia di un palmo.": "A dinner, no storyline. The group gets a hand's width closer.",
  "Spegni, davvero": "You really switch off",
  "Il telefono in borsa. Il corpo ringrazia.": "Phone in the bag. Your body says thanks.",
  "Il corpo, per una volta, non chiede scusa: una notte senza schema basta.": "Your body, for once, doesn't apologize: one night without a game plan is enough.",
  "Chiudi gli occhi. Sembra poco. Il giorno dopo il tiro è più pulito.": "You close your eyes. It seems like little. The next day your shot is cleaner.",
  "Spegni, davvero. Il telefono in borsa. Il corpo ringrazia.": "You really switch off. Phone in the bag. Your body says thanks.",
  "Una notte senza schema. Il corpo, per una volta, non chiede scusa.": "A night without a game plan. Your body, for once, doesn't apologize.",
  "Il telefono in borsa. Il silenzio, scelto, vale più di un'altra seduta.": "Phone in the bag. Silence, chosen, is worth more than another session.",
  "Spegni davvero. Domani il gesto esce più pulito, e tu non chiedi il perché.": "You really switch off. Tomorrow the motion comes out cleaner, and you don't ask why.",
  "quiet-{0}-{1}": "quiet-{0}-{1}",
  "Un ottobre senza titoli": "An October without headlines",
  "Niente copertine. Resta il lavoro, nudo, e tre modi di tenerlo.": "No magazine covers. What's left is the work, bare, and three ways to keep at it."
};
