/* English narrative for story-late. Key: Italian source text (see ../key.ts). */
export const EN_STORY_LATE: Readonly<Record<string, string>> = {
  "Trentadue anni": "Thirty-two years old",
  "Trentatré anni": "Thirty-three years old",
  "Trentaquattro anni": "Thirty-four years old",
  "Trentacinque anni": "Thirty-five years old",
  "Trentasei anni": "Thirty-six years old",
  "{0} anni": "{0} years old",
  "late-{0}-{1}": "late-{0}-{1}",
  "La linea dei trentadue": "The thirty-two line",
  "La linea dei trentatré": "The thirty-three line",
  "La linea dei trentaquattro": "The thirty-four line",
  "La linea dei trentacinque": "The thirty-five line",
  "La linea dei trentasei": "The thirty-six line",
  "L'anno che non torna": "The year that won't come back",
  "Prima che giugno sia un ricordo": "Before June becomes a memory",
  "Il contratto con il corpo": "The contract with your body",
  "Gli ultimi ottobre": "The last Octobers",
  "Una primavera da pesare": "A spring to weigh",
  "Ruolo, voce, poi il resto": "Role, voice, then the rest",
  "Prima il posto, poi il resto": "Your spot first, then the rest",
  "Il conto con le ginocchia": "Settling up with your knees",
  "Una firma, ogni ottobre": "A signature, every October",
  "Il mestiere, da qui in poi": "The craft, from here on",
  "Prima che il corpo alzi la voce": "Before your body raises its voice",
  "Lo specchio non mente. Il contratto è corto. {0} ti chiede come vuoi scendere, da qui a giugno.": "The mirror doesn't lie. The contract is short. {0} asks how you want to go down, from now until June.",
  "A {0} anni ogni ottobre è una firma. {1} aspetta di capire se firmi ancora.": "At {0}, every October is a signature. {1} is waiting to see if you'll sign again.",
  "Il campionato riparte. Tu conti i minuti che restano, non quelli che hai già dato.": "The season starts again. You count the minutes you have left, not the ones you've already given.",
  "Prima il ruolo, poi la voce. L'Europa, se arriva, è l'ultimo atto — non la fuga.": "Role first, then voice. Europe, if it comes, is the last act — not an escape.",
  "A {0} anni il campionato riparte. Tu conti i minuti che restano, e li tieni dritti.": "At {0}, the season starts again. You count the minutes you have left, and you keep them straight.",
  "A {0} anni il posto viene prima della copertina. {1} lo misura in minuti, non in interviste.": "At {0}, your spot comes before the cover. {1} measures it in minutes, not interviews.",
  "{0}, e il corpo fa l'appello prima dello staff. Tu rispondi ancora sì.": "{0}, and your body takes roll call before the staff does. You still answer yes.",
  "Ottobre a {0}: non è un arrivo. È un accordo col fisico, rinnovato un inverno alla volta.": "October in {0}: it's not an arrival. It's a deal with your body, renewed one winter at a time.",
  "La linea dei {0}. Non è un numero tondo: è un modo di scendere, e di restare.": "The {0} line. It's not a round number: it's a way of stepping down, and of staying.",
  "A {0} l'armadietto è ancora tuo. {1}: da qui a giugno, questo è già una vittoria.": "In {0}, the locker is still yours. {1}: from here to June, that's already a win.",
  "I minuti che restano": "The minutes that remain",
  "Il posto, tenuto": "The spot, held",
  "Il ruolo che ti resta": "The role you have left",
  "I minuti, chiesti chiaro": "The minutes, asked for plainly",
  "Il ruolo, tenuto": "The role, held",
  "Minuti veri, o quelli che tieni. Prima di tutto, il posto.": "Real minutes, or the ones you keep. Above all, your spot.",
  "Chiedi il ruolo, non la copertina. Te lo danno a pezzi. Li tieni.": "You ask for a role, not a cover. They give it to you in pieces. You keep them.",
  "I minuti che restano, detti chiaro. Il corpo firma dopo.": "The minutes that remain, said plainly. Your body signs later.",
  "Un posto, anche piccolo. Senza posto non c'è voce, e lo sai.": "A spot, even a small one. Without a spot there's no voice, and you know it.",
  "Il ruolo prima della voce. Te lo tieni, anche se è più stretto di un tempo.": "Role before voice. You keep it, even if it's narrower than it used to be.",
  "Il posto, tenuto. A quest'età è già una vittoria, e non la dichiari.": "The spot, held. At this age it's already a win, and you don't announce it.",
  "Minuti veri, o quelli che tieni. Prima di tutto, il posto, e lo tieni.": "Real minutes, or the ones you keep. Above all, your spot, and you keep it.",
  "La stanza, tenuta insieme": "The room, held together",
  "Due correzioni, e basta": "Two corrections, and that's it",
  "La voce dello spogliatoio": "The voice of the locker room",
  "Lo spogliatoio, tenuto": "The locker room, held",
  "La voce, usata poco": "The voice, used sparingly",
  "Meno possessi, più senso. I giovani ascoltano.": "Fewer possessions, more meaning. The young guys listen.",
  "Non sei più il piano. Sei chi tiene insieme il piano.": "You're no longer the plan. You're the one who holds the plan together.",
  "Due correzioni in allenamento. Lui alza lo sguardo. La carriera si passa così.": "Two corrections in practice. He looks up. That's how careers get passed on.",
  "La voce, usata così, vale più di un giro in più in sala pesi.": "The voice, used this way, is worth more than one more round in the weight room.",
  "Parli poco, e il poco tiene la stanza. A quest'età è il mestiere vero.": "You say little, and that little holds the room. At this age, that's the real craft.",
  "Due frasi, niente teatro. Lo spogliatoio, tenuto, è già un mestiere.": "Two sentences, no theater. A locker room held together is already a craft.",
  "La stanza si tiene con poco. Tu usi poco, e il poco basta.": "The room is held together with little. You use little, and little is enough.",
  "L'Europa, se resta un senso": "Europe, if it still makes sense",
  "Un giugno diverso": "A different June",
  "Un ultimo atto in Europa": "A last act in Europe",
  "L'Europa, nominata": "Europe, named",
  "Una porta, in un'altra lingua": "A door, in another language",
  "Cifra magra, palazzetti stretti. Non è una fuga: è una chiusura.": "A thin offer, cramped arenas. It's not an escape: it's a closing chapter.",
  "Palazzetti stretti, tattica lunga. Non è una fuga: è una chiusura.": "Cramped arenas, long tactics. It's not an escape: it's a closing chapter.",
  "L'offerta è magra. Il senso, se c'è, sta nel mestiere, non nella cifra.": "The offer is thin. The meaning, if there is one, lies in the craft, not the number.",
  "Da contendente l'Europa non compra il nome: compra gli ultimi possessi, a poco.": "As a contender, Europe doesn't buy the name: it buys the last possessions, cheaply.",
  "Ascolti. Il ruolo e la voce vengono prima; questa porta, magra, resta l'ultimo atto.": "You listen. Role and voice come first; this door, thin as it is, stays the last act.",
  "Cifra piccola, senso pieno. Non è una fuga: è una chiusura, se i minuti spariscono.": "A small number, full meaning. It's not an escape: it's a closing chapter, if the minutes disappear.",
  "L'Europa, da qui, è magra. Tu ascolti, non firmi, e tieni il posto.": "From here, Europe is thin. You listen, you don't sign, and you keep your spot.",
  "Una porta in un'altra lingua, e magra. Il ruolo, qui, viene prima.": "A door in another language, and a thin one. The role, here, comes first.",
  "Non firmi. Ascolti. L'Europa resta una porta socchiusa, e a quest'età le porte pesano.": "You don't sign. You listen. Europe stays a door left ajar, and at this age doors weigh a lot.",
  "Un altro fuso, la stessa palla. Il ruolo e la voce vengono prima; questo, se arriva, è l'ultimo atto.": "Another time zone, the same ball. Role and voice come first; this, if it comes, is the last act.",
  "Palazzetti più piccoli, teste più larghe. Non è un ritiro: è un altro giugno, se lo vuoi.": "Smaller arenas, broader minds. It's not retirement: it's another June, if you want it.",
  "Una chiamata da un altro fuso. La tieni in tasca, e il ruolo, qui, resta il primo conto.": "A call from another time zone. You keep it in your pocket, and the role, here, stays the first priority.",
  "L'Europa è una frase. A quest'età le frasi pesano, e questa di più.": "Europe is a sentence. At this age sentences weigh a lot, and this one more than most.",
  "Non è un addio. È una porta, nominata, non firmata, e tu la lasci socchiusa.": "It's not a goodbye. It's a door, named, not signed, and you leave it ajar.",
  "Lavori per chi viene dopo": "You work for whoever comes next",
  "Un ragazzo guarda. Tu gli fai spazio.": "A kid is watching. You make room for him.",
  "Gli fai spazio. Non è un funerale: è un passaggio, e lui lo capisce.": "You make room for him. It's not a funeral: it's a handoff, and he understands it.",
  "Un ragazzo ripete il tuo gesto. Per una volta ti basta.": "A kid repeats your move. For once, that's enough.",
  "Lavori per chi viene dopo. Il gesto, passato, resta tuo lo stesso.": "You work for whoever comes next. The move, passed on, stays yours all the same.",
  "Uno spazio, un ragazzo, una correzione. La carriera, così, non si chiude: si passa.": "A gap, a kid, a correction. That way, a career doesn't end: it gets passed on.",
  "Gli lasci un possesso. Lui lo tiene. Per una sera ti basta.": "You leave him a possession. He holds on to it. For one night, that's enough.",
  "Una porta in un'altra lingua": "A door in another language",
  "L'ultimo atto, nominato": "The last act, named",
  "Europa, se resta un senso": "Europe, if it still makes sense",
  "Un giugno diverso, se serve": "A different June, if needed",
  "Una porta, socchiusa, in un'altra lingua": "A door, ajar, in another language",
  "L'ultimo atto, detto piano": "The last act, said softly",
  "Da contendente l'offerta è magra. Prima il ruolo, poi la voce. L'Europa, se arriva, è l'ultimo atto — non una fuga da {0}.": "As a contender, the offer is thin. Role first, then voice. Europe, if it comes, is the last act — not an escape from {0}.",
  "Una chiamata da un altro fuso, cifra piccola, senso pieno. Non è un ritiro: è un altro giugno, se i minuti qui spariscono.": "A call from another time zone, a small number, full meaning. It's not retirement: it's another June, if the minutes here disappear.",
  "A {0} anni le porte si contano. Questa parla un'altra lingua, e non compra il nome.": "At {0}, you count the doors. This one speaks another language, and doesn't buy the name.",
  "Da {0} l'Europa è magra. Tu ascolti, e il posto, qui, resta il primo conto.": "From {0}, Europe looks thin. You listen, and your spot here stays the first priority.",
  "Cifra piccola. Il senso, se c'è, sta nel mestiere. Tu non firmi: tieni la porta socchiusa.": "A small number. The meaning, if there is one, lies in the craft. You don't sign: you keep the door ajar.",
  "Una porta in un'altra lingua. Da contendente non compra il nome: compra gli ultimi possessi, a poco.": "A door in another language. As a contender, it doesn't buy the name: it buys the last possessions, cheaply.",
  "Prima il ruolo, poi la voce. L'Europa, se arriva, è l'ultimo atto — non una fuga da {0}.": "Role first, then voice. Europe, if it comes, is the last act — not an escape from {0}.",
  "Una chiamata da un altro fuso. Palazzetti più stretti, tattica più lunga. Non è un ritiro: è un altro giugno.": "A call from another time zone. Tighter arenas, longer tactics. It's not retirement: it's another June.",
  "A {0} anni le porte si contano. Questa parla un'altra lingua, e pesa.": "At {0}, you count the doors. This one speaks another language, and it weighs.",
  "Da {0} una voce in un'altra lingua. Tu ascolti, e non fai la valigia.": "From {0}, a voice in another language. You listen, and you don't pack your bags.",
  "Palazzetti stretti, teste larghe. L'Europa resta una frase, e a quest'età le frasi pesano.": "Cramped arenas, broad minds. Europe stays a sentence, and at this age sentences weigh a lot.",
  "Non è un addio. È una porta, nominata, non firmata. Resta sul tavolo.": "It's not a goodbye. It's a door, named, not signed. It stays on the table.",
  "Ascolti, non firmi": "You listen, you don't sign",
  "La porta resta socchiusa. Il ruolo, qui, viene prima.": "The door stays ajar. The role, here, comes first.",
  "Non è un addio. È una frase, tenuta in tasca, per l'estate.": "It's not a goodbye. It's a sentence, kept in your pocket, for the summer.",
  "Ascolti. Il ruolo a {0} resta il primo conto.": "You listen. Your role in {0} stays the first priority.",
  "La porta resta socchiusa. Tu non la chiudi, e non la attraversi.": "The door stays ajar. You don't close it, and you don't walk through it.",
  "Ascolti, non firmi. Il mestiere, qui, viene prima di un altro fuso.": "You listen, you don't sign. The craft, here, comes before another time zone.",
  "Una frase in tasca. L'estate, poi, deciderà se tirarla fuori.": "A sentence in your pocket. The summer will decide whether to pull it out.",
  "Non giuri. Non rifiuti. A {0} il corridoio è ancora tuo.": "You don't swear. You don't refuse. In {0}, the hallway is still yours.",
  "La tieni come chiusura possibile": "You keep it as a possible final chapter",
  "Offerta magra. Se i minuti spariscono, l'Europa è un mestiere, non un esilio.": "A thin offer. If the minutes disappear, Europe is a job, not an exile.",
  "Se i minuti spariscono, l'Europa è un mestiere, non un esilio.": "If the minutes disappear, Europe is a job, not an exile.",
  "Un ultimo atto diverso, e magro. Lo nomini, non lo giuri.": "A different last act, and a thin one. You name it, you don't swear to it.",
  "La cifra non compra il nome. Compra gli ultimi possessi, se restano.": "The number doesn't buy the name. It buys the last possessions, if any remain.",
  "La tieni come chiusura. Non come fuga. La differenza, a quest'età, conta.": "You keep it as a final chapter. Not as an escape. At this age, the difference matters.",
  "Un giugno diverso, se serve. Magro, e detto chiaro.": "A different June, if needed. Thin, and said plainly.",
  "La porta, magra, resta aperta. Tu la nomini, e basta.": "The door, thin as it is, stays open. You name it, and that's it.",
  "Un ultimo atto diverso. Lo nomini, non lo giuri.": "A different last act. You name it, you don't swear to it.",
  "Palazzetti pieni, tattica stretta. Se arriva, arriva da adulto.": "Packed arenas, tight tactics. If it comes, it comes as a grown-up.",
  "La tieni come chiusura possibile. Non è un esilio: è un mestiere.": "You keep it as a possible final chapter. It's not an exile: it's a job.",
  "Un altro giugno, se i minuti spariscono. Lo nomini, piano.": "Another June, if the minutes disappear. You name it, softly.",
  "L'Europa, detta così, non è una fuga. È una porta, e tu la conosci.": "Europe, put this way, isn't an escape. It's a door, and you know it.",
  "La chiudi come ipotesi. Il ruolo, qui, resta il primo conto.": "You shelve it as a hypothesis. The role, here, stays the first priority.",
  "Restare è già una scelta": "Staying is already a choice",
  "La voce, qui, non si imballa. Il ruolo viene prima.": "Your voice, here, doesn't get packed away. The role comes first.",
  "A {0} il corridoio è ancora tuo. L'Europa può aspettare.": "In {0}, the hallway is still yours. Europe can wait.",
  "Chiudi la porta, piano. Il gruppo sente che resti.": "You close the door, softly. The group senses you're staying.",
  "Restare è già una scelta. La voce, qui, non si imballa.": "Staying is already a choice. Your voice, here, doesn't get packed away.",
  "Niente valigia. Il ruolo, tenuto, vale più di un altro fuso.": "No suitcase. The role, held, is worth more than another time zone.",
  "A {0} l'armadietto è tuo. Lo tieni, e basta.": "In {0}, the locker is yours. You keep it, and that's it.",
  "Chiudi la porta. Non è un giuramento: è un modo di stare.": "You close the door. It's not an oath: it's a way of being.",
  "un anello": "one ring",
  "{0} anelli": "{0} rings",
  "Quello che hai già alzato": "What you've already lifted",
  "Il fermo immagine di giugno": "The freeze-frame from June",
  "L'anello, e il dopo": "The ring, and what comes after",
  "Giugno in una stanza, di nuovo": "June in a room, again",
  "Quello che hai già alzato, e ottobre": "What you've already lifted, and October",
  "In sala video passa un fermo immagine di giugno. {0}. La stanza tace mezzo secondo di troppo.": "In the film room, a freeze-frame from June plays. {0}. The room goes quiet half a second too long.",
  "Un ragazzo nuovo chiede com'è, l'anello. Non è una domanda da spogliatoio. Lo è diventata.": "A new kid asks what the ring is like. It's not a locker-room question. It has become one.",
  "{0} in bacheca. Oggi è ottobre, e l'anello non gioca per te.": "{0} in the trophy case. Today it's October, and the ring doesn't play for you.",
  "Giugno è in una foto. Oggi è ottobre, e {0} non copre i possessi.": "June is in a photo. Today it's October, and {0} doesn't cover the possessions.",
  "La stanza tace su {0}. Tu non fai il museo. Fai il mestiere.": "The room goes quiet about {0}. You don't run a museum. You do the job.",
  "Racconti poco, e il poco basta": "You tell little, and the little is enough",
  "Il rispetto, a voce bassa.": "Respect, in a low voice.",
  "Non fai il museo. Fai il mestiere. Si capisce lo stesso.": "You don't run a museum. You do the job. It's understood all the same.",
  "Due frasi, niente video. Il rispetto, a quest'età, è basso e fermo.": "Two sentences, no video. Respect, at this age, is low and steady.",
  "Racconti poco. Lo spogliatoio capisce il poco, e basta.": "You tell little. The locker room understands the little, and that's it.",
  "Niente fermo immagine. Il mestiere, nudo, vale più dell'anello in bacheca.": "No freeze-frame. The craft, bare, is worth more than the ring in the case.",
  "Due minuti, voce bassa. Il rispetto, tenuto così, non ha bisogno di una targa.": "Two minutes, low voice. Respect, held this way, doesn't need a plaque.",
  "Racconti poco, e il poco tiene la stanza. Poi ottobre, che è più onesto.": "You tell little, and that little holds the room. Then October, which is more honest.",
  "Usi la fame di allora": "You use the hunger you had back then",
  "Non è nostalgia: è un metodo.": "It's not nostalgia: it's a method.",
  "Il corpo ricorda giugno. Per una settimana tiri come allora.": "Your body remembers June. For a week you shoot like you did back then.",
  "La fame di allora torna per sette giorni. Poi resta il mestiere, che è meglio.": "The old hunger comes back for seven days. Then the craft remains, which is better.",
  "Usi l'anello come sveglia, non come altare.": "You use the ring as an alarm clock, not an altar.",
  "La fame, ripresa. Il ferro, quella settimana, è più onesto.": "The hunger, recovered. The rim, that week, is more honest.",
  "Giugno torna nelle mani. Lo usi, poi lo metti via.": "June comes back to your hands. You use it, then put it away.",
  "Non è nostalgia: è un metodo. Per sette giorni il gesto è quello di allora.": "It's not nostalgia: it's a method. For seven days, the motion is the one from back then.",
  "Chiudi il discorso": "You close the subject",
  "Quello è stato. Questo è adesso.": "That was then. This is now.",
  "Niente altari. Il prossimo possesso è l'unico che conta.": "No altars. The next possession is the only one that counts.",
  "Chiudi il discorso. Resta ottobre, che è più onesto di giugno.": "You close the subject. October remains, which is more honest than June.",
  "Quello è stato. Questo si gioca adesso, senza cornice.": "That was then. This is played now, without a frame.",
  "Niente museo. Ottobre non legge le bacheche, e tu nemmeno.": "No museum. October doesn't read trophy cases, and neither do you.",
  "Chiudi. Il prossimo possesso non ha un anello, e questo è il punto.": "You close it. The next possession has no ring, and that's the point.",
  "Quello è stato. Questo è adesso. La differenza, tenuta, è il mestiere.": "That was then. This is now. The difference, held, is the craft.",
  "Ancora {0}": "Still {0}",
  "La stessa insegna, {0} inverni": "The same logo, {0} winters",
  "Casa, se questa parola tiene": "Home, if that word holds",
  "{0} inverni, la stessa porta": "{0} winters, the same door",
  "Il corridoio di {0}": "The hallway in {0}",
  "Fedeltà, o abitudine": "Loyalty, or habit",
  "{0} stagioni sotto la stessa insegna. C'è chi chiama questo fedeltà. C'è chi lo chiama abitudine.": "{0} seasons under the same logo. Some call it loyalty. Some call it habit.",
  "I tifosi ti riconoscono dal passo, non dal numero. {0} anni. {1}.": "The fans recognize you by your walk, not your number. {0} years. {1}.",
  "{0} è un corridoio che conosci al buio. {1} anni non sono un caso.": "{0} is a hallway you know in the dark. {1} years are no accident.",
  "{0} inverni. I tifosi ti riconoscono dal passo. Tu riconosci i muri, e resti.": "{0} winters. The fans recognize you by your walk. You recognize the walls, and you stay.",
  "Ancora {0}. {1} inverni sotto la stessa insegna, e l'armadietto ha il tuo odore.": "Still {0}. {1} winters under the same logo, and the locker smells like you.",
  "{0} stagioni. Casa, se questa parola tiene. A {1} tiene ancora.": "{0} seasons. Home, if that word holds. In {1}, it still does.",
  "Resti, e lo dici": "You stay, and you say so",
  "La casa è questa.": "This is home.",
  "A {0} il corridoio è corto. Lo conosci al buio.": "In {0}, the hallway is short. You know it in the dark.",
  "I muri di {0} non ti chiedono più il nome. È un lusso raro.": "The walls in {0} don't ask your name anymore. It's a rare luxury.",
  "Resti. A {0} l'armadietto è tuo, e questo, a quest'età, conta.": "You stay. In {0}, the locker is yours, and that, at this age, counts.",
  "Lo dici. A {0} la casa è questa, e i tifosi lo sentono dal passo.": "You say it. In {0}, this is home, and the fans can tell from your walk.",
  "{0} inverni. Restare, detto chiaro, vale più di una clausola.": "{0} winters. Staying, said plainly, is worth more than a clause.",
  "A {0} non devi più presentarti. Entri, e lo schema ti riconosce.": "In {0}, you no longer need to introduce yourself. You walk in, and the playbook recognizes you.",
  "Chiedi un ruolo più chiaro": "You ask for a clearer role",
  "Fedeltà non è silenzio.": "Loyalty isn't silence.",
  "{0} ascolta. Non promette. Sposta due minuti. È già qualcosa.": "{0} listens. He doesn't promise. He moves two minutes. It's something.",
  "Due minuti in più, detti piano. {0} non fa discorsi: fa la rotazione.": "Two more minutes, said softly. {0} doesn't give speeches: he sets the rotation.",
  "Chiedi. {0} non alza la voce. Sposta un possesso. Basta.": "You ask. {0} doesn't raise his voice. He moves a possession. That's enough.",
  "Fedeltà non è silenzio. {0} lo sa, e sposta un pezzo.": "Loyalty isn't silence. {0} knows it, and moves a piece.",
  "Chiedi un ruolo più chiaro. {0} non giura. Qualche minuto, però, si allunga.": "You ask for a clearer role. {0} doesn't swear to anything. A few minutes, though, get longer.",
  "Due possessi in più, detti senza urla. {0} annota, e basta.": "Two more possessions, asked for without shouting. {0} takes note, and that's it.",
  "Lasci aperta la porta": "You leave the door open",
  "L'estate parlerà.": "The summer will speak.",
  "Non minacci. Non giuri. Il mercato, da lontano, prende nota.": "You don't threaten. You don't swear. The market, from afar, takes note.",
  "Una porta socchiusa, senza urla. Qualcuno, fuori, annota.": "A door left ajar, no shouting. Someone, outside, takes note.",
  "Niente ultimatum. Il silenzio, stavolta, vale una clausola.": "No ultimatums. Silence, this time, is worth a clause.",
  "L'estate parlerà. Tu non alzi la voce, e il mercato lo sente lo stesso.": "The summer will speak. You don't raise your voice, and the market hears it anyway.",
  "Lasci aperta la porta. Non è un addio: è un modo di stare, per ora.": "You leave the door open. It's not a goodbye: it's a way of being, for now.",
  "Niente minacce. Una porta, socchiusa, e il resto è mestiere.": "No threats. A door, ajar, and the rest is craft.",
  "Un'altra lingua, lo stesso lavoro": "Another language, the same job",
  "Il tempo europeo": "European timing",
  "Palazzetti stretti, teste larghe": "Cramped arenas, broad minds",
  "Il giovedì europeo": "European Thursday",
  "Un'altra lingua tattica, lo stesso ferro": "Another tactical language, the same rim",
  "Palazzetto pieno, tattica stretta. A {0} ti chiedono di pensare prima di saltare.": "A packed arena, tight tactics. In {0} they ask you to think before you jump.",
  "L'Europa non perdona i possessi vuoti. Tu, a quest'età, ne hai visti troppi per sbagliarne uno di fretta.": "Europe doesn't forgive empty possessions. You, at this age, have seen too many to waste one in a hurry.",
  "A {0} il blocco e uscita ha un altro orario. Lo impari, o resti fuori dallo schema.": "In {0}, the pick-and-pop runs on a different clock. You learn it, or you fall out of the play.",
  "Un'altra lingua tattica, lo stesso ferro. A {0} il giovedì europeo non perdona.": "Another tactical language, the same rim. In {0}, European Thursday doesn't forgive.",
  "Palazzetti stretti, teste larghe. L'Europa ti chiede di leggere prima, e tu lo fai.": "Cramped arenas, broad minds. Europe asks you to read first, and you do.",
  "A {0} ogni possesso è una lezione. Gli errori si pagano in silenzio, e tu lo sai.": "In {0}, every possession is a lesson. Mistakes are paid for in silence, and you know it.",
  "Ti adatti al sistema": "You adapt to the system",
  "Meno isolamento, più lettura.": "Less isolation, more reading.",
  "Il blocco e uscita ha un altro tempo. Lo impari. Si vede.": "The pick-and-pop has a different timing. You learn it. It shows.",
  "Un'altra lingua tattica. Dopo due settimane il corpo la parla.": "Another tactical language. After two weeks your body speaks it.",
  "L'Europa ti chiede di leggere prima. Lo fai, e il palazzetto lo nota.": "Europe asks you to read first. You do, and the arena notices.",
  "Ti adatti. Il sistema, qui, è una grammatica, e tu la impari.": "You adapt. The system, here, is a grammar, and you learn it.",
  "Meno isolamento, più lettura. Il palazzetto, dopo un mese, ti riconosce.": "Less isolation, more reading. After a month, the arena recognizes you.",
  "Un altro orario, lo stesso ferro. Lo impari, e si vede dal passo.": "A different clock, the same rim. You learn it, and it shows in your stride.",
  "Porti il tuo gioco": "You bring your game",
  "Sei arrivato per questo.": "That's what you came here for.",
  "Un possesso tuo, netto. Il palazzetto ci mette un attimo a capire.": "One possession of yours, clean. The arena takes a moment to understand.",
  "Tieni, decidi, segni. Qui è un accento nuovo, e funziona.": "You hold, decide, score. Here it's a new accent, and it works.",
  "Un isolamento in una coppa tattica. Per una sera il palazzetto impara il tuo nome.": "An isolation in a tactical cup game. For one night, the arena learns your name.",
  "Porti il tuo gioco. Per una sera il palazzetto impara un altro orario.": "You bring your game. For one night, the arena learns a different clock.",
  "Un possesso tuo, detto chiaro. Qui è un accento, e tiene.": "One possession of yours, said plainly. Here it's an accent, and it holds.",
  "Sei arrivato per questo. Il palazzetto, un attimo dopo, lo sa.": "That's what you came here for. The arena knows it a moment later.",
  "Ascolti i veterani di qui": "You listen to the local veterans",
  "Loro questa palestra la sanno a memoria.": "They know this gym by heart.",
  "Due frasi in un caffè. Valgono un filmato.": "Two sentences over coffee. They're worth a film session.",
  "Un veterano locale ti spiega un'uscita. La tieni per il resto dell'inverno.": "A local veteran explains a set to you. You keep it for the rest of the winter.",
  "Impari in un bar, non in sala video. Strano, e giusto.": "You learn in a café, not in the film room. Strange, and right.",
  "Loro questa palestra la sanno a memoria. Tu ascolti, e il corpo impara.": "They know this gym by heart. You listen, and your body learns.",
  "Due minuti al caffè. Un'uscita nuova, tenuta per l'inverno.": "Two minutes over coffee. A new set, kept for the winter.",
  "Ascolti i veterani di qui. Il gesto, dopo, è un palmo più pulito.": "You listen to the local veterans. The motion, afterwards, is a touch cleaner.",
  "La primavera che non è bastata": "The spring that wasn't enough",
  "Quella serie, ancora": "That series, still",
  "Il maggio che resta nelle mani": "The May that stays in your hands",
  "Una porta chiusa, ancora aperta in testa": "A closed door, still open in your head",
  "L'eliminazione che non si è sciolta": "The elimination that never faded",
  "L'anno scorso: {0}. La ferita è chiusa. Il ricordo no.": "Last year: {0}. The wound has healed. The memory hasn't.",
  "Un'eliminazione resta nelle mani. Ogni palleggio di ottobre ne porta un pezzo.": "An elimination stays in your hands. Every dribble in October carries a piece of it.",
  "Fuori {0}. Ottobre lo sa, anche se tu fai finta di no.": "Out {0}. October knows it, even if you pretend it doesn't.",
  "La primavera che non è bastata. {0}. Il maggio resta nelle mani.": "The spring that wasn't enough. {0}. May stays in your hands.",
  "Si torna a casa a maggio. L'estate inizia troppo presto, e lo sai.": "You go home in May. The summer starts too early, and you know it.",
  "Una porta chiusa, ancora aperta in testa. {0}. Ottobre la rilegge.": "A closed door, still open in your head. {0}. October reads it again.",
  "Studi quella serie, fotogramma per fotogramma": "You study that series, frame by frame",
  "Il lutto, fatto mestiere.": "Grief, turned into craft.",
  "Rivedi i possessi. Trovi uno che non avevi visto. Basta quello.": "You review the possessions. You find one you hadn't seen. That's enough.",
  "La serie persa diventa un quaderno. Ottobre, poi, è più pulito.": "The lost series becomes a notebook. October, afterwards, is cleaner.",
  "Guardi senza pietà. Un errore, corretto, vale una settimana.": "You watch without mercy. One mistake, corrected, is worth a week.",
  "Il lutto, fatto mestiere. I fotogrammi, riletti, tengono per l'inverno.": "Grief, turned into craft. The frames, reviewed, hold up for the winter.",
  "Una serie, un quaderno. Ottobre, poi, non chiede alibi.": "A series, a notebook. October, afterwards, asks for no alibis.",
  "Guardi quella serie fino in fondo. Un possesso, corretto, basta.": "You watch that series all the way through. One possession, corrected, is enough.",
  "Cambi qualcosa nel corpo": "You change something in your body",
  "Meno peso, più primo passo.": "Less weight, more first step.",
  "Estate secca. A ottobre il primo contropiede è tuo.": "A lean summer. In October, the first fast break is yours.",
  "Lavoro sporco, niente alibi. Il primo passo di novembre è più lungo.": "Dirty work, no alibis. Your first step in November is longer.",
  "Sudore da vendetta quieta. Non si dichiara: si corre.": "The sweat of quiet revenge. You don't announce it: you run.",
  "Meno peso, più primo passo. Ottobre lo sente prima dello staff.": "Less weight, more first step. October feels it before the staff does.",
  "Cambi qualcosa nel corpo. Il maggio che resta nelle mani, a ottobre, pesa meno.": "You change something in your body. The May that stays in your hands weighs less in October.",
  "Sudore senza tesi. Il primo passo, a novembre, è più lungo.": "Sweat with no storyline. Your first step, in November, is longer.",
  "Non ne parli più": "You don't talk about it anymore",
  "Si gira pagina, davvero.": "You turn the page, for real.",
  "Il silenzio, stavolta, è una scelta. Tiene.": "Silence, this time, is a choice. It holds.",
  "Non commenti l'uscita. Il gruppo, per una volta, ti è grato.": "You don't comment on the elimination. The group, for once, is grateful.",
  "Chiudi la bocca. L'eliminazione pesa meno se non la racconti.": "You keep your mouth shut. The elimination weighs less if you don't retell it.",
  "Si gira pagina, davvero. Il silenzio, tenuto, vale più di un'intervista.": "You turn the page, for real. Silence, kept, is worth more than an interview.",
  "Non ne parli più. Ottobre, così, è più pulito.": "You don't talk about it anymore. October, this way, is cleaner.",
  "Chiudi. L'eliminazione resta, ma non la racconti, e pesa meno.": "You close it. The elimination stays, but you don't retell it, and it weighs less.",
  "Di nuovo, lui": "Him, again",
  "Il metro che non si spegne": "The yardstick that won't switch off",
  "Due vecchi, un corridoio": "Two old men, one hallway",
  "Il nome che alza ancora il tono": "The name that still raises the temperature",
  "Una rivalità che ha i capelli grigi": "A rivalry with gray hair",
  "{0} torna in una conferenza, in un fermo, in un tempo morto. L'età non ha spento quella voce.": "{0} comes back in a press conference, in a freeze-frame, in a timeout. Age hasn't silenced that voice.",
  "Lo incroci in un corridoio. {0}. Vi siete fatti vecchi insieme, senza dirvelo.": "You cross paths in a hallway. {0}. You grew old together, without saying so.",
  "{0} è ancora un nome che alza il tono. Anche adesso.": "{0} is still a name that raises the temperature. Even now.",
  "Di nuovo, lui. {0} resta un metro, e il metro, a quest'età, è ancora acceso.": "Him, again. {0} remains a yardstick, and at this age the yardstick is still on.",
  "Due vecchi, un corridoio. {0} non ha spento quella voce, e tu nemmeno.": "Two old men, one hallway. {0} hasn't silenced that voice, and neither have you.",
  "{0}: una rivalità che ha i capelli grigi, e tiene lo stesso.": "{0}: a rivalry with gray hair, and it holds anyway.",
  "Una stretta di mano, e basta": "A handshake, and that's it",
  "La guerra è finita. Resta il rispetto.": "The war is over. Respect remains.",
  "Due secondi. Niente fotografi. Pesano.": "Two seconds. No photographers. They weigh.",
  "Una stretta di mano vera. La rivalità, per un attimo, è un mestiere.": "A real handshake. The rivalry, for a moment, is a craft.",
  "Vi guardate. Basta. Poi ognuno torna alla sua palestra.": "You look at each other. That's enough. Then each of you goes back to his own gym.",
  "La guerra è finita. Resta il rispetto, basso e fermo.": "The war is over. Respect remains, low and steady.",
  "Una stretta di mano, e basta. Due vecchi, un corridoio, niente titoli.": "A handshake, and that's it. Two old men, one hallway, no headlines.",
  "Vi siete fatti vecchi insieme, senza dirvelo. Una stretta basta.": "You grew old together, without saying so. A handshake is enough.",
  "La tieni accesa": "You keep it burning",
  "Ti serve ancora.": "You still need it.",
  "Non è odio. È un metro. Lo usi.": "It's not hatred. It's a yardstick. You use it.",
  "Ti alleni contro un'ombra che ha un nome. Il ferro, quella settimana, è più onesto.": "You train against a shadow with a name. The rim, that week, is more honest.",
  "La rivalità diventa un orario, non un titolo.": "The rivalry becomes a schedule, not a headline.",
  "La tieni accesa. Ti serve ancora, e il ferro, quella settimana, lo sa.": "You keep it burning. You still need it, and the rim, that week, knows it.",
  "Un nome che alza il tono. Lo usi, senza dichiararlo.": "A name that raises the temperature. You use it, without saying so.",
  "Non è guerra. È un metro. A quest'età i metri, tenuti, valgono.": "It's not war. It's a yardstick. At this age, yardsticks, kept, are worth something.",
  "Gli chiedi una cosa vera": "You ask him something real",
  "Come si fa, a quest'età.": "How it's done, at this age.",
  "Una frase sola. Te la porti in palestra.": "A single sentence. You take it to the gym.",
  "Lui parla poco. Il poco ti basta per una settimana di lavoro.": "He says little. The little is enough for a week of work.",
  "Un messaggio, niente interviste. Lo rileggi prima delle ripetizioni.": "A message, no interviews. You reread it before your reps.",
  "Gli chiedi una cosa vera. Come si fa, a quest'età.": "You ask him something real. How it's done, at this age.",
  "Una frase, tenuta. Il ferro, quella settimana, è più onesto.": "One sentence, kept. The rim, that week, is more honest.",
  "Lui risponde poco. Il poco, a quest'età, vale una settimana.": "He answers briefly. Brief, at this age, is worth a week.",
  "Il corpo fa l'appello": "Your body takes roll call",
  "Cosa tiene, cosa no": "What holds, what doesn't",
  "L'inventario di ottobre": "October's inventory",
  "Le articolazioni hanno un'agenda": "Your joints keep a schedule",
  "Il riscaldamento più lungo": "The longer warm-up",
  "Quello che resta delle gambe": "What's left of your legs",
  "L'appello del corpo, ogni mattina": "Your body's roll call, every morning",
  "Cosa tiene, detto chiaro": "What holds, said plainly",
  "Non è un infortunio. È un inventario: cosa tiene, cosa no, cosa finge.": "It's not an injury. It's an inventory: what holds, what doesn't, what's pretending.",
  "{0} anni. Il riscaldamento dura di più. Il quarto quarto, a volte, di meno.": "{0} years old. The warm-up lasts longer. The fourth quarter, sometimes, shorter.",
  "Le articolazioni hanno un'agenda. Tu la leggi prima dello staff.": "Your joints keep a schedule. You read it before the staff does.",
  "A {0} anni ogni riscaldamento è un inventario. Tu lo fai prima che lo faccia lo staff.": "At {0}, every warm-up is an inventory. You take it before the staff does.",
  "Il corpo fa l'appello. Tu rispondi ancora sì, e scendi.": "Your body takes roll call. You still answer yes, and take the floor.",
  "A {0} anni il riscaldamento è già una partita. La vinci in silenzio, ogni sera.": "At {0}, the warm-up is already a game. You win it in silence, every night.",
  "Tagli il carico, e ascolti": "You cut the workload, and listen",
  "Il carico, tagliato": "The workload, cut",
  "Ascolti, e tagli il carico": "You listen, and cut the workload",
  "Durare è già un mestiere.": "Lasting is already a craft.",
  "Meno chili, più sonno. Novembre ti trova in piedi.": "Fewer kilos, more sleep. November finds you on your feet.",
  "Tagli il carico. Il corpo, per una volta, ringrazia in silenzio.": "You cut the workload. Your body, for once, says thanks in silence.",
  "Niente eroismo di ottobre. Arrivi a marzo con le gambe tue.": "No October heroics. You reach March on your own legs.",
  "Ascolti, e tagli. Durare, a quest'età, è già un mestiere.": "You listen, and you cut. Lasting, at this age, is already a craft.",
  "Il carico, tagliato. Marzo ti trova in piedi, senza dichiararlo.": "The workload, cut. March finds you on your feet, without announcing it.",
  "Meno chili sulla barra. Il tendine, a ottobre, non presenta il conto in anticipo.": "Fewer kilos on the bar. In October, your tendon doesn't send the bill early.",
  "Il gesto, nient'altro": "The motion, nothing else",
  "Tiro e passaggio, solo quello": "Shooting and passing, just that",
  "Insisti sul mestiere": "You stick to the craft",
  "Tiro, passaggio, nient'altro.": "Shooting, passing, nothing else.",
  "Niente eroismo. Solo ripetizioni. A ottobre si vede.": "No heroics. Just reps. By October it shows.",
  "Tiro, passaggio, nient'altro. Il gesto torna prima del fiato.": "Shooting, passing, nothing else. The motion comes back before your wind.",
  "Insisti sul semplice. È l'unica cosa che, a quest'età, cresce ancora.": "You stick to the simple things. At this age, it's the only thing that still grows.",
  "Il gesto, nient'altro. A ottobre lo staff lo capisce dal polso.": "The motion, nothing else. In October the staff can tell from your wrist.",
  "Tiro e passaggio, solo quello. Il resto, a quest'età, è rumore.": "Shooting and passing, just that. The rest, at this age, is noise.",
  "Insisti sul mestiere. Il semplice, tenuto, vale più di un giro in più.": "You stick to the craft. The simple things, kept, are worth more than one more round.",
  "I minuti, chiesti ancora": "Minutes, asked for again",
  "Ancora i minuti veri": "Real minutes, still",
  "Chiedi minuti veri, ancora": "You ask for real minutes, again",
  "Non vuoi sparire in punta.": "You don't want to fade away at the end.",
  "{0} non promette. Ti guarda. I minuti, qualche sera, arrivano.": "{0} doesn't promise. He looks at you. The minutes, some nights, come.",
  "Chiedi ancora. {0} non sorride. Qualche quarto, però, si allunga.": "You ask again. {0} doesn't smile. A few quarters, though, get longer.",
  "{0} ti lascia in campo un possesso in più. Non è un discorso: è un voto.": "{0} leaves you on the floor for one more possession. It's not a speech: it's a vote.",
  "I minuti, chiesti ancora. {0} non fa discorsi: fa la rotazione.": "Minutes, asked for again. {0} doesn't give speeches: he sets the rotation.",
  "Non vuoi sparire in punta. {0} lo capisce, e qualche possesso si allunga.": "You don't want to fade away at the end. {0} understands, and a few possessions get longer.",
  "Chiedi minuti veri. {0} ti guarda. Qualche sera, arrivano.": "You ask for real minutes. {0} looks at you. Some nights, they come.",
  "Europa. Palazzetti pieni, tattica stretta, un ultimo atto diverso.": "Europe. Packed arenas, tight tactics, a different last act.",
  "Un altro palcoscenico. Il ruolo e la voce vengono prima; questo, se arriva, è la chiusura.": "Another stage. Role and voice come first; this, if it comes, is the final chapter.",
  "Eurolega: un campionato che parla un'altra lingua. L'anello, lì, ha un altro peso.": "EuroLeague: a league that speaks another language. A ring, there, weighs differently.",
  "Un'altra geografia. I palazzetti più piccoli, le coppe più lunghe, un mestiere da adulti.": "A different geography. Smaller arenas, longer cup runs, a grown-up's craft.",
  "Un ultimo atto in un'altra lingua, con la stessa palla. Non è una fuga.": "A last act in another language, with the same ball. It's not an escape.",
  "Non è un esilio da {0}. È un giugno diverso, se i minuti qui spariscono.": "It's not an exile from {0}. It's a different June, if the minutes here disappear.",
  "Prima il posto, poi la voce. L'Europa, se firmi, è l'ultimo atto — detto chiaro.": "Your spot first, then your voice. Europe, if you sign, is the last act — said plainly.",
  "Offerta magra, senso pieno. L'Europa non compra il nome: compra gli ultimi possessi.": "A thin offer, full meaning. Europe doesn't buy the name: it buys the last possessions.",
  "Da contendente la cifra è piccola. Non è un esilio da {0}: è una chiusura, se i minuti spariscono.": "As a contender, the number is small. It's not an exile from {0}: it's a final chapter, if the minutes disappear.",
  "Il ruolo e la voce vengono prima. Questa porta, magra, resta l'ultimo atto.": "Role and voice come first. This door, thin as it is, stays the last act.",
  "{0}. {1} sa che questa potrebbe essere l'ultima primavera. Tu lo sai prima di loro.": "{0}. {1} knows this could be the last spring. You know it before they do.",
  "{0}. Il posto, tenuto, vale più di una copertina che nessuno chiede più.": "{0}. Your spot, held, is worth more than a cover nobody asks for anymore.",
  "{0}. Una sera ti chiedono com'è. Tu racconti poco, e il poco basta.": "{0}. One evening they ask you what it is like. You tell little, and the little is enough."
};
