/* English narrative for story-extra. Key: Italian source text (see ../key.ts). */
export const EN_STORY_EXTRA: Readonly<Record<string, string>> = {
  "Il primo tempo morto perso": "Your first lost timeout",
  "Sbagli lo schema, {COACH} chiama tempo morto. Lo sguardo di tutta la panchina ti arriva prima della voce, e resta.": "You blow the play, {COACH} calls a timeout. The look from the whole bench reaches you before the voice, and it lingers.",
  "Chiedi scusa in cerchio": "Apologize in the huddle",
  "Responsabilità, subito.": "Accountability, right away.",
  "Il gruppo chiude il discorso in dieci secondi. Tu impari il resto della notte.": "The group closes the matter in ten seconds. You spend the rest of the night learning.",
  "Correggi al possesso dopo": "Fix it on the next possession",
  "Parla il campo, non la voce.": "Let the floor talk, not your mouth.",
  "Il canestro successivo non è bello. È necessario.": "The next basket isn't pretty. It's necessary.",
  "Non vuoi peggiorare il momento.": "You don't want to make the moment worse.",
  "Nessuno ti rimprovera. Qualcuno nota che non hai parlato.": "Nobody scolds you. Someone notices you didn't speak.",
  "Un giornale locale ti chiama «progetto»": "A local paper calls you a \"project\"",
  "Non è un insulto. Fa più male di un insulto.": "It's not an insult. It hurts more than an insult.",
  "Appunti il ritaglio in armadietto": "You pin the clipping in your locker",
  "Ogni mattina, prima delle scarpe.": "Every morning, before your shoes.",
  "La parola «progetto» diventa un orario, non un'etichetta.": "The word \"project\" becomes a schedule, not a label.",
  "Rispondi con i numeri": "Answer with numbers",
  "Chiedi più minuti, più uso.": "You ask for more minutes, more usage.",
  "Ottieni possessi. Non tutti te li sei guadagnati.": "You get possessions. You haven't earned all of them.",
  "Chiami l'autore": "You call the writer",
  "Una conversazione, non una guerra.": "A conversation, not a war.",
  "L'articolo successivo è più preciso. Anche tu.": "The next article is more accurate. So are you.",
  "Il veterano ti toglie il tiro aperto": "The veteran takes your open shot",
  "Avevi il ritmo. Lui aveva l'anzianità.": "You had the rhythm. He had seniority.",
  "Glielo lasci, impari il tempo": "You let him have it, you learn the timing",
  "Gerarchia ora, spazio dopo.": "Hierarchy now, space later.",
  "A fine quarto ti cerca lui. Il cerchio si chiude.": "At the end of the quarter, he looks for you. The circle closes.",
  "Il possesso dopo tiri comunque": "You shoot anyway on the next possession",
  "Il coraggio si vede da lontano.": "Courage is visible from far away.",
  "Il canestro entra. Qualche sopracciglio no.": "The shot goes in. A few eyebrows don't come down.",
  "Ne parli a fine gara": "You talk about it after the game",
  "Due frasi, niente scena.": "Two sentences, no scene.",
  "Capisce. Tu capisci quando stai zitto, la volta dopo.": "He understands. You understand when to keep quiet, next time.",
  "Una gara da 40 punti, zero vittoria": "A 40-point game, zero win",
  "I numeri tuoi, il risultato loro. I titoli scelgono il primo.": "Your numbers, their result. The headlines pick the first.",
  "Parli solo della sconfitta": "You only talk about the loss",
  "Niente sequenze in conferenza. Solo la sconfitta, detta chiara.": "No highlight reels at the press conference. Just the loss, said plainly.",
  "Lo spogliatoio sente che i 40 non ti bastano.": "The locker room senses that 40 isn't enough for you.",
  "Rivendichi il tuo impatto": "You claim your impact",
  "Senza di te era peggio.": "Without you it would have been worse.",
  "Hai ragione. Non è il tipo di ragione che unisce.": "You're right. It's not the kind of right that brings people together.",
  "Chiedi i possessi della difesa": "You ask for the defensive possessions",
  "I 40 non coprono le coperture sbagliate. Si studiano, a volume basso.": "The 40 don't cover the blown coverages. You study them, volume down.",
  "A mezzanotte sei ancora in sala video.": "At midnight you're still in the film room.",
  "La dirigenza vuole «più spettacolo»": "The front office wants \"more show\"",
  "Meno gioco in post, più transizione. I tifosi comprano le schiacciate.": "Less post play, more transition. Fans buy dunks.",
  "Accetti il nuovo ritmo": "You accept the new pace",
  "Più primo passo, più rischio.": "More first step, more risk.",
  "Il palazzetto si alza prima. Il ginocchio prende appunti.": "The arena rises sooner. Your knee takes notes.",
  "Difendi il tuo gioco": "You defend your game",
  "Vince chi legge, non chi vola.": "The one who reads wins, not the one who flies.",
  "Tieni la bussola. Qualche fischio arriva comunque.": "You keep your compass. A few boos come anyway.",
  "Un ibrido": "A hybrid",
  "Spettacolo quando serve, controllo quando conta.": "Show when it's needed, control when it counts.",
  "Non fai felice nessuno del tutto. Fai felice la panchina.": "You don't make anyone fully happy. You make the bench happy.",
  "Due gare in due notti a ovest, fuso ostile": "Back-to-back games out west, brutal time zone",
  "Due gare in due notti, tre fusi, un ginocchio che parla.": "Two games in two nights, three time zones, a knee that talks.",
  "Giochi entrambe da titolare": "You start both",
  "Niente scuse, niente minuti gestiti.": "No excuses, no managed minutes.",
  "I tifosi in trasferta ti rispettano. Il fisico fa i conti a marzo.": "The road fans respect you. Your body settles the bill in March.",
  "Salti la seconda": "You sit out the second",
  "Aprile è più lungo di questa notte.": "April is longer than tonight.",
  "I social non perdonano. Il tendine sì.": "Social media doesn't forgive. Your tendon does.",
  "Esci dalla panchina nella seconda": "You come off the bench in the second",
  "Minuti veri, senza il peso del quinto fallo.": "Real minutes, without the weight of the fifth foul.",
  "Un compromesso da professionista, non da slogan.": "A professional's compromise, not a slogan's.",
  "{RIVAL} firma un contratto massimo: i paragoni ripartono": "{RIVAL} signs a max contract: the comparisons start again",
  "Stessi anni, due contratti, una sola versione dei fatti.": "Same age, two contracts, only one version of the facts.",
  "Usi i suoi numeri come bersaglio": "You use his numbers as a target",
  "La rivalità torna a essere un mestiere.": "The rivalry goes back to being a craft.",
  "Auguri pubblici, lavoro privato": "Public congratulations, private work",
  "Eleganza fuori, fame dentro.": "Elegance outside, hunger inside.",
  "I titoli si ammorbidiscono. Tu no.": "The headlines soften. You don't.",
  "Chiedi al tuo agente di muoversi": "You ask your agent to make a move",
  "Il contratto è un linguaggio.": "A contract is a language.",
  "La voce gira. In spogliatoio qualcuno fa due conti.": "Word gets around. In the locker room, someone does the math.",
  "Un quinto fallo stupido a tre minuti dalla fine": "A stupid fifth foul with three minutes left",
  "La panchina è un posto freddo quando la gara è viva.": "The bench is a cold place when the game is alive.",
  "Rivedi i contatti, uno a uno": "You review the contacts, one by one",
  "Mani, piedi, anticipo.": "Hands, feet, anticipation.",
  "Il fallo sparisce dai possessi che rivedi. Resta nella tua tecnica.": "The foul disappears from the possessions you review. It stays in your technique.",
  "Chiedi più aiuto in copertura": "You ask for more help on coverage",
  "Non vuoi fare il marcatore solo.": "You don't want to be the lone defender.",
  "Lo staff cambia una rotazione. Tu resti in campo più a lungo.": "The staff changes a rotation. You stay on the floor longer.",
  "Accetti il rischio, resti aggressivo": "You accept the risk, stay aggressive",
  "Senza contatto non sei tu.": "Without contact, you're not you.",
  "I fischi arrivano. Anche le palle rubate.": "The whistles come. So do the steals.",
  "Una gamba non risponde in riscaldamento": "A leg won't respond in warm-ups",
  "Niente referto ancora. Solo una certezza: stasera non sei intero.": "No medical report yet. Just one certainty: tonight you're not whole.",
  "Ti fermi": "You sit down",
  "Una notte persa, una stagione salvata.": "One night lost, one season saved.",
  "I tifosi fischiano il referto. Tu cammini verso l'autobus.": "The fans boo the medical report. You walk to the bus.",
  "Giochi, minuti ridotti": "You play, reduced minutes",
  "Presenza, non eroismo.": "Presence, not heroics.",
  "Entri, sistemi un possesso, esci. Un mestiere da veterano.": "You go in, fix a possession, come out. A veteran's craft.",
  "Giochi titolare comunque": "You start anyway",
  "La maglia pesa più della gamba.": "The jersey weighs more than the leg.",
  "Finisci la gara. Il mattino dopo il referto è più lungo.": "You finish the game. The next morning, the medical report is longer.",
  "Ti offrono una serata tributo a metà stagione": "They offer you a tribute night mid-season",
  "Una sequenza, vecchi compagni, lacrime in anticipo.": "A highlight reel, old teammates, tears ahead of time.",
  "Accetti, poi torni al lavoro": "You accept, then go back to work",
  "Il rispetto non è un ritiro.": "Respect isn't retirement.",
  "Piangi tre secondi. Il quarto successivo è tuo.": "You cry for three seconds. The next quarter is yours.",
  "Rinvii a fine carriera": "You postpone it to the end of your career",
  "Non vuoi il funerale mentre giochi.": "You don't want a funeral while you're still playing.",
  "Qualcuno si offende. Tu resti nel presente.": "Someone takes offense. You stay in the present.",
  "La trasformi in serata di beneficenza": "You turn it into a charity night",
  "Meno statue, più senso.": "Fewer statues, more meaning.",
  "Il palazzetto cambia registro. Anche tu.": "The arena changes its tone. So do you.",
  "Il nuovo titolare ti chiede lo spazio in post": "The new starter asks for your spot in the post",
  "Quello era il tuo metro quadrato. Adesso è un negoziato.": "That was your square meter. Now it's a negotiation.",
  "Glielo cedi, resti il lettore": "You give it up, stay the reader",
  "Palla e voce, non il fondo.": "Ball and voice, not the block.",
  "Il gioco gira. Il tuo nome resta nei tempi morti.": "The offense flows. Your name stays in the timeouts.",
  "Te lo giochi in allenamento": "You fight for it in practice",
  "Lo spazio si merita ogni giorno.": "Space is earned every day.",
  "Sudore, contatti, gerarchia aggiornata a sudore.": "Sweat, contact, a hierarchy updated in sweat.",
  "Chiedi un sistema a due riferimenti": "You ask for a two-option system",
  "Non è o lui o tu.": "It's not him or you.",
  "{COACH} disegna un'uscita nuova. Per una volta basta.": "{COACH} draws up a new set. For once, that's enough.",
  "Una rissa lampo in transizione": "A flash scuffle in transition",
  "Spintoni, panchine vuote, tre secondi che valgono una squalifica.": "Shoves, emptied benches, three seconds worth a suspension.",
  "Trattieni il compagno": "You hold back your teammate",
  "Sei il più lucido nel mucchio.": "You're the clearest head in the pile.",
  "Niente espulsione. In spogliatoio sei diventato un adulto.": "No ejection. In the locker room, you've become a grown-up.",
  "Non resti indietro": "You don't hang back",
  "Se si salta, salti.": "If it goes off, you go.",
  "Una tecnica, un titolo, un rispetto diverso in spogliatoio.": "A technical, a headline, a different kind of respect in the locker room.",
  "Esci dal mucchio, parli dopo": "You walk out of the pile, talk later",
  "Il referto è già abbastanza lungo.": "The box score is long enough already.",
  "Qualcuno ti chiama freddo. Lo staff ti chiama utile.": "Someone calls you cold. The staff calls you useful.",
  "Il fisioterapista trova un compenso sbagliato": "The physio finds a bad compensation",
  "Anni di salti sullo stesso piede. Si può ancora raddrizzare.": "Years of jumping off the same foot. It can still be straightened out.",
  "Un mese di rieducazione vera": "A month of real rehab",
  "Niente sequenze estive. Solo il corpo, rimesso a posto.": "No summer highlight reels. Just your body, put back in order.",
  "Niente telecamere in palestra. Un ottobre che cammina dritto.": "No cameras in the gym. An October that walks straight.",
  "Lavori intorno al problema": "You work around the problem",
  "Adatti il gesto, non ti fermi.": "You adapt the motion, you don't stop.",
  "Il tiro cambia di un grado. Le gare no.": "Your shot changes by one degree. The games don't.",
  "Ignori, è sempre stato così": "You ignore it, it's always been this way",
  "Finché entra, non si tocca.": "As long as it goes in, don't touch it.",
  "Per ora regge. I referti futuri hanno già una data.": "It holds for now. Future medical reports already have a date.",
  "Un ragazzo fuori dal palazzetto ti aspetta due ore": "A kid waits two hours for you outside the arena",
  "Maglia stinta, quaderno, una dedica che per lui è tutto.": "A faded jersey, a notebook, an autograph that means everything to him.",
  "Restituisci il tempo": "You give him your time",
  "Foto, firma, due minuti veri.": "Photo, signature, two real minutes.",
  "Non cambia una statistica. Cambia il modo in cui esci dal palazzetto.": "It doesn't change a stat. It changes how you walk out of the arena.",
  "Firma e vai": "You sign and go",
  "Il pullman non aspetta.": "The bus doesn't wait.",
  "Professionale. Dimenticato in dieci metri.": "Professional. Forgotten within ten meters.",
  "Lo fai entrare in palestra il giorno dopo": "You let him into the gym the next day",
  "Una tribuna vuota, un allenamento vero.": "Empty stands, a real practice.",
  "Lo staff alza un sopracciglio, poi lascia fare.": "The staff raises an eyebrow, then lets it happen.",
  "Una chiamata dalla tua Nazionale a metà settimana": "A midweek call-up from your national team",
  "Non è un torneo. È una finestra, tre gare, un aereo.": "It's not a tournament. It's a window, three games, a flight.",
  "Parti": "You go",
  "La maglia pesa più del calendario.": "The jersey weighs more than the schedule.",
  "Tre gare, un fuso, un orgoglio che non sta nel referto.": "Three games, a time zone, a pride that doesn't fit in the box score.",
  "Resti per il campionato": "You stay for the league",
  "Il club paga lo stipendio.": "The club pays your salary.",
  "Qualche fischio in estate. Un aprile più intero.": "A few boos in the summer. A healthier April.",
  "Una gara sola, poi rientri": "One game only, then you come back",
  "Presenza senza suicidio.": "Presence without self-destruction.",
  "Nessuno è del tutto contento. È il segno che hai scelto da adulto.": "Nobody is fully happy. That's the sign you chose like an adult.",
  "Il tuo primo doppio-doppio, e nessuno lo nota": "Your first double-double, and nobody notices",
  "Referto pulito, spogliatoio già sotto la doccia. Solo tu resti a guardare i numeri.": "Clean box score, locker room already in the showers. Only you stay to look at the numbers.",
  "Lo appunti sul quaderno": "You jot it in your notebook",
  "Una riga, una data, niente foto.": "One line, a date, no photo.",
  "Il secondo doppio-doppio arriva senza che lo cerchi.": "The second double-double comes without you chasing it.",
  "Lo mandi alla stampa locale": "You send it to the local press",
  "Se non lo racconti tu, non esiste.": "If you don't tell it, it doesn't exist.",
  "Un titolo piccolo. Un appetito più grande.": "A small headline. A bigger appetite.",
  "Chiedi i possessi sbagliati, nient'altro": "You ask for the bad possessions, nothing else",
  "I 10 e 10 non coprono i tre tempi morti.": "The 10 and 10 don't cover the three timeouts.",
  "{COACH} alza un sopracciglio. Poi ti lascia la chiavetta.": "{COACH} raises an eyebrow. Then hands you the USB stick.",
  "Un veterano ti invita a cena, poi ti interroga": "A veteran invites you to dinner, then grills you",
  "Non è amicizia. È un esame sul tuo posto in gerarchia.": "It's not friendship. It's an exam on your place in the pecking order.",
  "Rispondi con onestà": "You answer honestly",
  "Cosa sai fare, cosa ancora no.": "What you can do, what you can't yet.",
  "Paga lui. Il giorno dopo ti cerca in transizione.": "He pays. The next day he looks for you in transition.",
  "Alzi il tono, resti nel tuo": "You raise your tone, stay yourself",
  "Non sei un ospite. Sei della rosa.": "You're not a guest. You're on the roster.",
  "Il conto è tesissimo. In palestra, anche.": "The bill is tense. So is the gym, the next day.",
  "Ascolti, prendi appunti mentali": "You listen, take mental notes",
  "Lui ha dieci anni di possessi in più.": "He has ten more years of possessions than you.",
  "Torni con tre letture nuove. Nessuno lo sa.": "You come back with three new reads. Nobody knows.",
  "Il tuo agente parla di «finestra» in conferenza": "Your agent talks about a \"window\" at a press conference",
  "Non l'hai autorizzato. I titoli sì.": "You didn't authorize it. The headlines did.",
  "Lo smentisci, resti nella palestra": "You deny it, stay in the gym",
  "Il mercato non è il tuo mestiere, oggi.": "The market isn't your job, today.",
  "Lo spogliatoio respira. L'agente meno.": "The locker room breathes. The agent, less so.",
  "Lo lasci parlare": "You let him talk",
  "A volte serve una voce fuori dal cerchio.": "Sometimes you need a voice outside the circle.",
  "Le voci di scambio si infittiscono. Anche i possessi.": "Trade rumors pile up. So do the possessions.",
  "Chiami tu i microfoni": "You call the microphones yourself",
  "Una frase tua, non sua.": "A sentence of yours, not his.",
  "Chiudi la finestra con una battuta. Resta una fessura.": "You close the window with a quip. A crack remains.",
  "Una sera da 3 su 18, e il palazzetto fischia il tuo nome": "A 3-for-18 night, and the arena boos your name",
  "Non è il ferro. È il rapporto.": "It's not the rim. It's the relationship.",
  "Resti in palestra dopo": "You stay in the gym afterwards",
  "Duecento tiri, nessuno intorno.": "Two hundred shots, nobody around.",
  "Il palazzetto del giorno dopo è più silenzioso. Il ferro no.": "The next day's arena is quieter. The rim isn't.",
  "Chiedi un cambio di schema": "You ask for a change in the play calls",
  "Quei 18 tiri non erano i tuoi.": "Those 18 shots weren't yours.",
  "{COACH} stira la bocca. Poi sposta un blocco, e basta così.": "{COACH} purses his lips. Then he moves a screen, and that's that.",
  "La gara dopo cerchi il contatto": "The next game, you seek contact",
  "Punti in lunetta, non in pedana.": "Points at the line, not on the highlight reel.",
  "I fischi cambiano. I tuoi tiri, anche.": "The boos change. So do your shots.",
  "Un ragazzo del secondo turno ti chiede il tuo posto": "A second-round kid wants your spot",
  "Non a parole. Nei minuti del quarto quarto.": "Not in words. In fourth-quarter minutes.",
  "Gli fai spazio, resti la voce": "You make room for him, stay the voice",
  "Il mestiere cambia forma, non peso.": "The craft changes shape, not weight.",
  "I tempi morti diventano tuoi. I possessi, suoi.": "The timeouts become yours. The possessions, his.",
  "Te lo giochi ogni giorno": "You fight for it every day",
  "La rosa non è un lascito.": "The roster isn't an inheritance.",
  "Lui accelera. Tu non rallenti. Lo staff prende appunti.": "He speeds up. You don't slow down. The staff takes notes.",
  "Lo prendi sotto tutore": "You take him under your wing",
  "Due corpi, un'idea di gioco.": "Two bodies, one idea of the game.",
  "I titoli parlano di passaggio di consegne. In campo è più complicato, e meglio.": "The headlines talk about passing the torch. On the floor it's more complicated, and better.",
  "Un fischio a tre decimi, e il video ti dà torto": "A whistle at three tenths, and the replay proves you wrong",
  "Credevi di averla. Il monitor no.": "You thought you had it. The monitor didn't.",
  "Stringi la mano all'arbitro": "You shake the referee's hand",
  "La prossima chiamata potrebbe servirti.": "The next call might go your way.",
  "Un gesto piccolo. Un credito che non sta nel referto.": "A small gesture. A credit that doesn't show in the box score.",
  "Esplodi, poi ti scusi in conferenza": "You explode, then apologize at the press conference",
  "Il fuoco prima, la misura dopo.": "The fire first, the measure after.",
  "Una tecnica. Un titolo. Uno spogliatoio che ti capisce.": "A technical. A headline. A locker room that understands you.",
  "Chiedi i possessi, nient'altro": "You ask for the possessions, nothing else",
  "Capire il contatto, non il copione.": "Understand the contact, not the script.",
  "La volta dopo le mani sono più basse. Il fischio, anche.": "Next time your hands are lower. So is the whistle.",
  "La città vota una tassa per il nuovo palazzetto": "The city votes on a tax for the new arena",
  "I tifosi ti chiedono da che parte stai. Non è basket, ma lo è.": "The fans ask whose side you're on. It's not basketball, but it is.",
  "Resti neutrale": "You stay neutral",
  "Il contratto non è un programma elettorale.": "A contract isn't a campaign platform.",
  "Qualcuno ti chiama freddo. Lo spogliatoio ti chiama professionale.": "Someone calls you cold. The locker room calls you professional.",
  "Ti schieri con il quartiere": "You side with the neighborhood",
  "Il palazzetto è di chi ci vive intorno.": "The arena belongs to those who live around it.",
  "Un titolo diverso. Un rispetto diverso, fuori dal cerchio.": "A different headline. A different respect, outside the circle.",
  "Parli solo di parquet": "You only talk about hardwood",
  "Un campo migliore, un mestiere migliore.": "A better floor, a better craft.",
  "Né eroe né vigliacco. Un giocatore che sa il suo perimetro.": "Neither hero nor coward. A player who knows his perimeter.",
  "Un infortunio altrui ti spinge nel quintetto titolare": "Someone else's injury pushes you into the starting five",
  "Non l'hai chiesto. Non puoi far finta di niente.": "You didn't ask for it. You can't pretend nothing happened.",
  "Onori il posto, non lo festeggi": "You honor the spot, you don't celebrate it",
  "Minuti veri, voce bassa.": "Real minutes, low voice.",
  "Il titolare torna. Qualcosa del tuo ruolo resta.": "The starter comes back. Something of your role remains.",
  "Ti prendi ogni possesso": "You take every possession",
  "Le finestre si chiudono.": "Windows close.",
  "I numeri salgono. Qualche sguardo in panchina, anche.": "The numbers go up. So do a few looks from the bench.",
  "Chiami il compagno ogni sera": "You call your teammate every night",
  "Il posto è in prestito, la relazione no.": "The spot is on loan, the relationship isn't.",
  "Quando rientra, ti cerca. Non tutti lo farebbero.": "When he comes back, he looks for you. Not everyone would.",
  "Un tempo morto che dura troppo": "A timeout that lasts too long",
  "Lo schema è già detto. La stanza, no. Qualcuno deve chiudere il cerchio.": "The play has been called. The room hasn't. Someone has to close the circle.",
  "Parli tu, piano": "You speak, quietly",
  "Due dita sul petto, un compito a testa.": "Two fingers on the chest, one job each.",
  "Dici poco. Il gruppo si stringe. Qualcuno più vecchio di te annuisce.": "You say little. The group tightens. Someone older than you nods.",
  "Ascolti, poi esegui": "You listen, then execute",
  "Niente invenzioni. Il piano è già scritto.": "No improvising. The plan is already written.",
  "Ripeti lo schema a voce bassa. Entra. Lo staff non sorride: annuisce.": "You repeat the play under your breath. It goes in. The staff doesn't smile: it nods.",
  "Chiedi il possesso, se arriva": "You ask for the ball, if it comes",
  "Se hai la mano alzata, tieni.": "If your hand is up, keep it up.",
  "Alzi la mano. Qualcuno in panchina alza un sopracciglio. Poi la palla arriva.": "You raise your hand. Someone on the bench raises an eyebrow. Then the ball arrives.",
  "Il primo volo in cui non dormi": "The first flight where you don't sleep",
  "Ritardo a terra, cuffie, una gara fra trentasei ore. La testa gira a vuoto.": "A delay on the tarmac, headphones, a game in thirty-six hours. Your head spins in neutral.",
  "Tappi, mascherina, mestiere": "Earplugs, eye mask, professionalism",
  "Dormi come sai dormire: per lavoro.": "You sleep the way you know how: for work.",
  "Scendi a destinazione con gli occhi a posto. Pochi lo notano. Conta.": "You land with your eyes in order. Few people notice. It counts.",
  "Studi i possessi sul tavolino": "You study possessions on the tray table",
  "Lo schermo è piccolo. La testa no.": "The screen is small. Your head isn't.",
  "{COACH} non chiede il sonno. Chiede l'uscita. Sì, l'hai vista.": "{COACH} doesn't ask about sleep. He asks about the set. Yes, you've seen it.",
  "Carte in fondo all'aereo": "Cards at the back of the plane",
  "Il gruppo tiene, anche a diecimila metri.": "The group holds, even at ten thousand meters.",
  "Si vince poco, si parla tanto. Lo spogliatoio, il giorno dopo, è più corto.": "Little winning, lots of talking. The locker room, the next day, is shorter.",
  "Una conferenza in cui non alzano la mano": "A press conference where nobody raises a hand",
  "Tre minuti, nessuna domanda. I microfoni sono sull'altra sponda.": "Three minutes, no questions. The microphones are on the other side.",
  "Ringrazi e vai": "You say thanks and leave",
  "Il parquet è più onesto dei microfoni.": "The hardwood is more honest than microphones.",
  "Professionale. Dimenticato in dieci metri. Va bene così.": "Professional. Forgotten within ten meters. That's fine.",
  "Restituisci una frase vera": "You give back one true sentence",
  "Anche se non l'hanno chiesta.": "Even if nobody asked for it.",
  "Una frase sola. Qualcuno la tiene. Il resto della stanza è già altrove.": "One sentence. Someone keeps it. The rest of the room is already elsewhere.",
  "Resti a tirare, da solo": "You stay to shoot, alone",
  "Il palazzetto vuoto è un giudice onesto.": "An empty arena is an honest judge.",
  "I custodi chiudono. Tu resti un possesso in più, da solo, e basta.": "The custodians lock up. You stay one more possession, alone, and that's it.",
  "Sull'armadietto c'è un altro nome": "There's another name on your locker",
  "Un pezzo di nastro, una battuta. Lo spogliatoio guarda, e aspetta.": "A strip of tape, a joke. The locker room watches, and waits.",
  "Lo togli, senza scena": "You take it off, no scene",
  "Niente teatro. Solo il tuo nome, di nuovo.": "No theater. Just your name, again.",
  "Il nastro finisce nel cestino. Qualcuno annuisce. Il resto si chiude da solo.": "The tape ends up in the trash. Someone nods. The rest settles itself.",
  "Lo lasci una settimana": "You leave it up for a week",
  "Impari il tono prima di alzare la voce.": "You learn the tone before raising your voice.",
  "La battuta muore da sola. Tu impari quando lo spogliatoio è solo rumore.": "The joke dies on its own. You learn when the locker room is just noise.",
  "Rispondi con un nastro tuo": "You answer with a tape of your own",
  "Stesso registro, niente guerra.": "Same register, no war.",
  "Due risate. Una gerarchia aggiornata a nastro adesivo.": "Two laughs. A pecking order updated with adhesive tape.",
  "Il pullman resta al buio per un'ora": "The bus sits in the dark for an hour",
  "Una strada di campagna, il motore spento, una gara che non aspetta.": "A country road, engine off, a game that won't wait.",
  "Chiudi gli occhi, conservi le gambe": "You close your eyes, save your legs",
  "Il corpo prima dello schema.": "The body before the playbook.",
  "Arrivi intero. La gara, dopo, ha ancora le gambe.": "You arrive in one piece. The game, afterwards, still has legs.",
  "Rivedi i possessi sul telefono": "You review possessions on your phone",
  "Una chiavetta, tre uscite, niente lamento.": "A USB stick, three sets, no complaining.",
  "Quando lo staff chiede l'uscita, l'hai già vista. Il buio, almeno, è servito.": "When the staff asks about the set, you've already seen it. The darkness, at least, was useful.",
  "Tieni sveglio il gruppo": "You keep the group awake",
  "Carte, battute, il cerchio corto.": "Cards, jokes, a tight circle.",
  "Una battuta tiene meglio del silenzio. Il motore, alla fine, riparte già caldo.": "A joke holds better than silence. The engine, in the end, starts up already warm.",
  "Ti chiedono della casa, non del quarto quarto": "They ask about your house, not about the fourth quarter",
  "Tre registratori, una domanda che non riguarda il parquet.": "Three recorders, a question that has nothing to do with the hardwood.",
  "Riporti tutto al campo": "You bring it all back to the court",
  "Il mestiere sta lì, nient'altro.": "The craft is there, nothing else.",
  "Chiudi il perimetro. Qualcuno resta a bocca asciutta. Lo staff no.": "You close the perimeter. Someone leaves empty-handed. The staff doesn't.",
  "Tre frasi, poi basta": "Three sentences, then that's it",
  "Presenza, non confessione.": "Presence, not confession.",
  "Dai il minimo onesto. I titoli restano corti. Anche tu.": "You give the honest minimum. The headlines stay short. So do you.",
  "Ti alzi, vai in palestra": "You get up, go to the gym",
  "Il ferro non fa domande.": "The rim doesn't ask questions.",
  "La stanza resta senza coda. Tu resti con i tiri.": "The room has no follow-up. You stay with your shots.",
  "Lo staff ti chiede di diventare il marcatore": "The staff asks you to become the stopper",
  "Meno possessi tuoi, più notti sull'uomo migliore. È un mestiere, non un titolo.": "Fewer possessions for you, more nights on the best player. It's a craft, not a headline.",
  "Accetti, studi i piedi": "You accept, study your footwork",
  "Mani basse, anticipo, mestiere.": "Low hands, anticipation, craft.",
  "I punti calano. Le coperture no. {COACH} lo nota prima dei giornali.": "The points drop. The coverage doesn't. {COACH} notices before the papers do.",
  "Un possesso sì, uno no": "One possession yes, one no",
  "Identità mista, niente slogan.": "A mixed identity, no slogans.",
  "Non diventi una cosa sola. Diventi utile in due metri diversi.": "You don't become one thing. You become useful in two different spots.",
  "Difendi il tuo attacco": "You defend your offense",
  "I possessi tuoi restano tuoi.": "Your possessions stay yours.",
  "Tieni la palla. Qualche copertura resta scoperta. Lo sguardo in panchina, anche.": "You keep the ball. Some coverages stay open. So do the looks from the bench.",
  "Il rinnovo arriva in una stanza senza microfoni": "The extension arrives in a room with no microphones",
  "Niente conferenza. Una cifra, un anno, una stretta di mano nel corridoio.": "No press conference. A number, a year, a handshake in the hallway.",
  "Firmi e torni in palestra": "You sign and go back to the gym",
  "Il contratto è un mezzo, non una tesi.": "A contract is a means, not a thesis.",
  "Una firma, due passi, il parquet. Nessun titolo. Meglio.": "A signature, two steps, the hardwood. No headline. Better.",
  "Chiedi un anno in più, voce bassa": "You ask for one more year, quietly",
  "Tempo, non scena.": "Time, not theater.",
  "Un anno in più, detto piano. Il dirigente annuisce. I microfoni restano spenti.": "One more year, said softly. The executive nods. The microphones stay off.",
  "Rimandi, vuoi capire il ruolo": "You put it off, you want to understand the role",
  "Prima i minuti, poi la cifra.": "Minutes first, then the number.",
  "Niente firma oggi. Una conversazione onesta sul tuo metro quadrato.": "No signature today. An honest conversation about your square meter.",
  "In sala video, tre azioni di {RIVAL}, una tua": "In the film room, three plays by {RIVAL}, one of yours",
  "Non è un confronto. È un'eco. Lo staff non dice il nome. Non serve.": "It's not a comparison. It's an echo. The staff doesn't say the name. No need.",
  "Prendi appunti, niente orgoglio": "You take notes, no pride",
  "La lettura, non la rissa.": "The read, not the fight.",
  "Tre schemi nuovi. Il nome suo resta fuori dalla bocca.": "Three new plays. His name stays out of your mouth.",
  "Chiedi le tue tre, dopo": "You ask for your three, afterwards",
  "Lo stesso volume, lo stesso metro.": "Same volume, same yardstick.",
  "Ottieni lo stesso metro. L'eco, almeno, ha due voci.": "You get the same yardstick. The echo, at least, has two voices.",
  "Usi la sua uscita in gara": "You use his set in a game",
  "Se l'hai vista, la chiudi.": "If you've seen it, you shut it down.",
  "La volta dopo i piedi sono già lì. {RIVAL} lo sente, anche senza vederti.": "Next time your feet are already there. {RIVAL} feels it, even without seeing you."
};
