/* English narrative for summer. Key: Italian source text (see ../key.ts). */
export const EN_SUMMER: Readonly<Record<string, string>> = {
  "Estate già chiusa": "Summer already done",
  "Estate chiusa sul ruolo, senza pubblico": "A summer spent on your role, no audience",
  "Tre settimane di mestiere, già fatte": "Three weeks of craft, already done",
  "Ripetizioni, specchio, nient'altro: è andata così": "Reps, mirror, nothing else: that's how it went",
  "Il gesto, di nuovo, finché ha smesso di essere una decisione": "The motion, again, until it stopped being a decision",
  "Estate sul ruolo, già chiusa, senza testimoni": "A summer on your role, already done, no witnesses",
  "Luglio sul mestiere, nudo, già speso": "July on the craft, bare, already spent",
  "Tre settimane sullo specchio, senza copertina": "Three weeks in front of the mirror, no cover",
  "Lavoro sul ruolo, luglio già chiuso": "Work on your role, July already done",
  "Senza pubblico, tre settimane sul gesto": "No audience, three weeks on the motion",
  "Niente amichevoli da copertina. Solo il lavoro che ottobre chiederà.": "No showcase scrimmages. Just the work October will ask for.",
  "Tre settimane sporche. A ottobre si vedrà se sono bastate.": "Three dirty weeks. October will tell if they were enough.",
  "Sudore senza testimoni. Il ruolo, a settembre, è un altro di un palmo.": "Sweat with no witnesses. By September, your role has shifted a little.",
  "Hai chiuso luglio in palestra. Lo staff, a settembre, lo capisce dal passo.": "You closed out July in the gym. The staff can tell in September from your stride.",
  "Ripetizioni, specchio, nient'altro. Il ruolo, a ottobre, parla da solo.": "Reps, mirror, nothing else. In October, your role speaks for itself.",
  "L'estate, nuda: gli stessi tiri, lo stesso specchio, un polso che a settembre non è più una domanda.": "Summer, bare: the same shots, the same mirror, a wrist that by September is no longer a question.",
  "Hai tenuto il mestiere quando nessuno guardava. A ottobre il passo lo dice, senza che tu debba dichiararlo.": "You kept at the craft when nobody was watching. In October your stride says so, without you having to.",
  "Niente copertina. Il ruolo, a ottobre, è più stretto e più tuo.": "No cover. In October, your role is narrower and more yours.",
  "Luglio è restato in palestra. Settembre legge il passo, non le interviste.": "July stayed in the gym. September reads your stride, not the interviews.",
  "Estate di tregua, già spesa": "A summer of rest, already spent",
  "Ghiaccio, sonno, pazienza: tre settimane così": "Ice, sleep, patience: three weeks of it",
  "Il corpo ha chiesto tregua. Gliel'hai data": "Your body asked for a break. You gave it one",
  "Manutenzione, non vacanza. È andata così": "Maintenance, not vacation. That's how it went",
  "Estate di ghiaccio e pazienza, già spesa": "A summer of ice and patience, already spent",
  "La tregua del corpo, tenuta per intero": "Your body's break, taken in full",
  "Tre settimane di ghiaccio, già chiuse": "Three weeks of ice, already done",
  "Tregua del corpo, già firmata": "Your body's break, already signed",
  "Sonno, ghiaccio, un luglio tenuto": "Sleep, ice, a July well kept",
  "Luglio è stato una stanza chiusa: ghiaccio, camminate, la pazienza che a vent'anni non avevi.": "July was a closed room: ice, walks, the patience you didn't have at twenty.",
  "Hai dormito, camminato, tornato. L'orgoglio, a quest'età, è arrivare a ottobre intero.": "You slept, walked, came back. Pride, at this age, is reaching October in one piece.",
  "La tregua non è stata pigrizia. È la forma più adulta del lavoro, e l'hai tenuta.": "The break wasn't laziness. It's the most grown-up form of work, and you stuck to it.",
  "Il corpo ha chiesto tregua. Gliel'hai data, a pezzi, come si dà da bere a qualcuno che non deve spegnersi.": "Your body asked for a break. You gave it one, in small sips, the way you give water to someone who mustn't fade.",
  "Estate corta. Pesi leggeri, sonno lungo, un fisioterapista che ormai conosce i tuoi silenzi, e non li traduce.": "A short summer. Light weights, long sleep, a physio who by now knows your silences, and doesn't translate them.",
  "Arrivare a ottobre intero: a quest'età è l'unico orgoglio che conta, e tu l'hai tenuto senza dichiararlo.": "Reaching October in one piece: at this age it's the only pride that counts, and you kept it without announcing it.",
  "Hai dato al corpo ciò che a vent'anni chiamavi pigrizia. Adesso è mestiere.": "You gave your body what at twenty you called laziness. Now it's craft.",
  "Manutenzione vera: camminate, sonno, niente teatro. Arrivi a ottobre in piedi.": "Real maintenance: walks, sleep, no theater. You reach October on your feet.",
  "Le articolazioni hanno avuto un luglio. A settembre non presentano il conto in anticipo.": "Your joints had a July. In September, they don't send the bill early.",
  "Laboratorio di tiro, tre settimane": "Shooting lab, three weeks",
  "Mille uscite, lo stesso specchio: estate chiusa così": "A thousand curls, the same mirror: that's how summer ended",
  "Il gesto, nudo, ripetuto fino ad agosto": "The motion, bare, repeated until August",
  "Palestra vuota, mille uscite, estate così": "Empty gym, a thousand curls, that kind of summer",
  "Estate sul polso, senza pubblico": "A summer on your wrist, no audience",
  "Lo specchio, il gesto, nient'altro: tre settimane": "The mirror, the motion, nothing else: three weeks",
  "Il polso, nudo, per tre settimane": "The wrist, bare, for three weeks",
  "Tiri, specchio, estate già spesa": "Shots, mirror, summer already spent",
  "Un laboratorio senza pubblico, già chiuso": "A lab with no audience, already done",
  "Hai ripetuto finché il polso ha smesso di essere una domanda.": "You repeated it until your wrist stopped being a question.",
  "Pochi testimoni, molti tiri. Il miglioramento, se c'è, non ha fatto rumore.": "Few witnesses, lots of shots. The improvement, if there is one, made no noise.",
  "Agosto è stato una stanza senza pubblico. Meglio: si lavorava sul vero.": "August was a room with no audience. Better: you worked on the real thing.",
  "Tre volte al giorno, la stessa uscita. A settembre il gesto è un altro.": "Three times a day, the same curl. By September, the motion is different.",
  "Mille uscite, lo stesso specchio. Il polso, a settembre, non è più una domanda.": "A thousand curls, the same mirror. By September, your wrist is no longer a question.",
  "Palestra vuota, il gesto nudo. A ottobre lo staff lo capisce dal polso.": "Empty gym, the motion bare. In October the staff can tell from your wrist.",
  "Hai contato le uscite, non i filmati. A settembre il gesto è più corto e più vero.": "You counted curls, not clips. By September the motion is shorter and truer.",
  "Il laboratorio ha avuto un agosto. Lo staff, al primo allenamento, lo legge dal polso.": "The lab had its August. At the first practice, the staff reads it in your wrist.",
  "Niente amichevoli. Solo ripetizioni, e un ferro che a ottobre non chiede più il nome.": "No scrimmages. Just reps, and a rim that by October no longer asks your name.",
  "Finestra della tua Nazionale, già giocata": "National-team window, already played",
  "Tre gare, un aereo, un'altra maglia: estate così": "Three games, a flight, another jersey: that kind of summer",
  "La maglia che non sta nel contratto, indossata": "The jersey that's not in the contract, worn",
  "Tre sere per il tuo paese, già giocate": "Three nights for your country, already played",
  "Un'altra maglia, un luglio già chiuso": "Another jersey, a July already done",
  "La maglia che non paga i minuti, indossata": "The jersey that doesn't pay for minutes, worn",
  "Tre gare per il paese, già chiuse": "Three games for your country, already done",
  "La finestra azzurra, già giocata": "The national-team window, already played",
  "Un luglio in un'altra maglia, tenuto": "A July in another jersey, well kept",
  "Tre gare, un fuso, un orgoglio che non sta nel referto. Sei tornato.": "Three games, a time zone, a pride that doesn't fit in the box score. You're back.",
  "Sei tornato con le gambe pesanti e la testa più larga. Il club ha fatto due conti.": "You came back with heavy legs and a broader mind. The club did the math.",
  "Un'altra lingua in panchina. Il blocco e uscita, però, era lo stesso.": "Another language on the bench. The pick-and-pop, though, was the same.",
  "La maglia che non sta nel contratto, indossata. Tre gare, e sei tornato.": "The jersey that's not in the contract, worn. Three games, and you're back.",
  "Un aereo, tre gare, un'altra maglia. Il club, a settembre, fa due conti.": "A flight, three games, another jersey. The club does the math in September.",
  "La tua Nazionale non paga i minuti di club. Paga un altro debito, e tu lo sai.": "Your national team doesn't pay for club minutes. It pays another debt, and you know it.",
  "Tre sere per il paese. Il club, a settembre, conta le gambe, non i titoli.": "Three nights for your country. In September the club counts legs, not headlines.",
  "Hai indossato un'altra maglia. Sei tornato con la testa più larga, e basta.": "You wore another jersey. You came back with a broader mind, and that's it.",
  "La finestra, già giocata. Un debito diverso, e tu lo hai pagato senza dichiararlo.": "The window, already played. A different debt, and you paid it without announcing it.",
  "Un torneo estivo, asfalto, nient'altro: è successo": "A summer tournament, asphalt, nothing else: it happened",
  "Partite vere, senza staff, già giocate": "Real games, no staff, already played",
  "Un palazzetto piccolo, una fame grande, un luglio": "A small gym, a big hunger, one July",
  "Estate sul cemento, già chiusa": "A summer on concrete, already done",
  "Un torneo senza minutaggi, già giocato": "A tournament with no minutes count, already played",
  "Fame da palazzetto piccolo, tenuta": "Small-gym hunger, kept",
  "Asfalto, un luglio già speso": "Asphalt, a July already spent",
  "Un torneo vero, senza copertina": "A real tournament, no cover",
  "Cemento, fame, estate già chiusa": "Concrete, hunger, summer already done",
  "Sudore diverso. Ti ha ricordato perché hai cominciato, e quanto costa continuare.": "A different kind of sweat. It reminded you why you started, and what it costs to keep going.",
  "Niente minutaggi. Solo tiri, e un pubblico che non ti doveva niente.": "No minutes count. Just shots, and a crowd that owed you nothing.",
  "Sei tornato con le mani segnate e un gesto un po' più tuo.": "You came back with marked hands and a motion a little more your own.",
  "Un palazzetto piccolo, una fame grande. Il gesto, lì, è tornato a essere solo un gesto.": "A small gym, a big hunger. The motion, there, went back to being just a motion.",
  "Partite vere, senza staff. Sudore diverso, e una fame che a volte si era spenta.": "Real games, no staff. A different kind of sweat, and a hunger that had sometimes faded.",
  "Asfalto, un pubblico che non ti doveva niente. Tu hai tirato lo stesso.": "Asphalt, a crowd that owed you nothing. You shot anyway.",
  "Un torneo senza copertina. Le mani, a settembre, sono segnate, e il gesto è più tuo.": "A tournament with no cover. By September your hands are marked, and the motion is more yours.",
  "Cemento, un luglio. Ti ha ricordato il primo tiro, e quanto costa ancora.": "Concrete, one July. It reminded you of your first shot, and what it still costs.",
  "Senza staff, senza minuti. Solo il gesto, e una fame che a volte si era spenta.": "No staff, no minutes. Just the motion, and a hunger that had sometimes faded.",
  "Un filmato in palestra ha fatto il giro": "A clip from the gym went viral",
  "L'estate è finita su un telefono": "The summer ended on a phone",
  "Filmati estivi, lavoro vero sotto: è andata così": "Summer clips, real work underneath: that's how it went",
  "Una sequenza, troppi occhi, estate così": "A highlight reel, too many eyes, that kind of summer",
  "Troppi occhi su un telefono, luglio chiuso": "Too many eyes on a phone, July done",
  "Hai spento la telecamera, estate così": "You turned off the camera, that kind of summer",
  "Una sequenza virale, lavoro sotto": "A viral highlight reel, work underneath",
  "Il filmato ha girato, tu sei rimasto": "The clip went around, you stayed put",
  "Estate da telefono, già spenta": "A summer on a phone, already switched off",
  "I numeri sotto al filmato non contavano. Contava se a ottobre il gesto è ancora tuo.": "The numbers under the clip didn't matter. What mattered was whether the motion is still yours in October.",
  "Qualcuno in spogliatoio ha già visto la sequenza. Tu hai fatto finta di no, e hai tirato ancora.": "Someone in the locker room has already seen the clip. You pretended not to notice, and kept shooting.",
  "La fame, filmata. Poi hai spento il telefono e sei rimasto, e il gesto, senza pubblico, è tornato tuo.": "Hunger, filmed. Then you turned off your phone and stayed, and the motion, with no audience, became yours again.",
  "Troppi occhi su un telefono. Tu hai spento, e il lavoro, sotto, è rimasto lo stesso di sempre.": "Too many eyes on a phone. You switched off, and the work underneath stayed the same as ever.",
  "Un gesto è uscito dal palazzetto. Tu sei rimasto dentro, che è più raro.": "One move left the gym. You stayed inside, which is rarer.",
  "La rete ha trovato un tuo possesso. L'inverno, poi, chiede gli altri settantanove.": "The internet found one of your possessions. Winter, then, asks for the other seventy-nine.",
  "Hai spento la telecamera. Il gesto, senza pubblico, è tornato tuo.": "You turned off the camera. The motion, with no audience, became yours again.",
  "Un filmato, troppi occhi. Il lavoro, sotto, è rimasto lo stesso di sempre.": "One clip, too many eyes. The work underneath stayed the same as ever.",
  "La fame filmata, poi il silenzio. A ottobre il gesto è ancora tuo, o no.": "Hunger filmed, then silence. In October the motion is still yours, or it isn't.",
  "Due settimane di tregua, già prese": "Two weeks of rest, already taken",
  "Silenzio di luglio, tenuto": "July silence, kept",
  "Hai spento tutto, due settimane": "You switched everything off, for two weeks",
  "Tregua di luglio, già spesa": "A July break, already spent",
  "Il telefono in borsa, due settimane": "Phone in the bag, two weeks",
  "Estate spenta, e basta": "Summer switched off, and that's it",
  "Due settimane senza schema, già prese": "Two weeks without a game plan, already taken",
  "Luglio spento, tenuto intero": "July switched off, kept whole",
  "Tregua nuda, già firmata": "A bare break, already signed",
  "Un'estate corta di lavoro, lunga di sonno. Novembre, poi, ti trova in piedi.": "A summer short on work, long on sleep. November then finds you on your feet.",
  "Il telefono è rimasto in borsa. Il corpo, per una volta, non ha chiesto scusa.": "The phone stayed in the bag. Your body, for once, didn't apologize.",
  "Niente trekking, niente show. Solo la manutenzione di ciò che resta.": "No trekking, no show. Just maintenance of what's left.",
  "Due settimane di tregua, già prese. Il corpo, per una volta, ringrazia in silenzio.": "Two weeks of rest, already taken. Your body, for once, says thanks in silence.",
  "Hai spento tutto. Novembre ti trova in piedi, senza dichiararlo.": "You switched everything off. November finds you on your feet, without announcing it.",
  "Silenzio di luglio, tenuto. Il giorno dopo il tiro, stranamente, è uscito più pulito.": "July silence, kept. The next day your shot, strangely, came out cleaner.",
  "Due settimane senza schema. Il corpo ha ringraziato senza chiedere scusa.": "Two weeks without a game plan. Your body said thanks without apologizing.",
  "Hai spento il mestiere. A settembre il tiro, stranamente, è uscito più pulito.": "You switched off the craft. In September your shot, strangely, came out cleaner.",
  "Tregua nuda. Novembre ti trova in piedi, e questo basta.": "A bare break. November finds you on your feet, and that's enough.",
  "Il corpo, rimesso a pezzi in estate": "Your body, put back together over the summer",
  "Sala, cucina, nient'altro: tre settimane così": "Weight room, kitchen, nothing else: three weeks of it",
  "Meno chili, o più. Il mestiere ha deciso.": "Fewer kilos, or more. The craft decided.",
  "Estate di bilancia e di sonno": "A summer of scales and sleep",
  "Tre settimane sul corpo, già spese": "Three weeks on your body, already spent",
  "Lo specchio, giudice, un luglio": "The mirror as judge, one July",
  "Bilancia, sonno, estate già spesa": "Scales, sleep, summer already spent",
  "Il corpo, rimesso, un luglio tenuto": "Your body, rebuilt, a July well kept",
  "Sala e cucina, tre settimane chiuse": "Weight room and kitchen, three weeks done",
  "Lo specchio è stato un giudice onesto. A settembre il primo passo è un altro.": "The mirror was an honest judge. By September your first step is different.",
  "Niente filmati. Solo i numeri sulla bilancia, e un fisioterapista che ormai ti conosce.": "No clips. Just the numbers on the scale, and a physio who knows you by now.",
  "Lavoro sporco. Il contatto, a ottobre, lo sente prima la difesa avversaria.": "Dirty work. In October, the opposing defense feels the contact first.",
  "Il corpo, rimesso a pezzi. A ottobre il primo contatto è tuo, non del fisioterapista.": "Your body, put back together. In October the first contact is yours, not the physio's.",
  "Sala, cucina, nient'altro. A settembre il primo passo è un altro.": "Weight room, kitchen, nothing else. By September your first step is different.",
  "Hai messo peso dove serve. Il resto, a settembre, è un negoziato più corto.": "You put weight where it's needed. The rest, in September, is a shorter negotiation.",
  "Tre settimane sul corpo. A ottobre il primo contatto è tuo.": "Three weeks on your body. In October the first contact is yours.",
  "La bilancia ha detto la sua. Tu hai firmato, e il primo passo, a settembre, è un altro.": "The scale had its say. You signed off, and by September your first step is different.",
  "Niente copertina. Solo chili, sonno, un contatto che a ottobre è tuo.": "No cover. Just kilos, sleep, a contact that in October is yours.",
  "Estate passata in sala video": "A summer spent in the film room",
  "I possessi degli altri, a volume basso, per settimane": "Other people's possessions, volume down, for weeks",
  "Schemi, studio avversari, una matita: estate così": "Playbooks, opponent scouting, a pencil: that kind of summer",
  "Una stanza buia, i possessi riletti, già chiusa": "A dark room, possessions reviewed, already done",
  "Estate in una stanza buia, già chiusa": "A summer in a dark room, already done",
  "I possessi riletti, un luglio tenuto": "Possessions reviewed, a July well kept",
  "Sala video, matita, nient'altro": "Film room, pencil, nothing else",
  "Tre settimane di schemi, già spese": "Three weeks of playbooks, already spent",
  "Luglio sui filmati, senza pubblico": "July on film, no audience",
  "Niente sudore da copertina. A ottobre le letture arriveranno un tempo prima.": "No cover-worthy sweat. In October your reads will come a beat earlier.",
  "Hai riletto una serie. Hai trovato un possesso che non avevi visto. Basta quello.": "You reviewed a series. You found a possession you hadn't seen. That's enough.",
  "Lo staff, a settembre, trova gli appunti già fatti. Non è gloria. È mestiere.": "In September, the staff finds the notes already done. It's not glory. It's craft.",
  "Una stanza, una matita, i possessi che nessuno taglia. A ottobre le letture arrivano un tempo prima.": "A room, a pencil, the possessions nobody cuts. In October your reads come a beat earlier.",
  "Estate in una stanza buia. I possessi degli altri, a volume basso, e tu che annoti.": "A summer in a dark room. Other people's possessions, volume down, and you taking notes.",
  "Niente sudore da copertina. A ottobre le letture arriveranno un tempo prima, e nessuno chiederà perché.": "No cover-worthy sweat. In October your reads will come a beat earlier, and nobody will ask why.",
  "Hai riletto una serie. Hai trovato un possesso che non avevi visto. Lo tieni per l'inverno.": "You reviewed a series. You found a possession you hadn't seen. You keep it for the winter.",
  "Tre settimane di filmati. Lo staff, a settembre, trova gli appunti già fatti.": "Three weeks of film. In September, the staff finds the notes already done.",
  "Una matita, una stanza, i possessi. A ottobre le letture arrivano un tempo prima.": "A pencil, a room, the possessions. In October your reads come a beat earlier.",
  "Un documentario, o quasi: è uscito": "A documentary, or almost: it came out",
  "Microfoni d'estate, già spenti": "Summer microphones, already switched off",
  "La voce, fuori dal parquet, usata": "Your voice, off the court, put to use",
  "Due interviste, niente più: estate così": "Two interviews, no more: that kind of summer",
  "Hai parlato poco, e l'estate è passata": "You said little, and the summer passed",
  "La voce, usata fuori, già spenta": "Your voice, used off the court, already switched off",
  "Due microfoni, poi il silenzio": "Two microphones, then silence",
  "Parlato poco, luglio già chiuso": "You said little, July already done",
  "La voce fuori, già spesa": "Your voice off the court, already spent",
  "Hai parlato. Non troppo. I titoli hanno scelto tre frasi; tu ne avevi dette dieci.": "You talked. Not too much. The headlines picked three sentences; you had said ten.",
  "L'estate è diventata un racconto. Il lavoro, sotto, è continuato comunque.": "The summer became a story. The work underneath kept going anyway.",
  "Qualche credito in più, in conferenza. In palestra, lo stesso sudore.": "A bit more credit at press conferences. In the gym, the same sweat.",
  "Due interviste, niente più. Il mestiere, stavolta, è stato non diventare un titolo.": "Two interviews, no more. The craft, this time, was not becoming a headline.",
  "Hai parlato poco. I giorni, senza microfono, sono tornati tuoi.": "You said little. The days, without a microphone, became yours again.",
  "Microfoni d'estate, già spenti. In palestra, lo stesso sudore.": "Summer microphones, already switched off. In the gym, the same sweat.",
  "Due microfoni, poi il silenzio. Il mestiere è stato non diventare un titolo.": "Two microphones, then silence. The craft was not becoming a headline.",
  "Hai parlato poco. I giorni senza microfono sono tornati tuoi, e il sudore è lo stesso.": "You said little. The days without a microphone became yours again, and the sweat is the same.",
  "La voce, usata fuori, già spenta. In palestra, lo stesso lavoro.": "Your voice, used off the court, already switched off. In the gym, the same work.",
  "Il tuo nome ha girato tutto luglio": "Your name made the rounds all July",
  "Voci di scambio, tutta l'estate": "Trade rumors, all summer",
  "La dirigenza ha fatto i conti. I tuoi no": "The front office did the math. You didn't",
  "Una piazza nuova sul foglio, già nominata": "A new city on paper, already named",
  "L'estate è stata un corridoio di voci": "The summer was a hallway of rumors",
  "Il mercato ti ha mosso, almeno a parole": "The market moved you, at least in words",
  "Uno scambio, parlato sopra la tua testa": "A trade, discussed over your head",
  "Il nome, girato, un luglio tenuto": "Your name, passed around, a July well kept",
  "Voci di piazza, già ascoltate": "Rumors about a new city, already heard",
  "Non eri al tavolo. {0} ({1}) è nel foglio, e il mercato ha parlato sopra la tua testa.": "You weren't at the table. {0} ({1}) is on the sheet, and the market talked over your head.",
  "Voci, smentite, un silenzio. A {0} qualcuno ha fatto il tuo nome; a settembre l'armadietto è ancora tuo.": "Rumors, denials, a silence. In {0} someone mentioned your name; in September the locker is still yours.",
  "Qualcuno ha scritto {0} ({1}) sul foglio. Tu hai fatto la valigia, poi l'hai disfatta. Per ora.": "Someone wrote {0} ({1}) on the sheet. You packed your bag, then unpacked it. For now.",
  "{0} è una piazza vera, non una voce. L'estate l'ha nominata; tu non sei stato al tavolo.": "{0} is a real destination, not a rumor. The summer named it; you weren't at the table.",
  "A {0} ({1}) il tuo nome è uscito da un ufficio. Tu hai tenuto il mestiere, e la valigia semiaperta.": "In {0} ({1}) your name came out of an office. You kept at the craft, and your bag half-packed.",
  "Il foglio dice {0}. Non è un addio: è un'estate in cui la piazza ha un altro nome, e tu lo sai.": "The sheet says {0}. It's not a goodbye: it's a summer in which the city has another name, and you know it.",
  "La dirigenza ha fatto i conti. I tuoi no. {0} ({1}) resta nel foglio, come una porta socchiusa.": "The front office did the math. You didn't. {0} ({1}) stays on the sheet, like a door left ajar.",
  "{0}: una piazza, un corridoio, un'altra insegna. Per ora è solo una frase, e pesa lo stesso.": "{0}: a city, a hallway, another logo. For now it's just a sentence, and it weighs all the same.",
  "Voci, un silenzio, {0}. L'armadietto, a settembre, sa ancora di attesa.": "Rumors, a silence, {0}. The locker, in September, still smells of waiting.",
  "Una chiamata da Europa, già arrivata": "A call from Europe, already received",
  "Un agente, un fuso, un'altra idea di giugno": "An agent, a time zone, another idea of June",
  "L'ultimo atto, nominato, non firmato": "The last act, named, not signed",
  "Una porta, socchiusa, in un'altra lingua": "A door, ajar, in another language",
  "Europa, nominata, non firmata": "Europe, named, not signed",
  "Un altro fuso, la stessa palla, un luglio": "Another time zone, the same ball, one July",
  "Una porta europea, già nominata": "A European door, already named",
  "L'ultimo atto, ascoltato, non firmato": "The last act, heard out, not signed",
  "Un fuso, una voce, un luglio tenuto": "A time zone, a voice, a July well kept",
  "Non è stato un addio. È una porta, socchiusa, in un'altra lingua. Resta sul tavolo.": "It wasn't a goodbye. It's a door, ajar, in another language. It stays on the table.",
  "Palazzetti più piccoli, tattica più stretta. Te lo hanno detto piano, come un rispetto.": "Smaller arenas, tighter tactics. They told you softly, as a form of respect.",
  "Un ultimo atto diverso. Il ruolo, la voce, poi — se serve — l'Europa.": "A different last act. Role, voice, then — if needed — Europe.",
  "Una voce da un altro fuso. Non hai firmato. Hai ascoltato. L'inverno, poi, deciderà.": "A voice from another time zone. You didn't sign. You listened. Winter will decide.",
  "Europa resta una frase, per ora. Una frase che a quest'età pesa.": "Europe stays a sentence, for now. A sentence that weighs at this age.",
  "Una chiamata, nominata, non firmata. Il ruolo, qui, viene prima.": "A call, named, not signed. The role, here, comes first.",
  "Una porta in un'altra lingua. Resta sul tavolo, e pesa.": "A door in another language. It stays on the table, and it weighs.",
  "Non hai firmato. Hai ascoltato. L'inverno, poi, deciderà se quella porta serve.": "You didn't sign. You listened. Winter will decide whether that door is needed.",
  "Palazzetti più stretti, un ultimo atto nominato. Per ora è solo una frase.": "Tighter arenas, a last act named. For now it's just a sentence.",
  "Due settimane da uno specialista, alle spalle": "Two weeks with a specialist, behind you",
  "Un maestro, una palestra vuota, un luglio": "A mentor, an empty gym, one July",
  "Il gesto, corretto di un grado": "The motion, corrected by one degree",
  "Estate da specialista, già chiusa": "A summer with a specialist, already done",
  "Un grado sul gesto, tenuto": "One degree on the motion, kept",
  "Due settimane, un maestro, nient'altro": "Two weeks, a mentor, nothing else",
  "Luglio su un gesto solo, già speso": "July on a single motion, already spent",
  "Una correzione, tenuta, un luglio": "A correction, kept, one July",
  "Il maestro, il gesto, estate chiusa": "The mentor, the motion, summer done",
  "Niente telecamere. Un uomo, una palla, una correzione che tieni per l'inverno.": "No cameras. A man, a ball, a correction you keep for the winter.",
  "Il tiro è cambiato di un grado. Le gare, a ottobre, no — e questo è il punto.": "Your shot changed by one degree. The games, in October, didn't — and that's the point.",
  "Sei tornato con una uscita nuova. Lo staff la vede al primo allenamento.": "You came back with a new set. The staff sees it at the first practice.",
  "Un gesto solo, ripetuto fino a settembre. Lo staff lo vede prima del tabellone.": "A single motion, repeated until September. The staff sees it before the scoreboard does.",
  "Hai stretto il mestiere a una cosa. A ottobre quella cosa tiene.": "You narrowed the craft to one thing. In October that thing holds.",
  "Due settimane da uno specialista. Una correzione, tenuta, e il resto è rumore.": "Two weeks with a specialist. One correction, kept, and the rest is noise.",
  "Una correzione, un grado. A ottobre lo staff lo legge dal polso, non dalla copertina.": "One correction, one degree. In October the staff reads it in your wrist, not on a cover.",
  "Palestra vuota, un maestro. Il gesto, a settembre, è un altro di un palmo.": "An empty gym, a mentor. By September the motion has changed a little.",
  "Hai tenuto la correzione. Il resto, a ottobre, è rumore.": "You kept the correction. The rest, in October, is noise.",
  "Un campus, i ragazzi, la voce: estate così": "A camp, the kids, your voice: that kind of summer",
  "Hai insegnato, e il gesto è tornato": "You taught, and the motion came back",
  "Estate da tutore, già chiusa": "A summer as a mentor, already done",
  "Ragazzi, un ferro, tre giorni già chiusi": "Kids, a rim, three days already done",
  "Hai corretto un polso, estate così": "You fixed a wrist, that kind of summer",
  "La voce da tutore, già spesa": "Your mentor's voice, already spent",
  "Tre giorni da tutore, già chiusi": "Three days as a mentor, already done",
  "I ragazzi, la voce, un luglio tenuto": "The kids, your voice, a July well kept",
  "Un campus, già archiviato": "A camp, already filed away",
  "Hai corretto un polso. Il ragazzo ha fatto canestro. Qualcosa si è chiuso, in pace.": "You fixed a wrist. The kid scored. Something settled, at peace.",
  "La voce, usata così, è valsa più di un giro in più in sala pesi.": "Your voice, used this way, was worth more than one more round in the weight room.",
  "Sei tornato con le mani meno dure e la testa più chiara. Il ruolo, adesso, include questo.": "You came back with softer hands and a clearer head. Your role, now, includes this.",
  "Ragazzini, un ferro storto, tre giorni. Sei tornato con le mani più calme.": "Little kids, a crooked rim, three days. You came back with calmer hands.",
  "Hai insegnato un'uscita. Per una settimana il tuo gesto è stato più pulito.": "You taught a set. For a week your own motion was cleaner.",
  "Un campus, i ragazzi, la voce. Hai insegnato, e il gesto è tornato.": "A camp, the kids, your voice. You taught, and the motion came back.",
  "Tre giorni da tutore. La voce, usata così, vale più di un giro in sala pesi.": "Three days as a mentor. Your voice, used this way, is worth more than a round in the weight room.",
  "Hai corretto un polso. Il gesto, il tuo, è tornato più pulito.": "You fixed a wrist. Your own motion came back cleaner.",
  "I ragazzi, un ferro. Sei tornato con le mani più calme, e la testa più chiara.": "The kids, a rim. You came back with calmer hands, and a clearer head.",
  "Il carico, misurato e già firmato": "The workload, measured and already signed off",
  "Meno chili sulla barra, più anni": "Fewer kilos on the bar, more years",
  "Il fisioterapista ha vinto la discussione": "The physio won the argument",
  "Volume misurato, luglio già chiuso": "Measured volume, July already done",
  "Due sedute in meno, già decise": "Two fewer sessions, already decided",
  "Il carico, trattato da adulto": "The workload, handled like a grown-up",
  "Carico misurato, già firmato": "Measured workload, already signed off",
  "Due sedute tagliate, un luglio tenuto": "Two sessions cut, a July well kept",
  "Il volume, trattato da adulto": "The volume, handled like a grown-up",
  "Non è stata pigrizia. È un calendario che arriva a maggio, se lo tratti da adulto.": "It wasn't laziness. It's a calendar that lasts until May, if you handle it like a grown-up.",
  "Hai tagliato due sedute. Il tendine, a ottobre, non presenta il conto in anticipo.": "You cut two sessions. In October, your tendon doesn't send the bill early.",
  "Lo staff ha firmato il programma. Tu hai firmato il sonno.": "The staff signed off on the program. You signed off on sleep.",
  "Carico vero, non da copertina. A settembre le gambe arrivano già scritte.": "A real workload, not a cover-worthy one. By September your legs arrive already written.",
  "Hai tenuto il volume. Ottobre, poi, non chiede una prova: chiede continuità.": "You kept the volume. October, then, doesn't ask for proof: it asks for consistency.",
  "Meno chili sulla barra, più anni. Il fisioterapista ha vinto, e tu hai firmato.": "Fewer kilos on the bar, more years. The physio won, and you signed off.",
  "Due sedute in meno. Il tendine, a ottobre, non presenta il conto in anticipo.": "Two fewer sessions. In October, your tendon doesn't send the bill early.",
  "Il carico, trattato da adulto. A settembre le gambe arrivano già scritte.": "The workload, handled like a grown-up. By September your legs arrive already written.",
  "Hai firmato il sonno. Ottobre non chiede una prova: chiede continuità.": "You signed off on sleep. October doesn't ask for proof: it asks for consistency.",
  "Ritiro breve: tre giorni, troppi occhi, già finito": "A short camp: three days, too many eyes, already over",
  "Un invito estivo, una gerarchia nuova": "A summer invitation, a new pecking order",
  "Ti hanno guardato. Tu hai tirato.": "They watched you. You shot.",
  "Tre giorni, troppi occhi, già finiti": "Three days, too many eyes, already over",
  "Ritiro breve, già archiviato": "A short camp, already filed away",
  "Un invito, tre sessioni, nient'altro": "An invitation, three sessions, nothing else",
  "Tre giorni di ritiro, già chiusi": "Three days of camp, already done",
  "Un invito estivo, già archiviato": "A summer invitation, already filed away",
  "Troppi occhi, tre sessioni, estate così": "Too many eyes, three sessions, that kind of summer",
  "Niente contratto in palio, e invece sì: i minuti di ottobre si decidono anche così.": "No contract on the line, and yet there was: October minutes get decided this way too.",
  "Due possessi puliti, uno sporco. Lo staff ha preso appunti. Tu hai fatto finta di non vederli.": "Two clean possessions, one dirty. The staff took notes. You pretended not to see them.",
  "Sei tornato più stanco e più visibile. È il mestiere, a quest'età.": "You came back more tired and more visible. That's the craft, at this age.",
  "Ritiro breve, poche sessioni, niente teatro. Lo staff ha preso nota del passo.": "A short camp, few sessions, no theater. The staff took note of your stride.",
  "Tre giorni con i nuovi. Tu hai tenuto il tono, e basta.": "Three days with the new guys. You kept your tone, and that's it.",
  "Ti hanno guardato. Tu hai tirato. I minuti di ottobre si decidono anche così.": "They watched you. You shot. October minutes get decided this way too.",
  "Tre sessioni, troppi occhi. Lo staff ha preso nota del passo, e basta.": "Three sessions, too many eyes. The staff took note of your stride, and that's it.",
  "Un ritiro breve. I minuti di ottobre si decidono anche così, e tu lo sai.": "A short camp. October minutes get decided this way too, and you know it.",
  "Poche sessioni, niente teatro. Tu hai tenuto il tono, e lo staff ha preso appunti.": "Few sessions, no theater. You kept your tone, and the staff took notes.",
  "Due settimane in quota, già scese": "Two weeks at altitude, already back down",
  "Aria sottile, gambe dure, un luglio così": "Thin air, hard legs, that kind of July",
  "L'estate è finita più in alto del parquet": "The summer ended higher up than the hardwood",
  "Estate in quota, già scesa": "A summer at altitude, already back down",
  "Due settimane d'aria sottile": "Two weeks of thin air",
  "Luglio più in alto del parquet": "July, higher up than the hardwood",
  "Quota, fiato corto, estate già scesa": "Altitude, short breath, summer already back down",
  "Due settimane d'aria, già scese": "Two weeks of air, already back down",
  "In alto, un luglio tenuto": "Up high, a July well kept",
  "Hai corso dove l'aria manca. A ottobre il primo contropiede è più lungo, e tu lo sai.": "You ran where the air runs short. In October your first fast break is longer, and you know it.",
  "Niente pubblico, solo il fiato corto. Il corpo, a settembre, ha un altro serbatoio.": "No audience, just short breath. By September your body has a bigger tank.",
  "Due settimane in quota. Sei sceso più magro e più cattivo, nel modo giusto.": "Two weeks at altitude. You came down leaner and meaner, in the right way.",
  "Due settimane in quota. Sei sceso con un altro serbatoio, e ottobre lo sentirà.": "Two weeks at altitude. You came down with a bigger tank, and October will feel it.",
  "Aria sottile, gambe dure. Il primo contropiede di ottobre è più lungo.": "Thin air, hard legs. October's first fast break is longer.",
  "L'estate è finita più in alto del parquet. Sei sceso con un altro fiato.": "The summer ended higher up than the hardwood. You came down with different lungs.",
  "Aria sottile. Sei sceso con un altro serbatoio, e ottobre lo sentirà.": "Thin air. You came down with a bigger tank, and October will feel it.",
  "Hai corso in quota. Il primo contropiede di ottobre è più lungo, e tu lo sai.": "You ran at altitude. October's first fast break is longer, and you know it.",
  "Niente pubblico, solo il fiato. Sei sceso più magro, nel modo giusto.": "No audience, just your breath. You came down leaner, in the right way.",
  "Una gara di beneficenza, già giocata": "A charity game, already played",
  "Un palazzetto pieno per altro, un luglio": "An arena packed for something else, one July",
  "Hai messo la maglia per qualcuno, non per te": "You wore the jersey for someone else, not for you",
  "Una sera per altri, già giocata": "A night for others, already played",
  "Niente classifica, un luglio tenuto": "No standings, a July well kept",
  "Maglia per qualcuno, estate così": "A jersey for someone else, that kind of summer",
  "Una serata per altri, già chiusa": "An evening for others, already done",
  "Beneficenza, già giocata, un luglio": "Charity, already played, one July",
  "Il gesto per qualcuno, tenuto": "The motion for someone else, kept",
  "Hai giocato per altri. Il gesto è rimasto tuo, la sera è stata di qualcun altro.": "You played for others. The motion stayed yours; the night belonged to someone else.",
  "Un palazzetto pieno, niente classifica. Sei tornato più leggero, e lo staff lo ha letto nel passo.": "A packed arena, no standings. You came back lighter, and the staff read it in your stride.",
  "Niente minuti da copertina. Una serata che non sta nel contratto, e l'hai tenuta.": "No cover-worthy minutes. An evening that isn't in the contract, and you kept it.",
  "Hai messo la maglia per qualcuno, non per te. Il gesto è rimasto tuo.": "You wore the jersey for someone else, not for you. The motion stayed yours.",
  "Una gara di beneficenza, già giocata. Sei tornato più leggero.": "A charity game, already played. You came back lighter.",
  "Niente classifica. Una serata per altri, e il passo, a settembre, è più calmo.": "No standings. An evening for others, and by September your stride is calmer.",
  "Una serata per altri. Il gesto è rimasto tuo, e lo staff lo ha letto nel passo.": "An evening for others. The motion stayed yours, and the staff read it in your stride.",
  "Niente classifica, una maglia per qualcuno. Sei tornato più leggero.": "No standings, a jersey for someone else. You came back lighter.",
  "Hai giocato per altri. A settembre il passo è più calmo, e questo basta.": "You played for others. By September your stride is calmer, and that's enough.",
  "Due settimane a casa, già prese": "Two weeks at home, already taken",
  "La tavola di luglio, tenuta": "The July dinner table, kept",
  "Sei tornato dove il mestiere non entra": "You went back to where the craft doesn't reach",
  "Casa, luglio, già fatti": "Home, July, already done",
  "Due settimane lontano dal mestiere": "Two weeks away from the craft",
  "Estate a tavola, senza schemi": "A summer at the table, no playbooks",
  "Sei tornato a casa, e basta": "You went home, and that's it",
  "Tavola, silenzio, un luglio tenuto": "Table, silence, a July well kept",
  "Due settimane a casa, già chiuse": "Two weeks at home, already done",
  "Hai spento il mestiere due settimane. A settembre il tiro è uscito più pulito, stranamente.": "You switched off the craft for two weeks. In September your shot came out cleaner, strangely.",
  "Casa, tavola, silenzio. Il corpo ha ringraziato senza chiedere scusa.": "Home, table, silence. Your body said thanks without apologizing.",
  "Niente schemi. Solo volti che non votano i minuti. Sei tornato più intero.": "No playbooks. Just faces that don't vote on minutes. You came back more whole.",
  "Due settimane a casa. Il mestiere, spento, ti ha restituito un pezzo di te.": "Two weeks at home. The craft, switched off, gave you back a piece of yourself.",
  "La tavola di luglio, tenuta. A settembre il tiro è uscito più pulito.": "The July dinner table, kept. In September your shot came out cleaner.",
  "Sei tornato dove il mestiere non entra. Poi sei rientrato più intero.": "You went back to where the craft doesn't reach. Then you came back more whole.",
  "Due settimane lontano. Il corpo ha ringraziato, e il tiro, a settembre, è uscito più pulito.": "Two weeks away. Your body said thanks, and in September your shot came out cleaner.",
  "Casa, silenzio. Sei tornato più intero, senza dichiararlo.": "Home, silence. You came back more whole, without announcing it.",
  "Niente schemi, solo volti. A settembre il mestiere è più tuo.": "No playbooks, just faces. By September the craft is more yours.",
  "Estate di mobilità, già fatta": "A summer of mobility, already done",
  "Anca, caviglia, nient'altro: tre settimane così": "Hip, ankle, nothing else: three weeks of it",
  "Il fisioterapista ha vinto, e tu hai firmato": "The physio won, and you signed off",
  "Tre settimane di gradi, già spese": "Three weeks of range of motion, already spent",
  "Estate sulle articolazioni, tenuta": "A summer on your joints, kept",
  "Anca e caviglia, un luglio paziente": "Hip and ankle, a patient July",
  "Gradi, non chili: estate già fatta": "Degrees, not kilos: summer already done",
  "Tre settimane articolari, già spese": "Three weeks on your joints, already spent",
  "Anca, caviglia, un luglio tenuto": "Hip, ankle, a July well kept",
  "Niente chili sulla barra. Solo gradi di movimento. A ottobre il primo passo è più lungo.": "No kilos on the bar. Just degrees of motion. In October your first step is longer.",
  "Hai lavorato dove non si vede. Le ginocchia, a novembre, non presentano il conto in anticipo.": "You worked where it doesn't show. In November, your knees don't send the bill early.",
  "Tre settimane di pazienza articolare. Il mestiere, a quest'età, passa di lì.": "Three weeks of joint patience. The craft, at this age, goes through there.",
  "Estate di gradi, non di chili. A ottobre il primo passo è più lungo.": "A summer of degrees, not kilos. In October your first step is longer.",
  "Anca, caviglia, nient'altro. Le ginocchia, a novembre, non presentano il conto.": "Hip, ankle, nothing else. In November, your knees don't send the bill.",
  "Il fisioterapista ha vinto, e tu hai firmato. A ottobre il passo è più lungo.": "The physio won, and you signed off. In October your stride is longer.",
  "Solo gradi di movimento. A ottobre il primo passo è più lungo, e le ginocchia tacciono.": "Just degrees of motion. In October your first step is longer, and your knees stay quiet.",
  "Tre settimane articolari. Il mestiere, a quest'età, passa di lì, e tu l'hai tenuto.": "Three weeks on your joints. The craft, at this age, goes through there, and you kept at it.",
  "Hai lavorato dove non si vede. A ottobre il passo è più lungo.": "You worked where it doesn't show. In October your stride is longer.",
  "Campetti, asfalto, un luglio già chiuso": "Playgrounds, asphalt, a July already done",
  "Partite vere senza staff, già giocate": "Real games without staff, already played",
  "Un ferro storto, una fame dritta, un'estate": "A crooked rim, a straight hunger, one summer",
  "Estate d'asfalto, già chiusa": "A summer on asphalt, already done",
  "Un ferro storto, tre sere, nient'altro": "A crooked rim, three nights, nothing else",
  "Fame da campetto, tenuta": "Playground hunger, kept",
  "Asfalto storto, un luglio tenuto": "Crooked asphalt, a July well kept",
  "Campetti, già giocati, estate così": "Playgrounds, already played, that kind of summer",
  "Un ferro, una fame, già chiusi": "A rim, a hunger, already done",
  "Asfalto storto, tabelloni che cantano. Ti ha ricordato perché hai cominciato, e quanto costa continuare.": "Crooked asphalt, rattling backboards. It reminded you why you started, and what it costs to keep going.",
  "Sei tornato con le mani segnate e un gesto un po' più tuo, senza testimoni da contratto.": "You came back with marked hands and a motion a little more your own, with no contract witnesses.",
  "Campetti, asfalto, un luglio già chiuso. Le mani, a settembre, sono segnate.": "Playgrounds, asphalt, a July already done. By September your hands are marked.",
  "Un ferro storto, una fame dritta. Sei tornato con un gesto un po' più tuo.": "A crooked rim, a straight hunger. You came back with a motion a little more your own.",
  "Partite vere senza staff. Sudore diverso, e una fame che a volte si era spenta.": "Real games without staff. A different kind of sweat, and a hunger that had sometimes faded.",
  "Asfalto, un ferro storto. Le mani, a settembre, sono segnate, e il gesto è più tuo.": "Asphalt, a crooked rim. By September your hands are marked, and the motion is more yours.",
  "Senza staff, solo tiri. Una fame dritta, e tu sei tornato con le mani segnate.": "No staff, just shots. A straight hunger, and you came back with marked hands.",
  "Campetti, un luglio. Ti ha ricordato perché hai cominciato, senza testimoni da contratto.": "Playgrounds, one July. It reminded you why you started, with no contract witnesses.",
  "Due giorni con gli arbitri, già fatti": "Two days with the referees, already done",
  "Il fischio, studiato da vicino, un luglio": "The whistle, studied up close, one July",
  "Estate sul regolamento, non sul gesto": "A summer on the rulebook, not the motion",
  "Due giorni di palmo, già letti": "Two days of signals, already read",
  "Il fischio da vicino, un luglio tenuto": "The whistle up close, a July well kept",
  "Regolamento, non gesto: estate così": "Rulebook, not motion: that kind of summer",
  "Due giorni di fischio, già letti": "Two days of whistles, already read",
  "Il palmo, studiato, un luglio chiuso": "The signal, studied, a July done",
  "Regolamento da vicino, già fatto": "The rulebook up close, already done",
  "Hai visto il contatto dall'altra sponda. A ottobre le mani sono più basse, e i fischi anche.": "You saw contact from the other side. In October your hands are lower, and so are the whistles.",
  "Due giorni di regolamento. Lo staff, a settembre, trova un giocatore che non discute il palmo: lo legge.": "Two days of rulebook. In September, the staff finds a player who doesn't argue the call: he reads it.",
  "Niente sudore da copertina. Una lettura del fischio che tiene per l'inverno.": "No cover-worthy sweat. A read of the whistle that holds for the winter.",
  "Due giorni con gli arbitri. A ottobre le mani sono più basse.": "Two days with the referees. In October your hands are lower.",
  "Il fischio, studiato da vicino. Lo staff trova un giocatore che legge il palmo.": "The whistle, studied up close. The staff finds a player who reads the call.",
  "Estate sul regolamento, non sul gesto. Una lettura che tiene per l'inverno.": "A summer on the rulebook, not the motion. A read that holds for the winter.",
  "Hai letto il palmo dall'altra sponda. A ottobre le mani sono più basse.": "You read the call from the other side. In October your hands are lower.",
  "Due giorni con gli arbitri. Una lettura del fischio che tiene per l'inverno.": "Two days with the referees. A read of the whistle that holds for the winter.",
  "Il regolamento, da vicino. Lo staff trova un giocatore che legge il palmo, non lo discute.": "The rulebook, up close. The staff finds a player who reads the call, not argues it.",
  "Estate corta. Pesi leggeri, sonno lungo, un fisioterapista che ormai conosce i tuoi silenzi.": "A short summer. Light weights, long sleep, a physio who by now knows your silences.",
  "La tregua del corpo è la forma più adulta del lavoro. L'hai tenuta, senza chiedere che qualcuno la chiami coraggio.": "Your body's break is the most grown-up form of work. You kept it, without asking anyone to call it courage.",
  "Estate sul ruolo, nient'altro. A settembre lo staff lo capisce dal passo, non dalle dichiarazioni.": "A summer on your role, nothing else. In September the staff can tell from your stride, not from statements.",
  "Hai lavorato il mestiere, non la copertina. Ottobre lo dirà prima di te.": "You worked on the craft, not the cover. October will say so before you do.",
  "Tre settimane di mestiere, già fatte. A ottobre il passo lo dice, senza che tu debba dichiararlo.": "Three weeks of craft, already done. In October your stride says so, without you having to.",
  "Hai tenuto il mestiere quando nessuno guardava. A ottobre il passo lo dice.": "You kept at the craft when nobody was watching. In October your stride says so.",
  "Una porta, socchiusa, in un'altra lingua. Resta sul tavolo.": "A door, ajar, in another language. It stays on the table.",
  "Il ruolo, la voce, poi — se serve — l'Europa. Per ora è solo una porta socchiusa.": "Role, voice, then — if needed — Europe. For now it's just a door left ajar.",
  "Un ultimo atto nominato, non firmato. L'inverno, poi, deciderà.": "A last act named, not signed. Winter will decide.",
  "La maglia della tua Nazionale non sta nel contratto. Sta in un'altra stanza del mestiere, e l'hai indossata.": "Your national-team jersey isn't in the contract. It lives in another room of the craft, and you wore it.",
  "Tre gare, un aereo, un'altra maglia. Sei tornato con le gambe pesanti e la testa più larga.": "Three games, a flight, another jersey. You came back with heavy legs and a broader mind.",
  "La finestra della tua Nazionale, già giocata. Il club, a settembre, fa due conti.": "The national-team window, already played. The club does the math in September.",
  "Due settimane senza schema. Il giorno dopo il tiro, stranamente, è uscito più pulito.": "Two weeks without a game plan. The next day your shot, strangely, came out cleaner.",
  "Hai spento tutto. Il corpo, per una volta, non ha chiesto scusa.": "You switched everything off. Your body, for once, didn't apologize.",
  "Il telefono è rimasto in borsa. Il corpo, per una volta, ringrazia in silenzio.": "The phone stayed in the bag. Your body, for once, says thanks in silence.",
  "Silenzio di luglio, tenuto. Il giorno dopo il tiro esce più pulito.": "July silence, kept. The next day your shot comes out cleaner.",
  "L'estate è finita su un telefono. Tu hai spento, e sei rimasto in palestra.": "The summer ended on a phone. You switched off, and stayed in the gym.",
  "Troppi occhi su un telefono. Tu hai spento, e il lavoro è rimasto lo stesso.": "Too many eyes on a phone. You switched off, and the work stayed the same.",
  "Estate di chili e di sonno. A ottobre il primo contatto è tuo, non del fisioterapista.": "A summer of kilos and sleep. In October the first contact is yours, not the physio's.",
  "Sala, cucina, nient'altro. A ottobre il primo contatto è tuo.": "Weight room, kitchen, nothing else. In October the first contact is yours.",
  "Hai insegnato, e il gesto è tornato. Strano, e giusto.": "You taught, and the motion came back. Strange, and right.",
  "Un campus, i ragazzi, la voce. Sei tornato con le mani meno dure.": "A camp, the kids, your voice. You came back with softer hands.",
  "Meno chili sulla barra, più anni. A settembre le gambe arrivano già scritte.": "Fewer kilos on the bar, more years. By September your legs arrive already written.",
  "Due possessi puliti, uno sporco. Lo staff ha preso appunti.": "Two clean possessions, one dirty. The staff took notes.",
  "Il mercato ha parlato sopra la tua testa. Tu hai fatto la valigia, poi l'hai disfatta.": "The market talked over your head. You packed your bag, then unpacked it.",
  "Una piazza vera sul foglio. Tu non eri al tavolo, e l'estate è passata così.": "A real destination on the sheet. You weren't at the table, and the summer went by like that.",
  "Voci, smentite, un silenzio. L'armadietto, a settembre, sa ancora di attesa.": "Rumors, denials, a silence. The locker, in September, still smells of waiting.",
  "Qualcuno ha fatto il tuo nome. Per ora resta una frase, e pesa.": "Someone mentioned your name. For now it stays a sentence, and it weighs.",
  "Lo scambio è una porta socchiusa. Tu tieni il mestiere, e la valigia semiaperta.": "The trade is a door left ajar. You keep at the craft, and your bag half-packed.",
  "Il foglio ha un'altra insegna. Tu non hai firmato: hai ascoltato, e questo basta.": "The sheet has another logo on it. You didn't sign: you listened, and that's enough.",
  "L'estate ti ha mosso a parole. Il parquet, a ottobre, è ancora questo — per ora.": "The summer moved you in words. The hardwood, in October, is still this one — for now.",
  "Sei sceso più magro e più cattivo, nel modo giusto.": "You came down leaner and meaner, in the right way.",
  "Asfalto, un ferro storto, una fame dritta. Sei tornato con le mani segnate.": "Asphalt, a crooked rim, a straight hunger. You came back with marked hands.",
  "Asfalto storto, tabelloni che cantano. Ti ha ricordato perché hai cominciato.": "Crooked asphalt, rattling backboards. It reminded you why you started.",
  "Hai visto il contatto dall'altra sponda. A ottobre le mani sono più basse.": "You saw contact from the other side. In October your hands are lower.",
  "Due giorni di regolamento. Lo staff trova un giocatore che legge il palmo, non lo discute.": "Two days of rulebook. The staff finds a player who reads the call, not argues it.",
  "Due giorni con gli arbitri. A ottobre le mani sono più basse, e i fischi anche.": "Two days with the referees. In October your hands are lower, and so are the whistles.",
  "Hai riletto una serie. Hai trovato un possesso che non avevi visto. Basta quello, e lo tieni per l'inverno.": "You reviewed a series. You found a possession you hadn't seen. That's enough, and you keep it for the winter.",
  "Un torneo estivo, asfalto, nient'altro. Sudore diverso, e una fame che a volte si era spenta.": "A summer tournament, asphalt, nothing else. A different kind of sweat, and a hunger that had sometimes faded."
};
