/* English narrative for teams. Key: Italian source text (see ../key.ts). */
export const EN_TEAMS: Readonly<Record<string, string>> = {
  "Boston": "Boston",
  "Atlantic": "Atlantic",
  "Ciclo d'oro ancora vivo. Il riferimento dell'Est, parquet verde e standard alti.": "A golden era still alive. The benchmark of the East, green hardwood and high standards.",
  "Madison conta di nuovo. Un progetto da titolo, non da nostalgia.": "Madison matters again. A title project, not a nostalgia act.",
  "Philadelphia 76ers": "Philadelphia 76ers",
  "Philadelphia": "Philadelphia",
  "Talento in alto, salute in basso. Ogni aprile è una scommessa.": "Talent at the top, health at the bottom. Every April is a gamble.",
  "Brooklyn": "Brooklyn",
  "Ricostruzione nera. Minuti per chi vuole un ruolo, non un anello.": "A hard rebuild. Minutes for anyone who wants a role, not a ring.",
  "Toronto": "Toronto",
  "Identità difensiva, classifica a metà. Un posto dove imparare il mestiere.": "A defensive identity, mid-table standing. A place to learn the craft.",
  "Cleveland": "Cleveland",
  "Central": "Central",
  "L'Est passa da qui: ritmo, difesa, ambizione da testata.": "The East runs through here: pace, defense, headline ambitions.",
  "Detroit": "Detroit",
  "La risalita è vera. Giovani che non chiedono permesso.": "The climb back is real. Young players who don't ask permission.",
  "Milwaukee": "Milwaukee",
  "Un contendente che invecchia con classe — e con urgenza.": "A contender aging with class — and with urgency.",
  "Indianapolis": "Indianapolis",
  "Pace alto, coraggio alto. I playoff li cercano, non li aspettano.": "High pace, high courage. They chase the playoffs, they don't wait for them.",
  "Chicago": "Chicago",
  "Mercato enorme, roster a metà. La maglia pesa più della classifica.": "A huge market, a half-built roster. The jersey weighs more than the standings.",
  "Orlando": "Orlando",
  "Southeast": "Southeast",
  "Lunghi, lunghi, lunghi. Un Sud-est costruito per aprile.": "Length, length, length. A Southeast team built for April.",
  "Atlanta": "Atlanta",
  "Talento da highlight, difesa da lavoro. Sempre un passo dal salto.": "Highlight-reel talent, blue-collar defense. Always one step from the leap.",
  "Miami": "Miami",
  "La cultura Heat: minuti guadagnati, mai regalati. Playoff nel DNA.": "Heat culture: minutes earned, never given. Playoffs in their DNA.",
  "Charlotte": "Charlotte",
  "Talento giovane, classifica ostile. Un posto dove crescere in fretta.": "Young talent, hostile standings. A place to grow up fast.",
  "Washington": "Washington",
  "Ricostruzione lunga. I minuti ci sono, le vittorie no.": "A long rebuild. The minutes are there, the wins aren't.",
  "Northwest": "Northwest",
  "La macchina del West. Giovani, profondità, il metro della lega.": "The West's machine. Youth, depth, the league's yardstick.",
  "Denver": "Denver",
  "Il gioco più intelligente della lega. Un contendente che non alza la voce.": "The smartest game in the league. A contender that doesn't raise its voice.",
  "Minneapolis": "Minneapolis",
  "Difesa da élite, Nord freddo, ambizioni calde.": "Elite defense, cold North, hot ambitions.",
  "Portland": "Portland",
  "Ricostruire sotto la pioggia. Il futuro è più vicino della classifica.": "Rebuilding in the rain. The future is closer than the standings say.",
  "Tank e futuro. Lo Jazz aspetta il prossimo ciclo, minuti per tutti.": "Tanking and the future. The Jazz wait for the next cycle, minutes for everyone.",
  "Houston": "Houston",
  "Southwest": "Southwest",
  "Atletismo, lunghezza, un West che li teme di nuovo.": "Athleticism, length, a West that fears them again.",
  "Dallas": "Dallas",
  "Un palazzetto che chiede l'anello. Talento da copertina, roster da equilibrare.": "An arena that demands a ring. Cover-star talent, a roster to balance.",
  "Il futuro ha già un volto. Gli Spurs tornano a insegnare e a vincere.": "The future already has a face. The Spurs are back to teaching and winning.",
  "Memphis": "Memphis",
  "Grit and grind aggiornato. Quando sono interi, contano.": "Grit and grind, updated. When they're healthy, they matter.",
  "Salute e 'se'. Un roster da playoff in una città che aspetta.": "Health and \"ifs\". A playoff roster in a city that's waiting.",
  "Pacific": "Pacific",
  "Il marchio più pesante. Ogni stagione è una vetrina, e una scadenza.": "The heaviest brand. Every season is a showcase, and a deadline.",
  "Il tiro che ha cambiato la lega. Un ciclo che resiste, non si arrende.": "The shot that changed the league. A cycle that endures, and won't give up.",
  "Finestre strette, stipendi alti. I playoff restano l'unico giudizio.": "Tight windows, high salaries. The playoffs remain the only verdict.",
  "Phoenix": "Phoenix",
  "Deserto, stelle, e una classifica che non perdona i dettagli.": "Desert, stars, and standings that don't forgive details.",
  "Sacramento": "Sacramento",
  "Ritmo, pubblico, play-in. Sempre a un possesso dal salto.": "Pace, crowd, play-in. Always one possession from the leap.",
  "Madrid": "Madrid",
  "La casa dei titoli. Chi arriva qui impara a vincere, o a uscire.": "The home of titles. Whoever comes here learns to win, or to leave.",
  "Barcellona": "Barcelona",
  "Palau, orgoglio, un ciclo che non accetta secondi posti.": "The Palau, pride, a cycle that doesn't accept second place.",
  "Olympiacos": "Olympiacos",
  "Pireo": "Piraeus",
  "Il Pireo di notte è un altro sport. Difesa, cuore, Final Four.": "Piraeus at night is a different sport. Defense, heart, Final Four.",
  "Panathinaikos": "Panathinaikos",
  "Atene": "Athens",
  "Il derby come mestiere. Verdi, esigenti, sempre nel giro titolo.": "The derby as a way of life. Green, demanding, always in the title race.",
  "Fenerbahce": "Fenerbahce",
  "Istanbul": "Istanbul",
  "Istanbul non perdona. Un palazzetto che chiede l'Eurolega ogni anno.": "Istanbul doesn't forgive. An arena that demands the EuroLeague every year.",
  "Scuola di tiro e di letture. Un progetto che sa cos'è un anello.": "A school of shooting and reads. A project that knows what a ring is.",
  "EA7 Olimpia Milano": "EA7 Olimpia Milano",
  "Milano": "Milan",
  "Il Forum, la Serie A, l'Europa. Casa per chi vuole restare grande in Italia.": "The Forum, Serie A, Europe. Home for those who want to stay big in Italy.",
  "Bologna": "Bologna",
  "Nera, orgogliosa, un'altra idea di Italia. Palazzetto che morde.": "Black, proud, a different idea of Italy. An arena that bites.",
  "Monaco": "Monaco",
  "Principato, athleticism, un roster costruito per aprile.": "The Principality, athleticism, a roster built for April.",
  "Kaunas": "Kaunas",
  "Kaunas non è un mercato. È una religione verde.": "Kaunas isn't a market. It's a green religion.",
  "Belgrado": "Belgrade",
  "Belgrado a mezzanotte. Intensità che i numeri non spiegano.": "Belgrade at midnight. Intensity the numbers can't explain.",
  "Giallo, storia, un club che ha insegnato l'Europa a metà continente.": "Yellow, history, a club that taught Europe to half the continent.",
  "Baskonia": "Baskonia",
  "Vitoria": "Vitoria",
  "Vitoria forma giocatori. Poi li manda in NBA, o li tiene a vincere.": "Vitoria develops players. Then it sends them to the NBA, or keeps them to win.",
  "Bundesliga e Eurolega, stesso orgoglio. Un club che spende per restare.": "Bundesliga and EuroLeague, the same pride. A club that spends to stay on top.",
  "Stella Rossa: il derby, la curva, un'altra idea di playoff.": "Red Star: the derby, the curva, a different idea of the playoffs.",
  "Berlino": "Berlin",
  "Scuola tedesca, minuti per i giovani, un progetto più che un titolo.": "German school, minutes for young players, a project more than a title.",
  "Svincolato": "Free agent",
  "In attesa del Draft.": "Awaiting the Draft."
};
