/* English narrative for world. Key: Italian source text (see ../key.ts). */
export const EN_WORLD: Readonly<Record<string, string>> = {
  "Asher": "Asher",
  "Malik": "Malik",
  "Luka": "Luka",
  "Jalen": "Jalen",
  "Enzo": "Enzo",
  "Caleb": "Caleb",
  "Theo": "Theo",
  "Isaiah": "Isaiah",
  "Mateo": "Mateo",
  "Noah": "Noah",
  "Kobe": "Kobe",
  "Pavel": "Pavel",
  "Dario": "Dario",
  "Nico": "Nico",
  "Andre": "Andre",
  "Miles": "Miles",
  "Soren": "Soren",
  "Ellis": "Ellis",
  "Rafa": "Rafa",
  "Kenji": "Kenji",
  "Omar": "Omar",
  "Tomas": "Tomas",
  "Ilija": "Ilija",
  "Jamal": "Jamal",
  "Devin": "Devin",
  "Cole": "Cole",
  "Nasir": "Nasir",
  "Pietro": "Pietro",
  "Hugo": "Hugo",
  "Levi": "Levi",
  "Quinn": "Quinn",
  "Crowe": "Crowe",
  "Petrovic": "Petrovic",
  "Voss": "Voss",
  "Moretti": "Moretti",
  "Okoye": "Okoye",
  "Marais": "Marais",
  "Flint": "Flint",
  "Silva": "Silva",
  "Berg": "Berg",
  "Daramy": "Daramy",
  "Novak": "Novak",
  "Blake": "Blake",
  "Ward": "Ward",
  "Vance": "Vance",
  "Hale": "Hale",
  "Okoro": "Okoro",
  "Santos": "Santos",
  "Ilic": "Ilic",
  "Nakamura": "Nakamura",
  "Grant": "Grant",
  "Rossi": "Rossi",
  "Diallo": "Diallo",
  "Kemp": "Kemp",
  "Frost": "Frost",
  "Ndiaye": "Ndiaye",
  "Costa": "Costa",
  "Jensen": "Jensen",
  "Park": "Park",
  "Morrow": "Morrow",
  "Marchetti": "Marchetti",
  "Ellison": "Ellison",
  "Rivas": "Rivas",
  "Kovacs": "Kovacs",
  "Hartley": "Hartley",
  "Bellini": "Bellini",
  "Kruger": "Kruger",
  "Ibarra": "Ibarra",
  "Petrov": "Petrov",
  "{NAME} firma da svincolato a {DEST}. Lascia {FROM}.": "{NAME} signs as a free agent with {DEST}. Leaves {FROM}.",
  "Mercato: {NAME} sceglie {DEST}. Addio {FROM}.": "Free agency: {NAME} picks {DEST}. Goodbye, {FROM}.",
  "{NAME} cambia casacca: da {FROM} a {DEST}, da svincolato.": "{NAME} switches jerseys: from {FROM} to {DEST}, as a free agent.",
  "{DEST} ({GOAL}) chiama {NAME} dal mercato. {FROM} resta senza volto.": "{DEST} ({GOAL}) lands {NAME} in free agency. {FROM} is left without a face.",
  "{NAME}, {AGE} anni, sceglie {DEST}. {FROM} lo lascia partire.": "{NAME}, {AGE}, picks {DEST}. {FROM} lets him go.",
  "{NAME} lascia {FROM} a parametro zero. Prima firma: {DEST}.": "{NAME} leaves {FROM} as a free agent. First signing: {DEST}.",
  "Colpo di mercato: {DEST} chiude {NAME}. {FROM} non allinea l'offerta.": "Free-agency coup: {DEST} closes on {NAME}. {FROM} doesn't match the offer.",
  "Niente rinnovo a {FROM}. {NAME} accetta {DEST} e chiude.": "No extension in {FROM}. {NAME} accepts {DEST} and that's that.",
  "Da {FROM} a {DEST}, da svincolato: {NAME} cambia aria.": "From {FROM} to {DEST}, as a free agent: {NAME} needs a change of scenery.",
  "{DEST} ({GOAL}) vince il mercato su {NAME}. {FROM} resta a guardare.": "{DEST} ({GOAL}) wins the {NAME} sweepstakes. {FROM} is left watching.",
  "{NAME}, ancora {AGE} anni, sceglie {DEST} per crescere. Addio {FROM}.": "{NAME}, still only {AGE}, picks {DEST} to grow. Goodbye, {FROM}.",
  "{DEST} ({GOAL}) investe su {NAME}. {FROM} lo lascia partire giovane.": "{DEST} ({GOAL}) invests in {NAME}. {FROM} lets him go young.",
  "Promessa in movimento: {NAME} ({AGE}) firma a {DEST}. {FROM} non trattiene.": "Prospect on the move: {NAME} ({AGE}) signs with {DEST}. {FROM} doesn't hold on.",
  "{NAME} cambia piazza da ragazzo. {DEST} lo prende, {FROM} lo saluta.": "{NAME} changes cities as a kid. {DEST} takes him, {FROM} waves goodbye.",
  "{NAME}, {AGE} anni, va a {DEST} per {GOAL}. {FROM} chiude un ciclo.": "{NAME}, {AGE}, heads to {DEST} for {GOAL}. {FROM} closes a cycle.",
  "Veterano in movimento: {NAME} firma a {DEST}. {FROM} cambia volto.": "Veteran on the move: {NAME} signs with {DEST}. {FROM} changes its face.",
  "{DEST} chiama mestiere. {NAME}, {AGE} anni, lascia {FROM}.": "{DEST} calls for experience. {NAME}, {AGE}, leaves {FROM}.",
  "Fine di un ciclo a {FROM}: {NAME} atterra a {DEST}, progetto {GOAL}.": "End of an era in {FROM}: {NAME} lands in {DEST}, a {GOAL} project.",
  "{NAME}, volto di {FROM}, si svincola e sceglie {DEST}.": "{NAME}, the face of {FROM}, opts out and picks {DEST}.",
  "Terremoto di mercato: {DEST} strappa {NAME}. {FROM} perde la faccia.": "Free-agency earthquake: {DEST} snatches {NAME}. {FROM} loses its face.",
  "{NAME} non rinnova a {FROM}. Firma da stella a {DEST} ({GOAL}).": "{NAME} won't re-sign with {FROM}. He signs a star deal with {DEST} ({GOAL}).",
  "La stella cambia sponda: {NAME}, da {FROM} a {DEST}, a parametro zero.": "The star switches sides: {NAME}, from {FROM} to {DEST}, as a free agent.",
  "{A} ({PTS} punti) va a {TO}. {B} arriva a {FROM}.": "{A} ({PTS} points) goes to {TO}. {B} arrives in {FROM}.",
  "Scambio: {A} verso {TO}, {B} verso {FROM}.": "Trade: {A} to {TO}, {B} to {FROM}.",
  "{FROM} e {TO} si scambiano le facce: {A} per {B}.": "{FROM} and {TO} swap faces: {A} for {B}.",
  "{A} cambia sponda ({TO}). {B} fa il percorso inverso, a {FROM}.": "{A} switches sides ({TO}). {B} makes the opposite trip, to {FROM}.",
  "{TO} ({GOAL}) pesca {A}. {FROM} ({NEED}) prende {B}.": "{TO} ({GOAL}) lands {A}. {FROM} ({NEED}) takes {B}.",
  "{FROM} molla {A} a {TO} e riceve {B}, in ottica {NEED}.": "{FROM} ships {A} to {TO} and gets {B}, with an eye on {NEED}.",
  "Uno per uno tra {FROM} e {TO}: {A} contro {B}, senza giri di parole.": "One-for-one between {FROM} and {TO}: {A} for {B}, no beating around the bush.",
  "{A} porta i suoi {PTS} punti a {TO}. {FROM} si tiene {B} e chiude.": "{A} takes his {PTS} points to {TO}. {FROM} keeps {B} and closes the deal.",
  "{TO} prende {A}. {FROM} risponde con {B}. Pratica chiusa.": "{TO} takes {A}. {FROM} answers with {B}. Deal done.",
  "{A}, volto di {FROM}, finisce a {TO}. Di ritorno arriva {B}.": "{A}, the face of {FROM}, ends up in {TO}. Coming back: {B}.",
  "Cambio di ciclo: {A} ({YA} anni) verso {TO}, {B} ({YB} anni) verso {FROM}.": "A changing of the guard: {A} ({YA}) to {TO}, {B} ({YB}) to {FROM}.",
  "{FROM} cede gli anni, {TO} cede il mestiere: {A} per {B}.": "{FROM} gives up youth, {TO} gives up experience: {A} for {B}.",
  "Giovane per veterano: {A} a {TO}, {B} a {FROM}. Due progetti, uno scambio.": "Youth for a veteran: {A} to {TO}, {B} to {FROM}. Two projects, one trade.",
  "{TO} ({GOAL}) pesca {A}, {YA} anni. {FROM} ({NEED}) si tiene {B}.": "{TO} ({GOAL}) lands {A}, {YA}. {FROM} ({NEED}) keeps {B}.",
  "{TO} strappa {A}, il volto. {FROM} accetta {B} e tira dritto.": "{TO} snatches {A}, the face of the franchise. {FROM} accepts {B} and moves on.",
  "Scambio da testata: {A} va a {TO}. {B}, in cambio, a {FROM}.": "A headline trade: {A} goes to {TO}. {B}, in return, to {FROM}.",
  "{A} ({PTS} punti) cambia sponda. {TO} vince il colpo, {FROM} prende {B}.": "{A} ({PTS} points) switches sides. {TO} wins the deal, {FROM} takes {B}.",
  "{FROM} molla la stella. {A} finisce a {TO}, {B} fa il percorso inverso.": "{FROM} lets the star go. {A} ends up in {TO}, {B} makes the opposite trip.",
  "Operazione da {NEED}: {FROM} cede {A} e punta su {B}.": "A {NEED} move: {FROM} gives up {A} and bets on {B}.",
  "{FROM} smonta il volto. {A} va a {TO}, in cambio {B}.": "{FROM} dismantles its face. {A} goes to {TO}, {B} comes back.",
  "{TO} accelera per {GOAL}. Arriva {A}, parte {B} verso {FROM}.": "{TO} pushes for {GOAL}. {A} arrives, {B} heads to {FROM}.",
  "Ricostruzione in corso: {FROM} prende {B}, {TO} si tiene {A}.": "Rebuild underway: {FROM} takes {B}, {TO} keeps {A}.",
  "A {CITY} arriva {COACH}. Nuovo copione: {SYS}.": "{COACH} arrives in {CITY}. A new script: {SYS}.",
  "{CITY} cambia voce in panchina. {COACH}, sistema {SYS}.": "{CITY} changes the voice on the bench. {COACH}, {SYS} system.",
  "Panchina nuova a {CITY}: {COACH}. Si gioca a {SYS}.": "New bench in {CITY}: {COACH}. The style is {SYS}.",
  "{COACH} siede a {CITY}. Via il vecchio copione, adesso {SYS}.": "{COACH} takes the bench in {CITY}. Out with the old script, now it's {SYS}.",
  "La dirigenza di {CITY} chiama {COACH}. Obiettivo {GOAL}, mezzo {SYS}.": "The {CITY} front office calls {COACH}. Goal: {GOAL}; means: {SYS}.",
  "{CITY}, in ottica {GOAL}, affida la squadra a {COACH} ({SYS}).": "{CITY}, with an eye on {GOAL}, hands the team to {COACH} ({SYS}).",
  "Nuovo tecnico a {CITY}. {COACH} chiude {OLD} e apre {SYS}.": "New coach in {CITY}. {COACH} closes the {OLD} chapter and opens {SYS}.",
  "{COACH} a {CITY}: panchina nuova, stesso palazzetto, altro basket ({SYS}).": "{COACH} in {CITY}: new bench, same arena, different basketball ({SYS}).",
  "Esonero a {CITY}. Via il tecnico, resta il dubbio.": "Coach fired in {CITY}. The coach is gone, the doubts remain.",
  "{CITY} caccia l'allenatore. In panchina, per ora, il vuoto.": "{CITY} fires its coach. On the bench, for now, a void.",
  "Fine corsa in panchina a {CITY}. La piazza chiede un altro volto.": "End of the line on the bench in {CITY}. The fans want a new face.",
  "A {CITY} saltano il tecnico. {STAR} resta, lo staff no.": "The coach is out in {CITY}. {STAR} stays, the staff doesn't.",
  "Esonero lampo a {CITY}. La dirigenza non aspetta aprile.": "A swift firing in {CITY}. The front office won't wait until April.",
  "{CITY} chiude la panchina e riapre il discorso internamente.": "{CITY} clears the bench and reopens the discussion internally.",
  "Esonero a {CITY}. Il nuovo staff prova {SYS}.": "Coach fired in {CITY}. The new staff tries {SYS}.",
  "{CITY} gira pagina: via il tecnico, si gioca a {SYS}.": "{CITY} turns the page: the coach is out, the style is {SYS}.",
  "{CITY} cambia sistema: {SYS}.": "{CITY} changes systems: {SYS}.",
  "Nuovo sistema a {CITY} — {SYS}.": "New system in {CITY} — {SYS}.",
  "{CITY} gira pagina tattica: {SYS}.": "{CITY} turns the tactical page: {SYS}.",
  "A {CITY} non si tocca il roster. Cambia il copione: {SYS}.": "In {CITY} the roster stays untouched. The script changes: {SYS}.",
  "{CITY} abbandona {OLD}. Adesso si gioca a {SYS}.": "{CITY} abandons {OLD}. Now the style is {SYS}.",
  "Rivoluzione tattica a {CITY}: da {OLD} a {SYS}.": "Tactical revolution in {CITY}: from {OLD} to {SYS}.",
  "{CITY}, progetto {GOAL}, punta su {SYS}.": "{CITY}, a {GOAL} project, bets on {SYS}.",
  "Cambio di identità a {CITY}. Il palazzetto vedrà {SYS}.": "An identity change in {CITY}. The arena will see {SYS}.",
  "La piazza di {CITY} chiede un altro basket. Arriva {SYS}.": "The {CITY} fans want a different brand of basketball. Here comes {SYS}.",
  "{CITY} cambia idea di gioco. {STAR} resta, il sistema no: {SYS}.": "{CITY} changes its idea of the game. {STAR} stays, the system doesn't: {SYS}.",
  "Dinastia {NAME}: tre titoli di fila.": "The {NAME} dynasty: three titles in a row.",
  "Tre anelli di fila per {NAME}. Non è un ciclo, è un regno.": "Three straight rings for {NAME}. It's not a cycle, it's a reign.",
  "{NAME} non molla l'anello: tris consecutivo.": "{NAME} won't let go of the ring: three-peat.",
  "Tris di titoli, stessa maglia: {NAME} scrive la dinastia.": "Three titles, same jersey: {NAME} writes the dynasty.",
  "{NAME}, tre giugno di fila. Il resto della lega prende atto.": "{NAME}, three Junes in a row. The rest of the league takes note.",
  "Dinastia {NAME}. Tre titoli, una sola piazza.": "The {NAME} dynasty. Three titles, one city.",
  "{STAR} e {NAME}: il tris che chiude le discussioni.": "{STAR} and {NAME}: the three-peat that ends all arguments.",
  "Terzo titolo di fila, {NAME}. La lega gira intorno a {STAR}.": "Third straight title, {NAME}. The league revolves around {STAR}.",
  "{NAME} trova casa a {DEST}. Lascia {FROM}.": "{NAME} finds a home in {DEST}. Leaves {FROM}.",
  "{NAME} firma a {DEST}. {FROM} resta senza volto.": "{NAME} signs with {DEST}. {FROM} is left without a face.",
  "Da {FROM} a {DEST}: {NAME} cambia sponda.": "From {FROM} to {DEST}: {NAME} switches sides.",
  "{DEST} ({GOAL}) accoglie {NAME}. {FROM} lo lascia partire.": "{DEST} ({GOAL}) welcomes {NAME}. {FROM} lets him go.",
  "{NAME}, svincolato, atterra a {DEST}. {FROM} chiude il capitolo.": "{NAME}, a free agent, lands in {DEST}. {FROM} closes the chapter.",
  "Piazza nuova per {NAME}: {DEST}, progetto {GOAL}. Addio {FROM}.": "A new city for {NAME}: {DEST}, a {GOAL} project. Goodbye, {FROM}.",
  "{NAME} prende il posto a {DEST}. {OLD} esce di scena.": "{NAME} takes the spot in {DEST}. {OLD} leaves the stage.",
  "{DEST} sceglie {NAME}. Per {OLD} è finita.": "{DEST} picks {NAME}. For {OLD}, it's over.",
  "{NAME} arriva a {DEST}. {OLD} cede il passo, senza rumore.": "{NAME} arrives in {DEST}. {OLD} steps aside, quietly.",
  "{DEST} punta su {NAME}. {OLD} resta fuori dal quadro.": "{DEST} bets on {NAME}. {OLD} is out of the picture.",
  "Cambio di faccia a {DEST}: entra {NAME}, esce {OLD}.": "A new face in {DEST}: {NAME} in, {OLD} out.",
  "{NAME} chiude. Non c'era più un ruolo da stella.": "{NAME} calls it a career. There was no star role left.",
  "{NAME} si ferma. Il mestiere, per lui, è finito.": "{NAME} stops. The craft, for him, is over.",
  "Niente nuova maglia per {NAME}. Solo la chiusura.": "No new jersey for {NAME}. Just the ending.",
  "{NAME} si ritira a {AGE} anni. {TEAM} perde la sua faccia.": "{NAME} retires at {AGE}. {TEAM} loses its face.",
  "{NAME} appende le scarpe a {AGE} anni. {TEAM} deve trovare un altro volto.": "{NAME} hangs up his shoes at {AGE}. {TEAM} has to find another face.",
  "Fine corsa per {NAME}, {AGE} anni. {TEAM} resta senza stella.": "End of the road for {NAME}, {AGE}. {TEAM} is left without a star.",
  "{NAME} chiude a {AGE} anni. A {TEAM} cambia il nome sulla maglia.": "{NAME} retires at {AGE}. In {TEAM}, the name on the jersey changes.",
  "{OLD} cede il passo. A {TEAM} arriva la nuova generazione.": "{OLD} steps aside. {TEAM} welcomes the new generation.",
  "{OLD} esce. {TEAM} punta su un nome nuovo dal draft.": "{OLD} leaves. {TEAM} bets on a new name from the draft.",
  "Cambio di faccia a {TEAM}: {OLD} fa spazio.": "A new face in {TEAM}: {OLD} makes room.",
  "A {CITY} il draft spinge verso la crescita. {STAR} è il volto, si gioca a {SYS}.": "In {CITY}, the draft pushes toward development. {STAR} is the face, the style is {SYS}.",
  "{CITY} gira pagina dopo il draft: da {OLD} a {SYS}, con {STAR} in vetrina.": "{CITY} turns the page after the draft: from {OLD} to {SYS}, with {STAR} in the shop window.",
  "Nuovo volto, nuovo copione: {CITY} chiama {STAR} e punta su {SYS}.": "New face, new script: {CITY} calls on {STAR} and bets on {SYS}.",
  "Classe {Q} al draft: {WHO}.": "{Q} draft class: {WHO}.",
  "Al draft, classe {Q} — {WHO}.": "At the draft, a {Q} class — {WHO}.",
  "Chiamati al draft ({Q}): {WHO}.": "Called at the draft ({Q}): {WHO}.",
  "ritmo alto": "high pace",
  "metà campo": "half court",
  "tiro da tre": "three-point shooting",
  "movimento di palla": "ball movement",
  "fisicità": "physicality"
};
