/**
 * Old saves only. Until this release, careers started in English stored a few procedural
 * scenes, contract pitches and the "year before" line already in English. Those texts are
 * frozen in existing saves; this reverse catalog shows them in Italian when the game runs in
 * Italian. New careers always store Italian, so nothing here is ever written again.
 */
export const LEGACY_EN_IT: Readonly<Record<string, string>> = {
  // corpo
  "At {AGE}, the body sends the bill": "A {AGE} anni il corpo presenta il conto",
  "{AGE} years old, {TEAM}. The knee speaks before the report does. How do you answer?": "{AGE} anni, {TEAM}. Il ginocchio parla prima del referto. Come rispondi?",
  "You cut the minutes": "Tagli i minuti",
  "Fewer games, more full days.": "Meno partite, più giorni interi.",
  "You leave early. The next day's report is shorter.": "Esci prima. Il referto del giorno dopo è più corto.",
  "You play anyway": "Giochi lo stesso",
  "The group needs you tonight.": "Il gruppo ha bisogno di te stasera.",
  "You stay on the floor. The crowd sees it. So does the body.": "Resti in campo. Il pubblico lo vede. Anche il corpo.",
  "Gym work, out of sight": "Palestra, lontano dagli occhi",
  "No applause. Only the right movement.": "Niente applausi. Solo il gesto giusto.",
  "The gym door closes. Outside, nothing happens. Inside, it does.": "La porta della palestra si chiude. Fuori non succede niente. Dentro sì.",
  // sfida
  "At {AGE}, {RIVAL} comes looking": "A {AGE} anni {RIVAL} ti viene a cercare",
  "{RIVAL} is keeping score, and {TEAM} knows it. This is not a speech. It is a game.": "{RIVAL} tiene il conto, e {TEAM} lo sa. Non è un discorso. È una partita.",
  "You answer at the rim": "Rispondi al ferro",
  "The first possession is yours.": "Il primo possesso è tuo.",
  "{RIVAL} talks. You score. The argument ends on the scoreboard.": "{RIVAL} parla. Tu segni. La discussione finisce sul tabellone.",
  "You ignore him": "Lo ignori",
  "The system matters more than the duel.": "Il sistema conta più del duello.",
  "You don't answer. The coach notices. So does he, and that is enough.": "Non rispondi. Il coach lo nota. Anche lui, e basta così.",
  "You guard him": "Lo marchi tu",
  "The points can wait. He doesn't.": "I punti possono aspettare. Lui no.",
  "You take him. The bucket comes later, if it comes.": "Lo prendi tu. Il canestro arriva dopo, se arriva.",
  // contratto
  "At {AGE}, the contract is in its last winter": "A {AGE} anni il contratto è all'ultimo inverno",
  "{TEAM} can keep you or let you go. The summer is already in the room.": "{TEAM} può tenerti o lasciarti andare. L'estate è già nella stanza.",
  "You ask to stay": "Chiedi di restare",
  "Same jersey, said out loud.": "Stessa maglia, detto ad alta voce.",
  "You say it. The front office writes it down, and does not promise.": "Lo dici. La dirigenza prende nota, e non promette.",
  "You listen to the market": "Ascolti il mercato",
  "A door, not a betrayal.": "Una porta, non un tradimento.",
  "You listen. No signature. Just the price of your name.": "Ascolti. Nessuna firma. Solo il prezzo del tuo nome.",
  "You let the year talk": "Lasci parlare la stagione",
  "No meeting. Just games.": "Nessun incontro. Solo partite.",
  "You don't ask. The numbers, in April, will ask for you.": "Non chiedi. I numeri, ad aprile, chiederanno per te.",
  // freddo
  "At {AGE}, the shot has gone cold": "A {AGE} anni il tiro si è raffreddato",
  "{TEAM} keeps running the play. The rim, tonight, does not cooperate.": "{TEAM} continua a chiamare lo schema. Il ferro, stasera, non collabora.",
  "You keep shooting": "Continui a tirare",
  "The slump ends only if you shoot through it.": "Il momento no finisce solo se ci tiri attraverso.",
  "You shoot again. One goes down. It is not a cure. It is a start.": "Tiri ancora. Una entra. Non è una cura. È un inizio.",
  "You pass out of it": "Ne esci passando",
  "The open man is the play.": "Il compagno libero è lo schema.",
  "You give it up. The basket comes from someone else. The slump can wait.": "La cedi. Il canestro arriva da un altro. Il momento no può aspettare.",
  "You ask for a day": "Chiedi un giorno",
  "One practice, no crowd.": "Un allenamento, senza pubblico.",
  "You stay late. The empty gym is more honest than the box score.": "Resti fino a tardi. La palestra vuota è più onesta del referto.",
  // caldo
  "At {AGE}, the city is on you": "A {AGE} anni la città è tutta su di te",
  "{TEAM} is winning and the ball finds you. The noise arrives before the whistle.": "{TEAM} vince e la palla ti trova. Il rumore arriva prima del fischio.",
  "You take the last shot": "Prendi l'ultimo tiro",
  "The possession has your name on it.": "Il possesso porta il tuo nome.",
  "You call for it. Make or miss, the building already decided.": "La chiami. Dentro o fuori, il palazzetto ha già deciso.",
  "You share it": "La condividi",
  "A hot hand that still passes.": "Una mano calda che passa ancora.",
  "You give the last one away. The locker room remembers that more than the points.": "Cedi l'ultima. Lo spogliatoio lo ricorda più dei punti.",
  "You quiet the week": "Abbassi il volume della settimana",
  "No extra interviews.": "Niente interviste in più.",
  "You say less. The game, on Friday, has more room.": "Parli meno. La partita di venerdì ha più spazio.",
  // panchina
  "At {AGE}, the minutes are not there": "A {AGE} anni i minuti non ci sono",
  "{TEAM} has a rotation, and your name is near the end of it.": "{TEAM} ha una rotazione, e il tuo nome è verso il fondo.",
  "You ask the coach": "Chiedi al coach",
  "A closed door, a straight question.": "Una porta chiusa, una domanda diretta.",
  "You ask. He doesn't raise his voice. He moves one possession. That's it.": "Chiedi. Non alza la voce. Sposta un possesso. Basta.",
  "You take the garbage minutes": "Prendi i minuti a partita chiusa",
  "The end of the game still counts.": "Anche la fine della partita conta.",
  "You play the last four minutes. They are ugly. They are yours.": "Giochi gli ultimi quattro minuti. Sono brutti. Sono tuoi.",
  "You work and wait": "Lavori e aspetti",
  "No scene. Just the gym.": "Niente scene. Solo la palestra.",
  "You don't knock. When the minutes come, the body is already ready.": "Non bussi. Quando i minuti arrivano, il corpo è già pronto.",
  // anni
  "At {AGE}, the league starts counting": "A {AGE} anni la lega inizia a contare",
  "The legs are still there. The calendar is not on your side anymore.": "Le gambe ci sono ancora. Il calendario non è più dalla tua parte.",
  "You change the game": "Cambi gioco",
  "Less running, more reading.": "Meno corsa, più lettura.",
  "You play lower. The bucket comes a second later, and it still counts.": "Giochi più basso. Il canestro arriva un secondo dopo, e conta lo stesso.",
  "You keep the same body": "Tieni lo stesso corpo",
  "The old way, one more year.": "Alla vecchia maniera, un anno ancora.",
  "You don't change. Some nights it works. The knee keeps the receipt.": "Non cambi. Certe sere funziona. Il ginocchio conserva lo scontrino.",
  "You teach in the film room": "Insegni in sala video",
  "The voice becomes part of the job.": "La voce diventa parte del mestiere.",
  "You stop the tape. A younger teammate nods. That, too, is a possession.": "Fermi il filmato. Un compagno più giovane annuisce. Anche questo è un possesso.",
  // numeri
  "At {AGE}, the numbers already have a role": "A {AGE} anni i numeri hanno già un ruolo",
  "{TEAM} knows what you produce. The question is what you want next.": "{TEAM} sa cosa produci. La domanda è cosa vuoi adesso.",
  "You ask for the ball": "Chiedi la palla",
  "More usage, more noise.": "Più possessi, più rumore.",
  "You ask. The next game, the first action is yours.": "Chiedi. La partita dopo, la prima azione è tua.",
  "You stay in the role": "Resti nel ruolo",
  "The job is already working.": "Il mestiere funziona già.",
  "You don't ask for more. The line stays clean, and so does the locker room.": "Non chiedi di più. Il tabellino resta pulito, e anche lo spogliatoio.",
  "You add the other end": "Aggiungi l'altra metà campo",
  "The box score is not only points.": "Il referto non è fatto solo di punti.",
  "You take a charge. The points were already there. The stop is new.": "Prendi uno sfondamento. I punti c'erano già. Lo stop è nuovo.",
  // ruolo
  "At {AGE}, the role is the question": "A {AGE} anni la domanda è il ruolo",
  "{TEAM} has a shape. You can fill it, or push it.": "{TEAM} ha una forma. Puoi riempirla, o spingerla.",
  "You play your game": "Giochi il tuo gioco",
  "Your game, without asking permission.": "Il tuo gioco, senza chiedere permesso.",
  "You take the first move. The scheme, for a night, follows you.": "Fai la prima mossa. Lo schema, per una sera, ti segue.",
  "You stay in the scheme": "Resti nello schema",
  "The drawing matters more than the impulse.": "Il disegno conta più dell'impulso.",
  "You execute. It is not a show. It is a win that makes no noise.": "Esegui. Non è uno spettacolo. È una vittoria che non fa rumore.",
  "You play the helper": "Fai da spalla",
  "Someone else scores. You take his defender.": "Segna un altro. Tu ti prendi il suo difensore.",
  "Nobody says your name at the microphone. In the locker room, they do.": "Nessuno dice il tuo nome al microfono. In spogliatoio sì.",
  // Contract pitches (free agency).
  "Extension. {TEAM} wants you to stay.": "Rinnovo. {TEAM} vuole che resti.",
  "{TEAM} is chasing a ring. Less money, a real contender.": "{TEAM} va a caccia dell'anello. Meno soldi, una vera contendente.",
  "{TEAM} offers market money and a lead role.": "{TEAM} offre la cifra di mercato e un ruolo da protagonista.",
  "The richest offer comes from {TEAM}. The project comes after the check.": "L'offerta più ricca arriva da {TEAM}. Il progetto viene dopo l'assegno.",
  "EuroLeague: {TEAM}. Another stage, the same ball.": "Eurolega: {TEAM}. Un altro palcoscenico, la stessa palla.",
  "Two years at {TEAM} to show the peak is not behind you.": "Due anni a {TEAM} per dimostrare che il picco non è alle spalle.",
  "{TEAM} wants a piece for a title run. Real minutes.": "{TEAM} vuole un tassello per il titolo. Minuti veri.",
  "{TEAM} offers a lead role, without promising June.": "{TEAM} offre un ruolo da protagonista, senza promettere giugno.",
  "{TEAM} is rebuilding. The minutes come now. The wins come later.": "{TEAM} ricostruisce. I minuti arrivano subito. Le vittorie dopo.",
  // "The year before" line appended to procedural subtitles.
  "The year before, you finished at {0}.": "L'anno prima hai chiuso a {0}.",
  "{0} points": "{0} punti",
  "{0} rebounds": "{0} rimbalzi",
  "{0} assists": "{0} assist",
  "{0} steals and {1} blocks": "{0} palle rubate e {1} stoppate",
};
